/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiHousehold {
    public static final Emoji DOOR = new Emoji("\ud83d\udeaa", "\\uD83D\\uDEAA", Collections.singletonList(":door:"), Collections.singletonList(":door:"), Collections.singletonList(":door:"), Collections.unmodifiableList(Arrays.asList("back", "closet", "door", "front")), false, false, 0.6, Qualification.fromString("fully-qualified"), "door", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji ELEVATOR = new Emoji("\ud83d\uded7", "\\uD83D\\uDED7", Collections.singletonList(":elevator:"), Collections.singletonList(":elevator:"), Collections.singletonList(":elevator:"), Collections.unmodifiableList(Arrays.asList("accessibility", "elevator", "hoist", "lift")), false, false, 13.0, Qualification.fromString("fully-qualified"), "elevator", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji MIRROR = new Emoji("\ud83e\ude9e", "\\uD83E\\uDE9E", Collections.singletonList(":mirror:"), Collections.singletonList(":mirror:"), Collections.singletonList(":mirror:"), Collections.unmodifiableList(Arrays.asList("makeup", "mirror", "reflection", "reflector", "speculum")), false, false, 13.0, Qualification.fromString("fully-qualified"), "mirror", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji WINDOW = new Emoji("\ud83e\ude9f", "\\uD83E\\uDE9F", Collections.singletonList(":window:"), Collections.singletonList(":window:"), Collections.singletonList(":window:"), Collections.unmodifiableList(Arrays.asList("air", "frame", "fresh", "opening", "transparent", "view", "window")), false, false, 13.0, Qualification.fromString("fully-qualified"), "window", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji BED = new Emoji("\ud83d\udecf\ufe0f", "\\uD83D\\uDECF\\uFE0F", Collections.singletonList(":bed:"), Collections.singletonList(":bed:"), Collections.singletonList(":bed:"), Collections.unmodifiableList(Arrays.asList("bed", "hotel", "sleep")), false, false, 0.7, Qualification.fromString("fully-qualified"), "bed", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji BED_UNQUALIFIED = new Emoji("\ud83d\udecf", "\\uD83D\\uDECF", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bed", "hotel", "sleep")), false, false, 0.7, Qualification.fromString("unqualified"), "bed", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, true);
    public static final Emoji COUCH_AND_LAMP = new Emoji("\ud83d\udecb\ufe0f", "\\uD83D\\uDECB\\uFE0F", Collections.unmodifiableList(Arrays.asList(":couch:", ":couch_and_lamp:")), Collections.singletonList(":couch_and_lamp:"), Collections.singletonList(":couch_and_lamp:"), Collections.unmodifiableList(Arrays.asList("couch", "hotel", "lamp")), false, false, 0.7, Qualification.fromString("fully-qualified"), "couch and lamp", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji COUCH_AND_LAMP_UNQUALIFIED = new Emoji("\ud83d\udecb", "\\uD83D\\uDECB", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("couch", "hotel", "lamp")), false, false, 0.7, Qualification.fromString("unqualified"), "couch and lamp", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, true);
    public static final Emoji CHAIR = new Emoji("\ud83e\ude91", "\\uD83E\\uDE91", Collections.singletonList(":chair:"), Collections.singletonList(":chair:"), Collections.singletonList(":chair:"), Collections.unmodifiableList(Arrays.asList("chair", "seat", "sit")), false, false, 12.0, Qualification.fromString("fully-qualified"), "chair", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji TOILET = new Emoji("\ud83d\udebd", "\\uD83D\\uDEBD", Collections.singletonList(":toilet:"), Collections.singletonList(":toilet:"), Collections.singletonList(":toilet:"), Collections.unmodifiableList(Arrays.asList("bathroom", "toilet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "toilet", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji PLUNGER = new Emoji("\ud83e\udea0", "\\uD83E\\uDEA0", Collections.singletonList(":plunger:"), Collections.singletonList(":plunger:"), Collections.singletonList(":plunger:"), Collections.unmodifiableList(Arrays.asList("cup", "force", "plumber", "plunger", "poop", "suction", "toilet")), false, false, 13.0, Qualification.fromString("fully-qualified"), "plunger", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji SHOWER = new Emoji("\ud83d\udebf", "\\uD83D\\uDEBF", Collections.singletonList(":shower:"), Collections.singletonList(":shower:"), Collections.singletonList(":shower:"), Collections.unmodifiableList(Arrays.asList("shower", "water")), false, false, 1.0, Qualification.fromString("fully-qualified"), "shower", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji BATHTUB = new Emoji("\ud83d\udec1", "\\uD83D\\uDEC1", Collections.singletonList(":bathtub:"), Collections.singletonList(":bathtub:"), Collections.singletonList(":bathtub:"), Collections.unmodifiableList(Arrays.asList("bath", "bathtub")), false, false, 1.0, Qualification.fromString("fully-qualified"), "bathtub", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji MOUSE_TRAP = new Emoji("\ud83e\udea4", "\\uD83E\\uDEA4", Collections.singletonList(":mouse_trap:"), Collections.singletonList(":mouse_trap:"), Collections.singletonList(":mouse_trap:"), Collections.unmodifiableList(Arrays.asList("bait", "cheese", "lure", "mouse", "mousetrap", "snare", "trap")), false, false, 13.0, Qualification.fromString("fully-qualified"), "mouse trap", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji RAZOR = new Emoji("\ud83e\ude92", "\\uD83E\\uDE92", Collections.singletonList(":razor:"), Collections.singletonList(":razor:"), Collections.singletonList(":razor:"), Collections.unmodifiableList(Arrays.asList("razor", "sharp", "shave")), false, false, 12.0, Qualification.fromString("fully-qualified"), "razor", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji LOTION_BOTTLE = new Emoji("\ud83e\uddf4", "\\uD83E\\uDDF4", Collections.unmodifiableList(Arrays.asList(":squeeze_bottle:", ":lotion_bottle:")), Collections.singletonList(":lotion_bottle:"), Collections.singletonList(":lotion_bottle:"), Collections.unmodifiableList(Arrays.asList("bottle", "lotion", "moisturizer", "shampoo", "sunscreen")), false, false, 11.0, Qualification.fromString("fully-qualified"), "lotion bottle", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji SAFETY_PIN = new Emoji("\ud83e\uddf7", "\\uD83E\\uDDF7", Collections.singletonList(":safety_pin:"), Collections.singletonList(":safety_pin:"), Collections.singletonList(":safety_pin:"), Collections.unmodifiableList(Arrays.asList("diaper", "pin", "punk", "rock", "safety")), false, false, 11.0, Qualification.fromString("fully-qualified"), "safety pin", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji BROOM = new Emoji("\ud83e\uddf9", "\\uD83E\\uDDF9", Collections.singletonList(":broom:"), Collections.singletonList(":broom:"), Collections.singletonList(":broom:"), Collections.unmodifiableList(Arrays.asList("broom", "cleaning", "sweeping", "witch")), false, false, 11.0, Qualification.fromString("fully-qualified"), "broom", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji BASKET = new Emoji("\ud83e\uddfa", "\\uD83E\\uDDFA", Collections.singletonList(":basket:"), Collections.singletonList(":basket:"), Collections.singletonList(":basket:"), Collections.unmodifiableList(Arrays.asList("basket", "farming", "laundry", "picnic")), false, false, 11.0, Qualification.fromString("fully-qualified"), "basket", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji ROLL_OF_PAPER = new Emoji("\ud83e\uddfb", "\\uD83E\\uDDFB", Collections.singletonList(":roll_of_paper:"), Collections.singletonList(":roll_of_paper:"), Collections.singletonList(":roll_of_paper:"), Collections.unmodifiableList(Arrays.asList("paper", "roll", "toilet", "towels")), false, false, 11.0, Qualification.fromString("fully-qualified"), "roll of paper", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji BUCKET = new Emoji("\ud83e\udea3", "\\uD83E\\uDEA3", Collections.singletonList(":bucket:"), Collections.singletonList(":bucket:"), Collections.singletonList(":bucket:"), Collections.unmodifiableList(Arrays.asList("bucket", "cask", "pail", "vat")), false, false, 13.0, Qualification.fromString("fully-qualified"), "bucket", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji SOAP = new Emoji("\ud83e\uddfc", "\\uD83E\\uDDFC", Collections.singletonList(":soap:"), Collections.singletonList(":soap:"), Collections.singletonList(":soap:"), Collections.unmodifiableList(Arrays.asList("bar", "bathing", "clean", "cleaning", "lather", "soap", "soapdish")), false, false, 11.0, Qualification.fromString("fully-qualified"), "soap", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji BUBBLES = new Emoji("\ud83e\udee7", "\\uD83E\\uDEE7", Collections.singletonList(":bubbles:"), Collections.singletonList(":bubbles:"), Collections.singletonList(":bubbles:"), Collections.unmodifiableList(Arrays.asList("bubble", "bubbles", "burp", "clean", "floating", "pearl", "soap", "underwater")), false, false, 14.0, Qualification.fromString("fully-qualified"), "bubbles", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji TOOTHBRUSH = new Emoji("\ud83e\udea5", "\\uD83E\\uDEA5", Collections.singletonList(":toothbrush:"), Collections.singletonList(":toothbrush:"), Collections.singletonList(":toothbrush:"), Collections.unmodifiableList(Arrays.asList("bathroom", "brush", "clean", "dental", "hygiene", "teeth", "toiletry", "toothbrush")), false, false, 13.0, Qualification.fromString("fully-qualified"), "toothbrush", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji SPONGE = new Emoji("\ud83e\uddfd", "\\uD83E\\uDDFD", Collections.singletonList(":sponge:"), Collections.singletonList(":sponge:"), Collections.singletonList(":sponge:"), Collections.unmodifiableList(Arrays.asList("absorbing", "cleaning", "porous", "soak", "sponge")), false, false, 11.0, Qualification.fromString("fully-qualified"), "sponge", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji FIRE_EXTINGUISHER = new Emoji("\ud83e\uddef", "\\uD83E\\uDDEF", Collections.singletonList(":fire_extinguisher:"), Collections.singletonList(":fire_extinguisher:"), Collections.singletonList(":fire_extinguisher:"), Collections.unmodifiableList(Arrays.asList("extinguish", "extinguisher", "fire", "quench")), false, false, 11.0, Qualification.fromString("fully-qualified"), "fire extinguisher", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
    public static final Emoji SHOPPING_CART = new Emoji("\ud83d\uded2", "\\uD83D\\uDED2", Collections.unmodifiableList(Arrays.asList(":shopping_cart:", ":shopping_trolley:")), Collections.singletonList(":shopping_trolley:"), Collections.singletonList(":shopping_cart:"), Collections.unmodifiableList(Arrays.asList("cart", "shopping", "trolley")), false, false, 3.0, Qualification.fromString("fully-qualified"), "shopping cart", EmojiGroup.OBJECTS, EmojiSubGroup.HOUSEHOLD, false);
}

