/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiWarning {
    public static final Emoji WARNING = new Emoji("\u26a0\ufe0f", "\\u26A0\\uFE0F", Collections.singletonList(":warning:"), Collections.singletonList(":warning:"), Collections.singletonList(":warning:"), Collections.unmodifiableList(Arrays.asList("caution", "warning")), false, false, 0.6, Qualification.fromString("fully-qualified"), "warning", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, false);
    public static final Emoji WARNING_UNQUALIFIED = new Emoji("\u26a0", "\\u26A0", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("caution", "warning")), false, false, 0.6, Qualification.fromString("unqualified"), "warning", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, true);
    public static final Emoji CHILDREN_CROSSING = new Emoji("\ud83d\udeb8", "\\uD83D\\uDEB8", Collections.singletonList(":children_crossing:"), Collections.singletonList(":children_crossing:"), Collections.singletonList(":children_crossing:"), Collections.unmodifiableList(Arrays.asList("child", "children", "crossing", "pedestrian", "traffic")), false, false, 1.0, Qualification.fromString("fully-qualified"), "children crossing", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, false);
    public static final Emoji NO_ENTRY = new Emoji("\u26d4", "\\u26D4", Collections.singletonList(":no_entry:"), Collections.singletonList(":no_entry:"), Collections.singletonList(":no_entry:"), Collections.unmodifiableList(Arrays.asList("do", "entry", "fail", "forbidden", "no", "not", "pass", "prohibited", "traffic")), false, false, 0.6, Qualification.fromString("fully-qualified"), "no entry", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, true);
    public static final Emoji PROHIBITED = new Emoji("\ud83d\udeab", "\\uD83D\\uDEAB", Collections.unmodifiableList(Arrays.asList(":no_entry_sign:", ":prohibited:")), Collections.singletonList(":no_entry_sign:"), Collections.singletonList(":no_entry_sign:"), Collections.unmodifiableList(Arrays.asList("entry", "forbidden", "no", "not", "prohibited", "smoke")), false, false, 0.6, Qualification.fromString("fully-qualified"), "prohibited", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, false);
    public static final Emoji NO_BICYCLES = new Emoji("\ud83d\udeb3", "\\uD83D\\uDEB3", Collections.singletonList(":no_bicycles:"), Collections.singletonList(":no_bicycles:"), Collections.singletonList(":no_bicycles:"), Collections.unmodifiableList(Arrays.asList("bicycle", "bicycles", "bike", "forbidden", "no", "not", "prohibited")), false, false, 1.0, Qualification.fromString("fully-qualified"), "no bicycles", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, false);
    public static final Emoji NO_SMOKING = new Emoji("\ud83d\udead", "\\uD83D\\uDEAD", Collections.singletonList(":no_smoking:"), Collections.singletonList(":no_smoking:"), Collections.singletonList(":no_smoking:"), Collections.unmodifiableList(Arrays.asList("forbidden", "no", "not", "prohibited", "smoke", "smoking")), false, false, 0.6, Qualification.fromString("fully-qualified"), "no smoking", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, true);
    public static final Emoji NO_LITTERING = new Emoji("\ud83d\udeaf", "\\uD83D\\uDEAF", Collections.unmodifiableList(Arrays.asList(":do_not_litter:", ":no_littering:")), Collections.singletonList(":do_not_litter:"), Collections.singletonList(":do_not_litter:"), Collections.unmodifiableList(Arrays.asList("forbidden", "litter", "littering", "no", "not", "prohibited")), false, false, 1.0, Qualification.fromString("fully-qualified"), "no littering", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, false);
    public static final Emoji NON_POTABLE_WATER = new Emoji("\ud83d\udeb1", "\\uD83D\\uDEB1", Collections.singletonList(":non_potable_water:"), Collections.singletonList(":non-potable_water:"), Collections.singletonList(":non-potable_water:"), Collections.unmodifiableList(Arrays.asList("dry", "non-drinking", "non-potable", "prohibited", "water")), false, false, 1.0, Qualification.fromString("fully-qualified"), "non-potable water", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, false);
    public static final Emoji NO_PEDESTRIANS = new Emoji("\ud83d\udeb7", "\\uD83D\\uDEB7", Collections.singletonList(":no_pedestrians:"), Collections.singletonList(":no_pedestrians:"), Collections.singletonList(":no_pedestrians:"), Collections.unmodifiableList(Arrays.asList("forbidden", "no", "not", "pedestrian", "pedestrians", "prohibited")), false, false, 1.0, Qualification.fromString("fully-qualified"), "no pedestrians", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, false);
    public static final Emoji NO_MOBILE_PHONES = new Emoji("\ud83d\udcf5", "\\uD83D\\uDCF5", Collections.singletonList(":no_mobile_phones:"), Collections.singletonList(":no_mobile_phones:"), Collections.singletonList(":no_mobile_phones:"), Collections.unmodifiableList(Arrays.asList("cell", "forbidden", "mobile", "no", "not", "phone", "phones", "prohibited", "telephone")), false, false, 1.0, Qualification.fromString("fully-qualified"), "no mobile phones", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, false);
    public static final Emoji NO_ONE_UNDER_EIGHTEEN = new Emoji("\ud83d\udd1e", "\\uD83D\\uDD1E", Collections.singletonList(":underage:"), Collections.singletonList(":underage:"), Collections.singletonList(":underage:"), Collections.unmodifiableList(Arrays.asList("18", "age", "eighteen", "forbidden", "no", "not", "one", "prohibited", "restriction", "underage")), false, false, 0.6, Qualification.fromString("fully-qualified"), "no one under eighteen", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, false);
    public static final Emoji RADIOACTIVE = new Emoji("\u2622\ufe0f", "\\u2622\\uFE0F", Collections.unmodifiableList(Arrays.asList(":radioactive:", ":radioactive_sign:")), Collections.singletonList(":radioactive_sign:"), Collections.singletonList(":radioactive:"), Collections.unmodifiableList(Arrays.asList("radioactive", "sign")), false, false, 1.0, Qualification.fromString("fully-qualified"), "radioactive", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, false);
    public static final Emoji RADIOACTIVE_UNQUALIFIED = new Emoji("\u2622", "\\u2622", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("radioactive", "sign")), false, false, 1.0, Qualification.fromString("unqualified"), "radioactive", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, true);
    public static final Emoji BIOHAZARD = new Emoji("\u2623\ufe0f", "\\u2623\\uFE0F", Collections.unmodifiableList(Arrays.asList(":biohazard:", ":biohazard_sign:")), Collections.singletonList(":biohazard_sign:"), Collections.singletonList(":biohazard:"), Collections.unmodifiableList(Arrays.asList("biohazard", "sign")), false, false, 1.0, Qualification.fromString("fully-qualified"), "biohazard", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, false);
    public static final Emoji BIOHAZARD_UNQUALIFIED = new Emoji("\u2623", "\\u2623", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("biohazard", "sign")), false, false, 1.0, Qualification.fromString("unqualified"), "biohazard", EmojiGroup.SYMBOLS, EmojiSubGroup.WARNING, true);
}

