/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiFoodFruit {
    public static final Emoji GRAPES = new Emoji("\ud83c\udf47", "\\uD83C\\uDF47", Collections.singletonList(":grapes:"), Collections.singletonList(":grapes:"), Collections.singletonList(":grapes:"), Collections.unmodifiableList(Arrays.asList("Dionysus", "fruit", "grape", "grapes")), false, false, 0.6, Qualification.fromString("fully-qualified"), "grapes", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji MELON = new Emoji("\ud83c\udf48", "\\uD83C\\uDF48", Collections.singletonList(":melon:"), Collections.singletonList(":melon:"), Collections.singletonList(":melon:"), Collections.unmodifiableList(Arrays.asList("cantaloupe", "fruit", "melon")), false, false, 0.6, Qualification.fromString("fully-qualified"), "melon", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji WATERMELON = new Emoji("\ud83c\udf49", "\\uD83C\\uDF49", Collections.singletonList(":watermelon:"), Collections.singletonList(":watermelon:"), Collections.singletonList(":watermelon:"), Collections.unmodifiableList(Arrays.asList("fruit", "watermelon")), false, false, 0.6, Qualification.fromString("fully-qualified"), "watermelon", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji TANGERINE = new Emoji("\ud83c\udf4a", "\\uD83C\\uDF4A", Collections.singletonList(":tangerine:"), Collections.singletonList(":tangerine:"), Collections.unmodifiableList(Arrays.asList(":mandarin:", ":orange:", ":tangerine:")), Collections.unmodifiableList(Arrays.asList("c", "citrus", "fruit", "nectarine", "orange", "tangerine", "vitamin")), false, false, 0.6, Qualification.fromString("fully-qualified"), "tangerine", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji LEMON = new Emoji("\ud83c\udf4b", "\\uD83C\\uDF4B", Collections.singletonList(":lemon:"), Collections.singletonList(":lemon:"), Collections.singletonList(":lemon:"), Collections.unmodifiableList(Arrays.asList("citrus", "fruit", "lemon", "sour")), false, false, 1.0, Qualification.fromString("fully-qualified"), "lemon", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji LIME = new Emoji("\ud83c\udf4b\u200d\ud83d\udfe9", "\\uD83C\\uDF4B\\u200D\\uD83D\\uDFE9", Collections.singletonList(":lime:"), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("acidity", "citrus", "cocktail", "fruit", "garnish", "key", "lime", "margarita", "mojito", "refreshing", "salsa", "sour", "tangy", "tequila", "tropical", "zest")), false, false, 15.1, Qualification.fromString("fully-qualified"), "lime", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji BANANA = new Emoji("\ud83c\udf4c", "\\uD83C\\uDF4C", Collections.singletonList(":banana:"), Collections.singletonList(":banana:"), Collections.singletonList(":banana:"), Collections.unmodifiableList(Arrays.asList("banana", "fruit", "potassium")), false, false, 0.6, Qualification.fromString("fully-qualified"), "banana", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji PINEAPPLE = new Emoji("\ud83c\udf4d", "\\uD83C\\uDF4D", Collections.singletonList(":pineapple:"), Collections.singletonList(":pineapple:"), Collections.singletonList(":pineapple:"), Collections.unmodifiableList(Arrays.asList("colada", "fruit", "pina", "pineapple", "tropical")), false, false, 0.6, Qualification.fromString("fully-qualified"), "pineapple", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji MANGO = new Emoji("\ud83e\udd6d", "\\uD83E\\uDD6D", Collections.singletonList(":mango:"), Collections.singletonList(":mango:"), Collections.singletonList(":mango:"), Collections.unmodifiableList(Arrays.asList("food", "fruit", "mango", "tropical")), false, false, 11.0, Qualification.fromString("fully-qualified"), "mango", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji RED_APPLE = new Emoji("\ud83c\udf4e", "\\uD83C\\uDF4E", Collections.unmodifiableList(Arrays.asList(":apple:", ":red_apple:")), Collections.singletonList(":apple:"), Collections.singletonList(":apple:"), Collections.unmodifiableList(Arrays.asList("apple", "diet", "food", "fruit", "health", "red", "ripe")), false, false, 0.6, Qualification.fromString("fully-qualified"), "red apple", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji GREEN_APPLE = new Emoji("\ud83c\udf4f", "\\uD83C\\uDF4F", Collections.singletonList(":green_apple:"), Collections.singletonList(":green_apple:"), Collections.singletonList(":green_apple:"), Collections.unmodifiableList(Arrays.asList("apple", "fruit", "green")), false, false, 0.6, Qualification.fromString("fully-qualified"), "green apple", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji PEAR = new Emoji("\ud83c\udf50", "\\uD83C\\uDF50", Collections.singletonList(":pear:"), Collections.singletonList(":pear:"), Collections.singletonList(":pear:"), Collections.unmodifiableList(Arrays.asList("fruit", "pear")), false, false, 1.0, Qualification.fromString("fully-qualified"), "pear", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji PEACH = new Emoji("\ud83c\udf51", "\\uD83C\\uDF51", Collections.singletonList(":peach:"), Collections.singletonList(":peach:"), Collections.singletonList(":peach:"), Collections.unmodifiableList(Arrays.asList("fruit", "peach")), false, false, 0.6, Qualification.fromString("fully-qualified"), "peach", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji CHERRIES = new Emoji("\ud83c\udf52", "\\uD83C\\uDF52", Collections.singletonList(":cherries:"), Collections.singletonList(":cherries:"), Collections.singletonList(":cherries:"), Collections.unmodifiableList(Arrays.asList("berries", "cherries", "cherry", "fruit", "red")), false, false, 0.6, Qualification.fromString("fully-qualified"), "cherries", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji STRAWBERRY = new Emoji("\ud83c\udf53", "\\uD83C\\uDF53", Collections.singletonList(":strawberry:"), Collections.singletonList(":strawberry:"), Collections.singletonList(":strawberry:"), Collections.unmodifiableList(Arrays.asList("berry", "fruit", "strawberry")), false, false, 0.6, Qualification.fromString("fully-qualified"), "strawberry", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji BLUEBERRIES = new Emoji("\ud83e\uded0", "\\uD83E\\uDED0", Collections.singletonList(":blueberries:"), Collections.singletonList(":blueberries:"), Collections.singletonList(":blueberries:"), Collections.unmodifiableList(Arrays.asList("berries", "berry", "bilberry", "blue", "blueberries", "blueberry", "food", "fruit")), false, false, 13.0, Qualification.fromString("fully-qualified"), "blueberries", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji KIWI_FRUIT = new Emoji("\ud83e\udd5d", "\\uD83E\\uDD5D", Collections.unmodifiableList(Arrays.asList(":kiwi:", ":kiwifruit:", ":kiwi_fruit:")), Collections.singletonList(":kiwifruit:"), Collections.singletonList(":kiwi_fruit:"), Collections.unmodifiableList(Arrays.asList("food", "fruit", "kiwi")), false, false, 3.0, Qualification.fromString("fully-qualified"), "kiwi fruit", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji TOMATO = new Emoji("\ud83c\udf45", "\\uD83C\\uDF45", Collections.singletonList(":tomato:"), Collections.singletonList(":tomato:"), Collections.singletonList(":tomato:"), Collections.unmodifiableList(Arrays.asList("food", "fruit", "tomato", "vegetable")), false, false, 0.6, Qualification.fromString("fully-qualified"), "tomato", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji OLIVE = new Emoji("\ud83e\uded2", "\\uD83E\\uDED2", Collections.singletonList(":olive:"), Collections.singletonList(":olive:"), Collections.singletonList(":olive:"), Collections.unmodifiableList(Arrays.asList("food", "olive")), false, false, 13.0, Qualification.fromString("fully-qualified"), "olive", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
    public static final Emoji COCONUT = new Emoji("\ud83e\udd65", "\\uD83E\\uDD65", Collections.singletonList(":coconut:"), Collections.singletonList(":coconut:"), Collections.singletonList(":coconut:"), Collections.unmodifiableList(Arrays.asList("coconut", "colada", "palm", "pi\u00f1a")), false, false, 5.0, Qualification.fromString("fully-qualified"), "coconut", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_FRUIT, false);
}

