/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiFaceNeutralSkeptical {
    public static final Emoji ZIPPER_MOUTH_FACE = new Emoji("\ud83e\udd10", "\\uD83E\\uDD10", Collections.unmodifiableList(Arrays.asList(":zipper_mouth:", ":zipper_mouth_face:")), Collections.singletonList(":zipper_mouth_face:"), Collections.singletonList(":zipper_mouth_face:"), Collections.unmodifiableList(Arrays.asList("face", "keep", "mouth", "quiet", "secret", "shut", "zip", "zipper", "zipper-mouth")), false, false, 1.0, Qualification.fromString("fully-qualified"), "zipper-mouth face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji FACE_WITH_RAISED_EYEBROW = new Emoji("\ud83e\udd28", "\\uD83E\\uDD28", Collections.singletonList(":face_with_raised_eyebrow:"), Collections.unmodifiableList(Arrays.asList(":face_with_raised_eyebrow:", ":face_with_one_eyebrow_raised:")), Collections.singletonList(":raised_eyebrow:"), Collections.unmodifiableList(Arrays.asList("disapproval", "disbelief", "distrust", "emoji", "eyebrow", "face", "hmm", "mild", "raised", "skeptic", "skeptical", "skepticism", "surprise", "what")), false, false, 5.0, Qualification.fromString("fully-qualified"), "face with raised eyebrow", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji NEUTRAL_FACE = new Emoji("\ud83d\ude10", "\\uD83D\\uDE10", Collections.unmodifiableList(Arrays.asList(":neutral_face:", ":|", ":-|", "=|", "=-|")), Collections.singletonList(":neutral_face:"), Collections.singletonList(":neutral_face:"), Collections.unmodifiableList(Arrays.asList("awkward", "blank", "deadpan", "expressionless", "face", "fine", "jealous", "meh", "neutral", "oh", "shade", "straight", "unamused", "unhappy", "unimpressed", "whatever")), false, false, 0.7, Qualification.fromString("fully-qualified"), "neutral face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, true);
    public static final Emoji EXPRESSIONLESS_FACE = new Emoji("\ud83d\ude11", "\\uD83D\\uDE11", Collections.singletonList(":expressionless:"), Collections.singletonList(":expressionless:"), Collections.singletonList(":expressionless:"), Collections.unmodifiableList(Arrays.asList("awkward", "dead", "expressionless", "face", "fine", "inexpressive", "jealous", "meh", "not", "oh", "omg", "straight", "uh", "unhappy", "unimpressed", "whatever")), false, false, 1.0, Qualification.fromString("fully-qualified"), "expressionless face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji FACE_WITHOUT_MOUTH = new Emoji("\ud83d\ude36", "\\uD83D\\uDE36", Collections.singletonList(":no_mouth:"), Collections.singletonList(":no_mouth:"), Collections.singletonList(":no_mouth:"), Collections.unmodifiableList(Arrays.asList("awkward", "blank", "expressionless", "face", "mouth", "mouthless", "mute", "quiet", "secret", "silence", "silent", "speechless")), false, false, 1.0, Qualification.fromString("fully-qualified"), "face without mouth", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji DOTTED_LINE_FACE = new Emoji("\ud83e\udee5", "\\uD83E\\uDEE5", Collections.singletonList(":dotted_line_face:"), Collections.singletonList(":dotted_line_face:"), Collections.singletonList(":dotted_line_face:"), Collections.unmodifiableList(Arrays.asList("depressed", "disappear", "dotted", "face", "hidden", "hide", "introvert", "invisible", "line", "meh", "whatever", "wtv")), false, false, 14.0, Qualification.fromString("fully-qualified"), "dotted line face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji FACE_IN_CLOUDS = new Emoji("\ud83d\ude36\u200d\ud83c\udf2b\ufe0f", "\\uD83D\\uDE36\\u200D\\uD83C\\uDF2B\\uFE0F", Collections.singletonList(":face_in_clouds:"), Collections.singletonList(":face_in_clouds:"), Collections.singletonList(":face_in_clouds:"), Collections.unmodifiableList(Arrays.asList("absentminded", "clouds", "face", "fog", "head")), false, false, 13.1, Qualification.fromString("fully-qualified"), "face in clouds", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji FACE_IN_CLOUDS_MINIMALLY_QUALIFIED = new Emoji("\ud83d\ude36\u200d\ud83c\udf2b", "\\uD83D\\uDE36\\u200D\\uD83C\\uDF2B", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("absentminded", "clouds", "face", "fog", "head")), false, false, 13.1, Qualification.fromString("minimally-qualified"), "face in clouds", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji SMIRKING_FACE = new Emoji("\ud83d\ude0f", "\\uD83D\\uDE0F", Collections.unmodifiableList(Arrays.asList(":smirk:", ":smirking_face:")), Collections.singletonList(":smirk:"), Collections.singletonList(":smirk:"), Collections.unmodifiableList(Arrays.asList("boss", "dapper", "face", "flirt", "homie", "kidding", "leer", "shade", "slick", "sly", "smirk", "smug", "snicker", "suave", "suspicious", "swag")), false, false, 0.6, Qualification.fromString("fully-qualified"), "smirking face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji UNAMUSED_FACE = new Emoji("\ud83d\ude12", "\\uD83D\\uDE12", Collections.unmodifiableList(Arrays.asList(":unamused:", ":unamused_face:", ":s", ":-S", ":z", ":-Z", ":$", ":-$", "=s", "=-S", "=z", "=-Z", "=$", "=-$")), Collections.singletonList(":unamused:"), Collections.singletonList(":unamused:"), Collections.unmodifiableList(Arrays.asList("...", "bored", "face", "fine", "jealous", "jel", "jelly", "pissed", "smh", "ugh", "uhh", "unamused", "unhappy", "weird", "whatever")), false, false, 0.6, Qualification.fromString("fully-qualified"), "unamused face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji FACE_WITH_ROLLING_EYES = new Emoji("\ud83d\ude44", "\\uD83D\\uDE44", Collections.unmodifiableList(Arrays.asList(":rolling_eyes:", ":face_with_rolling_eyes:")), Collections.singletonList(":face_with_rolling_eyes:"), Collections.singletonList(":roll_eyes:"), Collections.unmodifiableList(Arrays.asList("eyeroll", "eyes", "face", "rolling", "shade", "ugh", "whatever")), false, false, 1.0, Qualification.fromString("fully-qualified"), "face with rolling eyes", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji GRIMACING_FACE = new Emoji("\ud83d\ude2c", "\\uD83D\\uDE2C", Collections.singletonList(":grimacing:"), Collections.singletonList(":grimacing:"), Collections.singletonList(":grimacing:"), Collections.unmodifiableList(Arrays.asList("awk", "awkward", "dentist", "face", "grimace", "grimacing", "grinning", "smile", "smiling")), false, false, 1.0, Qualification.fromString("fully-qualified"), "grimacing face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji FACE_EXHALING = new Emoji("\ud83d\ude2e\u200d\ud83d\udca8", "\\uD83D\\uDE2E\\u200D\\uD83D\\uDCA8", Collections.singletonList(":face_exhaling:"), Collections.singletonList(":face_exhaling:"), Collections.singletonList(":face_exhaling:"), Collections.unmodifiableList(Arrays.asList("blow", "blowing", "exhale", "exhaling", "exhausted", "face", "gasp", "groan", "relief", "sigh", "smiley", "smoke", "whisper", "whistle")), false, false, 13.1, Qualification.fromString("fully-qualified"), "face exhaling", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji LYING_FACE = new Emoji("\ud83e\udd25", "\\uD83E\\uDD25", Collections.unmodifiableList(Arrays.asList(":lying_face:", ":liar:")), Collections.singletonList(":lying_face:"), Collections.singletonList(":lying_face:"), Collections.unmodifiableList(Arrays.asList("face", "liar", "lie", "lying", "pinocchio")), false, false, 3.0, Qualification.fromString("fully-qualified"), "lying face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji SHAKING_FACE = new Emoji("\ud83e\udee8", "\\uD83E\\uDEE8", Collections.singletonList(":shaking_face:"), Collections.emptyList(), Collections.singletonList(":shaking_face:"), Collections.unmodifiableList(Arrays.asList("crazy", "daze", "earthquake", "face", "omg", "panic", "shaking", "shock", "surprise", "vibrate", "whoa", "wow")), false, false, 15.0, Qualification.fromString("fully-qualified"), "shaking face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji HEAD_SHAKING_HORIZONTALLY = new Emoji("\ud83d\ude42\u200d\u2194\ufe0f", "\\uD83D\\uDE42\\u200D\\u2194\\uFE0F", Collections.singletonList(":head_shaking_horizontally:"), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("head", "horizontally", "no", "shake", "shaking")), false, false, 15.1, Qualification.fromString("fully-qualified"), "head shaking horizontally", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji HEAD_SHAKING_HORIZONTALLY_MINIMALLY_QUALIFIED = new Emoji("\ud83d\ude42\u200d\u2194", "\\uD83D\\uDE42\\u200D\\u2194", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("head", "horizontally", "no", "shake", "shaking")), false, false, 15.1, Qualification.fromString("minimally-qualified"), "head shaking horizontally", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji HEAD_SHAKING_VERTICALLY = new Emoji("\ud83d\ude42\u200d\u2195\ufe0f", "\\uD83D\\uDE42\\u200D\\u2195\\uFE0F", Collections.singletonList(":head_shaking_vertically:"), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("head", "nod", "shaking", "vertically", "yes")), false, false, 15.1, Qualification.fromString("fully-qualified"), "head shaking vertically", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
    public static final Emoji HEAD_SHAKING_VERTICALLY_MINIMALLY_QUALIFIED = new Emoji("\ud83d\ude42\u200d\u2195", "\\uD83D\\uDE42\\u200D\\u2195", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("head", "nod", "shaking", "vertically", "yes")), false, false, 15.1, Qualification.fromString("minimally-qualified"), "head shaking vertically", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEUTRAL_SKEPTICAL, false);
}

