/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiArrow {
    public static final Emoji UP_ARROW = new Emoji("\u2b06\ufe0f", "\\u2B06\\uFE0F", Collections.unmodifiableList(Arrays.asList(":arrow_up:", ":up_arrow:")), Collections.singletonList(":arrow_up:"), Collections.singletonList(":arrow_up:"), Collections.unmodifiableList(Arrays.asList("arrow", "cardinal", "direction", "north", "up")), false, false, 0.6, Qualification.fromString("fully-qualified"), "up arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji UP_ARROW_UNQUALIFIED = new Emoji("\u2b06", "\\u2B06", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "cardinal", "direction", "north", "up")), false, false, 0.6, Qualification.fromString("unqualified"), "up arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji UP_RIGHT_ARROW = new Emoji("\u2197\ufe0f", "\\u2197\\uFE0F", Collections.singletonList(":arrow_upper_right:"), Collections.singletonList(":arrow_upper_right:"), Collections.singletonList(":arrow_upper_right:"), Collections.unmodifiableList(Arrays.asList("arrow", "direction", "intercardinal", "northeast", "up-right")), false, false, 0.6, Qualification.fromString("fully-qualified"), "up-right arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji UP_RIGHT_ARROW_UNQUALIFIED = new Emoji("\u2197", "\\u2197", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "direction", "intercardinal", "northeast", "up-right")), false, false, 0.6, Qualification.fromString("unqualified"), "up-right arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji RIGHT_ARROW = new Emoji("\u27a1\ufe0f", "\\u27A1\\uFE0F", Collections.unmodifiableList(Arrays.asList(":arrow_right:", ":right_arrow:")), Collections.singletonList(":arrow_right:"), Collections.singletonList(":arrow_right:"), Collections.unmodifiableList(Arrays.asList("arrow", "cardinal", "direction", "east", "right")), false, false, 0.6, Qualification.fromString("fully-qualified"), "right arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji RIGHT_ARROW_UNQUALIFIED = new Emoji("\u27a1", "\\u27A1", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "cardinal", "direction", "east", "right")), false, false, 0.6, Qualification.fromString("unqualified"), "right arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji DOWN_RIGHT_ARROW = new Emoji("\u2198\ufe0f", "\\u2198\\uFE0F", Collections.singletonList(":arrow_lower_right:"), Collections.singletonList(":arrow_lower_right:"), Collections.singletonList(":arrow_lower_right:"), Collections.unmodifiableList(Arrays.asList("arrow", "direction", "down-right", "intercardinal", "southeast")), false, false, 0.6, Qualification.fromString("fully-qualified"), "down-right arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji DOWN_RIGHT_ARROW_UNQUALIFIED = new Emoji("\u2198", "\\u2198", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "direction", "down-right", "intercardinal", "southeast")), false, false, 0.6, Qualification.fromString("unqualified"), "down-right arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji DOWN_ARROW = new Emoji("\u2b07\ufe0f", "\\u2B07\\uFE0F", Collections.unmodifiableList(Arrays.asList(":arrow_down:", ":down_arrow:")), Collections.singletonList(":arrow_down:"), Collections.singletonList(":arrow_down:"), Collections.unmodifiableList(Arrays.asList("arrow", "cardinal", "direction", "down", "south")), false, false, 0.6, Qualification.fromString("fully-qualified"), "down arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji DOWN_ARROW_UNQUALIFIED = new Emoji("\u2b07", "\\u2B07", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "cardinal", "direction", "down", "south")), false, false, 0.6, Qualification.fromString("unqualified"), "down arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji DOWN_LEFT_ARROW = new Emoji("\u2199\ufe0f", "\\u2199\\uFE0F", Collections.singletonList(":arrow_lower_left:"), Collections.singletonList(":arrow_lower_left:"), Collections.singletonList(":arrow_lower_left:"), Collections.unmodifiableList(Arrays.asList("arrow", "direction", "down-left", "intercardinal", "southwest")), false, false, 0.6, Qualification.fromString("fully-qualified"), "down-left arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji DOWN_LEFT_ARROW_UNQUALIFIED = new Emoji("\u2199", "\\u2199", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "direction", "down-left", "intercardinal", "southwest")), false, false, 0.6, Qualification.fromString("unqualified"), "down-left arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji LEFT_ARROW = new Emoji("\u2b05\ufe0f", "\\u2B05\\uFE0F", Collections.unmodifiableList(Arrays.asList(":arrow_left:", ":left_arrow:")), Collections.singletonList(":arrow_left:"), Collections.singletonList(":arrow_left:"), Collections.unmodifiableList(Arrays.asList("arrow", "cardinal", "direction", "left", "west")), false, false, 0.6, Qualification.fromString("fully-qualified"), "left arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji LEFT_ARROW_UNQUALIFIED = new Emoji("\u2b05", "\\u2B05", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "cardinal", "direction", "left", "west")), false, false, 0.6, Qualification.fromString("unqualified"), "left arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji UP_LEFT_ARROW = new Emoji("\u2196\ufe0f", "\\u2196\\uFE0F", Collections.unmodifiableList(Arrays.asList(":arrow_upper_left:", ":up_left_arrow:")), Collections.singletonList(":arrow_upper_left:"), Collections.singletonList(":arrow_upper_left:"), Collections.unmodifiableList(Arrays.asList("arrow", "direction", "intercardinal", "northwest", "up-left")), false, false, 0.6, Qualification.fromString("fully-qualified"), "up-left arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji UP_LEFT_ARROW_UNQUALIFIED = new Emoji("\u2196", "\\u2196", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "direction", "intercardinal", "northwest", "up-left")), false, false, 0.6, Qualification.fromString("unqualified"), "up-left arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji UP_DOWN_ARROW = new Emoji("\u2195\ufe0f", "\\u2195\\uFE0F", Collections.unmodifiableList(Arrays.asList(":arrow_up_down:", ":up_down_arrow:")), Collections.singletonList(":arrow_up_down:"), Collections.singletonList(":arrow_up_down:"), Collections.unmodifiableList(Arrays.asList("arrow", "up-down")), false, false, 0.6, Qualification.fromString("fully-qualified"), "up-down arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji UP_DOWN_ARROW_UNQUALIFIED = new Emoji("\u2195", "\\u2195", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "up-down")), false, false, 0.6, Qualification.fromString("unqualified"), "up-down arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji LEFT_RIGHT_ARROW = new Emoji("\u2194\ufe0f", "\\u2194\\uFE0F", Collections.singletonList(":left_right_arrow:"), Collections.singletonList(":left_right_arrow:"), Collections.singletonList(":left_right_arrow:"), Collections.unmodifiableList(Arrays.asList("arrow", "left-right")), false, false, 0.6, Qualification.fromString("fully-qualified"), "left-right arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji LEFT_RIGHT_ARROW_UNQUALIFIED = new Emoji("\u2194", "\\u2194", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "left-right")), false, false, 0.6, Qualification.fromString("unqualified"), "left-right arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji RIGHT_ARROW_CURVING_LEFT = new Emoji("\u21a9\ufe0f", "\\u21A9\\uFE0F", Collections.singletonList(":leftwards_arrow_with_hook:"), Collections.singletonList(":leftwards_arrow_with_hook:"), Collections.singletonList(":leftwards_arrow_with_hook:"), Collections.unmodifiableList(Arrays.asList("arrow", "curving", "left", "right")), false, false, 0.6, Qualification.fromString("fully-qualified"), "right arrow curving left", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji RIGHT_ARROW_CURVING_LEFT_UNQUALIFIED = new Emoji("\u21a9", "\\u21A9", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "curving", "left", "right")), false, false, 0.6, Qualification.fromString("unqualified"), "right arrow curving left", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji LEFT_ARROW_CURVING_RIGHT = new Emoji("\u21aa\ufe0f", "\\u21AA\\uFE0F", Collections.singletonList(":arrow_right_hook:"), Collections.singletonList(":arrow_right_hook:"), Collections.singletonList(":arrow_right_hook:"), Collections.unmodifiableList(Arrays.asList("arrow", "curving", "left", "right")), false, false, 0.6, Qualification.fromString("fully-qualified"), "left arrow curving right", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji LEFT_ARROW_CURVING_RIGHT_UNQUALIFIED = new Emoji("\u21aa", "\\u21AA", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "curving", "left", "right")), false, false, 0.6, Qualification.fromString("unqualified"), "left arrow curving right", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji RIGHT_ARROW_CURVING_UP = new Emoji("\u2934\ufe0f", "\\u2934\\uFE0F", Collections.singletonList(":arrow_heading_up:"), Collections.singletonList(":arrow_heading_up:"), Collections.singletonList(":arrow_heading_up:"), Collections.unmodifiableList(Arrays.asList("arrow", "curving", "right", "up")), false, false, 0.6, Qualification.fromString("fully-qualified"), "right arrow curving up", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji RIGHT_ARROW_CURVING_UP_UNQUALIFIED = new Emoji("\u2934", "\\u2934", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "curving", "right", "up")), false, false, 0.6, Qualification.fromString("unqualified"), "right arrow curving up", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji RIGHT_ARROW_CURVING_DOWN = new Emoji("\u2935\ufe0f", "\\u2935\\uFE0F", Collections.singletonList(":arrow_heading_down:"), Collections.singletonList(":arrow_heading_down:"), Collections.singletonList(":arrow_heading_down:"), Collections.unmodifiableList(Arrays.asList("arrow", "curving", "down", "right")), false, false, 0.6, Qualification.fromString("fully-qualified"), "right arrow curving down", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji RIGHT_ARROW_CURVING_DOWN_UNQUALIFIED = new Emoji("\u2935", "\\u2935", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "curving", "down", "right")), false, false, 0.6, Qualification.fromString("unqualified"), "right arrow curving down", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, true);
    public static final Emoji CLOCKWISE_VERTICAL_ARROWS = new Emoji("\ud83d\udd03", "\\uD83D\\uDD03", Collections.singletonList(":arrows_clockwise:"), Collections.singletonList(":arrows_clockwise:"), Collections.singletonList(":arrows_clockwise:"), Collections.unmodifiableList(Arrays.asList("arrow", "arrows", "clockwise", "refresh", "reload", "vertical")), false, false, 0.6, Qualification.fromString("fully-qualified"), "clockwise vertical arrows", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji COUNTERCLOCKWISE_ARROWS_BUTTON = new Emoji("\ud83d\udd04", "\\uD83D\\uDD04", Collections.singletonList(":arrows_counterclockwise:"), Collections.singletonList(":arrows_counterclockwise:"), Collections.singletonList(":arrows_counterclockwise:"), Collections.unmodifiableList(Arrays.asList("again", "anticlockwise", "arrow", "arrows", "button", "counterclockwise", "deja", "refresh", "rewindershins", "vu")), false, false, 1.0, Qualification.fromString("fully-qualified"), "counterclockwise arrows button", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji BACK_ARROW = new Emoji("\ud83d\udd19", "\\uD83D\\uDD19", Collections.unmodifiableList(Arrays.asList(":back:", ":back_arrow:")), Collections.singletonList(":back:"), Collections.singletonList(":back:"), Collections.unmodifiableList(Arrays.asList("arrow", "BACK")), false, false, 0.6, Qualification.fromString("fully-qualified"), "BACK arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji END_ARROW = new Emoji("\ud83d\udd1a", "\\uD83D\\uDD1A", Collections.unmodifiableList(Arrays.asList(":end:", ":end_arrow:")), Collections.singletonList(":end:"), Collections.singletonList(":end:"), Collections.unmodifiableList(Arrays.asList("arrow", "END")), false, false, 0.6, Qualification.fromString("fully-qualified"), "END arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji ON_ARROW = new Emoji("\ud83d\udd1b", "\\uD83D\\uDD1B", Collections.unmodifiableList(Arrays.asList(":on:", ":on_arrow:")), Collections.singletonList(":on:"), Collections.singletonList(":on:"), Collections.unmodifiableList(Arrays.asList("arrow", "mark", "ON!")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ON! arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji SOON_ARROW = new Emoji("\ud83d\udd1c", "\\uD83D\\uDD1C", Collections.unmodifiableList(Arrays.asList(":soon:", ":soon_arrow:")), Collections.singletonList(":soon:"), Collections.singletonList(":soon:"), Collections.unmodifiableList(Arrays.asList("arrow", "brb", "omw", "SOON")), false, false, 0.6, Qualification.fromString("fully-qualified"), "SOON arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
    public static final Emoji TOP_ARROW = new Emoji("\ud83d\udd1d", "\\uD83D\\uDD1D", Collections.unmodifiableList(Arrays.asList(":top:", ":top_arrow:")), Collections.singletonList(":top:"), Collections.singletonList(":top:"), Collections.unmodifiableList(Arrays.asList("arrow", "homie", "TOP", "up")), false, false, 0.6, Qualification.fromString("fully-qualified"), "TOP arrow", EmojiGroup.SYMBOLS, EmojiSubGroup.ARROW, false);
}

