/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiFaceAffection {
    public static final Emoji SMILING_FACE_WITH_HEARTS = new Emoji("\ud83e\udd70", "\\uD83E\\uDD70", Collections.singletonList(":smiling_face_with_3_hearts:"), Collections.singletonList(":smiling_face_with_3_hearts:"), Collections.singletonList(":smiling_face_with_three_hearts:"), Collections.unmodifiableList(Arrays.asList("3", "adore", "crush", "face", "heart", "hearts", "ily", "love", "romance", "smile", "smiling", "you")), false, false, 11.0, Qualification.fromString("fully-qualified"), "smiling face with hearts", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_AFFECTION, false);
    public static final Emoji SMILING_FACE_WITH_HEART_EYES = new Emoji("\ud83d\ude0d", "\\uD83D\\uDE0D", Collections.singletonList(":heart_eyes:"), Collections.singletonList(":heart_eyes:"), Collections.singletonList(":heart_eyes:"), Collections.unmodifiableList(Arrays.asList("143", "bae", "eye", "face", "feels", "heart-eyes", "hearts", "ily", "kisses", "love", "romance", "romantic", "smile", "xoxo")), false, false, 0.6, Qualification.fromString("fully-qualified"), "smiling face with heart-eyes", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_AFFECTION, false);
    public static final Emoji STAR_STRUCK = new Emoji("\ud83e\udd29", "\\uD83E\\uDD29", Collections.singletonList(":star_struck:"), Collections.unmodifiableList(Arrays.asList(":star-struck:", ":grinning_face_with_star_eyes:")), Collections.singletonList(":star_struck:"), Collections.unmodifiableList(Arrays.asList("excited", "eyes", "face", "grinning", "smile", "star", "star-struck", "starry-eyed", "wow")), false, false, 5.0, Qualification.fromString("fully-qualified"), "star-struck", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_AFFECTION, false);
    public static final Emoji FACE_BLOWING_A_KISS = new Emoji("\ud83d\ude18", "\\uD83D\\uDE18", Collections.singletonList(":kissing_heart:"), Collections.singletonList(":kissing_heart:"), Collections.singletonList(":kissing_heart:"), Collections.unmodifiableList(Arrays.asList("adorbs", "bae", "blowing", "face", "flirt", "heart", "ily", "kiss", "love", "lover", "miss", "muah", "romantic", "smooch", "xoxo", "you")), false, false, 0.6, Qualification.fromString("fully-qualified"), "face blowing a kiss", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_AFFECTION, false);
    public static final Emoji KISSING_FACE = new Emoji("\ud83d\ude17", "\\uD83D\\uDE17", Collections.unmodifiableList(Arrays.asList(":kissing:", ":kissing_face:", ":*", ":-*", "=*", "=-*")), Collections.singletonList(":kissing:"), Collections.singletonList(":kissing:"), Collections.unmodifiableList(Arrays.asList("143", "date", "dating", "face", "flirt", "ily", "kiss", "love", "smooch", "smooches", "xoxo", "you")), false, false, 1.0, Qualification.fromString("fully-qualified"), "kissing face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_AFFECTION, false);
    public static final Emoji SMILING_FACE = new Emoji("\u263a\ufe0f", "\\u263A\\uFE0F", Collections.unmodifiableList(Arrays.asList(":relaxed:", ":smiling_face:")), Collections.singletonList(":relaxed:"), Collections.singletonList(":relaxed:"), Collections.unmodifiableList(Arrays.asList("face", "happy", "outlined", "relaxed", "smile", "smiling")), false, false, 0.6, Qualification.fromString("fully-qualified"), "smiling face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_AFFECTION, false);
    public static final Emoji SMILING_FACE_UNQUALIFIED = new Emoji("\u263a", "\\u263A", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("face", "happy", "outlined", "relaxed", "smile", "smiling")), false, false, 0.6, Qualification.fromString("unqualified"), "smiling face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_AFFECTION, true);
    public static final Emoji KISSING_FACE_WITH_CLOSED_EYES = new Emoji("\ud83d\ude1a", "\\uD83D\\uDE1A", Collections.singletonList(":kissing_closed_eyes:"), Collections.singletonList(":kissing_closed_eyes:"), Collections.singletonList(":kissing_closed_eyes:"), Collections.unmodifiableList(Arrays.asList("143", "bae", "blush", "closed", "date", "dating", "eye", "eyes", "face", "flirt", "ily", "kisses", "kissing", "smooches", "xoxo")), false, false, 0.6, Qualification.fromString("fully-qualified"), "kissing face with closed eyes", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_AFFECTION, false);
    public static final Emoji KISSING_FACE_WITH_SMILING_EYES = new Emoji("\ud83d\ude19", "\\uD83D\\uDE19", Collections.singletonList(":kissing_smiling_eyes:"), Collections.singletonList(":kissing_smiling_eyes:"), Collections.singletonList(":kissing_smiling_eyes:"), Collections.unmodifiableList(Arrays.asList("143", "closed", "date", "dating", "eye", "eyes", "face", "flirt", "ily", "kiss", "kisses", "kissing", "love", "night", "smile", "smiling")), false, false, 1.0, Qualification.fromString("fully-qualified"), "kissing face with smiling eyes", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_AFFECTION, false);
    public static final Emoji SMILING_FACE_WITH_TEAR = new Emoji("\ud83e\udd72", "\\uD83E\\uDD72", Collections.unmodifiableList(Arrays.asList(":smiling_face_with_tear:", ":')", ":'-)", ":,)", ":,-)", "=')", "='-)", "=,)", "=,-)")), Collections.singletonList(":smiling_face_with_tear:"), Collections.singletonList(":smiling_face_with_tear:"), Collections.unmodifiableList(Arrays.asList("face", "glad", "grateful", "happy", "joy", "pain", "proud", "relieved", "smile", "smiley", "smiling", "tear", "touched")), false, false, 13.0, Qualification.fromString("fully-qualified"), "smiling face with tear", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_AFFECTION, false);
}

