/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiAlphanum {
    public static final Emoji INPUT_LATIN_UPPERCASE = new Emoji("\ud83d\udd20", "\\uD83D\\uDD20", Collections.singletonList(":capital_abcd:"), Collections.singletonList(":capital_abcd:"), Collections.singletonList(":capital_abcd:"), Collections.unmodifiableList(Arrays.asList("ABCD", "input", "latin", "letters", "uppercase")), false, false, 0.6, Qualification.fromString("fully-qualified"), "input latin uppercase", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji INPUT_LATIN_LOWERCASE = new Emoji("\ud83d\udd21", "\\uD83D\\uDD21", Collections.singletonList(":abcd:"), Collections.singletonList(":abcd:"), Collections.singletonList(":abcd:"), Collections.unmodifiableList(Arrays.asList("abcd", "input", "latin", "letters", "lowercase")), false, false, 0.6, Qualification.fromString("fully-qualified"), "input latin lowercase", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji INPUT_NUMBERS = new Emoji("\ud83d\udd22", "\\uD83D\\uDD22", Collections.unmodifiableList(Arrays.asList(":1234:", ":input_numbers:")), Collections.singletonList(":1234:"), Collections.singletonList(":1234:"), Collections.unmodifiableList(Arrays.asList("1234", "input", "numbers")), false, false, 0.6, Qualification.fromString("fully-qualified"), "input numbers", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji INPUT_SYMBOLS = new Emoji("\ud83d\udd23", "\\uD83D\\uDD23", Collections.unmodifiableList(Arrays.asList(":symbols:", ":input_symbols:")), Collections.singletonList(":symbols:"), Collections.singletonList(":symbols:"), Collections.unmodifiableList(Arrays.asList("&", "%", "\u266a", "\u3012", "input", "symbols")), false, false, 0.6, Qualification.fromString("fully-qualified"), "input symbols", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji INPUT_LATIN_LETTERS = new Emoji("\ud83d\udd24", "\\uD83D\\uDD24", Collections.singletonList(":abc:"), Collections.singletonList(":abc:"), Collections.singletonList(":abc:"), Collections.unmodifiableList(Arrays.asList("abc", "alphabet", "input", "latin", "letters")), false, false, 0.6, Qualification.fromString("fully-qualified"), "input latin letters", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji A_BUTTON_BLOOD_TYPE = new Emoji("\ud83c\udd70\ufe0f", "\\uD83C\\uDD70\\uFE0F", Collections.singletonList(":a:"), Collections.singletonList(":a:"), Collections.singletonList(":a:"), Collections.unmodifiableList(Arrays.asList("blood", "button", "type")), false, false, 0.6, Qualification.fromString("fully-qualified"), "A button (blood type)", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji A_BUTTON_BLOOD_TYPE_UNQUALIFIED = new Emoji("\ud83c\udd70", "\\uD83C\\uDD70", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("blood", "button", "type")), false, false, 0.6, Qualification.fromString("unqualified"), "A button (blood type)", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, true);
    public static final Emoji AB_BUTTON_BLOOD_TYPE = new Emoji("\ud83c\udd8e", "\\uD83C\\uDD8E", Collections.singletonList(":ab:"), Collections.singletonList(":ab:"), Collections.singletonList(":ab:"), Collections.unmodifiableList(Arrays.asList("AB", "blood", "button", "type")), false, false, 0.6, Qualification.fromString("fully-qualified"), "AB button (blood type)", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji B_BUTTON_BLOOD_TYPE = new Emoji("\ud83c\udd71\ufe0f", "\\uD83C\\uDD71\\uFE0F", Collections.singletonList(":b:"), Collections.singletonList(":b:"), Collections.singletonList(":b:"), Collections.unmodifiableList(Arrays.asList("B", "blood", "button", "type")), false, false, 0.6, Qualification.fromString("fully-qualified"), "B button (blood type)", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji B_BUTTON_BLOOD_TYPE_UNQUALIFIED = new Emoji("\ud83c\udd71", "\\uD83C\\uDD71", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("B", "blood", "button", "type")), false, false, 0.6, Qualification.fromString("unqualified"), "B button (blood type)", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, true);
    public static final Emoji CL_BUTTON = new Emoji("\ud83c\udd91", "\\uD83C\\uDD91", Collections.singletonList(":cl:"), Collections.singletonList(":cl:"), Collections.singletonList(":cl:"), Collections.unmodifiableList(Arrays.asList("button", "CL")), false, false, 0.6, Qualification.fromString("fully-qualified"), "CL button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji COOL_BUTTON = new Emoji("\ud83c\udd92", "\\uD83C\\uDD92", Collections.singletonList(":cool:"), Collections.singletonList(":cool:"), Collections.singletonList(":cool:"), Collections.unmodifiableList(Arrays.asList("button", "COOL")), false, false, 0.6, Qualification.fromString("fully-qualified"), "COOL button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji FREE_BUTTON = new Emoji("\ud83c\udd93", "\\uD83C\\uDD93", Collections.singletonList(":free:"), Collections.singletonList(":free:"), Collections.singletonList(":free:"), Collections.unmodifiableList(Arrays.asList("button", "FREE")), false, false, 0.6, Qualification.fromString("fully-qualified"), "FREE button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji INFORMATION = new Emoji("\u2139\ufe0f", "\\u2139\\uFE0F", Collections.unmodifiableList(Arrays.asList(":information_source:", ":information:")), Collections.singletonList(":information_source:"), Collections.singletonList(":information_source:"), Collections.unmodifiableList(Arrays.asList("I", "information")), false, false, 0.6, Qualification.fromString("fully-qualified"), "information", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji INFORMATION_UNQUALIFIED = new Emoji("\u2139", "\\u2139", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("I", "information")), false, false, 0.6, Qualification.fromString("unqualified"), "information", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, true);
    public static final Emoji ID_BUTTON = new Emoji("\ud83c\udd94", "\\uD83C\\uDD94", Collections.singletonList(":id:"), Collections.singletonList(":id:"), Collections.singletonList(":id:"), Collections.unmodifiableList(Arrays.asList("button", "ID", "identity")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ID button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji CIRCLED_M = new Emoji("\u24c2\ufe0f", "\\u24C2\\uFE0F", Collections.unmodifiableList(Arrays.asList(":m:", ":circled_m:")), Collections.singletonList(":m:"), Collections.singletonList(":m:"), Collections.unmodifiableList(Arrays.asList("circle", "circled", "M")), false, false, 0.6, Qualification.fromString("fully-qualified"), "circled M", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji CIRCLED_M_UNQUALIFIED = new Emoji("\u24c2", "\\u24C2", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("circle", "circled", "M")), false, false, 0.6, Qualification.fromString("unqualified"), "circled M", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, true);
    public static final Emoji NEW_BUTTON = new Emoji("\ud83c\udd95", "\\uD83C\\uDD95", Collections.singletonList(":new:"), Collections.singletonList(":new:"), Collections.singletonList(":new:"), Collections.unmodifiableList(Arrays.asList("button", "NEW")), false, false, 0.6, Qualification.fromString("fully-qualified"), "NEW button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji NG_BUTTON = new Emoji("\ud83c\udd96", "\\uD83C\\uDD96", Collections.singletonList(":ng:"), Collections.singletonList(":ng:"), Collections.singletonList(":ng:"), Collections.unmodifiableList(Arrays.asList("button", "NG")), false, false, 0.6, Qualification.fromString("fully-qualified"), "NG button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji O_BUTTON_BLOOD_TYPE = new Emoji("\ud83c\udd7e\ufe0f", "\\uD83C\\uDD7E\\uFE0F", Collections.singletonList(":o2:"), Collections.singletonList(":o2:"), Collections.singletonList(":o2:"), Collections.unmodifiableList(Arrays.asList("blood", "button", "O", "type")), false, false, 0.6, Qualification.fromString("fully-qualified"), "O button (blood type)", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji O_BUTTON_BLOOD_TYPE_UNQUALIFIED = new Emoji("\ud83c\udd7e", "\\uD83C\\uDD7E", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("blood", "button", "O", "type")), false, false, 0.6, Qualification.fromString("unqualified"), "O button (blood type)", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, true);
    public static final Emoji OK_BUTTON = new Emoji("\ud83c\udd97", "\\uD83C\\uDD97", Collections.singletonList(":ok:"), Collections.singletonList(":ok:"), Collections.singletonList(":ok:"), Collections.unmodifiableList(Arrays.asList("button", "OK", "okay")), false, false, 0.6, Qualification.fromString("fully-qualified"), "OK button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji P_BUTTON = new Emoji("\ud83c\udd7f\ufe0f", "\\uD83C\\uDD7F\\uFE0F", Collections.singletonList(":parking:"), Collections.singletonList(":parking:"), Collections.singletonList(":parking:"), Collections.unmodifiableList(Arrays.asList("button", "P", "parking")), false, false, 0.6, Qualification.fromString("fully-qualified"), "P button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji P_BUTTON_UNQUALIFIED = new Emoji("\ud83c\udd7f", "\\uD83C\\uDD7F", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("button", "P", "parking")), false, false, 0.6, Qualification.fromString("unqualified"), "P button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, true);
    public static final Emoji SOS_BUTTON = new Emoji("\ud83c\udd98", "\\uD83C\\uDD98", Collections.singletonList(":sos:"), Collections.singletonList(":sos:"), Collections.singletonList(":sos:"), Collections.unmodifiableList(Arrays.asList("button", "help", "SOS")), false, false, 0.6, Qualification.fromString("fully-qualified"), "SOS button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji UP_BUTTON = new Emoji("\ud83c\udd99", "\\uD83C\\uDD99", Collections.singletonList(":up:"), Collections.singletonList(":up:"), Collections.singletonList(":up:"), Collections.unmodifiableList(Arrays.asList("button", "mark", "UP", "UP!")), false, false, 0.6, Qualification.fromString("fully-qualified"), "UP! button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji VS_BUTTON = new Emoji("\ud83c\udd9a", "\\uD83C\\uDD9A", Collections.singletonList(":vs:"), Collections.singletonList(":vs:"), Collections.singletonList(":vs:"), Collections.unmodifiableList(Arrays.asList("button", "versus", "VS")), false, false, 0.6, Qualification.fromString("fully-qualified"), "VS button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_HERE_BUTTON = new Emoji("\ud83c\ude01", "\\uD83C\\uDE01", Collections.singletonList(":koko:"), Collections.singletonList(":koko:"), Collections.singletonList(":koko:"), Collections.unmodifiableList(Arrays.asList("button", "here", "Japanese", "katakana")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201chere\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_SERVICE_CHARGE_BUTTON = new Emoji("\ud83c\ude02\ufe0f", "\\uD83C\\uDE02\\uFE0F", Collections.singletonList(":sa:"), Collections.singletonList(":sa:"), Collections.singletonList(":sa:"), Collections.unmodifiableList(Arrays.asList("button", "charge", "Japanese", "katakana", "service")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201cservice charge\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_SERVICE_CHARGE_BUTTON_UNQUALIFIED = new Emoji("\ud83c\ude02", "\\uD83C\\uDE02", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("button", "charge", "Japanese", "katakana", "service")), false, false, 0.6, Qualification.fromString("unqualified"), "Japanese \u201cservice charge\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, true);
    public static final Emoji JAPANESE_MONTHLY_AMOUNT_BUTTON = new Emoji("\ud83c\ude37\ufe0f", "\\uD83C\\uDE37\\uFE0F", Collections.singletonList(":u6708:"), Collections.singletonList(":u6708:"), Collections.singletonList(":u6708:"), Collections.unmodifiableList(Arrays.asList("amount", "button", "ideograph", "Japanese", "monthly")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201cmonthly amount\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_MONTHLY_AMOUNT_BUTTON_UNQUALIFIED = new Emoji("\ud83c\ude37", "\\uD83C\\uDE37", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("amount", "button", "ideograph", "Japanese", "monthly")), false, false, 0.6, Qualification.fromString("unqualified"), "Japanese \u201cmonthly amount\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, true);
    public static final Emoji JAPANESE_NOT_FREE_OF_CHARGE_BUTTON = new Emoji("\ud83c\ude36", "\\uD83C\\uDE36", Collections.singletonList(":u6709:"), Collections.singletonList(":u6709:"), Collections.singletonList(":u6709:"), Collections.unmodifiableList(Arrays.asList("button", "charge", "free", "ideograph", "Japanese", "not")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201cnot free of charge\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_RESERVED_BUTTON = new Emoji("\ud83c\ude2f", "\\uD83C\\uDE2F", Collections.singletonList(":u6307:"), Collections.singletonList(":u6307:"), Collections.singletonList(":u6307:"), Collections.unmodifiableList(Arrays.asList("button", "ideograph", "Japanese", "reserved")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201creserved\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, true);
    public static final Emoji JAPANESE_BARGAIN_BUTTON = new Emoji("\ud83c\ude50", "\\uD83C\\uDE50", Collections.singletonList(":ideograph_advantage:"), Collections.singletonList(":ideograph_advantage:"), Collections.singletonList(":ideograph_advantage:"), Collections.unmodifiableList(Arrays.asList("bargain", "button", "ideograph", "Japanese")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201cbargain\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_DISCOUNT_BUTTON = new Emoji("\ud83c\ude39", "\\uD83C\\uDE39", Collections.singletonList(":u5272:"), Collections.singletonList(":u5272:"), Collections.singletonList(":u5272:"), Collections.unmodifiableList(Arrays.asList("button", "discount", "ideograph", "Japanese")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201cdiscount\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_FREE_OF_CHARGE_BUTTON = new Emoji("\ud83c\ude1a", "\\uD83C\\uDE1A", Collections.singletonList(":u7121:"), Collections.singletonList(":u7121:"), Collections.singletonList(":u7121:"), Collections.unmodifiableList(Arrays.asList("button", "charge", "free", "ideograph", "Japanese")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201cfree of charge\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, true);
    public static final Emoji JAPANESE_PROHIBITED_BUTTON = new Emoji("\ud83c\ude32", "\\uD83C\\uDE32", Collections.singletonList(":u7981:"), Collections.singletonList(":u7981:"), Collections.singletonList(":u7981:"), Collections.unmodifiableList(Arrays.asList("button", "ideograph", "Japanese", "prohibited")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201cprohibited\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_ACCEPTABLE_BUTTON = new Emoji("\ud83c\ude51", "\\uD83C\\uDE51", Collections.singletonList(":accept:"), Collections.singletonList(":accept:"), Collections.singletonList(":accept:"), Collections.unmodifiableList(Arrays.asList("acceptable", "button", "ideograph", "Japanese")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201cacceptable\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_APPLICATION_BUTTON = new Emoji("\ud83c\ude38", "\\uD83C\\uDE38", Collections.singletonList(":u7533:"), Collections.singletonList(":u7533:"), Collections.singletonList(":u7533:"), Collections.unmodifiableList(Arrays.asList("application", "button", "ideograph", "Japanese")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201capplication\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_PASSING_GRADE_BUTTON = new Emoji("\ud83c\ude34", "\\uD83C\\uDE34", Collections.singletonList(":u5408:"), Collections.singletonList(":u5408:"), Collections.singletonList(":u5408:"), Collections.unmodifiableList(Arrays.asList("button", "grade", "ideograph", "Japanese", "passing")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201cpassing grade\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_VACANCY_BUTTON = new Emoji("\ud83c\ude33", "\\uD83C\\uDE33", Collections.singletonList(":u7a7a:"), Collections.singletonList(":u7a7a:"), Collections.singletonList(":u7a7a:"), Collections.unmodifiableList(Arrays.asList("button", "ideograph", "Japanese", "vacancy")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201cvacancy\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_CONGRATULATIONS_BUTTON = new Emoji("\u3297\ufe0f", "\\u3297\\uFE0F", Collections.singletonList(":congratulations:"), Collections.singletonList(":congratulations:"), Collections.singletonList(":congratulations:"), Collections.unmodifiableList(Arrays.asList("button", "congratulations", "ideograph", "Japanese")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201ccongratulations\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_CONGRATULATIONS_BUTTON_UNQUALIFIED = new Emoji("\u3297", "\\u3297", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("button", "congratulations", "ideograph", "Japanese")), false, false, 0.6, Qualification.fromString("unqualified"), "Japanese \u201ccongratulations\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, true);
    public static final Emoji JAPANESE_SECRET_BUTTON = new Emoji("\u3299\ufe0f", "\\u3299\\uFE0F", Collections.singletonList(":secret:"), Collections.singletonList(":secret:"), Collections.singletonList(":secret:"), Collections.unmodifiableList(Arrays.asList("button", "ideograph", "Japanese", "secret")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201csecret\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_SECRET_BUTTON_UNQUALIFIED = new Emoji("\u3299", "\\u3299", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("button", "ideograph", "Japanese", "secret")), false, false, 0.6, Qualification.fromString("unqualified"), "Japanese \u201csecret\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, true);
    public static final Emoji JAPANESE_OPEN_FOR_BUSINESS_BUTTON = new Emoji("\ud83c\ude3a", "\\uD83C\\uDE3A", Collections.singletonList(":u55b6:"), Collections.singletonList(":u55b6:"), Collections.singletonList(":u55b6:"), Collections.unmodifiableList(Arrays.asList("business", "button", "ideograph", "Japanese", "open")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201copen for business\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
    public static final Emoji JAPANESE_NO_VACANCY_BUTTON = new Emoji("\ud83c\ude35", "\\uD83C\\uDE35", Collections.singletonList(":u6e80:"), Collections.singletonList(":u6e80:"), Collections.singletonList(":u6e80:"), Collections.unmodifiableList(Arrays.asList("button", "ideograph", "Japanese", "no", "vacancy")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese \u201cno vacancy\u201d button", EmojiGroup.SYMBOLS, EmojiSubGroup.ALPHANUM, false);
}

