/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiFoodSweet {
    public static final Emoji SOFT_ICE_CREAM = new Emoji("\ud83c\udf66", "\\uD83C\\uDF66", Collections.singletonList(":icecream:"), Collections.singletonList(":icecream:"), Collections.singletonList(":icecream:"), Collections.unmodifiableList(Arrays.asList("cream", "dessert", "food", "ice", "icecream", "restaurant", "serve", "soft", "sweet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "soft ice cream", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
    public static final Emoji SHAVED_ICE = new Emoji("\ud83c\udf67", "\\uD83C\\uDF67", Collections.singletonList(":shaved_ice:"), Collections.singletonList(":shaved_ice:"), Collections.singletonList(":shaved_ice:"), Collections.unmodifiableList(Arrays.asList("dessert", "ice", "restaurant", "shaved", "sweet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "shaved ice", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
    public static final Emoji ICE_CREAM = new Emoji("\ud83c\udf68", "\\uD83C\\uDF68", Collections.singletonList(":ice_cream:"), Collections.singletonList(":ice_cream:"), Collections.singletonList(":ice_cream:"), Collections.unmodifiableList(Arrays.asList("cream", "dessert", "food", "ice", "restaurant", "sweet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ice cream", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
    public static final Emoji DOUGHNUT = new Emoji("\ud83c\udf69", "\\uD83C\\uDF69", Collections.singletonList(":doughnut:"), Collections.singletonList(":doughnut:"), Collections.singletonList(":doughnut:"), Collections.unmodifiableList(Arrays.asList("breakfast", "dessert", "donut", "doughnut", "food", "sweet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "doughnut", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
    public static final Emoji COOKIE = new Emoji("\ud83c\udf6a", "\\uD83C\\uDF6A", Collections.singletonList(":cookie:"), Collections.singletonList(":cookie:"), Collections.singletonList(":cookie:"), Collections.unmodifiableList(Arrays.asList("chip", "chocolate", "cookie", "dessert", "sweet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "cookie", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
    public static final Emoji BIRTHDAY_CAKE = new Emoji("\ud83c\udf82", "\\uD83C\\uDF82", Collections.unmodifiableList(Arrays.asList(":birthday:", ":birthday_cake:")), Collections.singletonList(":birthday:"), Collections.singletonList(":birthday:"), Collections.unmodifiableList(Arrays.asList("bday", "birthday", "cake", "celebration", "dessert", "happy", "pastry", "sweet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "birthday cake", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
    public static final Emoji SHORTCAKE = new Emoji("\ud83c\udf70", "\\uD83C\\uDF70", Collections.unmodifiableList(Arrays.asList(":cake:", ":shortcake:")), Collections.singletonList(":cake:"), Collections.singletonList(":cake:"), Collections.unmodifiableList(Arrays.asList("cake", "dessert", "pastry", "shortcake", "slice", "sweet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "shortcake", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
    public static final Emoji CUPCAKE = new Emoji("\ud83e\uddc1", "\\uD83E\\uDDC1", Collections.singletonList(":cupcake:"), Collections.singletonList(":cupcake:"), Collections.singletonList(":cupcake:"), Collections.unmodifiableList(Arrays.asList("bakery", "cupcake", "dessert", "sprinkles", "sugar", "sweet", "treat")), false, false, 11.0, Qualification.fromString("fully-qualified"), "cupcake", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
    public static final Emoji PIE = new Emoji("\ud83e\udd67", "\\uD83E\\uDD67", Collections.singletonList(":pie:"), Collections.singletonList(":pie:"), Collections.singletonList(":pie:"), Collections.unmodifiableList(Arrays.asList("apple", "filling", "fruit", "meat", "pastry", "pie", "pumpkin", "slice")), false, false, 5.0, Qualification.fromString("fully-qualified"), "pie", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
    public static final Emoji CHOCOLATE_BAR = new Emoji("\ud83c\udf6b", "\\uD83C\\uDF6B", Collections.singletonList(":chocolate_bar:"), Collections.singletonList(":chocolate_bar:"), Collections.singletonList(":chocolate_bar:"), Collections.unmodifiableList(Arrays.asList("bar", "candy", "chocolate", "dessert", "halloween", "sweet", "tooth")), false, false, 0.6, Qualification.fromString("fully-qualified"), "chocolate bar", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
    public static final Emoji CANDY = new Emoji("\ud83c\udf6c", "\\uD83C\\uDF6C", Collections.singletonList(":candy:"), Collections.singletonList(":candy:"), Collections.singletonList(":candy:"), Collections.unmodifiableList(Arrays.asList("candy", "cavities", "dessert", "halloween", "restaurant", "sweet", "tooth", "wrapper")), false, false, 0.6, Qualification.fromString("fully-qualified"), "candy", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
    public static final Emoji LOLLIPOP = new Emoji("\ud83c\udf6d", "\\uD83C\\uDF6D", Collections.singletonList(":lollipop:"), Collections.singletonList(":lollipop:"), Collections.singletonList(":lollipop:"), Collections.unmodifiableList(Arrays.asList("candy", "dessert", "food", "lollipop", "restaurant", "sweet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "lollipop", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
    public static final Emoji CUSTARD = new Emoji("\ud83c\udf6e", "\\uD83C\\uDF6E", Collections.unmodifiableList(Arrays.asList(":custard:", ":pudding:", ":flan:")), Collections.singletonList(":custard:"), Collections.singletonList(":custard:"), Collections.unmodifiableList(Arrays.asList("custard", "dessert", "pudding", "sweet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "custard", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
    public static final Emoji HONEY_POT = new Emoji("\ud83c\udf6f", "\\uD83C\\uDF6F", Collections.singletonList(":honey_pot:"), Collections.singletonList(":honey_pot:"), Collections.singletonList(":honey_pot:"), Collections.unmodifiableList(Arrays.asList("barrel", "bear", "food", "honey", "honeypot", "jar", "pot", "sweet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "honey pot", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_SWEET, false);
}

