/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiPlantOther {
    public static final Emoji SEEDLING = new Emoji("\ud83c\udf31", "\\uD83C\\uDF31", Collections.singletonList(":seedling:"), Collections.singletonList(":seedling:"), Collections.singletonList(":seedling:"), Collections.unmodifiableList(Arrays.asList("plant", "sapling", "seedling", "sprout", "young")), false, false, 0.6, Qualification.fromString("fully-qualified"), "seedling", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji POTTED_PLANT = new Emoji("\ud83e\udeb4", "\\uD83E\\uDEB4", Collections.singletonList(":potted_plant:"), Collections.singletonList(":potted_plant:"), Collections.singletonList(":potted_plant:"), Collections.unmodifiableList(Arrays.asList("decor", "grow", "house", "nurturing", "plant", "pot", "potted")), false, false, 13.0, Qualification.fromString("fully-qualified"), "potted plant", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji EVERGREEN_TREE = new Emoji("\ud83c\udf32", "\\uD83C\\uDF32", Collections.singletonList(":evergreen_tree:"), Collections.singletonList(":evergreen_tree:"), Collections.singletonList(":evergreen_tree:"), Collections.unmodifiableList(Arrays.asList("christmas", "evergreen", "forest", "pine", "tree")), false, false, 1.0, Qualification.fromString("fully-qualified"), "evergreen tree", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji DECIDUOUS_TREE = new Emoji("\ud83c\udf33", "\\uD83C\\uDF33", Collections.singletonList(":deciduous_tree:"), Collections.singletonList(":deciduous_tree:"), Collections.singletonList(":deciduous_tree:"), Collections.unmodifiableList(Arrays.asList("deciduous", "forest", "green", "habitat", "shedding", "tree")), false, false, 1.0, Qualification.fromString("fully-qualified"), "deciduous tree", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji PALM_TREE = new Emoji("\ud83c\udf34", "\\uD83C\\uDF34", Collections.singletonList(":palm_tree:"), Collections.singletonList(":palm_tree:"), Collections.singletonList(":palm_tree:"), Collections.unmodifiableList(Arrays.asList("beach", "palm", "plant", "tree", "tropical")), false, false, 0.6, Qualification.fromString("fully-qualified"), "palm tree", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji CACTUS = new Emoji("\ud83c\udf35", "\\uD83C\\uDF35", Collections.singletonList(":cactus:"), Collections.singletonList(":cactus:"), Collections.singletonList(":cactus:"), Collections.unmodifiableList(Arrays.asList("cactus", "desert", "drought", "nature", "plant")), false, false, 0.6, Qualification.fromString("fully-qualified"), "cactus", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji SHEAF_OF_RICE = new Emoji("\ud83c\udf3e", "\\uD83C\\uDF3E", Collections.unmodifiableList(Arrays.asList(":ear_of_rice:", ":sheaf_of_rice:")), Collections.singletonList(":ear_of_rice:"), Collections.singletonList(":ear_of_rice:"), Collections.unmodifiableList(Arrays.asList("ear", "grain", "grains", "plant", "rice", "sheaf")), false, false, 0.6, Qualification.fromString("fully-qualified"), "sheaf of rice", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji HERB = new Emoji("\ud83c\udf3f", "\\uD83C\\uDF3F", Collections.singletonList(":herb:"), Collections.singletonList(":herb:"), Collections.singletonList(":herb:"), Collections.unmodifiableList(Arrays.asList("herb", "leaf", "plant")), false, false, 0.6, Qualification.fromString("fully-qualified"), "herb", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji SHAMROCK = new Emoji("\u2618\ufe0f", "\\u2618\\uFE0F", Collections.singletonList(":shamrock:"), Collections.singletonList(":shamrock:"), Collections.singletonList(":shamrock:"), Collections.unmodifiableList(Arrays.asList("irish", "plant", "shamrock")), false, false, 1.0, Qualification.fromString("fully-qualified"), "shamrock", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji SHAMROCK_UNQUALIFIED = new Emoji("\u2618", "\\u2618", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("irish", "plant", "shamrock")), false, false, 1.0, Qualification.fromString("unqualified"), "shamrock", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, true);
    public static final Emoji FOUR_LEAF_CLOVER = new Emoji("\ud83c\udf40", "\\uD83C\\uDF40", Collections.singletonList(":four_leaf_clover:"), Collections.singletonList(":four_leaf_clover:"), Collections.singletonList(":four_leaf_clover:"), Collections.unmodifiableList(Arrays.asList("4", "clover", "four", "four-leaf", "irish", "leaf", "lucky", "plant")), false, false, 0.6, Qualification.fromString("fully-qualified"), "four leaf clover", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji MAPLE_LEAF = new Emoji("\ud83c\udf41", "\\uD83C\\uDF41", Collections.singletonList(":maple_leaf:"), Collections.singletonList(":maple_leaf:"), Collections.singletonList(":maple_leaf:"), Collections.unmodifiableList(Arrays.asList("falling", "leaf", "maple")), false, false, 0.6, Qualification.fromString("fully-qualified"), "maple leaf", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji FALLEN_LEAF = new Emoji("\ud83c\udf42", "\\uD83C\\uDF42", Collections.singletonList(":fallen_leaf:"), Collections.singletonList(":fallen_leaf:"), Collections.singletonList(":fallen_leaf:"), Collections.unmodifiableList(Arrays.asList("autumn", "fall", "fallen", "falling", "leaf")), false, false, 0.6, Qualification.fromString("fully-qualified"), "fallen leaf", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji LEAF_FLUTTERING_IN_WIND = new Emoji("\ud83c\udf43", "\\uD83C\\uDF43", Collections.singletonList(":leaves:"), Collections.singletonList(":leaves:"), Collections.singletonList(":leaves:"), Collections.unmodifiableList(Arrays.asList("blow", "flutter", "fluttering", "leaf", "wind")), false, false, 0.6, Qualification.fromString("fully-qualified"), "leaf fluttering in wind", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji EMPTY_NEST = new Emoji("\ud83e\udeb9", "\\uD83E\\uDEB9", Collections.singletonList(":empty_nest:"), Collections.singletonList(":empty_nest:"), Collections.singletonList(":empty_nest:"), Collections.unmodifiableList(Arrays.asList("branch", "empty", "home", "nest", "nesting")), false, false, 14.0, Qualification.fromString("fully-qualified"), "empty nest", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji NEST_WITH_EGGS = new Emoji("\ud83e\udeba", "\\uD83E\\uDEBA", Collections.singletonList(":nest_with_eggs:"), Collections.singletonList(":nest_with_eggs:"), Collections.singletonList(":nest_with_eggs:"), Collections.unmodifiableList(Arrays.asList("bird", "branch", "egg", "eggs", "nest", "nesting")), false, false, 14.0, Qualification.fromString("fully-qualified"), "nest with eggs", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji MUSHROOM = new Emoji("\ud83c\udf44", "\\uD83C\\uDF44", Collections.singletonList(":mushroom:"), Collections.singletonList(":mushroom:"), Collections.singletonList(":mushroom:"), Collections.unmodifiableList(Arrays.asList("fungus", "mushroom", "toadstool")), false, false, 0.6, Qualification.fromString("fully-qualified"), "mushroom", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
    public static final Emoji LEAFLESS_TREE = new Emoji("\ud83e\udebe", "\\uD83E\\uDEBE", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bare", "barren", "branches", "dead", "drought", "leafless", "tree", "trunk", "winter", "wood")), false, false, 16.0, Qualification.fromString("fully-qualified"), "leafless tree", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_OTHER, false);
}

