/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiEmotion {
    public static final Emoji KISS_MARK = new Emoji("\ud83d\udc8b", "\\uD83D\\uDC8B", Collections.unmodifiableList(Arrays.asList(":kiss:", ":kiss_mark:")), Collections.singletonList(":kiss:"), Collections.singletonList(":kiss:"), Collections.unmodifiableList(Arrays.asList("dating", "emotion", "heart", "kiss", "kissing", "lips", "mark", "romance", "sexy")), false, false, 0.6, Qualification.fromString("fully-qualified"), "kiss mark", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji HUNDRED_POINTS = new Emoji("\ud83d\udcaf", "\\uD83D\\uDCAF", Collections.singletonList(":100:"), Collections.singletonList(":100:"), Collections.singletonList(":100:"), Collections.unmodifiableList(Arrays.asList("100", "a+", "agree", "clearly", "definitely", "faithful", "fleek", "full", "hundred", "keep", "perfect", "point", "score", "TRUE", "truth", "yup")), false, false, 0.6, Qualification.fromString("fully-qualified"), "hundred points", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji ANGER_SYMBOL = new Emoji("\ud83d\udca2", "\\uD83D\\uDCA2", Collections.singletonList(":anger:"), Collections.singletonList(":anger:"), Collections.singletonList(":anger:"), Collections.unmodifiableList(Arrays.asList("anger", "angry", "comic", "mad", "symbol", "upset")), false, false, 0.6, Qualification.fromString("fully-qualified"), "anger symbol", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji COLLISION = new Emoji("\ud83d\udca5", "\\uD83D\\uDCA5", Collections.unmodifiableList(Arrays.asList(":boom:", ":collision:")), Collections.unmodifiableList(Arrays.asList(":boom:", ":collision:")), Collections.unmodifiableList(Arrays.asList(":boom:", ":collision:")), Collections.unmodifiableList(Arrays.asList("bomb", "boom", "collide", "collision", "comic", "explode")), false, false, 0.6, Qualification.fromString("fully-qualified"), "collision", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji DIZZY = new Emoji("\ud83d\udcab", "\\uD83D\\uDCAB", Collections.singletonList(":dizzy:"), Collections.singletonList(":dizzy:"), Collections.singletonList(":dizzy:"), Collections.unmodifiableList(Arrays.asList("comic", "dizzy", "shining", "shooting", "star", "stars")), false, false, 0.6, Qualification.fromString("fully-qualified"), "dizzy", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji SWEAT_DROPLETS = new Emoji("\ud83d\udca6", "\\uD83D\\uDCA6", Collections.singletonList(":sweat_drops:"), Collections.singletonList(":sweat_drops:"), Collections.singletonList(":sweat_drops:"), Collections.unmodifiableList(Arrays.asList("comic", "drip", "droplet", "droplets", "drops", "splashing", "squirt", "sweat", "water", "wet", "work", "workout")), false, false, 0.6, Qualification.fromString("fully-qualified"), "sweat droplets", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji DASHING_AWAY = new Emoji("\ud83d\udca8", "\\uD83D\\uDCA8", Collections.unmodifiableList(Arrays.asList(":dash:", ":dashing_away:")), Collections.singletonList(":dash:"), Collections.singletonList(":dash:"), Collections.unmodifiableList(Arrays.asList("away", "cloud", "comic", "dash", "dashing", "fart", "fast", "go", "gone", "gotta", "running", "smoke")), false, false, 0.6, Qualification.fromString("fully-qualified"), "dashing away", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji HOLE = new Emoji("\ud83d\udd73\ufe0f", "\\uD83D\\uDD73\\uFE0F", Collections.singletonList(":hole:"), Collections.singletonList(":hole:"), Collections.singletonList(":hole:"), Collections.singletonList("hole"), false, false, 0.7, Qualification.fromString("fully-qualified"), "hole", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji HOLE_UNQUALIFIED = new Emoji("\ud83d\udd73", "\\uD83D\\uDD73", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.singletonList("hole"), false, false, 0.7, Qualification.fromString("unqualified"), "hole", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, true);
    public static final Emoji SPEECH_BALLOON = new Emoji("\ud83d\udcac", "\\uD83D\\uDCAC", Collections.singletonList(":speech_balloon:"), Collections.singletonList(":speech_balloon:"), Collections.singletonList(":speech_balloon:"), Collections.unmodifiableList(Arrays.asList("balloon", "bubble", "comic", "dialog", "message", "sms", "speech", "talk", "text", "typing")), false, false, 0.6, Qualification.fromString("fully-qualified"), "speech balloon", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji EYE_IN_SPEECH_BUBBLE = new Emoji("\ud83d\udc41\ufe0f\u200d\ud83d\udde8\ufe0f", "\\uD83D\\uDC41\\uFE0F\\u200D\\uD83D\\uDDE8\\uFE0F", Collections.emptyList(), Collections.singletonList(":eye-in-speech-bubble:"), Collections.singletonList(":eye_speech_bubble:"), Collections.unmodifiableList(Arrays.asList("balloon", "bubble", "eye", "speech", "witness")), false, false, 2.0, Qualification.fromString("fully-qualified"), "eye in speech bubble", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji EYE_IN_SPEECH_BUBBLE_UNQUALIFIED_0 = new Emoji("\ud83d\udc41\u200d\ud83d\udde8\ufe0f", "\\uD83D\\uDC41\\u200D\\uD83D\\uDDE8\\uFE0F", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("balloon", "bubble", "eye", "speech", "witness")), false, false, 2.0, Qualification.fromString("unqualified"), "eye in speech bubble", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji EYE_IN_SPEECH_BUBBLE_MINIMALLY_QUALIFIED = new Emoji("\ud83d\udc41\ufe0f\u200d\ud83d\udde8", "\\uD83D\\uDC41\\uFE0F\\u200D\\uD83D\\uDDE8", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("balloon", "bubble", "eye", "speech", "witness")), false, false, 2.0, Qualification.fromString("minimally-qualified"), "eye in speech bubble", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji EYE_IN_SPEECH_BUBBLE_UNQUALIFIED_1 = new Emoji("\ud83d\udc41\u200d\ud83d\udde8", "\\uD83D\\uDC41\\u200D\\uD83D\\uDDE8", Collections.singletonList(":eye_in_speech_bubble:"), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("balloon", "bubble", "eye", "speech", "witness")), false, false, 2.0, Qualification.fromString("unqualified"), "eye in speech bubble", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji LEFT_SPEECH_BUBBLE = new Emoji("\ud83d\udde8\ufe0f", "\\uD83D\\uDDE8\\uFE0F", Collections.unmodifiableList(Arrays.asList(":speech_left:", ":left_speech_bubble:")), Collections.singletonList(":left_speech_bubble:"), Collections.singletonList(":left_speech_bubble:"), Collections.unmodifiableList(Arrays.asList("balloon", "bubble", "dialog", "left", "speech")), false, false, 2.0, Qualification.fromString("fully-qualified"), "left speech bubble", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji LEFT_SPEECH_BUBBLE_UNQUALIFIED = new Emoji("\ud83d\udde8", "\\uD83D\\uDDE8", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("balloon", "bubble", "dialog", "left", "speech")), false, false, 2.0, Qualification.fromString("unqualified"), "left speech bubble", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, true);
    public static final Emoji RIGHT_ANGER_BUBBLE = new Emoji("\ud83d\uddef\ufe0f", "\\uD83D\\uDDEF\\uFE0F", Collections.unmodifiableList(Arrays.asList(":anger_right:", ":right_anger_bubble:")), Collections.singletonList(":right_anger_bubble:"), Collections.singletonList(":right_anger_bubble:"), Collections.unmodifiableList(Arrays.asList("anger", "angry", "balloon", "bubble", "mad", "right")), false, false, 0.7, Qualification.fromString("fully-qualified"), "right anger bubble", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji RIGHT_ANGER_BUBBLE_UNQUALIFIED = new Emoji("\ud83d\uddef", "\\uD83D\\uDDEF", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("anger", "angry", "balloon", "bubble", "mad", "right")), false, false, 0.7, Qualification.fromString("unqualified"), "right anger bubble", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, true);
    public static final Emoji THOUGHT_BALLOON = new Emoji("\ud83d\udcad", "\\uD83D\\uDCAD", Collections.singletonList(":thought_balloon:"), Collections.singletonList(":thought_balloon:"), Collections.singletonList(":thought_balloon:"), Collections.unmodifiableList(Arrays.asList("balloon", "bubble", "cartoon", "cloud", "comic", "daydream", "decisions", "dream", "idea", "invent", "invention", "realize", "think", "thoughts", "wonder")), false, false, 1.0, Qualification.fromString("fully-qualified"), "thought balloon", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
    public static final Emoji ZZZ = new Emoji("\ud83d\udca4", "\\uD83D\\uDCA4", Collections.singletonList(":zzz:"), Collections.singletonList(":zzz:"), Collections.singletonList(":zzz:"), Collections.unmodifiableList(Arrays.asList("comic", "good", "goodnight", "night", "sleep", "sleeping", "sleepy", "tired", "zzz")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ZZZ", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.EMOTION, false);
}

