/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiClothing {
    public static final Emoji GLASSES = new Emoji("\ud83d\udc53", "\\uD83D\\uDC53", Collections.unmodifiableList(Arrays.asList(":eyeglasses:", ":glasses:")), Collections.singletonList(":eyeglasses:"), Collections.singletonList(":eyeglasses:"), Collections.unmodifiableList(Arrays.asList("clothing", "eye", "eyeglasses", "eyewear", "glasses")), false, false, 0.6, Qualification.fromString("fully-qualified"), "glasses", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, true);
    public static final Emoji SUNGLASSES = new Emoji("\ud83d\udd76\ufe0f", "\\uD83D\\uDD76\\uFE0F", Collections.singletonList(":dark_sunglasses:"), Collections.singletonList(":dark_sunglasses:"), Collections.singletonList(":dark_sunglasses:"), Collections.unmodifiableList(Arrays.asList("dark", "eye", "eyewear", "glasses", "sunglasses")), false, false, 0.7, Qualification.fromString("fully-qualified"), "sunglasses", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji SUNGLASSES_UNQUALIFIED = new Emoji("\ud83d\udd76", "\\uD83D\\uDD76", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("dark", "eye", "eyewear", "glasses", "sunglasses")), false, false, 0.7, Qualification.fromString("unqualified"), "sunglasses", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, true);
    public static final Emoji GOGGLES = new Emoji("\ud83e\udd7d", "\\uD83E\\uDD7D", Collections.singletonList(":goggles:"), Collections.singletonList(":goggles:"), Collections.singletonList(":goggles:"), Collections.unmodifiableList(Arrays.asList("dive", "eye", "goggles", "protection", "scuba", "swimming", "welding")), false, false, 11.0, Qualification.fromString("fully-qualified"), "goggles", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji LAB_COAT = new Emoji("\ud83e\udd7c", "\\uD83E\\uDD7C", Collections.singletonList(":lab_coat:"), Collections.singletonList(":lab_coat:"), Collections.singletonList(":lab_coat:"), Collections.unmodifiableList(Arrays.asList("clothes", "coat", "doctor", "dr", "experiment", "jacket", "lab", "scientist", "white")), false, false, 11.0, Qualification.fromString("fully-qualified"), "lab coat", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji SAFETY_VEST = new Emoji("\ud83e\uddba", "\\uD83E\\uDDBA", Collections.singletonList(":safety_vest:"), Collections.singletonList(":safety_vest:"), Collections.singletonList(":safety_vest:"), Collections.unmodifiableList(Arrays.asList("emergency", "safety", "vest")), false, false, 12.0, Qualification.fromString("fully-qualified"), "safety vest", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji NECKTIE = new Emoji("\ud83d\udc54", "\\uD83D\\uDC54", Collections.singletonList(":necktie:"), Collections.singletonList(":necktie:"), Collections.singletonList(":necktie:"), Collections.unmodifiableList(Arrays.asList("clothing", "employed", "necktie", "serious", "shirt", "tie")), false, false, 0.6, Qualification.fromString("fully-qualified"), "necktie", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji T_SHIRT = new Emoji("\ud83d\udc55", "\\uD83D\\uDC55", Collections.unmodifiableList(Arrays.asList(":shirt:", ":t_shirt:")), Collections.unmodifiableList(Arrays.asList(":shirt:", ":tshirt:")), Collections.unmodifiableList(Arrays.asList(":shirt:", ":tshirt:")), Collections.unmodifiableList(Arrays.asList("blue", "casual", "clothes", "clothing", "collar", "dressed", "shirt", "shopping", "t-shirt", "tshirt", "weekend")), false, false, 0.6, Qualification.fromString("fully-qualified"), "t-shirt", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji JEANS = new Emoji("\ud83d\udc56", "\\uD83D\\uDC56", Collections.singletonList(":jeans:"), Collections.singletonList(":jeans:"), Collections.singletonList(":jeans:"), Collections.unmodifiableList(Arrays.asList("blue", "casual", "clothes", "clothing", "denim", "dressed", "jeans", "pants", "shopping", "trousers", "weekend")), false, false, 0.6, Qualification.fromString("fully-qualified"), "jeans", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji SCARF = new Emoji("\ud83e\udde3", "\\uD83E\\uDDE3", Collections.singletonList(":scarf:"), Collections.singletonList(":scarf:"), Collections.singletonList(":scarf:"), Collections.unmodifiableList(Arrays.asList("bundle", "cold", "neck", "scarf", "up")), false, false, 5.0, Qualification.fromString("fully-qualified"), "scarf", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji GLOVES = new Emoji("\ud83e\udde4", "\\uD83E\\uDDE4", Collections.singletonList(":gloves:"), Collections.singletonList(":gloves:"), Collections.singletonList(":gloves:"), Collections.unmodifiableList(Arrays.asList("gloves", "hand")), false, false, 5.0, Qualification.fromString("fully-qualified"), "gloves", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji COAT = new Emoji("\ud83e\udde5", "\\uD83E\\uDDE5", Collections.singletonList(":coat:"), Collections.singletonList(":coat:"), Collections.singletonList(":coat:"), Collections.unmodifiableList(Arrays.asList("brr", "bundle", "coat", "cold", "jacket", "up")), false, false, 5.0, Qualification.fromString("fully-qualified"), "coat", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji SOCKS = new Emoji("\ud83e\udde6", "\\uD83E\\uDDE6", Collections.singletonList(":socks:"), Collections.singletonList(":socks:"), Collections.singletonList(":socks:"), Collections.unmodifiableList(Arrays.asList("socks", "stocking")), false, false, 5.0, Qualification.fromString("fully-qualified"), "socks", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji DRESS = new Emoji("\ud83d\udc57", "\\uD83D\\uDC57", Collections.singletonList(":dress:"), Collections.singletonList(":dress:"), Collections.singletonList(":dress:"), Collections.unmodifiableList(Arrays.asList("clothes", "clothing", "dress", "dressed", "fancy", "shopping")), false, false, 0.6, Qualification.fromString("fully-qualified"), "dress", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji KIMONO = new Emoji("\ud83d\udc58", "\\uD83D\\uDC58", Collections.singletonList(":kimono:"), Collections.singletonList(":kimono:"), Collections.singletonList(":kimono:"), Collections.unmodifiableList(Arrays.asList("clothing", "comfortable", "kimono")), false, false, 0.6, Qualification.fromString("fully-qualified"), "kimono", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji SARI = new Emoji("\ud83e\udd7b", "\\uD83E\\uDD7B", Collections.singletonList(":sari:"), Collections.singletonList(":sari:"), Collections.singletonList(":sari:"), Collections.unmodifiableList(Arrays.asList("clothing", "dress", "sari")), false, false, 12.0, Qualification.fromString("fully-qualified"), "sari", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji ONE_PIECE_SWIMSUIT = new Emoji("\ud83e\ude71", "\\uD83E\\uDE71", Collections.singletonList(":one_piece_swimsuit:"), Collections.singletonList(":one-piece_swimsuit:"), Collections.singletonList(":one_piece_swimsuit:"), Collections.unmodifiableList(Arrays.asList("bathing", "one-piece", "suit", "swimsuit")), false, false, 12.0, Qualification.fromString("fully-qualified"), "one-piece swimsuit", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji BRIEFS = new Emoji("\ud83e\ude72", "\\uD83E\\uDE72", Collections.singletonList(":briefs:"), Collections.singletonList(":briefs:"), Collections.singletonList(":swim_brief:"), Collections.unmodifiableList(Arrays.asList("bathing", "briefs", "one-piece", "suit", "swimsuit", "underwear")), false, false, 12.0, Qualification.fromString("fully-qualified"), "briefs", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji SHORTS = new Emoji("\ud83e\ude73", "\\uD83E\\uDE73", Collections.singletonList(":shorts:"), Collections.singletonList(":shorts:"), Collections.singletonList(":shorts:"), Collections.unmodifiableList(Arrays.asList("bathing", "pants", "shorts", "suit", "swimsuit", "underwear")), false, false, 12.0, Qualification.fromString("fully-qualified"), "shorts", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji BIKINI = new Emoji("\ud83d\udc59", "\\uD83D\\uDC59", Collections.singletonList(":bikini:"), Collections.singletonList(":bikini:"), Collections.singletonList(":bikini:"), Collections.unmodifiableList(Arrays.asList("bathing", "beach", "bikini", "clothing", "pool", "suit", "swim")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bikini", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji WOMAN_S_CLOTHES = new Emoji("\ud83d\udc5a", "\\uD83D\\uDC5A", Collections.singletonList(":womans_clothes:"), Collections.singletonList(":womans_clothes:"), Collections.singletonList(":womans_clothes:"), Collections.unmodifiableList(Arrays.asList("blouse", "clothes", "clothing", "collar", "dress", "dressed", "lady", "shirt", "shopping", "woman", "woman\u2019s")), false, false, 0.6, Qualification.fromString("fully-qualified"), "woman\u2019s clothes", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji FOLDING_HAND_FAN = new Emoji("\ud83e\udead", "\\uD83E\\uDEAD", Collections.singletonList(":folding_hand_fan:"), Collections.emptyList(), Collections.singletonList(":folding_hand_fan:"), Collections.unmodifiableList(Arrays.asList("clack", "clap", "cool", "cooling", "dance", "fan", "flirt", "flutter", "folding", "hand", "hot", "shy")), false, false, 15.0, Qualification.fromString("fully-qualified"), "folding hand fan", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji PURSE = new Emoji("\ud83d\udc5b", "\\uD83D\\uDC5B", Collections.singletonList(":purse:"), Collections.singletonList(":purse:"), Collections.singletonList(":purse:"), Collections.unmodifiableList(Arrays.asList("clothes", "clothing", "coin", "dress", "fancy", "handbag", "purse", "shopping")), false, false, 0.6, Qualification.fromString("fully-qualified"), "purse", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji HANDBAG = new Emoji("\ud83d\udc5c", "\\uD83D\\uDC5C", Collections.singletonList(":handbag:"), Collections.singletonList(":handbag:"), Collections.singletonList(":handbag:"), Collections.unmodifiableList(Arrays.asList("bag", "clothes", "clothing", "dress", "handbag", "lady", "purse", "shopping")), false, false, 0.6, Qualification.fromString("fully-qualified"), "handbag", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji CLUTCH_BAG = new Emoji("\ud83d\udc5d", "\\uD83D\\uDC5D", Collections.unmodifiableList(Arrays.asList(":pouch:", ":clutch_bag:")), Collections.singletonList(":pouch:"), Collections.singletonList(":pouch:"), Collections.unmodifiableList(Arrays.asList("bag", "clothes", "clothing", "clutch", "dress", "handbag", "pouch", "purse")), false, false, 0.6, Qualification.fromString("fully-qualified"), "clutch bag", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji SHOPPING_BAGS = new Emoji("\ud83d\udecd\ufe0f", "\\uD83D\\uDECD\\uFE0F", Collections.singletonList(":shopping_bags:"), Collections.singletonList(":shopping_bags:"), Collections.singletonList(":shopping:"), Collections.unmodifiableList(Arrays.asList("bag", "bags", "hotel", "shopping")), false, false, 0.7, Qualification.fromString("fully-qualified"), "shopping bags", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji SHOPPING_BAGS_UNQUALIFIED = new Emoji("\ud83d\udecd", "\\uD83D\\uDECD", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bag", "bags", "hotel", "shopping")), false, false, 0.7, Qualification.fromString("unqualified"), "shopping bags", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, true);
    public static final Emoji BACKPACK = new Emoji("\ud83c\udf92", "\\uD83C\\uDF92", Collections.unmodifiableList(Arrays.asList(":school_satchel:", ":backpack:")), Collections.singletonList(":school_satchel:"), Collections.singletonList(":school_satchel:"), Collections.unmodifiableList(Arrays.asList("backpack", "backpacking", "bag", "bookbag", "com.hypherionmc.sdlink.shaded.education", "rucksack", "satchel", "school")), false, false, 0.6, Qualification.fromString("fully-qualified"), "backpack", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji THONG_SANDAL = new Emoji("\ud83e\ude74", "\\uD83E\\uDE74", Collections.singletonList(":thong_sandal:"), Collections.singletonList(":thong_sandal:"), Collections.singletonList(":thong_sandal:"), Collections.unmodifiableList(Arrays.asList("beach", "flip", "flop", "sandal", "sandals", "shoe", "thong", "thongs", "z\u014dri")), false, false, 13.0, Qualification.fromString("fully-qualified"), "thong sandal", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji MAN_S_SHOE = new Emoji("\ud83d\udc5e", "\\uD83D\\uDC5E", Collections.singletonList(":mans_shoe:"), Collections.unmodifiableList(Arrays.asList(":mans_shoe:", ":shoe:")), Collections.unmodifiableList(Arrays.asList(":mans_shoe:", ":shoe:")), Collections.unmodifiableList(Arrays.asList("brown", "clothes", "clothing", "feet", "foot", "kick", "man", "man\u2019s", "shoe", "shoes", "shopping")), false, false, 0.6, Qualification.fromString("fully-qualified"), "man\u2019s shoe", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji RUNNING_SHOE = new Emoji("\ud83d\udc5f", "\\uD83D\\uDC5F", Collections.unmodifiableList(Arrays.asList(":athletic_shoe:", ":running_shoe:")), Collections.singletonList(":athletic_shoe:"), Collections.singletonList(":athletic_shoe:"), Collections.unmodifiableList(Arrays.asList("athletic", "clothes", "clothing", "fast", "kick", "running", "shoe", "shoes", "shopping", "sneaker", "tennis")), false, false, 0.6, Qualification.fromString("fully-qualified"), "running shoe", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji HIKING_BOOT = new Emoji("\ud83e\udd7e", "\\uD83E\\uDD7E", Collections.singletonList(":hiking_boot:"), Collections.singletonList(":hiking_boot:"), Collections.singletonList(":hiking_boot:"), Collections.unmodifiableList(Arrays.asList("backpacking", "boot", "brown", "camping", "hiking", "outdoors", "shoe")), false, false, 11.0, Qualification.fromString("fully-qualified"), "hiking boot", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji FLAT_SHOE = new Emoji("\ud83e\udd7f", "\\uD83E\\uDD7F", Collections.unmodifiableList(Arrays.asList(":womans_flat_shoe:", ":flat_shoe:")), Collections.singletonList(":womans_flat_shoe:"), Collections.singletonList(":flat_shoe:"), Collections.unmodifiableList(Arrays.asList("ballet", "comfy", "flat", "flats", "shoe", "slip-on", "slipper")), false, false, 11.0, Qualification.fromString("fully-qualified"), "flat shoe", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji HIGH_HEELED_SHOE = new Emoji("\ud83d\udc60", "\\uD83D\\uDC60", Collections.singletonList(":high_heel:"), Collections.singletonList(":high_heel:"), Collections.singletonList(":high_heel:"), Collections.unmodifiableList(Arrays.asList("clothes", "clothing", "dress", "fashion", "heel", "heels", "high-heeled", "shoe", "shoes", "shopping", "stiletto", "woman")), false, false, 0.6, Qualification.fromString("fully-qualified"), "high-heeled shoe", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji WOMAN_S_SANDAL = new Emoji("\ud83d\udc61", "\\uD83D\\uDC61", Collections.unmodifiableList(Arrays.asList(":sandal:", ":womans_sandal:")), Collections.singletonList(":sandal:"), Collections.singletonList(":sandal:"), Collections.unmodifiableList(Arrays.asList("clothing", "sandal", "shoe", "woman", "woman\u2019s")), false, false, 0.6, Qualification.fromString("fully-qualified"), "woman\u2019s sandal", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji BALLET_SHOES = new Emoji("\ud83e\ude70", "\\uD83E\\uDE70", Collections.singletonList(":ballet_shoes:"), Collections.singletonList(":ballet_shoes:"), Collections.singletonList(":ballet_shoes:"), Collections.unmodifiableList(Arrays.asList("ballet", "dance", "shoes")), false, false, 12.0, Qualification.fromString("fully-qualified"), "ballet shoes", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji WOMAN_S_BOOT = new Emoji("\ud83d\udc62", "\\uD83D\\uDC62", Collections.unmodifiableList(Arrays.asList(":boot:", ":womans_boot:")), Collections.singletonList(":boot:"), Collections.singletonList(":boot:"), Collections.unmodifiableList(Arrays.asList("boot", "clothes", "clothing", "dress", "shoe", "shoes", "shopping", "woman", "woman\u2019s")), false, false, 0.6, Qualification.fromString("fully-qualified"), "woman\u2019s boot", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji HAIR_PICK = new Emoji("\ud83e\udeae", "\\uD83E\\uDEAE", Collections.singletonList(":hair_pick:"), Collections.emptyList(), Collections.singletonList(":hair_pick:"), Collections.unmodifiableList(Arrays.asList("Afro", "comb", "groom", "hair", "pick")), false, false, 15.0, Qualification.fromString("fully-qualified"), "hair pick", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji CROWN = new Emoji("\ud83d\udc51", "\\uD83D\\uDC51", Collections.singletonList(":crown:"), Collections.singletonList(":crown:"), Collections.singletonList(":crown:"), Collections.unmodifiableList(Arrays.asList("clothing", "crown", "family", "king", "medieval", "queen", "royal", "royalty", "win")), false, false, 0.6, Qualification.fromString("fully-qualified"), "crown", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji WOMAN_S_HAT = new Emoji("\ud83d\udc52", "\\uD83D\\uDC52", Collections.singletonList(":womans_hat:"), Collections.singletonList(":womans_hat:"), Collections.singletonList(":womans_hat:"), Collections.unmodifiableList(Arrays.asList("clothes", "clothing", "garden", "hat", "hats", "party", "woman", "woman\u2019s")), false, false, 0.6, Qualification.fromString("fully-qualified"), "woman\u2019s hat", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji TOP_HAT = new Emoji("\ud83c\udfa9", "\\uD83C\\uDFA9", Collections.unmodifiableList(Arrays.asList(":tophat:", ":top_hat:")), Collections.singletonList(":tophat:"), Collections.singletonList(":tophat:"), Collections.unmodifiableList(Arrays.asList("clothes", "clothing", "fancy", "formal", "hat", "magic", "top", "tophat")), false, false, 0.6, Qualification.fromString("fully-qualified"), "top hat", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji GRADUATION_CAP = new Emoji("\ud83c\udf93", "\\uD83C\\uDF93", Collections.singletonList(":mortar_board:"), Collections.singletonList(":mortar_board:"), Collections.singletonList(":mortar_board:"), Collections.unmodifiableList(Arrays.asList("cap", "celebration", "clothing", "com.hypherionmc.sdlink.shaded.education", "graduation", "hat", "scholar")), false, false, 0.6, Qualification.fromString("fully-qualified"), "graduation cap", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, true);
    public static final Emoji BILLED_CAP = new Emoji("\ud83e\udde2", "\\uD83E\\uDDE2", Collections.singletonList(":billed_cap:"), Collections.singletonList(":billed_cap:"), Collections.singletonList(":billed_cap:"), Collections.unmodifiableList(Arrays.asList("baseball", "bent", "billed", "cap", "dad", "hat")), false, false, 5.0, Qualification.fromString("fully-qualified"), "billed cap", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji MILITARY_HELMET = new Emoji("\ud83e\ude96", "\\uD83E\\uDE96", Collections.singletonList(":military_helmet:"), Collections.singletonList(":military_helmet:"), Collections.singletonList(":military_helmet:"), Collections.unmodifiableList(Arrays.asList("army", "helmet", "military", "soldier", "war", "warrior")), false, false, 13.0, Qualification.fromString("fully-qualified"), "military helmet", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji RESCUE_WORKER_S_HELMET = new Emoji("\u26d1\ufe0f", "\\u26D1\\uFE0F", Collections.unmodifiableList(Arrays.asList(":helmet_with_cross:", ":helmet_with_white_cross:")), Collections.singletonList(":helmet_with_white_cross:"), Collections.singletonList(":rescue_worker_helmet:"), Collections.unmodifiableList(Arrays.asList("aid", "cross", "face", "hat", "helmet", "rescue", "worker\u2019s")), false, false, 0.7, Qualification.fromString("fully-qualified"), "rescue worker\u2019s helmet", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji RESCUE_WORKER_S_HELMET_UNQUALIFIED = new Emoji("\u26d1", "\\u26D1", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("aid", "cross", "face", "hat", "helmet", "rescue", "worker\u2019s")), false, false, 0.7, Qualification.fromString("unqualified"), "rescue worker\u2019s helmet", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, true);
    public static final Emoji PRAYER_BEADS = new Emoji("\ud83d\udcff", "\\uD83D\\uDCFF", Collections.singletonList(":prayer_beads:"), Collections.singletonList(":prayer_beads:"), Collections.singletonList(":prayer_beads:"), Collections.unmodifiableList(Arrays.asList("beads", "clothing", "necklace", "prayer", "religion")), false, false, 1.0, Qualification.fromString("fully-qualified"), "prayer beads", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji LIPSTICK = new Emoji("\ud83d\udc84", "\\uD83D\\uDC84", Collections.singletonList(":lipstick:"), Collections.singletonList(":lipstick:"), Collections.singletonList(":lipstick:"), Collections.unmodifiableList(Arrays.asList("cosmetics", "date", "lipstick", "makeup")), false, false, 0.6, Qualification.fromString("fully-qualified"), "lipstick", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji RING = new Emoji("\ud83d\udc8d", "\\uD83D\\uDC8D", Collections.singletonList(":ring:"), Collections.singletonList(":ring:"), Collections.singletonList(":ring:"), Collections.unmodifiableList(Arrays.asList("diamond", "engaged", "engagement", "married", "ring", "romance", "shiny", "sparkling", "wedding")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ring", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
    public static final Emoji GEM_STONE = new Emoji("\ud83d\udc8e", "\\uD83D\\uDC8E", Collections.unmodifiableList(Arrays.asList(":gem:", ":gem_stone:")), Collections.singletonList(":gem:"), Collections.singletonList(":gem:"), Collections.unmodifiableList(Arrays.asList("diamond", "engagement", "gem", "jewel", "money", "romance", "stone", "wedding")), false, false, 0.6, Qualification.fromString("fully-qualified"), "gem stone", EmojiGroup.OBJECTS, EmojiSubGroup.CLOTHING, false);
}

