/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiAnimalMammal {
    public static final Emoji MONKEY_FACE = new Emoji("\ud83d\udc35", "\\uD83D\\uDC35", Collections.singletonList(":monkey_face:"), Collections.singletonList(":monkey_face:"), Collections.singletonList(":monkey_face:"), Collections.unmodifiableList(Arrays.asList("animal", "banana", "face", "monkey")), false, false, 0.6, Qualification.fromString("fully-qualified"), "monkey face", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji MONKEY = new Emoji("\ud83d\udc12", "\\uD83D\\uDC12", Collections.singletonList(":monkey:"), Collections.singletonList(":monkey:"), Collections.singletonList(":monkey:"), Collections.unmodifiableList(Arrays.asList("animal", "banana", "monkey")), false, false, 0.6, Qualification.fromString("fully-qualified"), "monkey", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji GORILLA = new Emoji("\ud83e\udd8d", "\\uD83E\\uDD8D", Collections.singletonList(":gorilla:"), Collections.singletonList(":gorilla:"), Collections.singletonList(":gorilla:"), Collections.unmodifiableList(Arrays.asList("animal", "gorilla")), false, false, 3.0, Qualification.fromString("fully-qualified"), "gorilla", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji ORANGUTAN = new Emoji("\ud83e\udda7", "\\uD83E\\uDDA7", Collections.singletonList(":orangutan:"), Collections.singletonList(":orangutan:"), Collections.singletonList(":orangutan:"), Collections.unmodifiableList(Arrays.asList("animal", "ape", "monkey", "orangutan")), false, false, 12.0, Qualification.fromString("fully-qualified"), "orangutan", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji DOG_FACE = new Emoji("\ud83d\udc36", "\\uD83D\\uDC36", Collections.unmodifiableList(Arrays.asList(":dog:", ":dog_face:")), Collections.singletonList(":dog:"), Collections.singletonList(":dog:"), Collections.unmodifiableList(Arrays.asList("adorbs", "animal", "dog", "face", "pet", "puppies", "puppy")), false, false, 0.6, Qualification.fromString("fully-qualified"), "dog face", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji DOG = new Emoji("\ud83d\udc15", "\\uD83D\\uDC15", Collections.singletonList(":dog2:"), Collections.singletonList(":dog2:"), Collections.singletonList(":dog2:"), Collections.unmodifiableList(Arrays.asList("animal", "animals", "dog", "dogs", "pet")), false, false, 0.7, Qualification.fromString("fully-qualified"), "dog", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, true);
    public static final Emoji GUIDE_DOG = new Emoji("\ud83e\uddae", "\\uD83E\\uDDAE", Collections.singletonList(":guide_dog:"), Collections.singletonList(":guide_dog:"), Collections.singletonList(":guide_dog:"), Collections.unmodifiableList(Arrays.asList("accessibility", "animal", "blind", "dog", "guide")), false, false, 12.0, Qualification.fromString("fully-qualified"), "guide dog", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji SERVICE_DOG = new Emoji("\ud83d\udc15\u200d\ud83e\uddba", "\\uD83D\\uDC15\\u200D\\uD83E\\uDDBA", Collections.singletonList(":service_dog:"), Collections.singletonList(":service_dog:"), Collections.singletonList(":service_dog:"), Collections.unmodifiableList(Arrays.asList("accessibility", "animal", "assistance", "dog", "service")), false, false, 12.0, Qualification.fromString("fully-qualified"), "service dog", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji POODLE = new Emoji("\ud83d\udc29", "\\uD83D\\uDC29", Collections.singletonList(":poodle:"), Collections.singletonList(":poodle:"), Collections.singletonList(":poodle:"), Collections.unmodifiableList(Arrays.asList("animal", "dog", "fluffy", "poodle")), false, false, 0.6, Qualification.fromString("fully-qualified"), "poodle", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji WOLF = new Emoji("\ud83d\udc3a", "\\uD83D\\uDC3A", Collections.singletonList(":wolf:"), Collections.singletonList(":wolf:"), Collections.singletonList(":wolf:"), Collections.unmodifiableList(Arrays.asList("animal", "face", "wolf")), false, false, 0.6, Qualification.fromString("fully-qualified"), "wolf", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji FOX = new Emoji("\ud83e\udd8a", "\\uD83E\\uDD8A", Collections.unmodifiableList(Arrays.asList(":fox:", ":fox_face:")), Collections.singletonList(":fox_face:"), Collections.singletonList(":fox_face:"), Collections.unmodifiableList(Arrays.asList("animal", "face", "fox")), false, false, 3.0, Qualification.fromString("fully-qualified"), "fox", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji RACCOON = new Emoji("\ud83e\udd9d", "\\uD83E\\uDD9D", Collections.singletonList(":raccoon:"), Collections.singletonList(":raccoon:"), Collections.singletonList(":raccoon:"), Collections.unmodifiableList(Arrays.asList("animal", "curious", "raccoon", "sly")), false, false, 11.0, Qualification.fromString("fully-qualified"), "raccoon", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji CAT_FACE = new Emoji("\ud83d\udc31", "\\uD83D\\uDC31", Collections.unmodifiableList(Arrays.asList(":cat:", ":cat_face:")), Collections.singletonList(":cat:"), Collections.singletonList(":cat:"), Collections.unmodifiableList(Arrays.asList("animal", "cat", "face", "kitten", "kitty", "pet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "cat face", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji CAT = new Emoji("\ud83d\udc08", "\\uD83D\\uDC08", Collections.singletonList(":cat2:"), Collections.singletonList(":cat2:"), Collections.singletonList(":cat2:"), Collections.unmodifiableList(Arrays.asList("animal", "animals", "cat", "cats", "kitten", "pet")), false, false, 0.7, Qualification.fromString("fully-qualified"), "cat", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, true);
    public static final Emoji BLACK_CAT = new Emoji("\ud83d\udc08\u200d\u2b1b", "\\uD83D\\uDC08\\u200D\\u2B1B", Collections.singletonList(":black_cat:"), Collections.singletonList(":black_cat:"), Collections.singletonList(":black_cat:"), Collections.unmodifiableList(Arrays.asList("animal", "black", "cat", "feline", "halloween", "meow", "unlucky")), false, false, 13.0, Qualification.fromString("fully-qualified"), "black cat", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji LION = new Emoji("\ud83e\udd81", "\\uD83E\\uDD81", Collections.unmodifiableList(Arrays.asList(":lion_face:", ":lion:")), Collections.singletonList(":lion_face:"), Collections.singletonList(":lion:"), Collections.unmodifiableList(Arrays.asList("alpha", "animal", "face", "Leo", "lion", "mane", "order", "rawr", "roar", "safari", "strong", "zodiac")), false, false, 1.0, Qualification.fromString("fully-qualified"), "lion", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji TIGER_FACE = new Emoji("\ud83d\udc2f", "\\uD83D\\uDC2F", Collections.unmodifiableList(Arrays.asList(":tiger:", ":tiger_face:")), Collections.singletonList(":tiger:"), Collections.singletonList(":tiger:"), Collections.unmodifiableList(Arrays.asList("animal", "big", "cat", "face", "predator", "tiger")), false, false, 0.6, Qualification.fromString("fully-qualified"), "tiger face", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji TIGER = new Emoji("\ud83d\udc05", "\\uD83D\\uDC05", Collections.singletonList(":tiger2:"), Collections.singletonList(":tiger2:"), Collections.singletonList(":tiger2:"), Collections.unmodifiableList(Arrays.asList("animal", "big", "cat", "predator", "tiger", "zoo")), false, false, 1.0, Qualification.fromString("fully-qualified"), "tiger", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji LEOPARD = new Emoji("\ud83d\udc06", "\\uD83D\\uDC06", Collections.singletonList(":leopard:"), Collections.singletonList(":leopard:"), Collections.singletonList(":leopard:"), Collections.unmodifiableList(Arrays.asList("animal", "big", "cat", "leopard", "predator", "zoo")), false, false, 1.0, Qualification.fromString("fully-qualified"), "leopard", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji HORSE_FACE = new Emoji("\ud83d\udc34", "\\uD83D\\uDC34", Collections.unmodifiableList(Arrays.asList(":horse:", ":horse_face:")), Collections.singletonList(":horse:"), Collections.singletonList(":horse:"), Collections.unmodifiableList(Arrays.asList("animal", "dressage", "equine", "face", "farm", "horse", "horses")), false, false, 0.6, Qualification.fromString("fully-qualified"), "horse face", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji MOOSE = new Emoji("\ud83e\udece", "\\uD83E\\uDECE", Collections.singletonList(":moose:"), Collections.emptyList(), Collections.singletonList(":moose:"), Collections.unmodifiableList(Arrays.asList("alces", "animal", "antlers", "elk", "mammal", "moose")), false, false, 15.0, Qualification.fromString("fully-qualified"), "moose", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji DONKEY = new Emoji("\ud83e\udecf", "\\uD83E\\uDECF", Collections.singletonList(":donkey:"), Collections.emptyList(), Collections.singletonList(":donkey:"), Collections.unmodifiableList(Arrays.asList("animal", "ass", "burro", "donkey", "hinny", "mammal", "mule", "stubborn")), false, false, 15.0, Qualification.fromString("fully-qualified"), "donkey", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji HORSE = new Emoji("\ud83d\udc0e", "\\uD83D\\uDC0E", Collections.singletonList(":racehorse:"), Collections.singletonList(":racehorse:"), Collections.singletonList(":racehorse:"), Collections.unmodifiableList(Arrays.asList("animal", "equestrian", "farm", "horse", "racehorse", "racing")), false, false, 0.6, Qualification.fromString("fully-qualified"), "horse", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji UNICORN = new Emoji("\ud83e\udd84", "\\uD83E\\uDD84", Collections.unmodifiableList(Arrays.asList(":unicorn:", ":unicorn_face:")), Collections.singletonList(":unicorn_face:"), Collections.singletonList(":unicorn:"), Collections.unmodifiableList(Arrays.asList("face", "unicorn")), false, false, 1.0, Qualification.fromString("fully-qualified"), "unicorn", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji ZEBRA = new Emoji("\ud83e\udd93", "\\uD83E\\uDD93", Collections.singletonList(":zebra:"), Collections.singletonList(":zebra_face:"), Collections.singletonList(":zebra:"), Collections.unmodifiableList(Arrays.asList("animal", "stripe", "zebra")), false, false, 5.0, Qualification.fromString("fully-qualified"), "zebra", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji DEER = new Emoji("\ud83e\udd8c", "\\uD83E\\uDD8C", Collections.singletonList(":deer:"), Collections.singletonList(":deer:"), Collections.singletonList(":deer:"), Collections.unmodifiableList(Arrays.asList("animal", "deer")), false, false, 3.0, Qualification.fromString("fully-qualified"), "deer", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji BISON = new Emoji("\ud83e\uddac", "\\uD83E\\uDDAC", Collections.singletonList(":bison:"), Collections.singletonList(":bison:"), Collections.singletonList(":bison:"), Collections.unmodifiableList(Arrays.asList("animal", "bison", "buffalo", "herd", "wisent")), false, false, 13.0, Qualification.fromString("fully-qualified"), "bison", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji COW_FACE = new Emoji("\ud83d\udc2e", "\\uD83D\\uDC2E", Collections.unmodifiableList(Arrays.asList(":cow:", ":cow_face:")), Collections.singletonList(":cow:"), Collections.singletonList(":cow:"), Collections.unmodifiableList(Arrays.asList("animal", "cow", "face", "farm", "milk", "moo")), false, false, 0.6, Qualification.fromString("fully-qualified"), "cow face", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji OX = new Emoji("\ud83d\udc02", "\\uD83D\\uDC02", Collections.singletonList(":ox:"), Collections.singletonList(":ox:"), Collections.singletonList(":ox:"), Collections.unmodifiableList(Arrays.asList("animal", "animals", "bull", "farm", "ox", "Taurus", "zodiac")), false, false, 1.0, Qualification.fromString("fully-qualified"), "ox", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji WATER_BUFFALO = new Emoji("\ud83d\udc03", "\\uD83D\\uDC03", Collections.singletonList(":water_buffalo:"), Collections.singletonList(":water_buffalo:"), Collections.singletonList(":water_buffalo:"), Collections.unmodifiableList(Arrays.asList("animal", "buffalo", "water", "zoo")), false, false, 1.0, Qualification.fromString("fully-qualified"), "water buffalo", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji COW = new Emoji("\ud83d\udc04", "\\uD83D\\uDC04", Collections.singletonList(":cow2:"), Collections.singletonList(":cow2:"), Collections.singletonList(":cow2:"), Collections.unmodifiableList(Arrays.asList("animal", "animals", "cow", "farm", "milk", "moo")), false, false, 1.0, Qualification.fromString("fully-qualified"), "cow", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji PIG_FACE = new Emoji("\ud83d\udc37", "\\uD83D\\uDC37", Collections.unmodifiableList(Arrays.asList(":pig:", ":pig_face:")), Collections.singletonList(":pig:"), Collections.singletonList(":pig:"), Collections.unmodifiableList(Arrays.asList("animal", "bacon", "face", "farm", "pig", "pork")), false, false, 0.6, Qualification.fromString("fully-qualified"), "pig face", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji PIG = new Emoji("\ud83d\udc16", "\\uD83D\\uDC16", Collections.singletonList(":pig2:"), Collections.singletonList(":pig2:"), Collections.singletonList(":pig2:"), Collections.unmodifiableList(Arrays.asList("animal", "bacon", "farm", "pig", "pork", "sow")), false, false, 1.0, Qualification.fromString("fully-qualified"), "pig", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji BOAR = new Emoji("\ud83d\udc17", "\\uD83D\\uDC17", Collections.singletonList(":boar:"), Collections.singletonList(":boar:"), Collections.singletonList(":boar:"), Collections.unmodifiableList(Arrays.asList("animal", "boar", "pig")), false, false, 0.6, Qualification.fromString("fully-qualified"), "boar", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji PIG_NOSE = new Emoji("\ud83d\udc3d", "\\uD83D\\uDC3D", Collections.singletonList(":pig_nose:"), Collections.singletonList(":pig_nose:"), Collections.singletonList(":pig_nose:"), Collections.unmodifiableList(Arrays.asList("animal", "face", "farm", "nose", "pig", "smell", "snout")), false, false, 0.6, Qualification.fromString("fully-qualified"), "pig nose", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji RAM = new Emoji("\ud83d\udc0f", "\\uD83D\\uDC0F", Collections.singletonList(":ram:"), Collections.singletonList(":ram:"), Collections.singletonList(":ram:"), Collections.unmodifiableList(Arrays.asList("animal", "Aries", "horns", "male", "ram", "sheep", "zodiac", "zoo")), false, false, 1.0, Qualification.fromString("fully-qualified"), "ram", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji EWE = new Emoji("\ud83d\udc11", "\\uD83D\\uDC11", Collections.unmodifiableList(Arrays.asList(":sheep:", ":ewe:")), Collections.singletonList(":sheep:"), Collections.singletonList(":sheep:"), Collections.unmodifiableList(Arrays.asList("animal", "baa", "ewe", "farm", "female", "fluffy", "lamb", "sheep", "wool")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ewe", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji GOAT = new Emoji("\ud83d\udc10", "\\uD83D\\uDC10", Collections.singletonList(":goat:"), Collections.singletonList(":goat:"), Collections.singletonList(":goat:"), Collections.unmodifiableList(Arrays.asList("animal", "Capricorn", "farm", "goat", "milk", "zodiac")), false, false, 1.0, Qualification.fromString("fully-qualified"), "goat", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji CAMEL = new Emoji("\ud83d\udc2a", "\\uD83D\\uDC2A", Collections.singletonList(":dromedary_camel:"), Collections.singletonList(":dromedary_camel:"), Collections.singletonList(":dromedary_camel:"), Collections.unmodifiableList(Arrays.asList("animal", "camel", "desert", "dromedary", "hump", "one")), false, false, 1.0, Qualification.fromString("fully-qualified"), "camel", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji TWO_HUMP_CAMEL = new Emoji("\ud83d\udc2b", "\\uD83D\\uDC2B", Collections.singletonList(":camel:"), Collections.singletonList(":camel:"), Collections.singletonList(":camel:"), Collections.unmodifiableList(Arrays.asList("animal", "bactrian", "camel", "desert", "hump", "two", "two-hump")), false, false, 0.6, Qualification.fromString("fully-qualified"), "two-hump camel", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji LLAMA = new Emoji("\ud83e\udd99", "\\uD83E\\uDD99", Collections.singletonList(":llama:"), Collections.singletonList(":llama:"), Collections.singletonList(":llama:"), Collections.unmodifiableList(Arrays.asList("alpaca", "animal", "guanaco", "llama", "vicu\u00f1a", "wool")), false, false, 11.0, Qualification.fromString("fully-qualified"), "llama", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji GIRAFFE = new Emoji("\ud83e\udd92", "\\uD83E\\uDD92", Collections.singletonList(":giraffe:"), Collections.singletonList(":giraffe_face:"), Collections.singletonList(":giraffe:"), Collections.unmodifiableList(Arrays.asList("animal", "giraffe", "spots")), false, false, 5.0, Qualification.fromString("fully-qualified"), "giraffe", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji ELEPHANT = new Emoji("\ud83d\udc18", "\\uD83D\\uDC18", Collections.singletonList(":elephant:"), Collections.singletonList(":elephant:"), Collections.singletonList(":elephant:"), Collections.unmodifiableList(Arrays.asList("animal", "elephant")), false, false, 0.6, Qualification.fromString("fully-qualified"), "elephant", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji MAMMOTH = new Emoji("\ud83e\udda3", "\\uD83E\\uDDA3", Collections.singletonList(":mammoth:"), Collections.singletonList(":mammoth:"), Collections.singletonList(":mammoth:"), Collections.unmodifiableList(Arrays.asList("animal", "extinction", "large", "mammoth", "tusk", "wooly")), false, false, 13.0, Qualification.fromString("fully-qualified"), "mammoth", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji RHINOCEROS = new Emoji("\ud83e\udd8f", "\\uD83E\\uDD8F", Collections.unmodifiableList(Arrays.asList(":rhino:", ":rhinoceros:")), Collections.singletonList(":rhinoceros:"), Collections.singletonList(":rhinoceros:"), Collections.unmodifiableList(Arrays.asList("animal", "rhinoceros")), false, false, 3.0, Qualification.fromString("fully-qualified"), "rhinoceros", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji HIPPOPOTAMUS = new Emoji("\ud83e\udd9b", "\\uD83E\\uDD9B", Collections.singletonList(":hippopotamus:"), Collections.singletonList(":hippopotamus:"), Collections.singletonList(":hippopotamus:"), Collections.unmodifiableList(Arrays.asList("animal", "hippo", "hippopotamus")), false, false, 11.0, Qualification.fromString("fully-qualified"), "hippopotamus", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji MOUSE_FACE = new Emoji("\ud83d\udc2d", "\\uD83D\\uDC2D", Collections.unmodifiableList(Arrays.asList(":mouse:", ":mouse_face:")), Collections.singletonList(":mouse:"), Collections.singletonList(":mouse:"), Collections.unmodifiableList(Arrays.asList("animal", "face", "mouse")), false, false, 0.6, Qualification.fromString("fully-qualified"), "mouse face", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji MOUSE = new Emoji("\ud83d\udc01", "\\uD83D\\uDC01", Collections.singletonList(":mouse2:"), Collections.singletonList(":mouse2:"), Collections.singletonList(":mouse2:"), Collections.unmodifiableList(Arrays.asList("animal", "animals", "mouse")), false, false, 1.0, Qualification.fromString("fully-qualified"), "mouse", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji RAT = new Emoji("\ud83d\udc00", "\\uD83D\\uDC00", Collections.singletonList(":rat:"), Collections.singletonList(":rat:"), Collections.singletonList(":rat:"), Collections.unmodifiableList(Arrays.asList("animal", "rat")), false, false, 1.0, Qualification.fromString("fully-qualified"), "rat", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji HAMSTER = new Emoji("\ud83d\udc39", "\\uD83D\\uDC39", Collections.singletonList(":hamster:"), Collections.singletonList(":hamster:"), Collections.singletonList(":hamster:"), Collections.unmodifiableList(Arrays.asList("animal", "face", "hamster", "pet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "hamster", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji RABBIT_FACE = new Emoji("\ud83d\udc30", "\\uD83D\\uDC30", Collections.unmodifiableList(Arrays.asList(":rabbit:", ":rabbit_face:")), Collections.singletonList(":rabbit:"), Collections.singletonList(":rabbit:"), Collections.unmodifiableList(Arrays.asList("animal", "bunny", "face", "pet", "rabbit")), false, false, 0.6, Qualification.fromString("fully-qualified"), "rabbit face", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji RABBIT = new Emoji("\ud83d\udc07", "\\uD83D\\uDC07", Collections.singletonList(":rabbit2:"), Collections.singletonList(":rabbit2:"), Collections.singletonList(":rabbit2:"), Collections.unmodifiableList(Arrays.asList("animal", "bunny", "pet", "rabbit")), false, false, 1.0, Qualification.fromString("fully-qualified"), "rabbit", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji CHIPMUNK = new Emoji("\ud83d\udc3f\ufe0f", "\\uD83D\\uDC3F\\uFE0F", Collections.singletonList(":chipmunk:"), Collections.singletonList(":chipmunk:"), Collections.singletonList(":chipmunk:"), Collections.unmodifiableList(Arrays.asList("animal", "chipmunk", "squirrel")), false, false, 0.7, Qualification.fromString("fully-qualified"), "chipmunk", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji CHIPMUNK_UNQUALIFIED = new Emoji("\ud83d\udc3f", "\\uD83D\\uDC3F", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("animal", "chipmunk", "squirrel")), false, false, 0.7, Qualification.fromString("unqualified"), "chipmunk", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, true);
    public static final Emoji BEAVER = new Emoji("\ud83e\uddab", "\\uD83E\\uDDAB", Collections.singletonList(":beaver:"), Collections.singletonList(":beaver:"), Collections.singletonList(":beaver:"), Collections.unmodifiableList(Arrays.asList("animal", "beaver", "dam", "teeth")), false, false, 13.0, Qualification.fromString("fully-qualified"), "beaver", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji HEDGEHOG = new Emoji("\ud83e\udd94", "\\uD83E\\uDD94", Collections.singletonList(":hedgehog:"), Collections.singletonList(":hedgehog:"), Collections.singletonList(":hedgehog:"), Collections.unmodifiableList(Arrays.asList("animal", "hedgehog", "spiny")), false, false, 5.0, Qualification.fromString("fully-qualified"), "hedgehog", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji BAT = new Emoji("\ud83e\udd87", "\\uD83E\\uDD87", Collections.singletonList(":bat:"), Collections.singletonList(":bat:"), Collections.singletonList(":bat:"), Collections.unmodifiableList(Arrays.asList("animal", "bat", "vampire")), false, false, 3.0, Qualification.fromString("fully-qualified"), "bat", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji BEAR = new Emoji("\ud83d\udc3b", "\\uD83D\\uDC3B", Collections.singletonList(":bear:"), Collections.singletonList(":bear:"), Collections.singletonList(":bear:"), Collections.unmodifiableList(Arrays.asList("animal", "bear", "face", "grizzly", "growl", "honey")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bear", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji POLAR_BEAR = new Emoji("\ud83d\udc3b\u200d\u2744\ufe0f", "\\uD83D\\uDC3B\\u200D\\u2744\\uFE0F", Collections.singletonList(":polar_bear:"), Collections.singletonList(":polar_bear:"), Collections.singletonList(":polar_bear:"), Collections.unmodifiableList(Arrays.asList("animal", "arctic", "bear", "polar", "white")), false, false, 13.0, Qualification.fromString("fully-qualified"), "polar bear", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji POLAR_BEAR_MINIMALLY_QUALIFIED = new Emoji("\ud83d\udc3b\u200d\u2744", "\\uD83D\\uDC3B\\u200D\\u2744", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("animal", "arctic", "bear", "polar", "white")), false, false, 13.0, Qualification.fromString("minimally-qualified"), "polar bear", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji KOALA = new Emoji("\ud83d\udc28", "\\uD83D\\uDC28", Collections.singletonList(":koala:"), Collections.singletonList(":koala:"), Collections.singletonList(":koala:"), Collections.unmodifiableList(Arrays.asList("animal", "australia", "bear", "down", "face", "koala", "marsupial", "under")), false, false, 0.6, Qualification.fromString("fully-qualified"), "koala", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji PANDA = new Emoji("\ud83d\udc3c", "\\uD83D\\uDC3C", Collections.unmodifiableList(Arrays.asList(":panda_face:", ":panda:")), Collections.singletonList(":panda_face:"), Collections.singletonList(":panda_face:"), Collections.unmodifiableList(Arrays.asList("animal", "bamboo", "face", "panda")), false, false, 0.6, Qualification.fromString("fully-qualified"), "panda", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji SLOTH = new Emoji("\ud83e\udda5", "\\uD83E\\uDDA5", Collections.singletonList(":sloth:"), Collections.singletonList(":sloth:"), Collections.singletonList(":sloth:"), Collections.unmodifiableList(Arrays.asList("lazy", "sloth", "slow")), false, false, 12.0, Qualification.fromString("fully-qualified"), "sloth", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji OTTER = new Emoji("\ud83e\udda6", "\\uD83E\\uDDA6", Collections.singletonList(":otter:"), Collections.singletonList(":otter:"), Collections.singletonList(":otter:"), Collections.unmodifiableList(Arrays.asList("animal", "fishing", "otter", "playful")), false, false, 12.0, Qualification.fromString("fully-qualified"), "otter", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji SKUNK = new Emoji("\ud83e\udda8", "\\uD83E\\uDDA8", Collections.singletonList(":skunk:"), Collections.singletonList(":skunk:"), Collections.singletonList(":skunk:"), Collections.unmodifiableList(Arrays.asList("animal", "skunk", "stink")), false, false, 12.0, Qualification.fromString("fully-qualified"), "skunk", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji KANGAROO = new Emoji("\ud83e\udd98", "\\uD83E\\uDD98", Collections.singletonList(":kangaroo:"), Collections.singletonList(":kangaroo:"), Collections.singletonList(":kangaroo:"), Collections.unmodifiableList(Arrays.asList("animal", "joey", "jump", "kangaroo", "marsupial")), false, false, 11.0, Qualification.fromString("fully-qualified"), "kangaroo", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji BADGER = new Emoji("\ud83e\udda1", "\\uD83E\\uDDA1", Collections.singletonList(":badger:"), Collections.singletonList(":badger:"), Collections.singletonList(":badger:"), Collections.unmodifiableList(Arrays.asList("animal", "badger", "honey", "pester")), false, false, 11.0, Qualification.fromString("fully-qualified"), "badger", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
    public static final Emoji PAW_PRINTS = new Emoji("\ud83d\udc3e", "\\uD83D\\uDC3E", Collections.unmodifiableList(Arrays.asList(":feet:", ":paw_prints:")), Collections.unmodifiableList(Arrays.asList(":feet:", ":paw_prints:")), Collections.unmodifiableList(Arrays.asList(":feet:", ":paw_prints:")), Collections.unmodifiableList(Arrays.asList("feet", "paw", "paws", "print", "prints")), false, false, 0.6, Qualification.fromString("fully-qualified"), "paw prints", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_MAMMAL, false);
}

