/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiTransportGround {
    public static final Emoji LOCOMOTIVE = new Emoji("\ud83d\ude82", "\\uD83D\\uDE82", Collections.unmodifiableList(Arrays.asList(":steam_locomotive:", ":locomotive:")), Collections.singletonList(":steam_locomotive:"), Collections.singletonList(":steam_locomotive:"), Collections.unmodifiableList(Arrays.asList("caboose", "engine", "locomotive", "railway", "steam", "train", "trains", "travel")), false, false, 1.0, Qualification.fromString("fully-qualified"), "locomotive", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji RAILWAY_CAR = new Emoji("\ud83d\ude83", "\\uD83D\\uDE83", Collections.singletonList(":railway_car:"), Collections.singletonList(":railway_car:"), Collections.singletonList(":railway_car:"), Collections.unmodifiableList(Arrays.asList("car", "electric", "railway", "train", "tram", "travel", "trolleybus")), false, false, 0.6, Qualification.fromString("fully-qualified"), "railway car", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji HIGH_SPEED_TRAIN = new Emoji("\ud83d\ude84", "\\uD83D\\uDE84", Collections.singletonList(":bullettrain_side:"), Collections.singletonList(":bullettrain_side:"), Collections.singletonList(":bullettrain_side:"), Collections.unmodifiableList(Arrays.asList("high-speed", "railway", "shinkansen", "speed", "train")), false, false, 0.6, Qualification.fromString("fully-qualified"), "high-speed train", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji BULLET_TRAIN = new Emoji("\ud83d\ude85", "\\uD83D\\uDE85", Collections.unmodifiableList(Arrays.asList(":bullettrain_front:", ":bullet_train:")), Collections.singletonList(":bullettrain_front:"), Collections.singletonList(":bullettrain_front:"), Collections.unmodifiableList(Arrays.asList("bullet", "high-speed", "nose", "railway", "shinkansen", "speed", "train", "travel")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bullet train", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji TRAIN = new Emoji("\ud83d\ude86", "\\uD83D\\uDE86", Collections.singletonList(":train2:"), Collections.singletonList(":train2:"), Collections.singletonList(":train2:"), Collections.unmodifiableList(Arrays.asList("arrived", "choo", "railway", "train")), false, false, 1.0, Qualification.fromString("fully-qualified"), "train", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji METRO = new Emoji("\ud83d\ude87", "\\uD83D\\uDE87", Collections.singletonList(":metro:"), Collections.singletonList(":metro:"), Collections.singletonList(":metro:"), Collections.unmodifiableList(Arrays.asList("metro", "subway", "travel")), false, false, 0.6, Qualification.fromString("fully-qualified"), "metro", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, true);
    public static final Emoji LIGHT_RAIL = new Emoji("\ud83d\ude88", "\\uD83D\\uDE88", Collections.singletonList(":light_rail:"), Collections.singletonList(":light_rail:"), Collections.singletonList(":light_rail:"), Collections.unmodifiableList(Arrays.asList("arrived", "light", "monorail", "rail", "railway")), false, false, 1.0, Qualification.fromString("fully-qualified"), "light rail", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji STATION = new Emoji("\ud83d\ude89", "\\uD83D\\uDE89", Collections.singletonList(":station:"), Collections.singletonList(":station:"), Collections.singletonList(":station:"), Collections.unmodifiableList(Arrays.asList("railway", "station", "train")), false, false, 0.6, Qualification.fromString("fully-qualified"), "station", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji TRAM = new Emoji("\ud83d\ude8a", "\\uD83D\\uDE8A", Collections.singletonList(":tram:"), Collections.singletonList(":tram:"), Collections.singletonList(":tram:"), Collections.unmodifiableList(Arrays.asList("tram", "trolleybus")), false, false, 1.0, Qualification.fromString("fully-qualified"), "tram", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji MONORAIL = new Emoji("\ud83d\ude9d", "\\uD83D\\uDE9D", Collections.singletonList(":monorail:"), Collections.singletonList(":monorail:"), Collections.singletonList(":monorail:"), Collections.unmodifiableList(Arrays.asList("monorail", "vehicle")), false, false, 1.0, Qualification.fromString("fully-qualified"), "monorail", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji MOUNTAIN_RAILWAY = new Emoji("\ud83d\ude9e", "\\uD83D\\uDE9E", Collections.singletonList(":mountain_railway:"), Collections.singletonList(":mountain_railway:"), Collections.singletonList(":mountain_railway:"), Collections.unmodifiableList(Arrays.asList("car", "mountain", "railway", "trip")), false, false, 1.0, Qualification.fromString("fully-qualified"), "mountain railway", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji TRAM_CAR = new Emoji("\ud83d\ude8b", "\\uD83D\\uDE8B", Collections.unmodifiableList(Arrays.asList(":train:", ":tram_car:")), Collections.singletonList(":train:"), Collections.singletonList(":train:"), Collections.unmodifiableList(Arrays.asList("bus", "car", "tram", "trolley", "trolleybus")), false, false, 1.0, Qualification.fromString("fully-qualified"), "tram car", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji BUS = new Emoji("\ud83d\ude8c", "\\uD83D\\uDE8C", Collections.singletonList(":bus:"), Collections.singletonList(":bus:"), Collections.singletonList(":bus:"), Collections.unmodifiableList(Arrays.asList("bus", "school", "vehicle")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bus", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji ONCOMING_BUS = new Emoji("\ud83d\ude8d", "\\uD83D\\uDE8D", Collections.singletonList(":oncoming_bus:"), Collections.singletonList(":oncoming_bus:"), Collections.singletonList(":oncoming_bus:"), Collections.unmodifiableList(Arrays.asList("bus", "cars", "oncoming")), false, false, 0.7, Qualification.fromString("fully-qualified"), "oncoming bus", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, true);
    public static final Emoji TROLLEYBUS = new Emoji("\ud83d\ude8e", "\\uD83D\\uDE8E", Collections.singletonList(":trolleybus:"), Collections.singletonList(":trolleybus:"), Collections.singletonList(":trolleybus:"), Collections.unmodifiableList(Arrays.asList("bus", "tram", "trolley", "trolleybus")), false, false, 1.0, Qualification.fromString("fully-qualified"), "trolleybus", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji MINIBUS = new Emoji("\ud83d\ude90", "\\uD83D\\uDE90", Collections.singletonList(":minibus:"), Collections.singletonList(":minibus:"), Collections.singletonList(":minibus:"), Collections.unmodifiableList(Arrays.asList("bus", "drive", "minibus", "van", "vehicle")), false, false, 1.0, Qualification.fromString("fully-qualified"), "minibus", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji AMBULANCE = new Emoji("\ud83d\ude91", "\\uD83D\\uDE91", Collections.singletonList(":ambulance:"), Collections.singletonList(":ambulance:"), Collections.singletonList(":ambulance:"), Collections.unmodifiableList(Arrays.asList("ambulance", "emergency", "vehicle")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ambulance", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, true);
    public static final Emoji FIRE_ENGINE = new Emoji("\ud83d\ude92", "\\uD83D\\uDE92", Collections.singletonList(":fire_engine:"), Collections.singletonList(":fire_engine:"), Collections.singletonList(":fire_engine:"), Collections.unmodifiableList(Arrays.asList("engine", "fire", "truck")), false, false, 0.6, Qualification.fromString("fully-qualified"), "fire engine", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji POLICE_CAR = new Emoji("\ud83d\ude93", "\\uD83D\\uDE93", Collections.singletonList(":police_car:"), Collections.singletonList(":police_car:"), Collections.singletonList(":police_car:"), Collections.unmodifiableList(Arrays.asList("5\u20130", "car", "cops", "patrol", "police")), false, false, 0.6, Qualification.fromString("fully-qualified"), "police car", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji ONCOMING_POLICE_CAR = new Emoji("\ud83d\ude94", "\\uD83D\\uDE94", Collections.singletonList(":oncoming_police_car:"), Collections.singletonList(":oncoming_police_car:"), Collections.singletonList(":oncoming_police_car:"), Collections.unmodifiableList(Arrays.asList("car", "oncoming", "police")), false, false, 0.7, Qualification.fromString("fully-qualified"), "oncoming police car", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, true);
    public static final Emoji TAXI = new Emoji("\ud83d\ude95", "\\uD83D\\uDE95", Collections.singletonList(":taxi:"), Collections.singletonList(":taxi:"), Collections.singletonList(":taxi:"), Collections.unmodifiableList(Arrays.asList("cab", "cabbie", "car", "drive", "taxi", "vehicle", "yellow")), false, false, 0.6, Qualification.fromString("fully-qualified"), "taxi", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji ONCOMING_TAXI = new Emoji("\ud83d\ude96", "\\uD83D\\uDE96", Collections.singletonList(":oncoming_taxi:"), Collections.singletonList(":oncoming_taxi:"), Collections.singletonList(":oncoming_taxi:"), Collections.unmodifiableList(Arrays.asList("cab", "cabbie", "cars", "drove", "hail", "oncoming", "taxi", "yellow")), false, false, 1.0, Qualification.fromString("fully-qualified"), "oncoming taxi", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji AUTOMOBILE = new Emoji("\ud83d\ude97", "\\uD83D\\uDE97", Collections.unmodifiableList(Arrays.asList(":red_car:", ":automobile:")), Collections.unmodifiableList(Arrays.asList(":car:", ":red_car:")), Collections.unmodifiableList(Arrays.asList(":car:", ":red_car:")), Collections.unmodifiableList(Arrays.asList("automobile", "car", "driving", "vehicle")), false, false, 0.6, Qualification.fromString("fully-qualified"), "automobile", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji ONCOMING_AUTOMOBILE = new Emoji("\ud83d\ude98", "\\uD83D\\uDE98", Collections.singletonList(":oncoming_automobile:"), Collections.singletonList(":oncoming_automobile:"), Collections.singletonList(":oncoming_automobile:"), Collections.unmodifiableList(Arrays.asList("automobile", "car", "cars", "drove", "oncoming", "vehicle")), false, false, 0.7, Qualification.fromString("fully-qualified"), "oncoming automobile", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, true);
    public static final Emoji SPORT_UTILITY_VEHICLE = new Emoji("\ud83d\ude99", "\\uD83D\\uDE99", Collections.singletonList(":blue_car:"), Collections.singletonList(":blue_car:"), Collections.singletonList(":blue_car:"), Collections.unmodifiableList(Arrays.asList("car", "drive", "recreational", "sport", "sportutility", "utility", "vehicle")), false, false, 0.6, Qualification.fromString("fully-qualified"), "sport utility vehicle", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji PICKUP_TRUCK = new Emoji("\ud83d\udefb", "\\uD83D\\uDEFB", Collections.singletonList(":pickup_truck:"), Collections.singletonList(":pickup_truck:"), Collections.singletonList(":pickup_truck:"), Collections.unmodifiableList(Arrays.asList("automobile", "car", "flatbed", "pick-up", "pickup", "transportation", "truck")), false, false, 13.0, Qualification.fromString("fully-qualified"), "pickup truck", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji DELIVERY_TRUCK = new Emoji("\ud83d\ude9a", "\\uD83D\\uDE9A", Collections.singletonList(":truck:"), Collections.singletonList(":truck:"), Collections.singletonList(":truck:"), Collections.unmodifiableList(Arrays.asList("car", "delivery", "drive", "truck", "vehicle")), false, false, 0.6, Qualification.fromString("fully-qualified"), "delivery truck", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji ARTICULATED_LORRY = new Emoji("\ud83d\ude9b", "\\uD83D\\uDE9B", Collections.singletonList(":articulated_lorry:"), Collections.singletonList(":articulated_lorry:"), Collections.singletonList(":articulated_lorry:"), Collections.unmodifiableList(Arrays.asList("articulated", "car", "drive", "lorry", "move", "semi", "truck", "vehicle")), false, false, 1.0, Qualification.fromString("fully-qualified"), "articulated lorry", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji TRACTOR = new Emoji("\ud83d\ude9c", "\\uD83D\\uDE9C", Collections.singletonList(":tractor:"), Collections.singletonList(":tractor:"), Collections.singletonList(":tractor:"), Collections.unmodifiableList(Arrays.asList("tractor", "vehicle")), false, false, 1.0, Qualification.fromString("fully-qualified"), "tractor", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji RACING_CAR = new Emoji("\ud83c\udfce\ufe0f", "\\uD83C\\uDFCE\\uFE0F", Collections.unmodifiableList(Arrays.asList(":race_car:", ":racing_car:")), Collections.singletonList(":racing_car:"), Collections.singletonList(":racing_car:"), Collections.unmodifiableList(Arrays.asList("car", "racing", "zoom")), false, false, 0.7, Qualification.fromString("fully-qualified"), "racing car", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji RACING_CAR_UNQUALIFIED = new Emoji("\ud83c\udfce", "\\uD83C\\uDFCE", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("car", "racing", "zoom")), false, false, 0.7, Qualification.fromString("unqualified"), "racing car", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, true);
    public static final Emoji MOTORCYCLE = new Emoji("\ud83c\udfcd\ufe0f", "\\uD83C\\uDFCD\\uFE0F", Collections.unmodifiableList(Arrays.asList(":motorcycle:", ":racing_motorcycle:")), Collections.singletonList(":racing_motorcycle:"), Collections.singletonList(":motorcycle:"), Collections.unmodifiableList(Arrays.asList("motorcycle", "racing")), false, false, 0.7, Qualification.fromString("fully-qualified"), "motorcycle", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji MOTORCYCLE_UNQUALIFIED = new Emoji("\ud83c\udfcd", "\\uD83C\\uDFCD", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("motorcycle", "racing")), false, false, 0.7, Qualification.fromString("unqualified"), "motorcycle", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, true);
    public static final Emoji MOTOR_SCOOTER = new Emoji("\ud83d\udef5", "\\uD83D\\uDEF5", Collections.unmodifiableList(Arrays.asList(":motor_scooter:", ":motorbike:")), Collections.singletonList(":motor_scooter:"), Collections.singletonList(":motor_scooter:"), Collections.unmodifiableList(Arrays.asList("motor", "scooter")), false, false, 3.0, Qualification.fromString("fully-qualified"), "motor scooter", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji MANUAL_WHEELCHAIR = new Emoji("\ud83e\uddbd", "\\uD83E\\uDDBD", Collections.singletonList(":manual_wheelchair:"), Collections.singletonList(":manual_wheelchair:"), Collections.singletonList(":manual_wheelchair:"), Collections.unmodifiableList(Arrays.asList("accessibility", "manual", "wheelchair")), false, false, 12.0, Qualification.fromString("fully-qualified"), "manual wheelchair", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji MOTORIZED_WHEELCHAIR = new Emoji("\ud83e\uddbc", "\\uD83E\\uDDBC", Collections.singletonList(":motorized_wheelchair:"), Collections.singletonList(":motorized_wheelchair:"), Collections.singletonList(":motorized_wheelchair:"), Collections.unmodifiableList(Arrays.asList("accessibility", "motorized", "wheelchair")), false, false, 12.0, Qualification.fromString("fully-qualified"), "motorized wheelchair", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji AUTO_RICKSHAW = new Emoji("\ud83d\udefa", "\\uD83D\\uDEFA", Collections.singletonList(":auto_rickshaw:"), Collections.singletonList(":auto_rickshaw:"), Collections.singletonList(":auto_rickshaw:"), Collections.unmodifiableList(Arrays.asList("auto", "rickshaw", "tuk")), false, false, 12.0, Qualification.fromString("fully-qualified"), "auto rickshaw", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji BICYCLE = new Emoji("\ud83d\udeb2", "\\uD83D\\uDEB2", Collections.unmodifiableList(Arrays.asList(":bike:", ":bicycle:")), Collections.singletonList(":bike:"), Collections.singletonList(":bike:"), Collections.unmodifiableList(Arrays.asList("bicycle", "bike", "class", "cycle", "cycling", "cyclist", "gang", "ride", "spin", "spinning")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bicycle", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, true);
    public static final Emoji KICK_SCOOTER = new Emoji("\ud83d\udef4", "\\uD83D\\uDEF4", Collections.unmodifiableList(Arrays.asList(":scooter:", ":kick_scooter:")), Collections.singletonList(":scooter:"), Collections.singletonList(":kick_scooter:"), Collections.unmodifiableList(Arrays.asList("kick", "scooter")), false, false, 3.0, Qualification.fromString("fully-qualified"), "kick scooter", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji SKATEBOARD = new Emoji("\ud83d\udef9", "\\uD83D\\uDEF9", Collections.singletonList(":skateboard:"), Collections.singletonList(":skateboard:"), Collections.singletonList(":skateboard:"), Collections.unmodifiableList(Arrays.asList("board", "skate", "skateboard", "skater", "wheels")), false, false, 11.0, Qualification.fromString("fully-qualified"), "skateboard", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji ROLLER_SKATE = new Emoji("\ud83d\udefc", "\\uD83D\\uDEFC", Collections.singletonList(":roller_skate:"), Collections.singletonList(":roller_skate:"), Collections.singletonList(":roller_skate:"), Collections.unmodifiableList(Arrays.asList("blades", "roller", "skate", "skates", "sport")), false, false, 13.0, Qualification.fromString("fully-qualified"), "roller skate", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji BUS_STOP = new Emoji("\ud83d\ude8f", "\\uD83D\\uDE8F", Collections.unmodifiableList(Arrays.asList(":busstop:", ":bus_stop:")), Collections.singletonList(":busstop:"), Collections.singletonList(":busstop:"), Collections.unmodifiableList(Arrays.asList("bus", "busstop", "stop")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bus stop", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji MOTORWAY = new Emoji("\ud83d\udee3\ufe0f", "\\uD83D\\uDEE3\\uFE0F", Collections.singletonList(":motorway:"), Collections.singletonList(":motorway:"), Collections.singletonList(":motorway:"), Collections.unmodifiableList(Arrays.asList("highway", "motorway", "road")), false, false, 0.7, Qualification.fromString("fully-qualified"), "motorway", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji MOTORWAY_UNQUALIFIED = new Emoji("\ud83d\udee3", "\\uD83D\\uDEE3", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("highway", "motorway", "road")), false, false, 0.7, Qualification.fromString("unqualified"), "motorway", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, true);
    public static final Emoji RAILWAY_TRACK = new Emoji("\ud83d\udee4\ufe0f", "\\uD83D\\uDEE4\\uFE0F", Collections.unmodifiableList(Arrays.asList(":railway_track:", ":railroad_track:")), Collections.singletonList(":railway_track:"), Collections.singletonList(":railway_track:"), Collections.unmodifiableList(Arrays.asList("railway", "track", "train")), false, false, 0.7, Qualification.fromString("fully-qualified"), "railway track", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji RAILWAY_TRACK_UNQUALIFIED = new Emoji("\ud83d\udee4", "\\uD83D\\uDEE4", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("railway", "track", "train")), false, false, 0.7, Qualification.fromString("unqualified"), "railway track", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, true);
    public static final Emoji OIL_DRUM = new Emoji("\ud83d\udee2\ufe0f", "\\uD83D\\uDEE2\\uFE0F", Collections.unmodifiableList(Arrays.asList(":oil:", ":oil_drum:")), Collections.singletonList(":oil_drum:"), Collections.singletonList(":oil_drum:"), Collections.unmodifiableList(Arrays.asList("drum", "oil")), false, false, 0.7, Qualification.fromString("fully-qualified"), "oil drum", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji OIL_DRUM_UNQUALIFIED = new Emoji("\ud83d\udee2", "\\uD83D\\uDEE2", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("drum", "oil")), false, false, 0.7, Qualification.fromString("unqualified"), "oil drum", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, true);
    public static final Emoji FUEL_PUMP = new Emoji("\u26fd", "\\u26FD", Collections.unmodifiableList(Arrays.asList(":fuelpump:", ":fuel_pump:")), Collections.singletonList(":fuelpump:"), Collections.singletonList(":fuelpump:"), Collections.unmodifiableList(Arrays.asList("diesel", "fuel", "fuelpump", "gas", "gasoline", "pump", "station")), false, false, 0.6, Qualification.fromString("fully-qualified"), "fuel pump", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, true);
    public static final Emoji WHEEL = new Emoji("\ud83d\udede", "\\uD83D\\uDEDE", Collections.singletonList(":wheel:"), Collections.singletonList(":wheel:"), Collections.singletonList(":wheel:"), Collections.unmodifiableList(Arrays.asList("car", "circle", "tire", "turn", "vehicle", "wheel")), false, false, 14.0, Qualification.fromString("fully-qualified"), "wheel", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji POLICE_CAR_LIGHT = new Emoji("\ud83d\udea8", "\\uD83D\\uDEA8", Collections.singletonList(":rotating_light:"), Collections.singletonList(":rotating_light:"), Collections.singletonList(":rotating_light:"), Collections.unmodifiableList(Arrays.asList("alarm", "alert", "beacon", "car", "emergency", "light", "police", "revolving", "siren")), false, false, 0.6, Qualification.fromString("fully-qualified"), "police car light", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji HORIZONTAL_TRAFFIC_LIGHT = new Emoji("\ud83d\udea5", "\\uD83D\\uDEA5", Collections.singletonList(":traffic_light:"), Collections.singletonList(":traffic_light:"), Collections.singletonList(":traffic_light:"), Collections.unmodifiableList(Arrays.asList("horizontal", "intersection", "light", "signal", "stop", "stoplight", "traffic")), false, false, 0.6, Qualification.fromString("fully-qualified"), "horizontal traffic light", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji VERTICAL_TRAFFIC_LIGHT = new Emoji("\ud83d\udea6", "\\uD83D\\uDEA6", Collections.singletonList(":vertical_traffic_light:"), Collections.singletonList(":vertical_traffic_light:"), Collections.singletonList(":vertical_traffic_light:"), Collections.unmodifiableList(Arrays.asList("drove", "intersection", "light", "signal", "stop", "stoplight", "traffic", "vertical")), false, false, 1.0, Qualification.fromString("fully-qualified"), "vertical traffic light", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji STOP_SIGN = new Emoji("\ud83d\uded1", "\\uD83D\\uDED1", Collections.unmodifiableList(Arrays.asList(":octagonal_sign:", ":stop_sign:")), Collections.singletonList(":octagonal_sign:"), Collections.singletonList(":stop_sign:"), Collections.unmodifiableList(Arrays.asList("octagonal", "sign", "stop")), false, false, 3.0, Qualification.fromString("fully-qualified"), "stop sign", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
    public static final Emoji CONSTRUCTION = new Emoji("\ud83d\udea7", "\\uD83D\\uDEA7", Collections.singletonList(":construction:"), Collections.singletonList(":construction:"), Collections.singletonList(":construction:"), Collections.unmodifiableList(Arrays.asList("barrier", "construction")), false, false, 0.6, Qualification.fromString("fully-qualified"), "construction", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_GROUND, false);
}

