/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiOtherSymbol {
    public static final Emoji MEDICAL_SYMBOL = new Emoji("\u2695\ufe0f", "\\u2695\\uFE0F", Collections.singletonList(":medical_symbol:"), Collections.unmodifiableList(Arrays.asList(":medical_symbol:", ":staff_of_aesculapius:")), Collections.singletonList(":medical_symbol:"), Collections.unmodifiableList(Arrays.asList("aesculapius", "medical", "medicine", "staff", "symbol")), false, false, 4.0, Qualification.fromString("fully-qualified"), "medical symbol", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji MEDICAL_SYMBOL_UNQUALIFIED = new Emoji("\u2695", "\\u2695", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("aesculapius", "medical", "medicine", "staff", "symbol")), false, false, 4.0, Qualification.fromString("unqualified"), "medical symbol", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji RECYCLING_SYMBOL = new Emoji("\u267b\ufe0f", "\\u267B\\uFE0F", Collections.singletonList(":recycle:"), Collections.singletonList(":recycle:"), Collections.singletonList(":recycle:"), Collections.unmodifiableList(Arrays.asList("recycle", "recycling", "symbol")), false, false, 0.6, Qualification.fromString("fully-qualified"), "recycling symbol", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji RECYCLING_SYMBOL_UNQUALIFIED = new Emoji("\u267b", "\\u267B", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("recycle", "recycling", "symbol")), false, false, 0.6, Qualification.fromString("unqualified"), "recycling symbol", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji FLEUR_DE_LIS = new Emoji("\u269c\ufe0f", "\\u269C\\uFE0F", Collections.singletonList(":fleur_de_lis:"), Collections.singletonList(":fleur_de_lis:"), Collections.singletonList(":fleur_de_lis:"), Collections.unmodifiableList(Arrays.asList("fleur-de-lis", "knights")), false, false, 1.0, Qualification.fromString("fully-qualified"), "fleur-de-lis", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji FLEUR_DE_LIS_UNQUALIFIED = new Emoji("\u269c", "\\u269C", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("fleur-de-lis", "knights")), false, false, 1.0, Qualification.fromString("unqualified"), "fleur-de-lis", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji TRIDENT_EMBLEM = new Emoji("\ud83d\udd31", "\\uD83D\\uDD31", Collections.singletonList(":trident:"), Collections.singletonList(":trident:"), Collections.singletonList(":trident:"), Collections.unmodifiableList(Arrays.asList("anchor", "emblem", "poseidon", "ship", "tool", "trident")), false, false, 0.6, Qualification.fromString("fully-qualified"), "trident emblem", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji NAME_BADGE = new Emoji("\ud83d\udcdb", "\\uD83D\\uDCDB", Collections.singletonList(":name_badge:"), Collections.singletonList(":name_badge:"), Collections.singletonList(":name_badge:"), Collections.unmodifiableList(Arrays.asList("badge", "name")), false, false, 0.6, Qualification.fromString("fully-qualified"), "name badge", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji JAPANESE_SYMBOL_FOR_BEGINNER = new Emoji("\ud83d\udd30", "\\uD83D\\uDD30", Collections.singletonList(":beginner:"), Collections.singletonList(":beginner:"), Collections.singletonList(":beginner:"), Collections.unmodifiableList(Arrays.asList("beginner", "chevron", "green", "Japanese", "leaf", "symbol", "tool", "yellow")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese symbol for beginner", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji HOLLOW_RED_CIRCLE = new Emoji("\u2b55", "\\u2B55", Collections.singletonList(":o:"), Collections.singletonList(":o:"), Collections.singletonList(":o:"), Collections.unmodifiableList(Arrays.asList("circle", "heavy", "hollow", "large", "o", "red")), false, false, 0.6, Qualification.fromString("fully-qualified"), "hollow red circle", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji CHECK_MARK_BUTTON = new Emoji("\u2705", "\\u2705", Collections.singletonList(":white_check_mark:"), Collections.singletonList(":white_check_mark:"), Collections.singletonList(":white_check_mark:"), Collections.unmodifiableList(Arrays.asList("\u2713", "button", "check", "checked", "checkmark", "complete", "completed", "done", "fixed", "mark", "tick")), false, false, 0.6, Qualification.fromString("fully-qualified"), "check mark button", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji CHECK_BOX_WITH_CHECK = new Emoji("\u2611\ufe0f", "\\u2611\\uFE0F", Collections.singletonList(":ballot_box_with_check:"), Collections.singletonList(":ballot_box_with_check:"), Collections.singletonList(":ballot_box_with_check:"), Collections.unmodifiableList(Arrays.asList("\u2713", "ballot", "box", "check", "checked", "done", "off", "tick")), false, false, 0.6, Qualification.fromString("fully-qualified"), "check box with check", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji CHECK_BOX_WITH_CHECK_UNQUALIFIED = new Emoji("\u2611", "\\u2611", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("\u2713", "ballot", "box", "check", "checked", "done", "off", "tick")), false, false, 0.6, Qualification.fromString("unqualified"), "check box with check", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji CHECK_MARK = new Emoji("\u2714\ufe0f", "\\u2714\\uFE0F", Collections.unmodifiableList(Arrays.asList(":heavy_check_mark:", ":check_mark:")), Collections.singletonList(":heavy_check_mark:"), Collections.singletonList(":heavy_check_mark:"), Collections.unmodifiableList(Arrays.asList("\u2713", "check", "checked", "checkmark", "done", "heavy", "mark", "tick")), false, false, 0.6, Qualification.fromString("fully-qualified"), "check mark", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji CHECK_MARK_UNQUALIFIED = new Emoji("\u2714", "\\u2714", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("\u2713", "check", "checked", "checkmark", "done", "heavy", "mark", "tick")), false, false, 0.6, Qualification.fromString("unqualified"), "check mark", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji CROSS_MARK = new Emoji("\u274c", "\\u274C", Collections.unmodifiableList(Arrays.asList(":x:", ":cross_mark:")), Collections.singletonList(":x:"), Collections.singletonList(":x:"), Collections.unmodifiableList(Arrays.asList("\u00d7", "cancel", "cross", "mark", "multiplication", "multiply", "x")), false, false, 0.6, Qualification.fromString("fully-qualified"), "cross mark", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji CROSS_MARK_BUTTON = new Emoji("\u274e", "\\u274E", Collections.singletonList(":negative_squared_cross_mark:"), Collections.singletonList(":negative_squared_cross_mark:"), Collections.singletonList(":negative_squared_cross_mark:"), Collections.unmodifiableList(Arrays.asList("\u00d7", "button", "cross", "mark", "multiplication", "multiply", "square", "x")), false, false, 0.6, Qualification.fromString("fully-qualified"), "cross mark button", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji CURLY_LOOP = new Emoji("\u27b0", "\\u27B0", Collections.singletonList(":curly_loop:"), Collections.singletonList(":curly_loop:"), Collections.singletonList(":curly_loop:"), Collections.unmodifiableList(Arrays.asList("curl", "curly", "loop")), false, false, 0.6, Qualification.fromString("fully-qualified"), "curly loop", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji DOUBLE_CURLY_LOOP = new Emoji("\u27bf", "\\u27BF", Collections.singletonList(":loop:"), Collections.singletonList(":loop:"), Collections.singletonList(":loop:"), Collections.unmodifiableList(Arrays.asList("curl", "curly", "double", "loop")), false, false, 1.0, Qualification.fromString("fully-qualified"), "double curly loop", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji PART_ALTERNATION_MARK = new Emoji("\u303d\ufe0f", "\\u303D\\uFE0F", Collections.singletonList(":part_alternation_mark:"), Collections.singletonList(":part_alternation_mark:"), Collections.singletonList(":part_alternation_mark:"), Collections.unmodifiableList(Arrays.asList("alternation", "mark", "part")), false, false, 0.6, Qualification.fromString("fully-qualified"), "part alternation mark", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji PART_ALTERNATION_MARK_UNQUALIFIED = new Emoji("\u303d", "\\u303D", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("alternation", "mark", "part")), false, false, 0.6, Qualification.fromString("unqualified"), "part alternation mark", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji EIGHT_SPOKED_ASTERISK = new Emoji("\u2733\ufe0f", "\\u2733\\uFE0F", Collections.singletonList(":eight_spoked_asterisk:"), Collections.singletonList(":eight_spoked_asterisk:"), Collections.singletonList(":eight_spoked_asterisk:"), Collections.unmodifiableList(Arrays.asList("*", "asterisk", "eight-spoked")), false, false, 0.6, Qualification.fromString("fully-qualified"), "eight-spoked asterisk", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji EIGHT_SPOKED_ASTERISK_UNQUALIFIED = new Emoji("\u2733", "\\u2733", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("*", "asterisk", "eight-spoked")), false, false, 0.6, Qualification.fromString("unqualified"), "eight-spoked asterisk", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji EIGHT_POINTED_STAR = new Emoji("\u2734\ufe0f", "\\u2734\\uFE0F", Collections.singletonList(":eight_pointed_black_star:"), Collections.singletonList(":eight_pointed_black_star:"), Collections.singletonList(":eight_pointed_black_star:"), Collections.unmodifiableList(Arrays.asList("*", "eight-pointed", "star")), false, false, 0.6, Qualification.fromString("fully-qualified"), "eight-pointed star", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji EIGHT_POINTED_STAR_UNQUALIFIED = new Emoji("\u2734", "\\u2734", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("*", "eight-pointed", "star")), false, false, 0.6, Qualification.fromString("unqualified"), "eight-pointed star", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji SPARKLE = new Emoji("\u2747\ufe0f", "\\u2747\\uFE0F", Collections.singletonList(":sparkle:"), Collections.singletonList(":sparkle:"), Collections.singletonList(":sparkle:"), Collections.unmodifiableList(Arrays.asList("*", "sparkle")), false, false, 0.6, Qualification.fromString("fully-qualified"), "sparkle", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji SPARKLE_UNQUALIFIED = new Emoji("\u2747", "\\u2747", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("*", "sparkle")), false, false, 0.6, Qualification.fromString("unqualified"), "sparkle", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji COPYRIGHT = new Emoji("\u00a9\ufe0f", "\\u00A9\\uFE0F", Collections.singletonList(":copyright:"), Collections.singletonList(":copyright:"), Collections.singletonList(":copyright:"), Collections.unmodifiableList(Arrays.asList("C", "copyright")), false, false, 0.6, Qualification.fromString("fully-qualified"), "copyright", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji COPYRIGHT_UNQUALIFIED = new Emoji("\u00a9", "\\u00A9", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("C", "copyright")), false, false, 0.6, Qualification.fromString("unqualified"), "copyright", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji REGISTERED = new Emoji("\u00ae\ufe0f", "\\u00AE\\uFE0F", Collections.singletonList(":registered:"), Collections.singletonList(":registered:"), Collections.singletonList(":registered:"), Collections.unmodifiableList(Arrays.asList("R", "registered")), false, false, 0.6, Qualification.fromString("fully-qualified"), "registered", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji REGISTERED_UNQUALIFIED = new Emoji("\u00ae", "\\u00AE", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("R", "registered")), false, false, 0.6, Qualification.fromString("unqualified"), "registered", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji TRADE_MARK = new Emoji("\u2122\ufe0f", "\\u2122\\uFE0F", Collections.unmodifiableList(Arrays.asList(":tm:", ":trade_mark:")), Collections.singletonList(":tm:"), Collections.singletonList(":tm:"), Collections.unmodifiableList(Arrays.asList("mark", "TM", "trade", "trademark")), false, false, 0.6, Qualification.fromString("fully-qualified"), "trade mark", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
    public static final Emoji TRADE_MARK_UNQUALIFIED = new Emoji("\u2122", "\\u2122", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("mark", "TM", "trade", "trademark")), false, false, 0.6, Qualification.fromString("unqualified"), "trade mark", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, true);
    public static final Emoji SPLATTER = new Emoji("\ud83e\udedf", "\\uD83E\\uDEDF", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("drip", "holi", "ink", "liquid", "mess", "paint", "spill", "splatter", "stain")), false, false, 16.0, Qualification.fromString("fully-qualified"), "splatter", EmojiGroup.SYMBOLS, EmojiSubGroup.OTHER_SYMBOL, false);
}

