/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiMusicalInstrument {
    public static final Emoji SAXOPHONE = new Emoji("\ud83c\udfb7", "\\uD83C\\uDFB7", Collections.singletonList(":saxophone:"), Collections.singletonList(":saxophone:"), Collections.singletonList(":saxophone:"), Collections.unmodifiableList(Arrays.asList("instrument", "music", "sax", "saxophone")), false, false, 0.6, Qualification.fromString("fully-qualified"), "saxophone", EmojiGroup.OBJECTS, EmojiSubGroup.MUSICAL_INSTRUMENT, false);
    public static final Emoji ACCORDION = new Emoji("\ud83e\ude97", "\\uD83E\\uDE97", Collections.singletonList(":accordion:"), Collections.singletonList(":accordion:"), Collections.singletonList(":accordion:"), Collections.unmodifiableList(Arrays.asList("accordion", "box", "concertina", "instrument", "music", "squeeze", "squeezebox")), false, false, 13.0, Qualification.fromString("fully-qualified"), "accordion", EmojiGroup.OBJECTS, EmojiSubGroup.MUSICAL_INSTRUMENT, false);
    public static final Emoji GUITAR = new Emoji("\ud83c\udfb8", "\\uD83C\\uDFB8", Collections.singletonList(":guitar:"), Collections.singletonList(":guitar:"), Collections.singletonList(":guitar:"), Collections.unmodifiableList(Arrays.asList("guitar", "instrument", "music", "strat")), false, false, 0.6, Qualification.fromString("fully-qualified"), "guitar", EmojiGroup.OBJECTS, EmojiSubGroup.MUSICAL_INSTRUMENT, false);
    public static final Emoji MUSICAL_KEYBOARD = new Emoji("\ud83c\udfb9", "\\uD83C\\uDFB9", Collections.singletonList(":musical_keyboard:"), Collections.singletonList(":musical_keyboard:"), Collections.singletonList(":musical_keyboard:"), Collections.unmodifiableList(Arrays.asList("instrument", "keyboard", "music", "musical", "piano")), false, false, 0.6, Qualification.fromString("fully-qualified"), "musical keyboard", EmojiGroup.OBJECTS, EmojiSubGroup.MUSICAL_INSTRUMENT, false);
    public static final Emoji TRUMPET = new Emoji("\ud83c\udfba", "\\uD83C\\uDFBA", Collections.singletonList(":trumpet:"), Collections.singletonList(":trumpet:"), Collections.singletonList(":trumpet:"), Collections.unmodifiableList(Arrays.asList("instrument", "music", "trumpet")), false, false, 0.6, Qualification.fromString("fully-qualified"), "trumpet", EmojiGroup.OBJECTS, EmojiSubGroup.MUSICAL_INSTRUMENT, false);
    public static final Emoji VIOLIN = new Emoji("\ud83c\udfbb", "\\uD83C\\uDFBB", Collections.singletonList(":violin:"), Collections.singletonList(":violin:"), Collections.singletonList(":violin:"), Collections.unmodifiableList(Arrays.asList("instrument", "music", "violin")), false, false, 0.6, Qualification.fromString("fully-qualified"), "violin", EmojiGroup.OBJECTS, EmojiSubGroup.MUSICAL_INSTRUMENT, false);
    public static final Emoji BANJO = new Emoji("\ud83e\ude95", "\\uD83E\\uDE95", Collections.singletonList(":banjo:"), Collections.singletonList(":banjo:"), Collections.singletonList(":banjo:"), Collections.unmodifiableList(Arrays.asList("banjo", "music", "stringed")), false, false, 12.0, Qualification.fromString("fully-qualified"), "banjo", EmojiGroup.OBJECTS, EmojiSubGroup.MUSICAL_INSTRUMENT, false);
    public static final Emoji DRUM = new Emoji("\ud83e\udd41", "\\uD83E\\uDD41", Collections.unmodifiableList(Arrays.asList(":drum:", ":drum_with_drumsticks:")), Collections.singletonList(":drum_with_drumsticks:"), Collections.singletonList(":drum:"), Collections.unmodifiableList(Arrays.asList("drum", "drumsticks", "music")), false, false, 3.0, Qualification.fromString("fully-qualified"), "drum", EmojiGroup.OBJECTS, EmojiSubGroup.MUSICAL_INSTRUMENT, false);
    public static final Emoji LONG_DRUM = new Emoji("\ud83e\ude98", "\\uD83E\\uDE98", Collections.singletonList(":long_drum:"), Collections.singletonList(":long_drum:"), Collections.singletonList(":long_drum:"), Collections.unmodifiableList(Arrays.asList("beat", "conga", "drum", "instrument", "long", "rhythm")), false, false, 13.0, Qualification.fromString("fully-qualified"), "long drum", EmojiGroup.OBJECTS, EmojiSubGroup.MUSICAL_INSTRUMENT, false);
    public static final Emoji MARACAS = new Emoji("\ud83e\ude87", "\\uD83E\\uDE87", Collections.singletonList(":maracas:"), Collections.emptyList(), Collections.singletonList(":maracas:"), Collections.unmodifiableList(Arrays.asList("cha", "dance", "instrument", "maracas", "music", "party", "percussion", "rattle", "shake", "shaker")), false, false, 15.0, Qualification.fromString("fully-qualified"), "maracas", EmojiGroup.OBJECTS, EmojiSubGroup.MUSICAL_INSTRUMENT, false);
    public static final Emoji FLUTE = new Emoji("\ud83e\ude88", "\\uD83E\\uDE88", Collections.singletonList(":flute:"), Collections.emptyList(), Collections.singletonList(":flute:"), Collections.unmodifiableList(Arrays.asList("band", "fife", "flautist", "flute", "instrument", "marching", "music", "orchestra", "piccolo", "pipe", "recorder", "woodwind")), false, false, 15.0, Qualification.fromString("fully-qualified"), "flute", EmojiGroup.OBJECTS, EmojiSubGroup.MUSICAL_INSTRUMENT, false);
    public static final Emoji HARP = new Emoji("\ud83e\ude89", "\\uD83E\\uDE89", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cupid", "harp", "instrument", "love", "music", "orchestra")), false, false, 16.0, Qualification.fromString("fully-qualified"), "harp", EmojiGroup.OBJECTS, EmojiSubGroup.MUSICAL_INSTRUMENT, false);
}

