/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiAvSymbol {
    public static final Emoji SHUFFLE_TRACKS_BUTTON = new Emoji("\ud83d\udd00", "\\uD83D\\uDD00", Collections.singletonList(":twisted_rightwards_arrows:"), Collections.singletonList(":twisted_rightwards_arrows:"), Collections.singletonList(":twisted_rightwards_arrows:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "crossed", "shuffle", "tracks")), false, false, 1.0, Qualification.fromString("fully-qualified"), "shuffle tracks button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji REPEAT_BUTTON = new Emoji("\ud83d\udd01", "\\uD83D\\uDD01", Collections.singletonList(":repeat:"), Collections.singletonList(":repeat:"), Collections.singletonList(":repeat:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "clockwise", "repeat")), false, false, 1.0, Qualification.fromString("fully-qualified"), "repeat button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji REPEAT_SINGLE_BUTTON = new Emoji("\ud83d\udd02", "\\uD83D\\uDD02", Collections.singletonList(":repeat_one:"), Collections.singletonList(":repeat_one:"), Collections.singletonList(":repeat_one:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "clockwise", "once", "repeat", "single")), false, false, 1.0, Qualification.fromString("fully-qualified"), "repeat single button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji PLAY_BUTTON = new Emoji("\u25b6\ufe0f", "\\u25B6\\uFE0F", Collections.singletonList(":arrow_forward:"), Collections.singletonList(":arrow_forward:"), Collections.singletonList(":arrow_forward:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "play", "right", "triangle")), false, false, 0.6, Qualification.fromString("fully-qualified"), "play button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji PLAY_BUTTON_UNQUALIFIED = new Emoji("\u25b6", "\\u25B6", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "button", "play", "right", "triangle")), false, false, 0.6, Qualification.fromString("unqualified"), "play button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, true);
    public static final Emoji FAST_FORWARD_BUTTON = new Emoji("\u23e9", "\\u23E9", Collections.singletonList(":fast_forward:"), Collections.singletonList(":fast_forward:"), Collections.singletonList(":fast_forward:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "double", "fast", "fast-forward", "forward")), false, false, 0.6, Qualification.fromString("fully-qualified"), "fast-forward button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, true);
    public static final Emoji NEXT_TRACK_BUTTON = new Emoji("\u23ed\ufe0f", "\\u23ED\\uFE0F", Collections.unmodifiableList(Arrays.asList(":track_next:", ":next_track:")), Collections.singletonList(":black_right_pointing_double_triangle_with_vertical_bar:"), Collections.singletonList(":next_track_button:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "next", "scene", "track", "triangle")), false, false, 0.7, Qualification.fromString("fully-qualified"), "next track button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji NEXT_TRACK_BUTTON_UNQUALIFIED = new Emoji("\u23ed", "\\u23ED", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "button", "next", "scene", "track", "triangle")), false, false, 0.7, Qualification.fromString("unqualified"), "next track button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, true);
    public static final Emoji PLAY_OR_PAUSE_BUTTON = new Emoji("\u23ef\ufe0f", "\\u23EF\\uFE0F", Collections.singletonList(":play_pause:"), Collections.singletonList(":black_right_pointing_triangle_with_double_vertical_bar:"), Collections.singletonList(":play_or_pause_button:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "pause", "play", "right", "triangle")), false, false, 1.0, Qualification.fromString("fully-qualified"), "play or pause button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji PLAY_OR_PAUSE_BUTTON_UNQUALIFIED = new Emoji("\u23ef", "\\u23EF", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "button", "pause", "play", "right", "triangle")), false, false, 1.0, Qualification.fromString("unqualified"), "play or pause button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, true);
    public static final Emoji REVERSE_BUTTON = new Emoji("\u25c0\ufe0f", "\\u25C0\\uFE0F", Collections.singletonList(":arrow_backward:"), Collections.singletonList(":arrow_backward:"), Collections.singletonList(":arrow_backward:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "left", "reverse", "triangle")), false, false, 0.6, Qualification.fromString("fully-qualified"), "reverse button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji REVERSE_BUTTON_UNQUALIFIED = new Emoji("\u25c0", "\\u25C0", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "button", "left", "reverse", "triangle")), false, false, 0.6, Qualification.fromString("unqualified"), "reverse button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, true);
    public static final Emoji FAST_REVERSE_BUTTON = new Emoji("\u23ea", "\\u23EA", Collections.singletonList(":rewind:"), Collections.singletonList(":rewind:"), Collections.singletonList(":rewind:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "double", "fast", "reverse", "rewind")), false, false, 0.6, Qualification.fromString("fully-qualified"), "fast reverse button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, true);
    public static final Emoji LAST_TRACK_BUTTON = new Emoji("\u23ee\ufe0f", "\\u23EE\\uFE0F", Collections.unmodifiableList(Arrays.asList(":track_previous:", ":previous_track:")), Collections.singletonList(":black_left_pointing_double_triangle_with_vertical_bar:"), Collections.singletonList(":previous_track_button:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "last", "previous", "scene", "track", "triangle")), false, false, 0.7, Qualification.fromString("fully-qualified"), "last track button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji LAST_TRACK_BUTTON_UNQUALIFIED = new Emoji("\u23ee", "\\u23EE", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arrow", "button", "last", "previous", "scene", "track", "triangle")), false, false, 0.7, Qualification.fromString("unqualified"), "last track button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, true);
    public static final Emoji UPWARDS_BUTTON = new Emoji("\ud83d\udd3c", "\\uD83D\\uDD3C", Collections.singletonList(":arrow_up_small:"), Collections.singletonList(":arrow_up_small:"), Collections.singletonList(":arrow_up_small:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "red", "up", "upwards")), false, false, 0.6, Qualification.fromString("fully-qualified"), "upwards button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji FAST_UP_BUTTON = new Emoji("\u23eb", "\\u23EB", Collections.singletonList(":arrow_double_up:"), Collections.singletonList(":arrow_double_up:"), Collections.singletonList(":arrow_double_up:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "double", "fast", "up")), false, false, 0.6, Qualification.fromString("fully-qualified"), "fast up button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, true);
    public static final Emoji DOWNWARDS_BUTTON = new Emoji("\ud83d\udd3d", "\\uD83D\\uDD3D", Collections.singletonList(":arrow_down_small:"), Collections.singletonList(":arrow_down_small:"), Collections.singletonList(":arrow_down_small:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "down", "downwards", "red")), false, false, 0.6, Qualification.fromString("fully-qualified"), "downwards button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji FAST_DOWN_BUTTON = new Emoji("\u23ec", "\\u23EC", Collections.singletonList(":arrow_double_down:"), Collections.singletonList(":arrow_double_down:"), Collections.singletonList(":arrow_double_down:"), Collections.unmodifiableList(Arrays.asList("arrow", "button", "double", "down", "fast")), false, false, 0.6, Qualification.fromString("fully-qualified"), "fast down button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, true);
    public static final Emoji PAUSE_BUTTON = new Emoji("\u23f8\ufe0f", "\\u23F8\\uFE0F", Collections.unmodifiableList(Arrays.asList(":pause_button:", ":double_vertical_bar:")), Collections.singletonList(":double_vertical_bar:"), Collections.singletonList(":pause_button:"), Collections.unmodifiableList(Arrays.asList("bar", "button", "double", "pause", "vertical")), false, false, 0.7, Qualification.fromString("fully-qualified"), "pause button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji PAUSE_BUTTON_UNQUALIFIED = new Emoji("\u23f8", "\\u23F8", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bar", "button", "double", "pause", "vertical")), false, false, 0.7, Qualification.fromString("unqualified"), "pause button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, true);
    public static final Emoji STOP_BUTTON = new Emoji("\u23f9\ufe0f", "\\u23F9\\uFE0F", Collections.singletonList(":stop_button:"), Collections.singletonList(":black_square_for_stop:"), Collections.singletonList(":stop_button:"), Collections.unmodifiableList(Arrays.asList("button", "square", "stop")), false, false, 0.7, Qualification.fromString("fully-qualified"), "stop button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji STOP_BUTTON_UNQUALIFIED = new Emoji("\u23f9", "\\u23F9", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("button", "square", "stop")), false, false, 0.7, Qualification.fromString("unqualified"), "stop button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, true);
    public static final Emoji RECORD_BUTTON = new Emoji("\u23fa\ufe0f", "\\u23FA\\uFE0F", Collections.singletonList(":record_button:"), Collections.singletonList(":black_circle_for_record:"), Collections.singletonList(":record_button:"), Collections.unmodifiableList(Arrays.asList("button", "circle", "record")), false, false, 0.7, Qualification.fromString("fully-qualified"), "record button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji RECORD_BUTTON_UNQUALIFIED = new Emoji("\u23fa", "\\u23FA", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("button", "circle", "record")), false, false, 0.7, Qualification.fromString("unqualified"), "record button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, true);
    public static final Emoji EJECT_BUTTON = new Emoji("\u23cf\ufe0f", "\\u23CF\\uFE0F", Collections.unmodifiableList(Arrays.asList(":eject:", ":eject_symbol:")), Collections.singletonList(":eject:"), Collections.singletonList(":eject_button:"), Collections.unmodifiableList(Arrays.asList("button", "eject")), false, false, 1.0, Qualification.fromString("fully-qualified"), "eject button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji EJECT_BUTTON_UNQUALIFIED = new Emoji("\u23cf", "\\u23CF", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("button", "eject")), false, false, 1.0, Qualification.fromString("unqualified"), "eject button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, true);
    public static final Emoji CINEMA = new Emoji("\ud83c\udfa6", "\\uD83C\\uDFA6", Collections.singletonList(":cinema:"), Collections.singletonList(":cinema:"), Collections.singletonList(":cinema:"), Collections.unmodifiableList(Arrays.asList("camera", "cinema", "film", "movie")), false, false, 0.6, Qualification.fromString("fully-qualified"), "cinema", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji DIM_BUTTON = new Emoji("\ud83d\udd05", "\\uD83D\\uDD05", Collections.singletonList(":low_brightness:"), Collections.singletonList(":low_brightness:"), Collections.singletonList(":low_brightness:"), Collections.unmodifiableList(Arrays.asList("brightness", "button", "dim", "low")), false, false, 1.0, Qualification.fromString("fully-qualified"), "dim button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji BRIGHT_BUTTON = new Emoji("\ud83d\udd06", "\\uD83D\\uDD06", Collections.singletonList(":high_brightness:"), Collections.singletonList(":high_brightness:"), Collections.singletonList(":high_brightness:"), Collections.unmodifiableList(Arrays.asList("bright", "brightness", "button", "light")), false, false, 1.0, Qualification.fromString("fully-qualified"), "bright button", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji ANTENNA_BARS = new Emoji("\ud83d\udcf6", "\\uD83D\\uDCF6", Collections.unmodifiableList(Arrays.asList(":signal_strength:", ":antenna_bars:")), Collections.singletonList(":signal_strength:"), Collections.singletonList(":signal_strength:"), Collections.unmodifiableList(Arrays.asList("antenna", "bar", "bars", "cell", "communication", "mobile", "phone", "signal", "telephone")), false, false, 0.6, Qualification.fromString("fully-qualified"), "antenna bars", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji WIRELESS = new Emoji("\ud83d\udedc", "\\uD83D\\uDEDC", Collections.singletonList(":wireless:"), Collections.emptyList(), Collections.singletonList(":wireless:"), Collections.unmodifiableList(Arrays.asList("broadband", "computer", "connectivity", "hotspot", "internet", "network", "router", "smartphone", "wi-fi", "wifi", "wireless", "wlan")), false, false, 15.0, Qualification.fromString("fully-qualified"), "wireless", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji VIBRATION_MODE = new Emoji("\ud83d\udcf3", "\\uD83D\\uDCF3", Collections.singletonList(":vibration_mode:"), Collections.singletonList(":vibration_mode:"), Collections.singletonList(":vibration_mode:"), Collections.unmodifiableList(Arrays.asList("cell", "communication", "mobile", "mode", "phone", "telephone", "vibration")), false, false, 0.6, Qualification.fromString("fully-qualified"), "vibration mode", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
    public static final Emoji MOBILE_PHONE_OFF = new Emoji("\ud83d\udcf4", "\\uD83D\\uDCF4", Collections.singletonList(":mobile_phone_off:"), Collections.singletonList(":mobile_phone_off:"), Collections.singletonList(":mobile_phone_off:"), Collections.unmodifiableList(Arrays.asList("cell", "mobile", "off", "phone", "telephone")), false, false, 0.6, Qualification.fromString("fully-qualified"), "mobile phone off", EmojiGroup.SYMBOLS, EmojiSubGroup.AV_SYMBOL, false);
}

