/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiTransportAir {
    public static final Emoji AIRPLANE = new Emoji("\u2708\ufe0f", "\\u2708\\uFE0F", Collections.singletonList(":airplane:"), Collections.singletonList(":airplane:"), Collections.singletonList(":airplane:"), Collections.unmodifiableList(Arrays.asList("aeroplane", "airplane", "fly", "flying", "jet", "plane", "travel")), false, false, 0.6, Qualification.fromString("fully-qualified"), "airplane", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, false);
    public static final Emoji AIRPLANE_UNQUALIFIED = new Emoji("\u2708", "\\u2708", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("aeroplane", "airplane", "fly", "flying", "jet", "plane", "travel")), false, false, 0.6, Qualification.fromString("unqualified"), "airplane", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, true);
    public static final Emoji SMALL_AIRPLANE = new Emoji("\ud83d\udee9\ufe0f", "\\uD83D\\uDEE9\\uFE0F", Collections.unmodifiableList(Arrays.asList(":airplane_small:", ":small_airplane:")), Collections.singletonList(":small_airplane:"), Collections.singletonList(":small_airplane:"), Collections.unmodifiableList(Arrays.asList("aeroplane", "airplane", "plane", "small")), false, false, 0.7, Qualification.fromString("fully-qualified"), "small airplane", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, false);
    public static final Emoji SMALL_AIRPLANE_UNQUALIFIED = new Emoji("\ud83d\udee9", "\\uD83D\\uDEE9", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("aeroplane", "airplane", "plane", "small")), false, false, 0.7, Qualification.fromString("unqualified"), "small airplane", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, true);
    public static final Emoji AIRPLANE_DEPARTURE = new Emoji("\ud83d\udeeb", "\\uD83D\\uDEEB", Collections.singletonList(":airplane_departure:"), Collections.singletonList(":airplane_departure:"), Collections.singletonList(":flight_departure:"), Collections.unmodifiableList(Arrays.asList("aeroplane", "airplane", "check-in", "departure", "departures", "plane")), false, false, 1.0, Qualification.fromString("fully-qualified"), "airplane departure", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, false);
    public static final Emoji AIRPLANE_ARRIVAL = new Emoji("\ud83d\udeec", "\\uD83D\\uDEEC", Collections.singletonList(":airplane_arriving:"), Collections.singletonList(":airplane_arriving:"), Collections.singletonList(":flight_arrival:"), Collections.unmodifiableList(Arrays.asList("aeroplane", "airplane", "arrival", "arrivals", "arriving", "landing", "plane")), false, false, 1.0, Qualification.fromString("fully-qualified"), "airplane arrival", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, false);
    public static final Emoji PARACHUTE = new Emoji("\ud83e\ude82", "\\uD83E\\uDE82", Collections.singletonList(":parachute:"), Collections.singletonList(":parachute:"), Collections.singletonList(":parachute:"), Collections.unmodifiableList(Arrays.asList("hang-glide", "parachute", "parasail", "skydive")), false, false, 12.0, Qualification.fromString("fully-qualified"), "parachute", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, false);
    public static final Emoji SEAT = new Emoji("\ud83d\udcba", "\\uD83D\\uDCBA", Collections.singletonList(":seat:"), Collections.singletonList(":seat:"), Collections.singletonList(":seat:"), Collections.unmodifiableList(Arrays.asList("chair", "seat")), false, false, 0.6, Qualification.fromString("fully-qualified"), "seat", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, false);
    public static final Emoji HELICOPTER = new Emoji("\ud83d\ude81", "\\uD83D\\uDE81", Collections.singletonList(":helicopter:"), Collections.singletonList(":helicopter:"), Collections.singletonList(":helicopter:"), Collections.unmodifiableList(Arrays.asList("copter", "helicopter", "roflcopter", "travel", "vehicle")), false, false, 1.0, Qualification.fromString("fully-qualified"), "helicopter", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, false);
    public static final Emoji SUSPENSION_RAILWAY = new Emoji("\ud83d\ude9f", "\\uD83D\\uDE9F", Collections.singletonList(":suspension_railway:"), Collections.singletonList(":suspension_railway:"), Collections.singletonList(":suspension_railway:"), Collections.unmodifiableList(Arrays.asList("railway", "suspension")), false, false, 1.0, Qualification.fromString("fully-qualified"), "suspension railway", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, false);
    public static final Emoji MOUNTAIN_CABLEWAY = new Emoji("\ud83d\udea0", "\\uD83D\\uDEA0", Collections.singletonList(":mountain_cableway:"), Collections.singletonList(":mountain_cableway:"), Collections.singletonList(":mountain_cableway:"), Collections.unmodifiableList(Arrays.asList("cable", "cableway", "gondola", "lift", "mountain", "ski")), false, false, 1.0, Qualification.fromString("fully-qualified"), "mountain cableway", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, false);
    public static final Emoji AERIAL_TRAMWAY = new Emoji("\ud83d\udea1", "\\uD83D\\uDEA1", Collections.singletonList(":aerial_tramway:"), Collections.singletonList(":aerial_tramway:"), Collections.singletonList(":aerial_tramway:"), Collections.unmodifiableList(Arrays.asList("aerial", "cable", "car", "gondola", "ropeway", "tramway")), false, false, 1.0, Qualification.fromString("fully-qualified"), "aerial tramway", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, false);
    public static final Emoji SATELLITE = new Emoji("\ud83d\udef0\ufe0f", "\\uD83D\\uDEF0\\uFE0F", Collections.singletonList(":satellite_orbital:"), Collections.singletonList(":satellite:"), Collections.singletonList(":artificial_satellite:"), Collections.unmodifiableList(Arrays.asList("satellite", "space")), false, false, 0.7, Qualification.fromString("fully-qualified"), "satellite", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, false);
    public static final Emoji SATELLITE_UNQUALIFIED = new Emoji("\ud83d\udef0", "\\uD83D\\uDEF0", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("satellite", "space")), false, false, 0.7, Qualification.fromString("unqualified"), "satellite", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, true);
    public static final Emoji ROCKET = new Emoji("\ud83d\ude80", "\\uD83D\\uDE80", Collections.singletonList(":rocket:"), Collections.singletonList(":rocket:"), Collections.singletonList(":rocket:"), Collections.unmodifiableList(Arrays.asList("launch", "rocket", "rockets", "space", "travel")), false, false, 0.6, Qualification.fromString("fully-qualified"), "rocket", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, false);
    public static final Emoji FLYING_SAUCER = new Emoji("\ud83d\udef8", "\\uD83D\\uDEF8", Collections.singletonList(":flying_saucer:"), Collections.singletonList(":flying_saucer:"), Collections.singletonList(":flying_saucer:"), Collections.unmodifiableList(Arrays.asList("aliens", "extra", "flying", "saucer", "terrestrial", "UFO")), false, false, 5.0, Qualification.fromString("fully-qualified"), "flying saucer", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_AIR, false);
}

