/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiMusic {
    public static final Emoji MUSICAL_SCORE = new Emoji("\ud83c\udfbc", "\\uD83C\\uDFBC", Collections.singletonList(":musical_score:"), Collections.singletonList(":musical_score:"), Collections.singletonList(":musical_score:"), Collections.unmodifiableList(Arrays.asList("music", "musical", "note", "score")), false, false, 0.6, Qualification.fromString("fully-qualified"), "musical score", EmojiGroup.OBJECTS, EmojiSubGroup.MUSIC, false);
    public static final Emoji MUSICAL_NOTE = new Emoji("\ud83c\udfb5", "\\uD83C\\uDFB5", Collections.singletonList(":musical_note:"), Collections.singletonList(":musical_note:"), Collections.singletonList(":musical_note:"), Collections.unmodifiableList(Arrays.asList("music", "musical", "note", "sound")), false, false, 0.6, Qualification.fromString("fully-qualified"), "musical note", EmojiGroup.OBJECTS, EmojiSubGroup.MUSIC, false);
    public static final Emoji MUSICAL_NOTES = new Emoji("\ud83c\udfb6", "\\uD83C\\uDFB6", Collections.unmodifiableList(Arrays.asList(":notes:", ":musical_notes:")), Collections.singletonList(":notes:"), Collections.singletonList(":notes:"), Collections.unmodifiableList(Arrays.asList("music", "musical", "note", "notes", "sound")), false, false, 0.6, Qualification.fromString("fully-qualified"), "musical notes", EmojiGroup.OBJECTS, EmojiSubGroup.MUSIC, false);
    public static final Emoji STUDIO_MICROPHONE = new Emoji("\ud83c\udf99\ufe0f", "\\uD83C\\uDF99\\uFE0F", Collections.unmodifiableList(Arrays.asList(":microphone2:", ":studio_microphone:")), Collections.singletonList(":studio_microphone:"), Collections.singletonList(":studio_microphone:"), Collections.unmodifiableList(Arrays.asList("mic", "microphone", "music", "studio")), false, false, 0.7, Qualification.fromString("fully-qualified"), "studio microphone", EmojiGroup.OBJECTS, EmojiSubGroup.MUSIC, false);
    public static final Emoji STUDIO_MICROPHONE_UNQUALIFIED = new Emoji("\ud83c\udf99", "\\uD83C\\uDF99", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("mic", "microphone", "music", "studio")), false, false, 0.7, Qualification.fromString("unqualified"), "studio microphone", EmojiGroup.OBJECTS, EmojiSubGroup.MUSIC, true);
    public static final Emoji LEVEL_SLIDER = new Emoji("\ud83c\udf9a\ufe0f", "\\uD83C\\uDF9A\\uFE0F", Collections.singletonList(":level_slider:"), Collections.singletonList(":level_slider:"), Collections.singletonList(":level_slider:"), Collections.unmodifiableList(Arrays.asList("level", "music", "slider")), false, false, 0.7, Qualification.fromString("fully-qualified"), "level slider", EmojiGroup.OBJECTS, EmojiSubGroup.MUSIC, false);
    public static final Emoji LEVEL_SLIDER_UNQUALIFIED = new Emoji("\ud83c\udf9a", "\\uD83C\\uDF9A", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("level", "music", "slider")), false, false, 0.7, Qualification.fromString("unqualified"), "level slider", EmojiGroup.OBJECTS, EmojiSubGroup.MUSIC, true);
    public static final Emoji CONTROL_KNOBS = new Emoji("\ud83c\udf9b\ufe0f", "\\uD83C\\uDF9B\\uFE0F", Collections.singletonList(":control_knobs:"), Collections.singletonList(":control_knobs:"), Collections.singletonList(":control_knobs:"), Collections.unmodifiableList(Arrays.asList("control", "knobs", "music")), false, false, 0.7, Qualification.fromString("fully-qualified"), "control knobs", EmojiGroup.OBJECTS, EmojiSubGroup.MUSIC, false);
    public static final Emoji CONTROL_KNOBS_UNQUALIFIED = new Emoji("\ud83c\udf9b", "\\uD83C\\uDF9B", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("control", "knobs", "music")), false, false, 0.7, Qualification.fromString("unqualified"), "control knobs", EmojiGroup.OBJECTS, EmojiSubGroup.MUSIC, true);
    public static final Emoji MICROPHONE = new Emoji("\ud83c\udfa4", "\\uD83C\\uDFA4", Collections.singletonList(":microphone:"), Collections.singletonList(":microphone:"), Collections.singletonList(":microphone:"), Collections.unmodifiableList(Arrays.asList("karaoke", "mic", "microphone", "music", "sing", "sound")), false, false, 0.6, Qualification.fromString("fully-qualified"), "microphone", EmojiGroup.OBJECTS, EmojiSubGroup.MUSIC, false);
    public static final Emoji HEADPHONE = new Emoji("\ud83c\udfa7", "\\uD83C\\uDFA7", Collections.unmodifiableList(Arrays.asList(":headphones:", ":headphone:")), Collections.singletonList(":headphones:"), Collections.singletonList(":headphones:"), Collections.unmodifiableList(Arrays.asList("earbud", "headphone", "sound")), false, false, 0.6, Qualification.fromString("fully-qualified"), "headphone", EmojiGroup.OBJECTS, EmojiSubGroup.MUSIC, true);
    public static final Emoji RADIO = new Emoji("\ud83d\udcfb", "\\uD83D\\uDCFB", Collections.singletonList(":radio:"), Collections.singletonList(":radio:"), Collections.singletonList(":radio:"), Collections.unmodifiableList(Arrays.asList("entertainment", "radio", "tbt", "video")), false, false, 0.6, Qualification.fromString("fully-qualified"), "radio", EmojiGroup.OBJECTS, EmojiSubGroup.MUSIC, true);
}

