/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiOtherObject {
    public static final Emoji CIGARETTE = new Emoji("\ud83d\udeac", "\\uD83D\\uDEAC", Collections.unmodifiableList(Arrays.asList(":smoking:", ":cigarette:")), Collections.singletonList(":smoking:"), Collections.singletonList(":smoking:"), Collections.unmodifiableList(Arrays.asList("cigarette", "smoking")), false, false, 0.6, Qualification.fromString("fully-qualified"), "cigarette", EmojiGroup.OBJECTS, EmojiSubGroup.OTHER_OBJECT, false);
    public static final Emoji COFFIN = new Emoji("\u26b0\ufe0f", "\\u26B0\\uFE0F", Collections.singletonList(":coffin:"), Collections.singletonList(":coffin:"), Collections.singletonList(":coffin:"), Collections.unmodifiableList(Arrays.asList("coffin", "dead", "death", "vampire")), false, false, 1.0, Qualification.fromString("fully-qualified"), "coffin", EmojiGroup.OBJECTS, EmojiSubGroup.OTHER_OBJECT, false);
    public static final Emoji COFFIN_UNQUALIFIED = new Emoji("\u26b0", "\\u26B0", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("coffin", "dead", "death", "vampire")), false, false, 1.0, Qualification.fromString("unqualified"), "coffin", EmojiGroup.OBJECTS, EmojiSubGroup.OTHER_OBJECT, true);
    public static final Emoji HEADSTONE = new Emoji("\ud83e\udea6", "\\uD83E\\uDEA6", Collections.singletonList(":headstone:"), Collections.singletonList(":headstone:"), Collections.singletonList(":headstone:"), Collections.unmodifiableList(Arrays.asList("cemetery", "dead", "grave", "graveyard", "headstone", "memorial", "rip", "tomb", "tombstone")), false, false, 13.0, Qualification.fromString("fully-qualified"), "headstone", EmojiGroup.OBJECTS, EmojiSubGroup.OTHER_OBJECT, false);
    public static final Emoji FUNERAL_URN = new Emoji("\u26b1\ufe0f", "\\u26B1\\uFE0F", Collections.unmodifiableList(Arrays.asList(":urn:", ":funeral_urn:")), Collections.singletonList(":funeral_urn:"), Collections.singletonList(":funeral_urn:"), Collections.unmodifiableList(Arrays.asList("ashes", "death", "funeral", "urn")), false, false, 1.0, Qualification.fromString("fully-qualified"), "funeral urn", EmojiGroup.OBJECTS, EmojiSubGroup.OTHER_OBJECT, false);
    public static final Emoji FUNERAL_URN_UNQUALIFIED = new Emoji("\u26b1", "\\u26B1", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("ashes", "death", "funeral", "urn")), false, false, 1.0, Qualification.fromString("unqualified"), "funeral urn", EmojiGroup.OBJECTS, EmojiSubGroup.OTHER_OBJECT, true);
    public static final Emoji NAZAR_AMULET = new Emoji("\ud83e\uddff", "\\uD83E\\uDDFF", Collections.singletonList(":nazar_amulet:"), Collections.singletonList(":nazar_amulet:"), Collections.singletonList(":nazar_amulet:"), Collections.unmodifiableList(Arrays.asList("amulet", "bead", "blue", "charm", "evil-eye", "nazar", "talisman")), false, false, 11.0, Qualification.fromString("fully-qualified"), "nazar amulet", EmojiGroup.OBJECTS, EmojiSubGroup.OTHER_OBJECT, false);
    public static final Emoji HAMSA = new Emoji("\ud83e\udeac", "\\uD83E\\uDEAC", Collections.singletonList(":hamsa:"), Collections.singletonList(":hamsa:"), Collections.singletonList(":hamsa:"), Collections.unmodifiableList(Arrays.asList("amulet", "Fatima", "fortune", "guide", "hamsa", "hand", "Mary", "Miriam", "palm", "protect", "protection")), false, false, 14.0, Qualification.fromString("fully-qualified"), "hamsa", EmojiGroup.OBJECTS, EmojiSubGroup.OTHER_OBJECT, false);
    public static final Emoji MOAI = new Emoji("\ud83d\uddff", "\\uD83D\\uDDFF", Collections.unmodifiableList(Arrays.asList(":moyai:", ":moai:")), Collections.singletonList(":moyai:"), Collections.singletonList(":moyai:"), Collections.unmodifiableList(Arrays.asList("face", "moai", "moyai", "statue", "stoneface", "travel")), false, false, 0.6, Qualification.fromString("fully-qualified"), "moai", EmojiGroup.OBJECTS, EmojiSubGroup.OTHER_OBJECT, false);
    public static final Emoji PLACARD = new Emoji("\ud83e\udea7", "\\uD83E\\uDEA7", Collections.singletonList(":placard:"), Collections.singletonList(":placard:"), Collections.singletonList(":placard:"), Collections.unmodifiableList(Arrays.asList("card", "demonstration", "notice", "picket", "placard", "plaque", "protest", "sign")), false, false, 13.0, Qualification.fromString("fully-qualified"), "placard", EmojiGroup.OBJECTS, EmojiSubGroup.OTHER_OBJECT, false);
    public static final Emoji IDENTIFICATION_CARD = new Emoji("\ud83e\udeaa", "\\uD83E\\uDEAA", Collections.singletonList(":identification_card:"), Collections.singletonList(":identification_card:"), Collections.singletonList(":identification_card:"), Collections.unmodifiableList(Arrays.asList("card", "credentials", "document", "ID", "identification", "license", "security")), false, false, 14.0, Qualification.fromString("fully-qualified"), "identification card", EmojiGroup.OBJECTS, EmojiSubGroup.OTHER_OBJECT, false);
}

