/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiTool {
    public static final Emoji HAMMER = new Emoji("\ud83d\udd28", "\\uD83D\\uDD28", Collections.singletonList(":hammer:"), Collections.singletonList(":hammer:"), Collections.singletonList(":hammer:"), Collections.unmodifiableList(Arrays.asList("hammer", "home", "improvement", "repairs", "tool")), false, false, 0.6, Qualification.fromString("fully-qualified"), "hammer", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji AXE = new Emoji("\ud83e\ude93", "\\uD83E\\uDE93", Collections.singletonList(":axe:"), Collections.singletonList(":axe:"), Collections.singletonList(":axe:"), Collections.unmodifiableList(Arrays.asList("ax", "axe", "chop", "hatchet", "split", "wood")), false, false, 12.0, Qualification.fromString("fully-qualified"), "axe", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji PICK = new Emoji("\u26cf\ufe0f", "\\u26CF\\uFE0F", Collections.singletonList(":pick:"), Collections.singletonList(":pick:"), Collections.singletonList(":pick:"), Collections.unmodifiableList(Arrays.asList("hammer", "mining", "pick", "tool")), false, false, 0.7, Qualification.fromString("fully-qualified"), "pick", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji PICK_UNQUALIFIED = new Emoji("\u26cf", "\\u26CF", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("hammer", "mining", "pick", "tool")), false, false, 0.7, Qualification.fromString("unqualified"), "pick", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, true);
    public static final Emoji HAMMER_AND_PICK = new Emoji("\u2692\ufe0f", "\\u2692\\uFE0F", Collections.unmodifiableList(Arrays.asList(":hammer_pick:", ":hammer_and_pick:")), Collections.singletonList(":hammer_and_pick:"), Collections.singletonList(":hammer_and_pick:"), Collections.unmodifiableList(Arrays.asList("hammer", "pick", "tool")), false, false, 1.0, Qualification.fromString("fully-qualified"), "hammer and pick", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji HAMMER_AND_PICK_UNQUALIFIED = new Emoji("\u2692", "\\u2692", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("hammer", "pick", "tool")), false, false, 1.0, Qualification.fromString("unqualified"), "hammer and pick", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, true);
    public static final Emoji HAMMER_AND_WRENCH = new Emoji("\ud83d\udee0\ufe0f", "\\uD83D\\uDEE0\\uFE0F", Collections.unmodifiableList(Arrays.asList(":tools:", ":hammer_and_wrench:")), Collections.singletonList(":hammer_and_wrench:"), Collections.singletonList(":hammer_and_wrench:"), Collections.unmodifiableList(Arrays.asList("hammer", "spanner", "tool", "wrench")), false, false, 0.7, Qualification.fromString("fully-qualified"), "hammer and wrench", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji HAMMER_AND_WRENCH_UNQUALIFIED = new Emoji("\ud83d\udee0", "\\uD83D\\uDEE0", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("hammer", "spanner", "tool", "wrench")), false, false, 0.7, Qualification.fromString("unqualified"), "hammer and wrench", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, true);
    public static final Emoji DAGGER = new Emoji("\ud83d\udde1\ufe0f", "\\uD83D\\uDDE1\\uFE0F", Collections.unmodifiableList(Arrays.asList(":dagger:", ":dagger_knife:")), Collections.singletonList(":dagger_knife:"), Collections.singletonList(":dagger:"), Collections.unmodifiableList(Arrays.asList("dagger", "knife", "weapon")), false, false, 0.7, Qualification.fromString("fully-qualified"), "dagger", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji DAGGER_UNQUALIFIED = new Emoji("\ud83d\udde1", "\\uD83D\\uDDE1", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("dagger", "knife", "weapon")), false, false, 0.7, Qualification.fromString("unqualified"), "dagger", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, true);
    public static final Emoji CROSSED_SWORDS = new Emoji("\u2694\ufe0f", "\\u2694\\uFE0F", Collections.singletonList(":crossed_swords:"), Collections.singletonList(":crossed_swords:"), Collections.singletonList(":crossed_swords:"), Collections.unmodifiableList(Arrays.asList("crossed", "swords", "weapon")), false, false, 1.0, Qualification.fromString("fully-qualified"), "crossed swords", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji CROSSED_SWORDS_UNQUALIFIED = new Emoji("\u2694", "\\u2694", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("crossed", "swords", "weapon")), false, false, 1.0, Qualification.fromString("unqualified"), "crossed swords", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, true);
    public static final Emoji BOMB = new Emoji("\ud83d\udca3", "\\uD83D\\uDCA3", Collections.singletonList(":bomb:"), Collections.singletonList(":bomb:"), Collections.singletonList(":bomb:"), Collections.unmodifiableList(Arrays.asList("bomb", "boom", "comic", "dangerous", "explosion", "hot")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bomb", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, true);
    public static final Emoji BOOMERANG = new Emoji("\ud83e\ude83", "\\uD83E\\uDE83", Collections.singletonList(":boomerang:"), Collections.singletonList(":boomerang:"), Collections.singletonList(":boomerang:"), Collections.unmodifiableList(Arrays.asList("boomerang", "rebound", "repercussion", "weapon")), false, false, 13.0, Qualification.fromString("fully-qualified"), "boomerang", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji BOW_AND_ARROW = new Emoji("\ud83c\udff9", "\\uD83C\\uDFF9", Collections.unmodifiableList(Arrays.asList(":bow_and_arrow:", ":archery:")), Collections.singletonList(":bow_and_arrow:"), Collections.singletonList(":bow_and_arrow:"), Collections.unmodifiableList(Arrays.asList("archer", "archery", "arrow", "bow", "Sagittarius", "tool", "weapon", "zodiac")), false, false, 1.0, Qualification.fromString("fully-qualified"), "bow and arrow", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji SHIELD = new Emoji("\ud83d\udee1\ufe0f", "\\uD83D\\uDEE1\\uFE0F", Collections.singletonList(":shield:"), Collections.singletonList(":shield:"), Collections.singletonList(":shield:"), Collections.unmodifiableList(Arrays.asList("shield", "weapon")), false, false, 0.7, Qualification.fromString("fully-qualified"), "shield", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji SHIELD_UNQUALIFIED = new Emoji("\ud83d\udee1", "\\uD83D\\uDEE1", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("shield", "weapon")), false, false, 0.7, Qualification.fromString("unqualified"), "shield", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, true);
    public static final Emoji CARPENTRY_SAW = new Emoji("\ud83e\ude9a", "\\uD83E\\uDE9A", Collections.singletonList(":carpentry_saw:"), Collections.singletonList(":carpentry_saw:"), Collections.singletonList(":carpentry_saw:"), Collections.unmodifiableList(Arrays.asList("carpenter", "carpentry", "cut", "lumber", "saw", "tool", "trim")), false, false, 13.0, Qualification.fromString("fully-qualified"), "carpentry saw", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji WRENCH = new Emoji("\ud83d\udd27", "\\uD83D\\uDD27", Collections.singletonList(":wrench:"), Collections.singletonList(":wrench:"), Collections.singletonList(":wrench:"), Collections.unmodifiableList(Arrays.asList("home", "improvement", "spanner", "tool", "wrench")), false, false, 0.6, Qualification.fromString("fully-qualified"), "wrench", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji SCREWDRIVER = new Emoji("\ud83e\ude9b", "\\uD83E\\uDE9B", Collections.singletonList(":screwdriver:"), Collections.singletonList(":screwdriver:"), Collections.singletonList(":screwdriver:"), Collections.unmodifiableList(Arrays.asList("flathead", "handy", "screw", "screwdriver", "tool")), false, false, 13.0, Qualification.fromString("fully-qualified"), "screwdriver", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji NUT_AND_BOLT = new Emoji("\ud83d\udd29", "\\uD83D\\uDD29", Collections.singletonList(":nut_and_bolt:"), Collections.singletonList(":nut_and_bolt:"), Collections.singletonList(":nut_and_bolt:"), Collections.unmodifiableList(Arrays.asList("bolt", "home", "improvement", "nut", "tool")), false, false, 0.6, Qualification.fromString("fully-qualified"), "nut and bolt", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji GEAR = new Emoji("\u2699\ufe0f", "\\u2699\\uFE0F", Collections.singletonList(":gear:"), Collections.singletonList(":gear:"), Collections.singletonList(":gear:"), Collections.unmodifiableList(Arrays.asList("cog", "cogwheel", "gear", "tool")), false, false, 1.0, Qualification.fromString("fully-qualified"), "gear", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji GEAR_UNQUALIFIED = new Emoji("\u2699", "\\u2699", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cog", "cogwheel", "gear", "tool")), false, false, 1.0, Qualification.fromString("unqualified"), "gear", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, true);
    public static final Emoji CLAMP = new Emoji("\ud83d\udddc\ufe0f", "\\uD83D\\uDDDC\\uFE0F", Collections.unmodifiableList(Arrays.asList(":compression:", ":clamp:")), Collections.singletonList(":compression:"), Collections.singletonList(":clamp:"), Collections.unmodifiableList(Arrays.asList("clamp", "compress", "tool", "vice")), false, false, 0.7, Qualification.fromString("fully-qualified"), "clamp", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji CLAMP_UNQUALIFIED = new Emoji("\ud83d\udddc", "\\uD83D\\uDDDC", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("clamp", "compress", "tool", "vice")), false, false, 0.7, Qualification.fromString("unqualified"), "clamp", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, true);
    public static final Emoji BALANCE_SCALE = new Emoji("\u2696\ufe0f", "\\u2696\\uFE0F", Collections.unmodifiableList(Arrays.asList(":scales:", ":balance_scale:")), Collections.singletonList(":scales:"), Collections.singletonList(":balance_scale:"), Collections.unmodifiableList(Arrays.asList("balance", "justice", "Libra", "scale", "scales", "tool", "weight", "zodiac")), false, false, 1.0, Qualification.fromString("fully-qualified"), "balance scale", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji BALANCE_SCALE_UNQUALIFIED = new Emoji("\u2696", "\\u2696", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("balance", "justice", "Libra", "scale", "scales", "tool", "weight", "zodiac")), false, false, 1.0, Qualification.fromString("unqualified"), "balance scale", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, true);
    public static final Emoji WHITE_CANE = new Emoji("\ud83e\uddaf", "\\uD83E\\uDDAF", Collections.singletonList(":probing_cane:"), Collections.singletonList(":probing_cane:"), Collections.singletonList(":probing_cane:"), Collections.unmodifiableList(Arrays.asList("accessibility", "blind", "cane", "probing", "white")), false, false, 12.0, Qualification.fromString("fully-qualified"), "white cane", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji LINK = new Emoji("\ud83d\udd17", "\\uD83D\\uDD17", Collections.singletonList(":link:"), Collections.singletonList(":link:"), Collections.singletonList(":link:"), Collections.unmodifiableList(Arrays.asList("link", "links")), false, false, 0.6, Qualification.fromString("fully-qualified"), "link", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji BROKEN_CHAIN = new Emoji("\u26d3\ufe0f\u200d\ud83d\udca5", "\\u26D3\\uFE0F\\u200D\\uD83D\\uDCA5", Collections.singletonList(":broken_chain:"), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("break", "breaking", "broken", "chain", "cuffs", "freedom")), false, false, 15.1, Qualification.fromString("fully-qualified"), "broken chain", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji BROKEN_CHAIN_UNQUALIFIED = new Emoji("\u26d3\u200d\ud83d\udca5", "\\u26D3\\u200D\\uD83D\\uDCA5", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("break", "breaking", "broken", "chain", "cuffs", "freedom")), false, false, 15.1, Qualification.fromString("unqualified"), "broken chain", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji CHAINS = new Emoji("\u26d3\ufe0f", "\\u26D3\\uFE0F", Collections.singletonList(":chains:"), Collections.singletonList(":chains:"), Collections.singletonList(":chains:"), Collections.unmodifiableList(Arrays.asList("chain", "chains")), false, false, 0.7, Qualification.fromString("fully-qualified"), "chains", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji CHAINS_UNQUALIFIED = new Emoji("\u26d3", "\\u26D3", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("chain", "chains")), false, false, 0.7, Qualification.fromString("unqualified"), "chains", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, true);
    public static final Emoji HOOK = new Emoji("\ud83e\ude9d", "\\uD83E\\uDE9D", Collections.singletonList(":hook:"), Collections.singletonList(":hook:"), Collections.singletonList(":hook:"), Collections.unmodifiableList(Arrays.asList("catch", "crook", "curve", "ensnare", "hook", "point", "selling")), false, false, 13.0, Qualification.fromString("fully-qualified"), "hook", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji TOOLBOX = new Emoji("\ud83e\uddf0", "\\uD83E\\uDDF0", Collections.singletonList(":toolbox:"), Collections.singletonList(":toolbox:"), Collections.singletonList(":toolbox:"), Collections.unmodifiableList(Arrays.asList("box", "chest", "mechanic", "red", "tool", "toolbox")), false, false, 11.0, Qualification.fromString("fully-qualified"), "toolbox", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji MAGNET = new Emoji("\ud83e\uddf2", "\\uD83E\\uDDF2", Collections.singletonList(":magnet:"), Collections.singletonList(":magnet:"), Collections.singletonList(":magnet:"), Collections.unmodifiableList(Arrays.asList("attraction", "horseshoe", "magnet", "magnetic", "negative", "positive", "shape", "u")), false, false, 11.0, Qualification.fromString("fully-qualified"), "magnet", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji LADDER = new Emoji("\ud83e\ude9c", "\\uD83E\\uDE9C", Collections.singletonList(":ladder:"), Collections.singletonList(":ladder:"), Collections.singletonList(":ladder:"), Collections.unmodifiableList(Arrays.asList("climb", "ladder", "rung", "step")), false, false, 13.0, Qualification.fromString("fully-qualified"), "ladder", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
    public static final Emoji SHOVEL = new Emoji("\ud83e\ude8f", "\\uD83E\\uDE8F", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bury", "dig", "garden", "hole", "plant", "scoop", "shovel", "snow", "spade")), false, false, 16.0, Qualification.fromString("fully-qualified"), "shovel", EmojiGroup.OBJECTS, EmojiSubGroup.TOOL, false);
}

