/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiBodyParts {
    public static final Emoji FLEXED_BICEPS = new Emoji("\ud83d\udcaa", "\\uD83D\\uDCAA", Collections.unmodifiableList(Arrays.asList(":muscle:", ":flexed_biceps:")), Collections.singletonList(":muscle:"), Collections.singletonList(":muscle:"), Collections.unmodifiableList(Arrays.asList("arm", "beast", "bench", "biceps", "bodybuilder", "bro", "curls", "flex", "gains", "gym", "jacked", "muscle", "press", "ripped", "strong", "weightlift")), false, false, 0.6, Qualification.fromString("fully-qualified"), "flexed biceps", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji FLEXED_BICEPS_LIGHT_SKIN_TONE = new Emoji("\ud83d\udcaa\ud83c\udffb", "\\uD83D\\uDCAA\\uD83C\\uDFFB", Collections.unmodifiableList(Arrays.asList(":muscle_tone1:", ":muscle::skin-tone-1:", ":flexed_biceps::skin-tone-1:")), Collections.singletonList(":muscle::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arm", "beast", "bench", "biceps", "bodybuilder", "bro", "curls", "flex", "gains", "gym", "jacked", "light skin tone", "muscle", "press", "ripped", "strong", "weightlift")), true, false, 1.0, Qualification.fromString("fully-qualified"), "flexed biceps: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji FLEXED_BICEPS_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83d\udcaa\ud83c\udffc", "\\uD83D\\uDCAA\\uD83C\\uDFFC", Collections.unmodifiableList(Arrays.asList(":muscle_tone2:", ":muscle::skin-tone-2:", ":flexed_biceps::skin-tone-2:")), Collections.singletonList(":muscle::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arm", "beast", "bench", "biceps", "bodybuilder", "bro", "curls", "flex", "gains", "gym", "jacked", "medium-light skin tone", "muscle", "press", "ripped", "strong", "weightlift")), true, false, 1.0, Qualification.fromString("fully-qualified"), "flexed biceps: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji FLEXED_BICEPS_MEDIUM_SKIN_TONE = new Emoji("\ud83d\udcaa\ud83c\udffd", "\\uD83D\\uDCAA\\uD83C\\uDFFD", Collections.unmodifiableList(Arrays.asList(":muscle_tone3:", ":muscle::skin-tone-3:", ":flexed_biceps::skin-tone-3:")), Collections.singletonList(":muscle::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arm", "beast", "bench", "biceps", "bodybuilder", "bro", "curls", "flex", "gains", "gym", "jacked", "medium skin tone", "muscle", "press", "ripped", "strong", "weightlift")), true, false, 1.0, Qualification.fromString("fully-qualified"), "flexed biceps: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji FLEXED_BICEPS_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83d\udcaa\ud83c\udffe", "\\uD83D\\uDCAA\\uD83C\\uDFFE", Collections.unmodifiableList(Arrays.asList(":muscle_tone4:", ":muscle::skin-tone-4:", ":flexed_biceps::skin-tone-4:")), Collections.singletonList(":muscle::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arm", "beast", "bench", "biceps", "bodybuilder", "bro", "curls", "flex", "gains", "gym", "jacked", "medium-dark skin tone", "muscle", "press", "ripped", "strong", "weightlift")), true, false, 1.0, Qualification.fromString("fully-qualified"), "flexed biceps: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji FLEXED_BICEPS_DARK_SKIN_TONE = new Emoji("\ud83d\udcaa\ud83c\udfff", "\\uD83D\\uDCAA\\uD83C\\uDFFF", Collections.unmodifiableList(Arrays.asList(":muscle_tone5:", ":muscle::skin-tone-5:", ":flexed_biceps::skin-tone-5:")), Collections.singletonList(":muscle::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("arm", "beast", "bench", "biceps", "bodybuilder", "bro", "curls", "dark skin tone", "flex", "gains", "gym", "jacked", "muscle", "press", "ripped", "strong", "weightlift")), true, false, 1.0, Qualification.fromString("fully-qualified"), "flexed biceps: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji MECHANICAL_ARM = new Emoji("\ud83e\uddbe", "\\uD83E\\uDDBE", Collections.singletonList(":mechanical_arm:"), Collections.singletonList(":mechanical_arm:"), Collections.singletonList(":mechanical_arm:"), Collections.unmodifiableList(Arrays.asList("accessibility", "arm", "mechanical", "prosthetic")), false, false, 12.0, Qualification.fromString("fully-qualified"), "mechanical arm", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji MECHANICAL_LEG = new Emoji("\ud83e\uddbf", "\\uD83E\\uDDBF", Collections.singletonList(":mechanical_leg:"), Collections.singletonList(":mechanical_leg:"), Collections.singletonList(":mechanical_leg:"), Collections.unmodifiableList(Arrays.asList("accessibility", "leg", "mechanical", "prosthetic")), false, false, 12.0, Qualification.fromString("fully-qualified"), "mechanical leg", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji LEG = new Emoji("\ud83e\uddb5", "\\uD83E\\uDDB5", Collections.singletonList(":leg:"), Collections.singletonList(":leg:"), Collections.singletonList(":leg:"), Collections.unmodifiableList(Arrays.asList("bent", "foot", "kick", "knee", "leg", "limb")), false, false, 11.0, Qualification.fromString("fully-qualified"), "leg", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji LEG_LIGHT_SKIN_TONE = new Emoji("\ud83e\uddb5\ud83c\udffb", "\\uD83E\\uDDB5\\uD83C\\uDFFB", Collections.unmodifiableList(Arrays.asList(":leg_tone1:", ":leg_light_skin_tone:", ":leg::skin-tone-1:")), Collections.singletonList(":leg::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bent", "foot", "kick", "knee", "leg", "light skin tone", "limb")), true, false, 11.0, Qualification.fromString("fully-qualified"), "leg: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji LEG_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83e\uddb5\ud83c\udffc", "\\uD83E\\uDDB5\\uD83C\\uDFFC", Collections.unmodifiableList(Arrays.asList(":leg_tone2:", ":leg_medium_light_skin_tone:", ":leg::skin-tone-2:")), Collections.singletonList(":leg::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bent", "foot", "kick", "knee", "leg", "limb", "medium-light skin tone")), true, false, 11.0, Qualification.fromString("fully-qualified"), "leg: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji LEG_MEDIUM_SKIN_TONE = new Emoji("\ud83e\uddb5\ud83c\udffd", "\\uD83E\\uDDB5\\uD83C\\uDFFD", Collections.unmodifiableList(Arrays.asList(":leg_tone3:", ":leg_medium_skin_tone:", ":leg::skin-tone-3:")), Collections.singletonList(":leg::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bent", "foot", "kick", "knee", "leg", "limb", "medium skin tone")), true, false, 11.0, Qualification.fromString("fully-qualified"), "leg: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji LEG_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83e\uddb5\ud83c\udffe", "\\uD83E\\uDDB5\\uD83C\\uDFFE", Collections.unmodifiableList(Arrays.asList(":leg_tone4:", ":leg_medium_dark_skin_tone:", ":leg::skin-tone-4:")), Collections.singletonList(":leg::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bent", "foot", "kick", "knee", "leg", "limb", "medium-dark skin tone")), true, false, 11.0, Qualification.fromString("fully-qualified"), "leg: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji LEG_DARK_SKIN_TONE = new Emoji("\ud83e\uddb5\ud83c\udfff", "\\uD83E\\uDDB5\\uD83C\\uDFFF", Collections.unmodifiableList(Arrays.asList(":leg_tone5:", ":leg_dark_skin_tone:", ":leg::skin-tone-5:")), Collections.singletonList(":leg::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bent", "dark skin tone", "foot", "kick", "knee", "leg", "limb")), true, false, 11.0, Qualification.fromString("fully-qualified"), "leg: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji FOOT = new Emoji("\ud83e\uddb6", "\\uD83E\\uDDB6", Collections.singletonList(":foot:"), Collections.singletonList(":foot:"), Collections.singletonList(":foot:"), Collections.unmodifiableList(Arrays.asList("ankle", "feet", "foot", "kick", "stomp")), false, false, 11.0, Qualification.fromString("fully-qualified"), "foot", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji FOOT_LIGHT_SKIN_TONE = new Emoji("\ud83e\uddb6\ud83c\udffb", "\\uD83E\\uDDB6\\uD83C\\uDFFB", Collections.unmodifiableList(Arrays.asList(":foot_tone1:", ":foot_light_skin_tone:", ":foot::skin-tone-1:")), Collections.singletonList(":foot::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("ankle", "feet", "foot", "kick", "light skin tone", "stomp")), true, false, 11.0, Qualification.fromString("fully-qualified"), "foot: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji FOOT_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83e\uddb6\ud83c\udffc", "\\uD83E\\uDDB6\\uD83C\\uDFFC", Collections.unmodifiableList(Arrays.asList(":foot_tone2:", ":foot_medium_light_skin_tone:", ":foot::skin-tone-2:")), Collections.singletonList(":foot::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("ankle", "feet", "foot", "kick", "medium-light skin tone", "stomp")), true, false, 11.0, Qualification.fromString("fully-qualified"), "foot: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji FOOT_MEDIUM_SKIN_TONE = new Emoji("\ud83e\uddb6\ud83c\udffd", "\\uD83E\\uDDB6\\uD83C\\uDFFD", Collections.unmodifiableList(Arrays.asList(":foot_tone3:", ":foot_medium_skin_tone:", ":foot::skin-tone-3:")), Collections.singletonList(":foot::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("ankle", "feet", "foot", "kick", "medium skin tone", "stomp")), true, false, 11.0, Qualification.fromString("fully-qualified"), "foot: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji FOOT_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83e\uddb6\ud83c\udffe", "\\uD83E\\uDDB6\\uD83C\\uDFFE", Collections.unmodifiableList(Arrays.asList(":foot_tone4:", ":foot_medium_dark_skin_tone:", ":foot::skin-tone-4:")), Collections.singletonList(":foot::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("ankle", "feet", "foot", "kick", "medium-dark skin tone", "stomp")), true, false, 11.0, Qualification.fromString("fully-qualified"), "foot: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji FOOT_DARK_SKIN_TONE = new Emoji("\ud83e\uddb6\ud83c\udfff", "\\uD83E\\uDDB6\\uD83C\\uDFFF", Collections.unmodifiableList(Arrays.asList(":foot_tone5:", ":foot_dark_skin_tone:", ":foot::skin-tone-5:")), Collections.singletonList(":foot::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("ankle", "dark skin tone", "feet", "foot", "kick", "stomp")), true, false, 11.0, Qualification.fromString("fully-qualified"), "foot: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EAR = new Emoji("\ud83d\udc42", "\\uD83D\\uDC42", Collections.singletonList(":ear:"), Collections.singletonList(":ear:"), Collections.singletonList(":ear:"), Collections.unmodifiableList(Arrays.asList("body", "ear", "ears", "hear", "hearing", "listen", "listening", "sound")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ear", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, true);
    public static final Emoji EAR_LIGHT_SKIN_TONE = new Emoji("\ud83d\udc42\ud83c\udffb", "\\uD83D\\uDC42\\uD83C\\uDFFB", Collections.unmodifiableList(Arrays.asList(":ear_tone1:", ":ear::skin-tone-1:")), Collections.singletonList(":ear::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("body", "ear", "ears", "hear", "hearing", "light skin tone", "listen", "listening", "sound")), true, false, 1.0, Qualification.fromString("fully-qualified"), "ear: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EAR_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83d\udc42\ud83c\udffc", "\\uD83D\\uDC42\\uD83C\\uDFFC", Collections.unmodifiableList(Arrays.asList(":ear_tone2:", ":ear::skin-tone-2:")), Collections.singletonList(":ear::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("body", "ear", "ears", "hear", "hearing", "listen", "listening", "medium-light skin tone", "sound")), true, false, 1.0, Qualification.fromString("fully-qualified"), "ear: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EAR_MEDIUM_SKIN_TONE = new Emoji("\ud83d\udc42\ud83c\udffd", "\\uD83D\\uDC42\\uD83C\\uDFFD", Collections.unmodifiableList(Arrays.asList(":ear_tone3:", ":ear::skin-tone-3:")), Collections.singletonList(":ear::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("body", "ear", "ears", "hear", "hearing", "listen", "listening", "medium skin tone", "sound")), true, false, 1.0, Qualification.fromString("fully-qualified"), "ear: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EAR_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83d\udc42\ud83c\udffe", "\\uD83D\\uDC42\\uD83C\\uDFFE", Collections.unmodifiableList(Arrays.asList(":ear_tone4:", ":ear::skin-tone-4:")), Collections.singletonList(":ear::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("body", "ear", "ears", "hear", "hearing", "listen", "listening", "medium-dark skin tone", "sound")), true, false, 1.0, Qualification.fromString("fully-qualified"), "ear: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EAR_DARK_SKIN_TONE = new Emoji("\ud83d\udc42\ud83c\udfff", "\\uD83D\\uDC42\\uD83C\\uDFFF", Collections.unmodifiableList(Arrays.asList(":ear_tone5:", ":ear::skin-tone-5:")), Collections.singletonList(":ear::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("body", "dark skin tone", "ear", "ears", "hear", "hearing", "listen", "listening", "sound")), true, false, 1.0, Qualification.fromString("fully-qualified"), "ear: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EAR_WITH_HEARING_AID = new Emoji("\ud83e\uddbb", "\\uD83E\\uDDBB", Collections.singletonList(":ear_with_hearing_aid:"), Collections.singletonList(":ear_with_hearing_aid:"), Collections.singletonList(":ear_with_hearing_aid:"), Collections.unmodifiableList(Arrays.asList("accessibility", "aid", "ear", "hard", "hearing")), false, false, 12.0, Qualification.fromString("fully-qualified"), "ear with hearing aid", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EAR_WITH_HEARING_AID_LIGHT_SKIN_TONE = new Emoji("\ud83e\uddbb\ud83c\udffb", "\\uD83E\\uDDBB\\uD83C\\uDFFB", Collections.unmodifiableList(Arrays.asList(":ear_with_hearing_aid_tone1:", ":ear_with_hearing_aid_light_skin_tone:", ":ear_with_hearing_aid::skin-tone-1:")), Collections.singletonList(":ear_with_hearing_aid::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("accessibility", "aid", "ear", "hard", "hearing", "light skin tone")), true, false, 12.0, Qualification.fromString("fully-qualified"), "ear with hearing aid: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EAR_WITH_HEARING_AID_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83e\uddbb\ud83c\udffc", "\\uD83E\\uDDBB\\uD83C\\uDFFC", Collections.unmodifiableList(Arrays.asList(":ear_with_hearing_aid_tone2:", ":ear_with_hearing_aid_medium_light_skin_tone:", ":ear_with_hearing_aid::skin-tone-2:")), Collections.singletonList(":ear_with_hearing_aid::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("accessibility", "aid", "ear", "hard", "hearing", "medium-light skin tone")), true, false, 12.0, Qualification.fromString("fully-qualified"), "ear with hearing aid: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EAR_WITH_HEARING_AID_MEDIUM_SKIN_TONE = new Emoji("\ud83e\uddbb\ud83c\udffd", "\\uD83E\\uDDBB\\uD83C\\uDFFD", Collections.unmodifiableList(Arrays.asList(":ear_with_hearing_aid_tone3:", ":ear_with_hearing_aid_medium_skin_tone:", ":ear_with_hearing_aid::skin-tone-3:")), Collections.singletonList(":ear_with_hearing_aid::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("accessibility", "aid", "ear", "hard", "hearing", "medium skin tone")), true, false, 12.0, Qualification.fromString("fully-qualified"), "ear with hearing aid: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EAR_WITH_HEARING_AID_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83e\uddbb\ud83c\udffe", "\\uD83E\\uDDBB\\uD83C\\uDFFE", Collections.unmodifiableList(Arrays.asList(":ear_with_hearing_aid_tone4:", ":ear_with_hearing_aid_medium_dark_skin_tone:", ":ear_with_hearing_aid::skin-tone-4:")), Collections.singletonList(":ear_with_hearing_aid::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("accessibility", "aid", "ear", "hard", "hearing", "medium-dark skin tone")), true, false, 12.0, Qualification.fromString("fully-qualified"), "ear with hearing aid: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EAR_WITH_HEARING_AID_DARK_SKIN_TONE = new Emoji("\ud83e\uddbb\ud83c\udfff", "\\uD83E\\uDDBB\\uD83C\\uDFFF", Collections.unmodifiableList(Arrays.asList(":ear_with_hearing_aid_tone5:", ":ear_with_hearing_aid_dark_skin_tone:", ":ear_with_hearing_aid::skin-tone-5:")), Collections.singletonList(":ear_with_hearing_aid::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("accessibility", "aid", "dark skin tone", "ear", "hard", "hearing")), true, false, 12.0, Qualification.fromString("fully-qualified"), "ear with hearing aid: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji NOSE = new Emoji("\ud83d\udc43", "\\uD83D\\uDC43", Collections.singletonList(":nose:"), Collections.singletonList(":nose:"), Collections.singletonList(":nose:"), Collections.unmodifiableList(Arrays.asList("body", "nose", "noses", "nosey", "odor", "smell", "smells")), false, false, 0.6, Qualification.fromString("fully-qualified"), "nose", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji NOSE_LIGHT_SKIN_TONE = new Emoji("\ud83d\udc43\ud83c\udffb", "\\uD83D\\uDC43\\uD83C\\uDFFB", Collections.unmodifiableList(Arrays.asList(":nose_tone1:", ":nose::skin-tone-1:")), Collections.singletonList(":nose::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("body", "light skin tone", "nose", "noses", "nosey", "odor", "smell", "smells")), true, false, 1.0, Qualification.fromString("fully-qualified"), "nose: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji NOSE_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83d\udc43\ud83c\udffc", "\\uD83D\\uDC43\\uD83C\\uDFFC", Collections.unmodifiableList(Arrays.asList(":nose_tone2:", ":nose::skin-tone-2:")), Collections.singletonList(":nose::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("body", "medium-light skin tone", "nose", "noses", "nosey", "odor", "smell", "smells")), true, false, 1.0, Qualification.fromString("fully-qualified"), "nose: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji NOSE_MEDIUM_SKIN_TONE = new Emoji("\ud83d\udc43\ud83c\udffd", "\\uD83D\\uDC43\\uD83C\\uDFFD", Collections.unmodifiableList(Arrays.asList(":nose_tone3:", ":nose::skin-tone-3:")), Collections.singletonList(":nose::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("body", "medium skin tone", "nose", "noses", "nosey", "odor", "smell", "smells")), true, false, 1.0, Qualification.fromString("fully-qualified"), "nose: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji NOSE_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83d\udc43\ud83c\udffe", "\\uD83D\\uDC43\\uD83C\\uDFFE", Collections.unmodifiableList(Arrays.asList(":nose_tone4:", ":nose::skin-tone-4:")), Collections.singletonList(":nose::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("body", "medium-dark skin tone", "nose", "noses", "nosey", "odor", "smell", "smells")), true, false, 1.0, Qualification.fromString("fully-qualified"), "nose: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji NOSE_DARK_SKIN_TONE = new Emoji("\ud83d\udc43\ud83c\udfff", "\\uD83D\\uDC43\\uD83C\\uDFFF", Collections.unmodifiableList(Arrays.asList(":nose_tone5:", ":nose::skin-tone-5:")), Collections.singletonList(":nose::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("body", "dark skin tone", "nose", "noses", "nosey", "odor", "smell", "smells")), true, false, 1.0, Qualification.fromString("fully-qualified"), "nose: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji BRAIN = new Emoji("\ud83e\udde0", "\\uD83E\\uDDE0", Collections.singletonList(":brain:"), Collections.singletonList(":brain:"), Collections.singletonList(":brain:"), Collections.unmodifiableList(Arrays.asList("brain", "intelligent", "smart")), false, false, 5.0, Qualification.fromString("fully-qualified"), "brain", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji ANATOMICAL_HEART = new Emoji("\ud83e\udec0", "\\uD83E\\uDEC0", Collections.singletonList(":anatomical_heart:"), Collections.singletonList(":anatomical_heart:"), Collections.singletonList(":anatomical_heart:"), Collections.unmodifiableList(Arrays.asList("anatomical", "beat", "cardiology", "heart", "heartbeat", "organ", "pulse", "real", "red")), false, false, 13.0, Qualification.fromString("fully-qualified"), "anatomical heart", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji LUNGS = new Emoji("\ud83e\udec1", "\\uD83E\\uDEC1", Collections.singletonList(":lungs:"), Collections.singletonList(":lungs:"), Collections.singletonList(":lungs:"), Collections.unmodifiableList(Arrays.asList("breath", "breathe", "exhalation", "inhalation", "lung", "lungs", "organ", "respiration")), false, false, 13.0, Qualification.fromString("fully-qualified"), "lungs", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji TOOTH = new Emoji("\ud83e\uddb7", "\\uD83E\\uDDB7", Collections.singletonList(":tooth:"), Collections.singletonList(":tooth:"), Collections.singletonList(":tooth:"), Collections.unmodifiableList(Arrays.asList("dentist", "pearly", "teeth", "tooth", "white")), false, false, 11.0, Qualification.fromString("fully-qualified"), "tooth", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji BONE = new Emoji("\ud83e\uddb4", "\\uD83E\\uDDB4", Collections.singletonList(":bone:"), Collections.singletonList(":bone:"), Collections.singletonList(":bone:"), Collections.unmodifiableList(Arrays.asList("bone", "bones", "dog", "skeleton", "wishbone")), false, false, 11.0, Qualification.fromString("fully-qualified"), "bone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EYES = new Emoji("\ud83d\udc40", "\\uD83D\\uDC40", Collections.singletonList(":eyes:"), Collections.singletonList(":eyes:"), Collections.singletonList(":eyes:"), Collections.unmodifiableList(Arrays.asList("body", "eye", "eyes", "face", "googly", "look", "looking", "omg", "peep", "see", "seeing")), false, false, 0.6, Qualification.fromString("fully-qualified"), "eyes", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EYE = new Emoji("\ud83d\udc41\ufe0f", "\\uD83D\\uDC41\\uFE0F", Collections.singletonList(":eye:"), Collections.singletonList(":eye:"), Collections.singletonList(":eye:"), Collections.unmodifiableList(Arrays.asList("1", "body", "eye", "one")), false, false, 0.7, Qualification.fromString("fully-qualified"), "eye", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji EYE_UNQUALIFIED = new Emoji("\ud83d\udc41", "\\uD83D\\uDC41", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("1", "body", "eye", "one")), false, false, 0.7, Qualification.fromString("unqualified"), "eye", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, true);
    public static final Emoji TONGUE = new Emoji("\ud83d\udc45", "\\uD83D\\uDC45", Collections.singletonList(":tongue:"), Collections.singletonList(":tongue:"), Collections.singletonList(":tongue:"), Collections.unmodifiableList(Arrays.asList("body", "lick", "slurp", "tongue")), false, false, 0.6, Qualification.fromString("fully-qualified"), "tongue", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji MOUTH = new Emoji("\ud83d\udc44", "\\uD83D\\uDC44", Collections.unmodifiableList(Arrays.asList(":lips:", ":mouth:")), Collections.singletonList(":lips:"), Collections.singletonList(":lips:"), Collections.unmodifiableList(Arrays.asList("beauty", "body", "kiss", "kissing", "lips", "lipstick", "mouth")), false, false, 0.6, Qualification.fromString("fully-qualified"), "mouth", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
    public static final Emoji BITING_LIP = new Emoji("\ud83e\udee6", "\\uD83E\\uDEE6", Collections.singletonList(":biting_lip:"), Collections.singletonList(":biting_lip:"), Collections.singletonList(":biting_lip:"), Collections.unmodifiableList(Arrays.asList("anxious", "bite", "biting", "fear", "flirt", "flirting", "kiss", "lip", "lipstick", "nervous", "sexy", "uncomfortable", "worried", "worry")), false, false, 14.0, Qualification.fromString("fully-qualified"), "biting lip", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.BODY_PARTS, false);
}

