/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiMail {
    public static final Emoji ENVELOPE = new Emoji("\u2709\ufe0f", "\\u2709\\uFE0F", Collections.singletonList(":envelope:"), Collections.unmodifiableList(Arrays.asList(":email:", ":envelope:")), Collections.singletonList(":envelope:"), Collections.unmodifiableList(Arrays.asList("e-mail", "email", "envelope", "letter")), false, false, 0.6, Qualification.fromString("fully-qualified"), "envelope", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, false);
    public static final Emoji ENVELOPE_UNQUALIFIED = new Emoji("\u2709", "\\u2709", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("e-mail", "email", "envelope", "letter")), false, false, 0.6, Qualification.fromString("unqualified"), "envelope", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, true);
    public static final Emoji E_MAIL = new Emoji("\ud83d\udce7", "\\uD83D\\uDCE7", Collections.unmodifiableList(Arrays.asList(":e_mail:", ":email:")), Collections.singletonList(":e-mail:"), Collections.unmodifiableList(Arrays.asList(":e-mail:", ":email:")), Collections.unmodifiableList(Arrays.asList("e-mail", "email", "letter", "mail")), false, false, 0.6, Qualification.fromString("fully-qualified"), "e-mail", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, false);
    public static final Emoji INCOMING_ENVELOPE = new Emoji("\ud83d\udce8", "\\uD83D\\uDCE8", Collections.singletonList(":incoming_envelope:"), Collections.singletonList(":incoming_envelope:"), Collections.singletonList(":incoming_envelope:"), Collections.unmodifiableList(Arrays.asList("delivering", "e-mail", "email", "envelope", "incoming", "letter", "mail", "receive", "sent")), false, false, 0.6, Qualification.fromString("fully-qualified"), "incoming envelope", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, false);
    public static final Emoji ENVELOPE_WITH_ARROW = new Emoji("\ud83d\udce9", "\\uD83D\\uDCE9", Collections.singletonList(":envelope_with_arrow:"), Collections.singletonList(":envelope_with_arrow:"), Collections.singletonList(":envelope_with_arrow:"), Collections.unmodifiableList(Arrays.asList("arrow", "communication", "down", "e-mail", "email", "envelope", "letter", "mail", "outgoing", "send", "sent")), false, false, 0.6, Qualification.fromString("fully-qualified"), "envelope with arrow", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, false);
    public static final Emoji OUTBOX_TRAY = new Emoji("\ud83d\udce4", "\\uD83D\\uDCE4", Collections.singletonList(":outbox_tray:"), Collections.singletonList(":outbox_tray:"), Collections.singletonList(":outbox_tray:"), Collections.unmodifiableList(Arrays.asList("box", "email", "letter", "mail", "outbox", "sent", "tray")), false, false, 0.6, Qualification.fromString("fully-qualified"), "outbox tray", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, true);
    public static final Emoji INBOX_TRAY = new Emoji("\ud83d\udce5", "\\uD83D\\uDCE5", Collections.singletonList(":inbox_tray:"), Collections.singletonList(":inbox_tray:"), Collections.singletonList(":inbox_tray:"), Collections.unmodifiableList(Arrays.asList("box", "email", "inbox", "letter", "mail", "receive", "tray", "zero")), false, false, 0.6, Qualification.fromString("fully-qualified"), "inbox tray", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, true);
    public static final Emoji PACKAGE = new Emoji("\ud83d\udce6", "\\uD83D\\uDCE6", Collections.singletonList(":package:"), Collections.singletonList(":package:"), Collections.singletonList(":package:"), Collections.unmodifiableList(Arrays.asList("box", "communication", "delivery", "package", "parcel", "shipping")), false, false, 0.6, Qualification.fromString("fully-qualified"), "package", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, true);
    public static final Emoji CLOSED_MAILBOX_WITH_RAISED_FLAG = new Emoji("\ud83d\udceb", "\\uD83D\\uDCEB", Collections.singletonList(":mailbox:"), Collections.singletonList(":mailbox:"), Collections.singletonList(":mailbox:"), Collections.unmodifiableList(Arrays.asList("closed", "communication", "flag", "mail", "mailbox", "postbox", "raised")), false, false, 0.6, Qualification.fromString("fully-qualified"), "closed mailbox with raised flag", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, true);
    public static final Emoji CLOSED_MAILBOX_WITH_LOWERED_FLAG = new Emoji("\ud83d\udcea", "\\uD83D\\uDCEA", Collections.singletonList(":mailbox_closed:"), Collections.singletonList(":mailbox_closed:"), Collections.singletonList(":mailbox_closed:"), Collections.unmodifiableList(Arrays.asList("closed", "flag", "lowered", "mail", "mailbox", "postbox")), false, false, 0.6, Qualification.fromString("fully-qualified"), "closed mailbox with lowered flag", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, true);
    public static final Emoji OPEN_MAILBOX_WITH_RAISED_FLAG = new Emoji("\ud83d\udcec", "\\uD83D\\uDCEC", Collections.singletonList(":mailbox_with_mail:"), Collections.singletonList(":mailbox_with_mail:"), Collections.singletonList(":mailbox_with_mail:"), Collections.unmodifiableList(Arrays.asList("flag", "mail", "mailbox", "open", "postbox", "raised")), false, false, 0.7, Qualification.fromString("fully-qualified"), "open mailbox with raised flag", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, true);
    public static final Emoji OPEN_MAILBOX_WITH_LOWERED_FLAG = new Emoji("\ud83d\udced", "\\uD83D\\uDCED", Collections.singletonList(":mailbox_with_no_mail:"), Collections.singletonList(":mailbox_with_no_mail:"), Collections.singletonList(":mailbox_with_no_mail:"), Collections.unmodifiableList(Arrays.asList("flag", "lowered", "mail", "mailbox", "open", "postbox")), false, false, 0.7, Qualification.fromString("fully-qualified"), "open mailbox with lowered flag", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, true);
    public static final Emoji POSTBOX = new Emoji("\ud83d\udcee", "\\uD83D\\uDCEE", Collections.singletonList(":postbox:"), Collections.singletonList(":postbox:"), Collections.singletonList(":postbox:"), Collections.unmodifiableList(Arrays.asList("mail", "mailbox", "postbox")), false, false, 0.6, Qualification.fromString("fully-qualified"), "postbox", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, false);
    public static final Emoji BALLOT_BOX_WITH_BALLOT = new Emoji("\ud83d\uddf3\ufe0f", "\\uD83D\\uDDF3\\uFE0F", Collections.unmodifiableList(Arrays.asList(":ballot_box:", ":ballot_box_with_ballot:")), Collections.singletonList(":ballot_box_with_ballot:"), Collections.singletonList(":ballot_box:"), Collections.unmodifiableList(Arrays.asList("ballot", "box")), false, false, 0.7, Qualification.fromString("fully-qualified"), "ballot box with ballot", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, false);
    public static final Emoji BALLOT_BOX_WITH_BALLOT_UNQUALIFIED = new Emoji("\ud83d\uddf3", "\\uD83D\\uDDF3", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("ballot", "box")), false, false, 0.7, Qualification.fromString("unqualified"), "ballot box with ballot", EmojiGroup.OBJECTS, EmojiSubGroup.MAIL, true);
}

