/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiTransportWater {
    public static final Emoji ANCHOR = new Emoji("\u2693", "\\u2693", Collections.singletonList(":anchor:"), Collections.singletonList(":anchor:"), Collections.singletonList(":anchor:"), Collections.unmodifiableList(Arrays.asList("anchor", "ship", "tool")), false, false, 0.6, Qualification.fromString("fully-qualified"), "anchor", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_WATER, true);
    public static final Emoji RING_BUOY = new Emoji("\ud83d\udedf", "\\uD83D\\uDEDF", Collections.singletonList(":ring_buoy:"), Collections.singletonList(":ring_buoy:"), Collections.singletonList(":ring_buoy:"), Collections.unmodifiableList(Arrays.asList("buoy", "float", "life", "lifesaver", "preserver", "rescue", "ring", "safety", "save", "saver", "swim")), false, false, 14.0, Qualification.fromString("fully-qualified"), "ring buoy", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_WATER, false);
    public static final Emoji SAILBOAT = new Emoji("\u26f5", "\\u26F5", Collections.singletonList(":sailboat:"), Collections.unmodifiableList(Arrays.asList(":boat:", ":sailboat:")), Collections.unmodifiableList(Arrays.asList(":boat:", ":sailboat:")), Collections.unmodifiableList(Arrays.asList("boat", "resort", "sailboat", "sailing", "sea", "yacht")), false, false, 0.6, Qualification.fromString("fully-qualified"), "sailboat", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_WATER, true);
    public static final Emoji CANOE = new Emoji("\ud83d\udef6", "\\uD83D\\uDEF6", Collections.unmodifiableList(Arrays.asList(":canoe:", ":kayak:")), Collections.singletonList(":canoe:"), Collections.singletonList(":canoe:"), Collections.unmodifiableList(Arrays.asList("boat", "canoe")), false, false, 3.0, Qualification.fromString("fully-qualified"), "canoe", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_WATER, false);
    public static final Emoji SPEEDBOAT = new Emoji("\ud83d\udea4", "\\uD83D\\uDEA4", Collections.singletonList(":speedboat:"), Collections.singletonList(":speedboat:"), Collections.singletonList(":speedboat:"), Collections.unmodifiableList(Arrays.asList("billionaire", "boat", "lake", "luxury", "millionaire", "speedboat", "summer", "travel")), false, false, 0.6, Qualification.fromString("fully-qualified"), "speedboat", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_WATER, false);
    public static final Emoji PASSENGER_SHIP = new Emoji("\ud83d\udef3\ufe0f", "\\uD83D\\uDEF3\\uFE0F", Collections.unmodifiableList(Arrays.asList(":cruise_ship:", ":passenger_ship:")), Collections.singletonList(":passenger_ship:"), Collections.singletonList(":passenger_ship:"), Collections.unmodifiableList(Arrays.asList("passenger", "ship")), false, false, 0.7, Qualification.fromString("fully-qualified"), "passenger ship", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_WATER, false);
    public static final Emoji PASSENGER_SHIP_UNQUALIFIED = new Emoji("\ud83d\udef3", "\\uD83D\\uDEF3", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("passenger", "ship")), false, false, 0.7, Qualification.fromString("unqualified"), "passenger ship", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_WATER, true);
    public static final Emoji FERRY = new Emoji("\u26f4\ufe0f", "\\u26F4\\uFE0F", Collections.singletonList(":ferry:"), Collections.singletonList(":ferry:"), Collections.singletonList(":ferry:"), Collections.unmodifiableList(Arrays.asList("boat", "ferry", "passenger")), false, false, 0.7, Qualification.fromString("fully-qualified"), "ferry", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_WATER, false);
    public static final Emoji FERRY_UNQUALIFIED = new Emoji("\u26f4", "\\u26F4", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("boat", "ferry", "passenger")), false, false, 0.7, Qualification.fromString("unqualified"), "ferry", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_WATER, true);
    public static final Emoji MOTOR_BOAT = new Emoji("\ud83d\udee5\ufe0f", "\\uD83D\\uDEE5\\uFE0F", Collections.unmodifiableList(Arrays.asList(":motorboat:", ":motor_boat:")), Collections.singletonList(":motor_boat:"), Collections.singletonList(":motor_boat:"), Collections.unmodifiableList(Arrays.asList("boat", "motor", "motorboat")), false, false, 0.7, Qualification.fromString("fully-qualified"), "motor boat", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_WATER, false);
    public static final Emoji MOTOR_BOAT_UNQUALIFIED = new Emoji("\ud83d\udee5", "\\uD83D\\uDEE5", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("boat", "motor", "motorboat")), false, false, 0.7, Qualification.fromString("unqualified"), "motor boat", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_WATER, true);
    public static final Emoji SHIP = new Emoji("\ud83d\udea2", "\\uD83D\\uDEA2", Collections.singletonList(":ship:"), Collections.singletonList(":ship:"), Collections.singletonList(":ship:"), Collections.unmodifiableList(Arrays.asList("boat", "passenger", "ship", "travel")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ship", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.TRANSPORT_WATER, false);
}

