/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiFlag {
    public static final Emoji CHEQUERED_FLAG = new Emoji("\ud83c\udfc1", "\\uD83C\\uDFC1", Collections.singletonList(":checkered_flag:"), Collections.singletonList(":checkered_flag:"), Collections.singletonList(":checkered_flag:"), Collections.unmodifiableList(Arrays.asList("checkered", "chequered", "finish", "flag", "flags", "game", "race", "racing", "sport", "win")), false, false, 0.6, Qualification.fromString("fully-qualified"), "chequered flag", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, false);
    public static final Emoji TRIANGULAR_FLAG = new Emoji("\ud83d\udea9", "\\uD83D\\uDEA9", Collections.singletonList(":triangular_flag_on_post:"), Collections.singletonList(":triangular_flag_on_post:"), Collections.singletonList(":triangular_flag_on_post:"), Collections.unmodifiableList(Arrays.asList("construction", "flag", "golf", "post", "triangular")), false, false, 0.6, Qualification.fromString("fully-qualified"), "triangular flag", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, false);
    public static final Emoji CROSSED_FLAGS = new Emoji("\ud83c\udf8c", "\\uD83C\\uDF8C", Collections.singletonList(":crossed_flags:"), Collections.singletonList(":crossed_flags:"), Collections.singletonList(":crossed_flags:"), Collections.unmodifiableList(Arrays.asList("celebration", "cross", "crossed", "flags", "Japanese")), false, false, 0.6, Qualification.fromString("fully-qualified"), "crossed flags", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, false);
    public static final Emoji BLACK_FLAG = new Emoji("\ud83c\udff4", "\\uD83C\\uDFF4", Collections.singletonList(":flag_black:"), Collections.singletonList(":waving_black_flag:"), Collections.singletonList(":black_flag:"), Collections.unmodifiableList(Arrays.asList("black", "flag", "waving")), false, false, 1.0, Qualification.fromString("fully-qualified"), "black flag", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, false);
    public static final Emoji WHITE_FLAG = new Emoji("\ud83c\udff3\ufe0f", "\\uD83C\\uDFF3\\uFE0F", Collections.singletonList(":flag_white:"), Collections.singletonList(":waving_white_flag:"), Collections.singletonList(":white_flag:"), Collections.unmodifiableList(Arrays.asList("flag", "waving", "white")), false, false, 0.7, Qualification.fromString("fully-qualified"), "white flag", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, false);
    public static final Emoji WHITE_FLAG_UNQUALIFIED = new Emoji("\ud83c\udff3", "\\uD83C\\uDFF3", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("flag", "waving", "white")), false, false, 0.7, Qualification.fromString("unqualified"), "white flag", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, true);
    public static final Emoji RAINBOW_FLAG = new Emoji("\ud83c\udff3\ufe0f\u200d\ud83c\udf08", "\\uD83C\\uDFF3\\uFE0F\\u200D\\uD83C\\uDF08", Collections.unmodifiableList(Arrays.asList(":rainbow_flag:", ":gay_pride_flag:")), Collections.singletonList(":rainbow-flag:"), Collections.singletonList(":rainbow_flag:"), Collections.unmodifiableList(Arrays.asList("bisexual", "flag", "gay", "genderqueer", "glbt", "glbtq", "lesbian", "lgbt", "lgbtq", "lgbtqia", "pride", "queer", "rainbow", "trans", "transgender")), false, false, 4.0, Qualification.fromString("fully-qualified"), "rainbow flag", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, false);
    public static final Emoji RAINBOW_FLAG_UNQUALIFIED = new Emoji("\ud83c\udff3\u200d\ud83c\udf08", "\\uD83C\\uDFF3\\u200D\\uD83C\\uDF08", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bisexual", "flag", "gay", "genderqueer", "glbt", "glbtq", "lesbian", "lgbt", "lgbtq", "lgbtqia", "pride", "queer", "rainbow", "trans", "transgender")), false, false, 4.0, Qualification.fromString("unqualified"), "rainbow flag", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, false);
    public static final Emoji TRANSGENDER_FLAG = new Emoji("\ud83c\udff3\ufe0f\u200d\u26a7\ufe0f", "\\uD83C\\uDFF3\\uFE0F\\u200D\\u26A7\\uFE0F", Collections.singletonList(":transgender_flag:"), Collections.singletonList(":transgender_flag:"), Collections.singletonList(":transgender_flag:"), Collections.unmodifiableList(Arrays.asList("blue", "flag", "light", "pink", "transgender", "white")), false, false, 13.0, Qualification.fromString("fully-qualified"), "transgender flag", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, false);
    public static final Emoji TRANSGENDER_FLAG_UNQUALIFIED_0 = new Emoji("\ud83c\udff3\u200d\u26a7\ufe0f", "\\uD83C\\uDFF3\\u200D\\u26A7\\uFE0F", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("blue", "flag", "light", "pink", "transgender", "white")), false, false, 13.0, Qualification.fromString("unqualified"), "transgender flag", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, false);
    public static final Emoji TRANSGENDER_FLAG_MINIMALLY_QUALIFIED = new Emoji("\ud83c\udff3\ufe0f\u200d\u26a7", "\\uD83C\\uDFF3\\uFE0F\\u200D\\u26A7", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("blue", "flag", "light", "pink", "transgender", "white")), false, false, 13.0, Qualification.fromString("minimally-qualified"), "transgender flag", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, false);
    public static final Emoji TRANSGENDER_FLAG_UNQUALIFIED_1 = new Emoji("\ud83c\udff3\u200d\u26a7", "\\uD83C\\uDFF3\\u200D\\u26A7", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("blue", "flag", "light", "pink", "transgender", "white")), false, false, 13.0, Qualification.fromString("unqualified"), "transgender flag", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, false);
    public static final Emoji PIRATE_FLAG = new Emoji("\ud83c\udff4\u200d\u2620\ufe0f", "\\uD83C\\uDFF4\\u200D\\u2620\\uFE0F", Collections.singletonList(":pirate_flag:"), Collections.singletonList(":pirate_flag:"), Collections.singletonList(":pirate_flag:"), Collections.unmodifiableList(Arrays.asList("flag", "Jolly", "pirate", "plunder", "Roger", "treasure")), false, false, 11.0, Qualification.fromString("fully-qualified"), "pirate flag", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, false);
    public static final Emoji PIRATE_FLAG_MINIMALLY_QUALIFIED = new Emoji("\ud83c\udff4\u200d\u2620", "\\uD83C\\uDFF4\\u200D\\u2620", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("flag", "Jolly", "pirate", "plunder", "Roger", "treasure")), false, false, 11.0, Qualification.fromString("minimally-qualified"), "pirate flag", EmojiGroup.FLAGS, EmojiSubGroup.FLAG, false);
}

