/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiTransportSign {
    public static final Emoji ATM_SIGN = new Emoji("\ud83c\udfe7", "\\uD83C\\uDFE7", Collections.singletonList(":atm:"), Collections.singletonList(":atm:"), Collections.singletonList(":atm:"), Collections.unmodifiableList(Arrays.asList("ATM", "automated", "bank", "cash", "money", "sign", "teller")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ATM sign", EmojiGroup.SYMBOLS, EmojiSubGroup.TRANSPORT_SIGN, false);
    public static final Emoji LITTER_IN_BIN_SIGN = new Emoji("\ud83d\udeae", "\\uD83D\\uDEAE", Collections.singletonList(":put_litter_in_its_place:"), Collections.singletonList(":put_litter_in_its_place:"), Collections.singletonList(":put_litter_in_its_place:"), Collections.unmodifiableList(Arrays.asList("bin", "litter", "litterbin", "sign")), false, false, 1.0, Qualification.fromString("fully-qualified"), "litter in bin sign", EmojiGroup.SYMBOLS, EmojiSubGroup.TRANSPORT_SIGN, false);
    public static final Emoji POTABLE_WATER = new Emoji("\ud83d\udeb0", "\\uD83D\\uDEB0", Collections.singletonList(":potable_water:"), Collections.singletonList(":potable_water:"), Collections.singletonList(":potable_water:"), Collections.unmodifiableList(Arrays.asList("drinking", "potable", "water")), false, false, 1.0, Qualification.fromString("fully-qualified"), "potable water", EmojiGroup.SYMBOLS, EmojiSubGroup.TRANSPORT_SIGN, false);
    public static final Emoji WHEELCHAIR_SYMBOL = new Emoji("\u267f", "\\u267F", Collections.singletonList(":wheelchair:"), Collections.singletonList(":wheelchair:"), Collections.singletonList(":wheelchair:"), Collections.unmodifiableList(Arrays.asList("access", "handicap", "symbol", "wheelchair")), false, false, 0.6, Qualification.fromString("fully-qualified"), "wheelchair symbol", EmojiGroup.SYMBOLS, EmojiSubGroup.TRANSPORT_SIGN, true);
    public static final Emoji MEN_S_ROOM = new Emoji("\ud83d\udeb9", "\\uD83D\\uDEB9", Collections.unmodifiableList(Arrays.asList(":mens:", ":mens_room:")), Collections.singletonList(":mens:"), Collections.singletonList(":mens:"), Collections.unmodifiableList(Arrays.asList("bathroom", "lavatory", "man", "men\u2019s", "restroom", "room", "toilet", "WC")), false, false, 0.6, Qualification.fromString("fully-qualified"), "men\u2019s room", EmojiGroup.SYMBOLS, EmojiSubGroup.TRANSPORT_SIGN, true);
    public static final Emoji WOMEN_S_ROOM = new Emoji("\ud83d\udeba", "\\uD83D\\uDEBA", Collections.unmodifiableList(Arrays.asList(":womens:", ":womens_room:")), Collections.singletonList(":womens:"), Collections.singletonList(":womens:"), Collections.unmodifiableList(Arrays.asList("bathroom", "lavatory", "restroom", "room", "toilet", "WC", "woman", "women\u2019s")), false, false, 0.6, Qualification.fromString("fully-qualified"), "women\u2019s room", EmojiGroup.SYMBOLS, EmojiSubGroup.TRANSPORT_SIGN, true);
    public static final Emoji RESTROOM = new Emoji("\ud83d\udebb", "\\uD83D\\uDEBB", Collections.singletonList(":restroom:"), Collections.singletonList(":restroom:"), Collections.singletonList(":restroom:"), Collections.unmodifiableList(Arrays.asList("bathroom", "lavatory", "restroom", "toilet", "WC")), false, false, 0.6, Qualification.fromString("fully-qualified"), "restroom", EmojiGroup.SYMBOLS, EmojiSubGroup.TRANSPORT_SIGN, false);
    public static final Emoji BABY_SYMBOL = new Emoji("\ud83d\udebc", "\\uD83D\\uDEBC", Collections.singletonList(":baby_symbol:"), Collections.singletonList(":baby_symbol:"), Collections.singletonList(":baby_symbol:"), Collections.unmodifiableList(Arrays.asList("baby", "changing", "symbol")), false, false, 0.6, Qualification.fromString("fully-qualified"), "baby symbol", EmojiGroup.SYMBOLS, EmojiSubGroup.TRANSPORT_SIGN, true);
    public static final Emoji WATER_CLOSET = new Emoji("\ud83d\udebe", "\\uD83D\\uDEBE", Collections.unmodifiableList(Arrays.asList(":wc:", ":water_closet:")), Collections.singletonList(":wc:"), Collections.singletonList(":wc:"), Collections.unmodifiableList(Arrays.asList("bathroom", "closet", "lavatory", "restroom", "toilet", "water", "WC")), false, false, 0.6, Qualification.fromString("fully-qualified"), "water closet", EmojiGroup.SYMBOLS, EmojiSubGroup.TRANSPORT_SIGN, false);
    public static final Emoji PASSPORT_CONTROL = new Emoji("\ud83d\udec2", "\\uD83D\\uDEC2", Collections.singletonList(":passport_control:"), Collections.singletonList(":passport_control:"), Collections.singletonList(":passport_control:"), Collections.unmodifiableList(Arrays.asList("control", "passport")), false, false, 1.0, Qualification.fromString("fully-qualified"), "passport control", EmojiGroup.SYMBOLS, EmojiSubGroup.TRANSPORT_SIGN, false);
    public static final Emoji CUSTOMS = new Emoji("\ud83d\udec3", "\\uD83D\\uDEC3", Collections.singletonList(":customs:"), Collections.singletonList(":customs:"), Collections.singletonList(":customs:"), Collections.unmodifiableList(Arrays.asList("customs", "packing")), false, false, 1.0, Qualification.fromString("fully-qualified"), "customs", EmojiGroup.SYMBOLS, EmojiSubGroup.TRANSPORT_SIGN, false);
    public static final Emoji BAGGAGE_CLAIM = new Emoji("\ud83d\udec4", "\\uD83D\\uDEC4", Collections.singletonList(":baggage_claim:"), Collections.singletonList(":baggage_claim:"), Collections.singletonList(":baggage_claim:"), Collections.unmodifiableList(Arrays.asList("arrived", "baggage", "bags", "case", "checked", "claim", "journey", "packing", "plane", "ready", "travel", "trip")), false, false, 1.0, Qualification.fromString("fully-qualified"), "baggage claim", EmojiGroup.SYMBOLS, EmojiSubGroup.TRANSPORT_SIGN, false);
    public static final Emoji LEFT_LUGGAGE = new Emoji("\ud83d\udec5", "\\uD83D\\uDEC5", Collections.singletonList(":left_luggage:"), Collections.singletonList(":left_luggage:"), Collections.singletonList(":left_luggage:"), Collections.unmodifiableList(Arrays.asList("baggage", "case", "left", "locker", "luggage")), false, false, 1.0, Qualification.fromString("fully-qualified"), "left luggage", EmojiGroup.SYMBOLS, EmojiSubGroup.TRANSPORT_SIGN, false);
}

