/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiPlaceGeographic {
    public static final Emoji SNOW_CAPPED_MOUNTAIN = new Emoji("\ud83c\udfd4\ufe0f", "\\uD83C\\uDFD4\\uFE0F", Collections.unmodifiableList(Arrays.asList(":mountain_snow:", ":snow_capped_mountain:")), Collections.singletonList(":snow_capped_mountain:"), Collections.singletonList(":mountain_snow:"), Collections.unmodifiableList(Arrays.asList("cold", "mountain", "snow", "snow-capped")), false, false, 0.7, Qualification.fromString("fully-qualified"), "snow-capped mountain", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, false);
    public static final Emoji SNOW_CAPPED_MOUNTAIN_UNQUALIFIED = new Emoji("\ud83c\udfd4", "\\uD83C\\uDFD4", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cold", "mountain", "snow", "snow-capped")), false, false, 0.7, Qualification.fromString("unqualified"), "snow-capped mountain", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, true);
    public static final Emoji MOUNTAIN = new Emoji("\u26f0\ufe0f", "\\u26F0\\uFE0F", Collections.singletonList(":mountain:"), Collections.singletonList(":mountain:"), Collections.singletonList(":mountain:"), Collections.singletonList("mountain"), false, false, 0.7, Qualification.fromString("fully-qualified"), "mountain", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, false);
    public static final Emoji MOUNTAIN_UNQUALIFIED = new Emoji("\u26f0", "\\u26F0", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.singletonList("mountain"), false, false, 0.7, Qualification.fromString("unqualified"), "mountain", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, true);
    public static final Emoji VOLCANO = new Emoji("\ud83c\udf0b", "\\uD83C\\uDF0B", Collections.singletonList(":volcano:"), Collections.singletonList(":volcano:"), Collections.singletonList(":volcano:"), Collections.unmodifiableList(Arrays.asList("eruption", "mountain", "nature", "volcano")), false, false, 0.6, Qualification.fromString("fully-qualified"), "volcano", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, false);
    public static final Emoji MOUNT_FUJI = new Emoji("\ud83d\uddfb", "\\uD83D\\uDDFB", Collections.singletonList(":mount_fuji:"), Collections.singletonList(":mount_fuji:"), Collections.singletonList(":mount_fuji:"), Collections.unmodifiableList(Arrays.asList("fuji", "mount", "mountain", "nature")), false, false, 0.6, Qualification.fromString("fully-qualified"), "mount fuji", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, false);
    public static final Emoji CAMPING = new Emoji("\ud83c\udfd5\ufe0f", "\\uD83C\\uDFD5\\uFE0F", Collections.singletonList(":camping:"), Collections.singletonList(":camping:"), Collections.singletonList(":camping:"), Collections.singletonList("camping"), false, false, 0.7, Qualification.fromString("fully-qualified"), "camping", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, false);
    public static final Emoji CAMPING_UNQUALIFIED = new Emoji("\ud83c\udfd5", "\\uD83C\\uDFD5", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.singletonList("camping"), false, false, 0.7, Qualification.fromString("unqualified"), "camping", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, true);
    public static final Emoji BEACH_WITH_UMBRELLA = new Emoji("\ud83c\udfd6\ufe0f", "\\uD83C\\uDFD6\\uFE0F", Collections.unmodifiableList(Arrays.asList(":beach:", ":beach_with_umbrella:")), Collections.singletonList(":beach_with_umbrella:"), Collections.singletonList(":beach_umbrella:"), Collections.unmodifiableList(Arrays.asList("beach", "umbrella")), false, false, 0.7, Qualification.fromString("fully-qualified"), "beach with umbrella", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, false);
    public static final Emoji BEACH_WITH_UMBRELLA_UNQUALIFIED = new Emoji("\ud83c\udfd6", "\\uD83C\\uDFD6", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("beach", "umbrella")), false, false, 0.7, Qualification.fromString("unqualified"), "beach with umbrella", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, true);
    public static final Emoji DESERT = new Emoji("\ud83c\udfdc\ufe0f", "\\uD83C\\uDFDC\\uFE0F", Collections.singletonList(":desert:"), Collections.singletonList(":desert:"), Collections.singletonList(":desert:"), Collections.singletonList("desert"), false, false, 0.7, Qualification.fromString("fully-qualified"), "desert", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, false);
    public static final Emoji DESERT_UNQUALIFIED = new Emoji("\ud83c\udfdc", "\\uD83C\\uDFDC", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.singletonList("desert"), false, false, 0.7, Qualification.fromString("unqualified"), "desert", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, true);
    public static final Emoji DESERT_ISLAND = new Emoji("\ud83c\udfdd\ufe0f", "\\uD83C\\uDFDD\\uFE0F", Collections.unmodifiableList(Arrays.asList(":island:", ":desert_island:")), Collections.singletonList(":desert_island:"), Collections.singletonList(":desert_island:"), Collections.unmodifiableList(Arrays.asList("desert", "island")), false, false, 0.7, Qualification.fromString("fully-qualified"), "desert island", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, false);
    public static final Emoji DESERT_ISLAND_UNQUALIFIED = new Emoji("\ud83c\udfdd", "\\uD83C\\uDFDD", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("desert", "island")), false, false, 0.7, Qualification.fromString("unqualified"), "desert island", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, true);
    public static final Emoji NATIONAL_PARK = new Emoji("\ud83c\udfde\ufe0f", "\\uD83C\\uDFDE\\uFE0F", Collections.unmodifiableList(Arrays.asList(":park:", ":national_park:")), Collections.singletonList(":national_park:"), Collections.singletonList(":national_park:"), Collections.unmodifiableList(Arrays.asList("national", "park")), false, false, 0.7, Qualification.fromString("fully-qualified"), "national park", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, false);
    public static final Emoji NATIONAL_PARK_UNQUALIFIED = new Emoji("\ud83c\udfde", "\\uD83C\\uDFDE", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("national", "park")), false, false, 0.7, Qualification.fromString("unqualified"), "national park", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_GEOGRAPHIC, true);
}

