/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiPlantFlower {
    public static final Emoji BOUQUET = new Emoji("\ud83d\udc90", "\\uD83D\\uDC90", Collections.singletonList(":bouquet:"), Collections.singletonList(":bouquet:"), Collections.singletonList(":bouquet:"), Collections.unmodifiableList(Arrays.asList("anniversary", "birthday", "bouquet", "date", "flower", "love", "plant", "romance")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bouquet", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_FLOWER, false);
    public static final Emoji CHERRY_BLOSSOM = new Emoji("\ud83c\udf38", "\\uD83C\\uDF38", Collections.singletonList(":cherry_blossom:"), Collections.singletonList(":cherry_blossom:"), Collections.singletonList(":cherry_blossom:"), Collections.unmodifiableList(Arrays.asList("blossom", "cherry", "flower", "plant", "spring", "springtime")), false, false, 0.6, Qualification.fromString("fully-qualified"), "cherry blossom", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_FLOWER, false);
    public static final Emoji WHITE_FLOWER = new Emoji("\ud83d\udcae", "\\uD83D\\uDCAE", Collections.singletonList(":white_flower:"), Collections.singletonList(":white_flower:"), Collections.singletonList(":white_flower:"), Collections.unmodifiableList(Arrays.asList("flower", "white")), false, false, 0.6, Qualification.fromString("fully-qualified"), "white flower", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_FLOWER, false);
    public static final Emoji LOTUS = new Emoji("\ud83e\udeb7", "\\uD83E\\uDEB7", Collections.singletonList(":lotus:"), Collections.singletonList(":lotus:"), Collections.singletonList(":lotus:"), Collections.unmodifiableList(Arrays.asList("beauty", "Buddhism", "calm", "flower", "Hinduism", "lotus", "peace", "purity", "serenity")), false, false, 14.0, Qualification.fromString("fully-qualified"), "lotus", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_FLOWER, false);
    public static final Emoji ROSETTE = new Emoji("\ud83c\udff5\ufe0f", "\\uD83C\\uDFF5\\uFE0F", Collections.singletonList(":rosette:"), Collections.singletonList(":rosette:"), Collections.singletonList(":rosette:"), Collections.unmodifiableList(Arrays.asList("plant", "rosette")), false, false, 0.7, Qualification.fromString("fully-qualified"), "rosette", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_FLOWER, false);
    public static final Emoji ROSETTE_UNQUALIFIED = new Emoji("\ud83c\udff5", "\\uD83C\\uDFF5", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("plant", "rosette")), false, false, 0.7, Qualification.fromString("unqualified"), "rosette", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_FLOWER, true);
    public static final Emoji ROSE = new Emoji("\ud83c\udf39", "\\uD83C\\uDF39", Collections.singletonList(":rose:"), Collections.singletonList(":rose:"), Collections.singletonList(":rose:"), Collections.unmodifiableList(Arrays.asList("beauty", "elegant", "flower", "love", "plant", "red", "rose", "valentine")), false, false, 0.6, Qualification.fromString("fully-qualified"), "rose", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_FLOWER, false);
    public static final Emoji WILTED_FLOWER = new Emoji("\ud83e\udd40", "\\uD83E\\uDD40", Collections.unmodifiableList(Arrays.asList(":wilted_rose:", ":wilted_flower:")), Collections.singletonList(":wilted_flower:"), Collections.singletonList(":wilted_flower:"), Collections.unmodifiableList(Arrays.asList("dying", "flower", "wilted")), false, false, 3.0, Qualification.fromString("fully-qualified"), "wilted flower", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_FLOWER, false);
    public static final Emoji HIBISCUS = new Emoji("\ud83c\udf3a", "\\uD83C\\uDF3A", Collections.singletonList(":hibiscus:"), Collections.singletonList(":hibiscus:"), Collections.singletonList(":hibiscus:"), Collections.unmodifiableList(Arrays.asList("flower", "hibiscus", "plant")), false, false, 0.6, Qualification.fromString("fully-qualified"), "hibiscus", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_FLOWER, false);
    public static final Emoji SUNFLOWER = new Emoji("\ud83c\udf3b", "\\uD83C\\uDF3B", Collections.singletonList(":sunflower:"), Collections.singletonList(":sunflower:"), Collections.singletonList(":sunflower:"), Collections.unmodifiableList(Arrays.asList("flower", "outdoors", "plant", "sun", "sunflower")), false, false, 0.6, Qualification.fromString("fully-qualified"), "sunflower", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_FLOWER, false);
    public static final Emoji BLOSSOM = new Emoji("\ud83c\udf3c", "\\uD83C\\uDF3C", Collections.singletonList(":blossom:"), Collections.singletonList(":blossom:"), Collections.singletonList(":blossom:"), Collections.unmodifiableList(Arrays.asList("blossom", "buttercup", "dandelion", "flower", "plant")), false, false, 0.6, Qualification.fromString("fully-qualified"), "blossom", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_FLOWER, false);
    public static final Emoji TULIP = new Emoji("\ud83c\udf37", "\\uD83C\\uDF37", Collections.singletonList(":tulip:"), Collections.singletonList(":tulip:"), Collections.singletonList(":tulip:"), Collections.unmodifiableList(Arrays.asList("blossom", "flower", "growth", "plant", "tulip")), false, false, 0.6, Qualification.fromString("fully-qualified"), "tulip", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_FLOWER, false);
    public static final Emoji HYACINTH = new Emoji("\ud83e\udebb", "\\uD83E\\uDEBB", Collections.singletonList(":hyacinth:"), Collections.emptyList(), Collections.singletonList(":hyacinth:"), Collections.unmodifiableList(Arrays.asList("bloom", "bluebonnet", "flower", "hyacinth", "indigo", "lavender", "lilac", "lupine", "plant", "purple", "shrub", "snapdragon", "spring", "violet")), false, false, 15.0, Qualification.fromString("fully-qualified"), "hyacinth", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.PLANT_FLOWER, false);
}

