/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiHandProp {
    public static final Emoji WRITING_HAND = new Emoji("\u270d\ufe0f", "\\u270D\\uFE0F", Collections.singletonList(":writing_hand:"), Collections.singletonList(":writing_hand:"), Collections.singletonList(":writing_hand:"), Collections.unmodifiableList(Arrays.asList("hand", "write", "writing")), false, false, 0.7, Qualification.fromString("fully-qualified"), "writing hand", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji WRITING_HAND_UNQUALIFIED = new Emoji("\u270d", "\\u270D", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("hand", "write", "writing")), false, false, 0.7, Qualification.fromString("unqualified"), "writing hand", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, true);
    public static final Emoji WRITING_HAND_LIGHT_SKIN_TONE = new Emoji("\u270d\ud83c\udffb", "\\u270D\\uD83C\\uDFFB", Collections.unmodifiableList(Arrays.asList(":writing_hand_tone1:", ":writing_hand::skin-tone-1:")), Collections.singletonList(":writing_hand::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("hand", "light skin tone", "write", "writing")), true, false, 1.0, Qualification.fromString("fully-qualified"), "writing hand: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji WRITING_HAND_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\u270d\ud83c\udffc", "\\u270D\\uD83C\\uDFFC", Collections.unmodifiableList(Arrays.asList(":writing_hand_tone2:", ":writing_hand::skin-tone-2:")), Collections.singletonList(":writing_hand::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("hand", "medium-light skin tone", "write", "writing")), true, false, 1.0, Qualification.fromString("fully-qualified"), "writing hand: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji WRITING_HAND_MEDIUM_SKIN_TONE = new Emoji("\u270d\ud83c\udffd", "\\u270D\\uD83C\\uDFFD", Collections.unmodifiableList(Arrays.asList(":writing_hand_tone3:", ":writing_hand::skin-tone-3:")), Collections.singletonList(":writing_hand::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("hand", "medium skin tone", "write", "writing")), true, false, 1.0, Qualification.fromString("fully-qualified"), "writing hand: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji WRITING_HAND_MEDIUM_DARK_SKIN_TONE = new Emoji("\u270d\ud83c\udffe", "\\u270D\\uD83C\\uDFFE", Collections.unmodifiableList(Arrays.asList(":writing_hand_tone4:", ":writing_hand::skin-tone-4:")), Collections.singletonList(":writing_hand::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("hand", "medium-dark skin tone", "write", "writing")), true, false, 1.0, Qualification.fromString("fully-qualified"), "writing hand: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji WRITING_HAND_DARK_SKIN_TONE = new Emoji("\u270d\ud83c\udfff", "\\u270D\\uD83C\\uDFFF", Collections.unmodifiableList(Arrays.asList(":writing_hand_tone5:", ":writing_hand::skin-tone-5:")), Collections.singletonList(":writing_hand::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("dark skin tone", "hand", "write", "writing")), true, false, 1.0, Qualification.fromString("fully-qualified"), "writing hand: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji NAIL_POLISH = new Emoji("\ud83d\udc85", "\\uD83D\\uDC85", Collections.unmodifiableList(Arrays.asList(":nail_care:", ":nail_polish:")), Collections.singletonList(":nail_care:"), Collections.singletonList(":nail_care:"), Collections.unmodifiableList(Arrays.asList("bored", "care", "cosmetics", "done", "makeup", "manicure", "nail", "polish", "whatever")), false, false, 0.6, Qualification.fromString("fully-qualified"), "nail polish", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji NAIL_POLISH_LIGHT_SKIN_TONE = new Emoji("\ud83d\udc85\ud83c\udffb", "\\uD83D\\uDC85\\uD83C\\uDFFB", Collections.unmodifiableList(Arrays.asList(":nail_care_tone1:", ":nail_care::skin-tone-1:", ":nail_polish::skin-tone-1:")), Collections.singletonList(":nail_care::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bored", "care", "cosmetics", "done", "light skin tone", "makeup", "manicure", "nail", "polish", "whatever")), true, false, 1.0, Qualification.fromString("fully-qualified"), "nail polish: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji NAIL_POLISH_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83d\udc85\ud83c\udffc", "\\uD83D\\uDC85\\uD83C\\uDFFC", Collections.unmodifiableList(Arrays.asList(":nail_care_tone2:", ":nail_care::skin-tone-2:", ":nail_polish::skin-tone-2:")), Collections.singletonList(":nail_care::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bored", "care", "cosmetics", "done", "makeup", "manicure", "medium-light skin tone", "nail", "polish", "whatever")), true, false, 1.0, Qualification.fromString("fully-qualified"), "nail polish: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji NAIL_POLISH_MEDIUM_SKIN_TONE = new Emoji("\ud83d\udc85\ud83c\udffd", "\\uD83D\\uDC85\\uD83C\\uDFFD", Collections.unmodifiableList(Arrays.asList(":nail_care_tone3:", ":nail_care::skin-tone-3:", ":nail_polish::skin-tone-3:")), Collections.singletonList(":nail_care::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bored", "care", "cosmetics", "done", "makeup", "manicure", "medium skin tone", "nail", "polish", "whatever")), true, false, 1.0, Qualification.fromString("fully-qualified"), "nail polish: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji NAIL_POLISH_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83d\udc85\ud83c\udffe", "\\uD83D\\uDC85\\uD83C\\uDFFE", Collections.unmodifiableList(Arrays.asList(":nail_care_tone4:", ":nail_care::skin-tone-4:", ":nail_polish::skin-tone-4:")), Collections.singletonList(":nail_care::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bored", "care", "cosmetics", "done", "makeup", "manicure", "medium-dark skin tone", "nail", "polish", "whatever")), true, false, 1.0, Qualification.fromString("fully-qualified"), "nail polish: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji NAIL_POLISH_DARK_SKIN_TONE = new Emoji("\ud83d\udc85\ud83c\udfff", "\\uD83D\\uDC85\\uD83C\\uDFFF", Collections.unmodifiableList(Arrays.asList(":nail_care_tone5:", ":nail_care::skin-tone-5:", ":nail_polish::skin-tone-5:")), Collections.singletonList(":nail_care::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bored", "care", "cosmetics", "dark skin tone", "done", "makeup", "manicure", "nail", "polish", "whatever")), true, false, 1.0, Qualification.fromString("fully-qualified"), "nail polish: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji SELFIE = new Emoji("\ud83e\udd33", "\\uD83E\\uDD33", Collections.singletonList(":selfie:"), Collections.singletonList(":selfie:"), Collections.singletonList(":selfie:"), Collections.unmodifiableList(Arrays.asList("camera", "phone", "selfie")), false, false, 3.0, Qualification.fromString("fully-qualified"), "selfie", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji SELFIE_LIGHT_SKIN_TONE = new Emoji("\ud83e\udd33\ud83c\udffb", "\\uD83E\\uDD33\\uD83C\\uDFFB", Collections.unmodifiableList(Arrays.asList(":selfie_tone1:", ":selfie::skin-tone-1:")), Collections.singletonList(":selfie::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("camera", "light skin tone", "phone", "selfie")), true, false, 3.0, Qualification.fromString("fully-qualified"), "selfie: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji SELFIE_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83e\udd33\ud83c\udffc", "\\uD83E\\uDD33\\uD83C\\uDFFC", Collections.unmodifiableList(Arrays.asList(":selfie_tone2:", ":selfie::skin-tone-2:")), Collections.singletonList(":selfie::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("camera", "medium-light skin tone", "phone", "selfie")), true, false, 3.0, Qualification.fromString("fully-qualified"), "selfie: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji SELFIE_MEDIUM_SKIN_TONE = new Emoji("\ud83e\udd33\ud83c\udffd", "\\uD83E\\uDD33\\uD83C\\uDFFD", Collections.unmodifiableList(Arrays.asList(":selfie_tone3:", ":selfie::skin-tone-3:")), Collections.singletonList(":selfie::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("camera", "medium skin tone", "phone", "selfie")), true, false, 3.0, Qualification.fromString("fully-qualified"), "selfie: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji SELFIE_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83e\udd33\ud83c\udffe", "\\uD83E\\uDD33\\uD83C\\uDFFE", Collections.unmodifiableList(Arrays.asList(":selfie_tone4:", ":selfie::skin-tone-4:")), Collections.singletonList(":selfie::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("camera", "medium-dark skin tone", "phone", "selfie")), true, false, 3.0, Qualification.fromString("fully-qualified"), "selfie: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
    public static final Emoji SELFIE_DARK_SKIN_TONE = new Emoji("\ud83e\udd33\ud83c\udfff", "\\uD83E\\uDD33\\uD83C\\uDFFF", Collections.unmodifiableList(Arrays.asList(":selfie_tone5:", ":selfie::skin-tone-5:")), Collections.singletonList(":selfie::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("camera", "dark skin tone", "phone", "selfie")), true, false, 3.0, Qualification.fromString("fully-qualified"), "selfie: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.HAND_PROP, false);
}

