/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiAnimalBug {
    public static final Emoji SNAIL = new Emoji("\ud83d\udc0c", "\\uD83D\\uDC0C", Collections.singletonList(":snail:"), Collections.singletonList(":snail:"), Collections.singletonList(":snail:"), Collections.unmodifiableList(Arrays.asList("animal", "escargot", "garden", "nature", "slug", "snail")), false, false, 0.6, Qualification.fromString("fully-qualified"), "snail", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji BUTTERFLY = new Emoji("\ud83e\udd8b", "\\uD83E\\uDD8B", Collections.singletonList(":butterfly:"), Collections.singletonList(":butterfly:"), Collections.singletonList(":butterfly:"), Collections.unmodifiableList(Arrays.asList("butterfly", "insect", "pretty")), false, false, 3.0, Qualification.fromString("fully-qualified"), "butterfly", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji BUG = new Emoji("\ud83d\udc1b", "\\uD83D\\uDC1B", Collections.singletonList(":bug:"), Collections.singletonList(":bug:"), Collections.singletonList(":bug:"), Collections.unmodifiableList(Arrays.asList("animal", "bug", "garden", "insect")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bug", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji ANT = new Emoji("\ud83d\udc1c", "\\uD83D\\uDC1C", Collections.singletonList(":ant:"), Collections.singletonList(":ant:"), Collections.singletonList(":ant:"), Collections.unmodifiableList(Arrays.asList("animal", "ant", "garden", "insect")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ant", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji HONEYBEE = new Emoji("\ud83d\udc1d", "\\uD83D\\uDC1D", Collections.unmodifiableList(Arrays.asList(":bee:", ":honeybee:")), Collections.unmodifiableList(Arrays.asList(":bee:", ":honeybee:")), Collections.unmodifiableList(Arrays.asList(":bee:", ":honeybee:")), Collections.unmodifiableList(Arrays.asList("animal", "bee", "bumblebee", "honey", "honeybee", "insect", "nature", "spring")), false, false, 0.6, Qualification.fromString("fully-qualified"), "honeybee", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji BEETLE = new Emoji("\ud83e\udeb2", "\\uD83E\\uDEB2", Collections.singletonList(":beetle:"), Collections.singletonList(":beetle:"), Collections.singletonList(":beetle:"), Collections.unmodifiableList(Arrays.asList("animal", "beetle", "bug", "insect")), false, false, 13.0, Qualification.fromString("fully-qualified"), "beetle", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji LADY_BEETLE = new Emoji("\ud83d\udc1e", "\\uD83D\\uDC1E", Collections.singletonList(":lady_beetle:"), Collections.unmodifiableList(Arrays.asList(":ladybug:", ":lady_beetle:")), Collections.singletonList(":lady_beetle:"), Collections.unmodifiableList(Arrays.asList("animal", "beetle", "garden", "insect", "lady", "ladybird", "ladybug", "nature")), false, false, 0.6, Qualification.fromString("fully-qualified"), "lady beetle", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji CRICKET = new Emoji("\ud83e\udd97", "\\uD83E\\uDD97", Collections.singletonList(":cricket:"), Collections.singletonList(":cricket:"), Collections.singletonList(":cricket:"), Collections.unmodifiableList(Arrays.asList("animal", "bug", "cricket", "grasshopper", "insect", "Orthoptera")), false, false, 5.0, Qualification.fromString("fully-qualified"), "cricket", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji COCKROACH = new Emoji("\ud83e\udeb3", "\\uD83E\\uDEB3", Collections.singletonList(":cockroach:"), Collections.singletonList(":cockroach:"), Collections.singletonList(":cockroach:"), Collections.unmodifiableList(Arrays.asList("animal", "cockroach", "insect", "pest", "roach")), false, false, 13.0, Qualification.fromString("fully-qualified"), "cockroach", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji SPIDER = new Emoji("\ud83d\udd77\ufe0f", "\\uD83D\\uDD77\\uFE0F", Collections.singletonList(":spider:"), Collections.singletonList(":spider:"), Collections.singletonList(":spider:"), Collections.unmodifiableList(Arrays.asList("animal", "insect", "spider")), false, false, 0.7, Qualification.fromString("fully-qualified"), "spider", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji SPIDER_UNQUALIFIED = new Emoji("\ud83d\udd77", "\\uD83D\\uDD77", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("animal", "insect", "spider")), false, false, 0.7, Qualification.fromString("unqualified"), "spider", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, true);
    public static final Emoji SPIDER_WEB = new Emoji("\ud83d\udd78\ufe0f", "\\uD83D\\uDD78\\uFE0F", Collections.singletonList(":spider_web:"), Collections.singletonList(":spider_web:"), Collections.singletonList(":spider_web:"), Collections.unmodifiableList(Arrays.asList("spider", "web")), false, false, 0.7, Qualification.fromString("fully-qualified"), "spider web", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji SPIDER_WEB_UNQUALIFIED = new Emoji("\ud83d\udd78", "\\uD83D\\uDD78", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("spider", "web")), false, false, 0.7, Qualification.fromString("unqualified"), "spider web", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, true);
    public static final Emoji SCORPION = new Emoji("\ud83e\udd82", "\\uD83E\\uDD82", Collections.singletonList(":scorpion:"), Collections.singletonList(":scorpion:"), Collections.singletonList(":scorpion:"), Collections.unmodifiableList(Arrays.asList("Scorpio", "scorpion", "Scorpius", "zodiac")), false, false, 1.0, Qualification.fromString("fully-qualified"), "scorpion", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji MOSQUITO = new Emoji("\ud83e\udd9f", "\\uD83E\\uDD9F", Collections.singletonList(":mosquito:"), Collections.singletonList(":mosquito:"), Collections.singletonList(":mosquito:"), Collections.unmodifiableList(Arrays.asList("bite", "disease", "fever", "insect", "malaria", "mosquito", "pest", "virus")), false, false, 11.0, Qualification.fromString("fully-qualified"), "mosquito", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji FLY = new Emoji("\ud83e\udeb0", "\\uD83E\\uDEB0", Collections.singletonList(":fly:"), Collections.singletonList(":fly:"), Collections.singletonList(":fly:"), Collections.unmodifiableList(Arrays.asList("animal", "disease", "fly", "insect", "maggot", "pest", "rotting")), false, false, 13.0, Qualification.fromString("fully-qualified"), "fly", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji WORM = new Emoji("\ud83e\udeb1", "\\uD83E\\uDEB1", Collections.singletonList(":worm:"), Collections.singletonList(":worm:"), Collections.singletonList(":worm:"), Collections.unmodifiableList(Arrays.asList("animal", "annelid", "earthworm", "parasite", "worm")), false, false, 13.0, Qualification.fromString("fully-qualified"), "worm", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
    public static final Emoji MICROBE = new Emoji("\ud83e\udda0", "\\uD83E\\uDDA0", Collections.singletonList(":microbe:"), Collections.singletonList(":microbe:"), Collections.singletonList(":microbe:"), Collections.unmodifiableList(Arrays.asList("amoeba", "bacteria", "microbe", "science", "virus")), false, false, 11.0, Qualification.fromString("fully-qualified"), "microbe", EmojiGroup.ANIMALS_AND_NATURE, EmojiSubGroup.ANIMAL_BUG, false);
}

