/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiFaceNegative {
    public static final Emoji FACE_WITH_STEAM_FROM_NOSE = new Emoji("\ud83d\ude24", "\\uD83D\\uDE24", Collections.singletonList(":triumph:"), Collections.singletonList(":triumph:"), Collections.singletonList(":triumph:"), Collections.unmodifiableList(Arrays.asList("anger", "angry", "face", "feels", "fume", "fuming", "furious", "fury", "mad", "nose", "steam", "triumph", "unhappy", "won")), false, false, 0.6, Qualification.fromString("fully-qualified"), "face with steam from nose", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEGATIVE, false);
    public static final Emoji ENRAGED_FACE = new Emoji("\ud83d\ude21", "\\uD83D\\uDE21", Collections.unmodifiableList(Arrays.asList(":rage:", ":pouting_face:", ":@", ":-@", "=@", "=-@")), Collections.singletonList(":rage:"), Collections.unmodifiableList(Arrays.asList(":pout:", ":rage:")), Collections.unmodifiableList(Arrays.asList("anger", "angry", "enraged", "face", "feels", "mad", "maddening", "pouting", "rage", "red", "shade", "unhappy", "upset")), false, false, 0.6, Qualification.fromString("fully-qualified"), "enraged face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEGATIVE, false);
    public static final Emoji ANGRY_FACE = new Emoji("\ud83d\ude20", "\\uD83D\\uDE20", Collections.unmodifiableList(Arrays.asList(":angry:", ":angry_face:", ">:(", ">:-(", ">=(", ">=-(")), Collections.singletonList(":angry:"), Collections.singletonList(":angry:"), Collections.unmodifiableList(Arrays.asList("anger", "angry", "blame", "face", "feels", "frustrated", "mad", "maddening", "rage", "shade", "unhappy", "upset")), false, false, 0.6, Qualification.fromString("fully-qualified"), "angry face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEGATIVE, false);
    public static final Emoji FACE_WITH_SYMBOLS_ON_MOUTH = new Emoji("\ud83e\udd2c", "\\uD83E\\uDD2C", Collections.singletonList(":face_with_symbols_over_mouth:"), Collections.unmodifiableList(Arrays.asList(":face_with_symbols_on_mouth:", ":serious_face_with_symbols_covering_mouth:")), Collections.singletonList(":cursing_face:"), Collections.unmodifiableList(Arrays.asList("censor", "cursing", "cussing", "face", "mad", "mouth", "pissed", "swearing", "symbols")), false, false, 5.0, Qualification.fromString("fully-qualified"), "face with symbols on mouth", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEGATIVE, false);
    public static final Emoji SMILING_FACE_WITH_HORNS = new Emoji("\ud83d\ude08", "\\uD83D\\uDE08", Collections.unmodifiableList(Arrays.asList(":smiling_imp:", "]:)", "]:-)", "]=)", "]=-)")), Collections.singletonList(":smiling_imp:"), Collections.singletonList(":smiling_imp:"), Collections.unmodifiableList(Arrays.asList("demon", "devil", "evil", "face", "fairy", "fairytale", "fantasy", "horns", "purple", "shade", "smile", "smiling", "tale")), false, false, 1.0, Qualification.fromString("fully-qualified"), "smiling face with horns", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEGATIVE, false);
    public static final Emoji ANGRY_FACE_WITH_HORNS = new Emoji("\ud83d\udc7f", "\\uD83D\\uDC7F", Collections.unmodifiableList(Arrays.asList(":imp:", "]:(", "]:-(", "]=(", "]=-(")), Collections.singletonList(":imp:"), Collections.singletonList(":imp:"), Collections.unmodifiableList(Arrays.asList("angry", "demon", "devil", "evil", "face", "fairy", "fairytale", "fantasy", "horns", "imp", "mischievous", "purple", "shade", "tale")), false, false, 0.6, Qualification.fromString("fully-qualified"), "angry face with horns", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEGATIVE, false);
    public static final Emoji SKULL = new Emoji("\ud83d\udc80", "\\uD83D\\uDC80", Collections.unmodifiableList(Arrays.asList(":skull:", ":skeleton:")), Collections.singletonList(":skull:"), Collections.singletonList(":skull:"), Collections.unmodifiableList(Arrays.asList("body", "dead", "death", "face", "fairy", "fairytale", "i\u2019m", "lmao", "monster", "skull", "tale", "yolo")), false, false, 0.6, Qualification.fromString("fully-qualified"), "skull", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEGATIVE, false);
    public static final Emoji SKULL_AND_CROSSBONES = new Emoji("\u2620\ufe0f", "\\u2620\\uFE0F", Collections.unmodifiableList(Arrays.asList(":skull_crossbones:", ":skull_and_crossbones:")), Collections.singletonList(":skull_and_crossbones:"), Collections.singletonList(":skull_and_crossbones:"), Collections.unmodifiableList(Arrays.asList("bone", "crossbones", "dead", "death", "face", "monster", "skull")), false, false, 1.0, Qualification.fromString("fully-qualified"), "skull and crossbones", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEGATIVE, false);
    public static final Emoji SKULL_AND_CROSSBONES_UNQUALIFIED = new Emoji("\u2620", "\\u2620", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bone", "crossbones", "dead", "death", "face", "monster", "skull")), false, false, 1.0, Qualification.fromString("unqualified"), "skull and crossbones", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_NEGATIVE, true);
}

