/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiFaceConcerned {
    public static final Emoji CONFUSED_FACE = new Emoji("\ud83d\ude15", "\\uD83D\\uDE15", Collections.unmodifiableList(Arrays.asList(":confused:", ":confused_face:", ":-\\", ":-/", "=-\\", "=-/")), Collections.singletonList(":confused:"), Collections.singletonList(":confused:"), Collections.unmodifiableList(Arrays.asList("befuddled", "confused", "confusing", "dunno", "face", "frown", "hm", "meh", "not", "sad", "sorry", "sure")), false, false, 1.0, Qualification.fromString("fully-qualified"), "confused face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji FACE_WITH_DIAGONAL_MOUTH = new Emoji("\ud83e\udee4", "\\uD83E\\uDEE4", Collections.singletonList(":face_with_diagonal_mouth:"), Collections.singletonList(":face_with_diagonal_mouth:"), Collections.singletonList(":face_with_diagonal_mouth:"), Collections.unmodifiableList(Arrays.asList("confused", "confusion", "diagonal", "disappointed", "doubt", "doubtful", "face", "frustrated", "frustration", "meh", "mouth", "skeptical", "unsure", "whatever", "wtv")), false, false, 14.0, Qualification.fromString("fully-qualified"), "face with diagonal mouth", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji WORRIED_FACE = new Emoji("\ud83d\ude1f", "\\uD83D\\uDE1F", Collections.unmodifiableList(Arrays.asList(":worried:", ":worried_face:")), Collections.singletonList(":worried:"), Collections.singletonList(":worried:"), Collections.unmodifiableList(Arrays.asList("anxious", "butterflies", "face", "nerves", "nervous", "sad", "stress", "stressed", "surprised", "worried", "worry")), false, false, 1.0, Qualification.fromString("fully-qualified"), "worried face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji SLIGHTLY_FROWNING_FACE = new Emoji("\ud83d\ude41", "\\uD83D\\uDE41", Collections.unmodifiableList(Arrays.asList(":slight_frown:", ":slightly_frowning_face:")), Collections.singletonList(":slightly_frowning_face:"), Collections.singletonList(":slightly_frowning_face:"), Collections.unmodifiableList(Arrays.asList("face", "frown", "frowning", "sad", "slightly")), false, false, 1.0, Qualification.fromString("fully-qualified"), "slightly frowning face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji FROWNING_FACE = new Emoji("\u2639\ufe0f", "\\u2639\\uFE0F", Collections.unmodifiableList(Arrays.asList(":frowning2:", ":white_frowning_face:", ":frowning_face:")), Collections.singletonList(":white_frowning_face:"), Collections.singletonList(":frowning_face:"), Collections.unmodifiableList(Arrays.asList("face", "frown", "frowning", "sad")), false, false, 0.7, Qualification.fromString("fully-qualified"), "frowning face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji FROWNING_FACE_UNQUALIFIED = new Emoji("\u2639", "\\u2639", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("face", "frown", "frowning", "sad")), false, false, 0.7, Qualification.fromString("unqualified"), "frowning face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, true);
    public static final Emoji FACE_WITH_OPEN_MOUTH = new Emoji("\ud83d\ude2e", "\\uD83D\\uDE2E", Collections.unmodifiableList(Arrays.asList(":open_mouth:", ":o", ":-o", ":O", ":-O", "=o", "=-o", "=O", "=-O")), Collections.singletonList(":open_mouth:"), Collections.singletonList(":open_mouth:"), Collections.unmodifiableList(Arrays.asList("believe", "face", "forgot", "mouth", "omg", "open", "shocked", "surprised", "sympathy", "unbelievable", "unreal", "whoa", "wow", "you")), false, false, 1.0, Qualification.fromString("fully-qualified"), "face with open mouth", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji HUSHED_FACE = new Emoji("\ud83d\ude2f", "\\uD83D\\uDE2F", Collections.unmodifiableList(Arrays.asList(":hushed:", ":hushed_face:")), Collections.singletonList(":hushed:"), Collections.singletonList(":hushed:"), Collections.unmodifiableList(Arrays.asList("epic", "face", "hushed", "omg", "stunned", "surprised", "whoa", "woah")), false, false, 1.0, Qualification.fromString("fully-qualified"), "hushed face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji ASTONISHED_FACE = new Emoji("\ud83d\ude32", "\\uD83D\\uDE32", Collections.singletonList(":astonished:"), Collections.singletonList(":astonished:"), Collections.singletonList(":astonished:"), Collections.unmodifiableList(Arrays.asList("astonished", "cost", "face", "no", "omg", "shocked", "totally", "way")), false, false, 0.6, Qualification.fromString("fully-qualified"), "astonished face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji FLUSHED_FACE = new Emoji("\ud83d\ude33", "\\uD83D\\uDE33", Collections.unmodifiableList(Arrays.asList(":flushed:", ":flushed_face:")), Collections.singletonList(":flushed:"), Collections.singletonList(":flushed:"), Collections.unmodifiableList(Arrays.asList("amazed", "awkward", "crazy", "dazed", "dead", "disbelief", "embarrassed", "face", "flushed", "geez", "heat", "hot", "impressed", "jeez", "what", "wow")), false, false, 0.6, Qualification.fromString("fully-qualified"), "flushed face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji PLEADING_FACE = new Emoji("\ud83e\udd7a", "\\uD83E\\uDD7A", Collections.singletonList(":pleading_face:"), Collections.singletonList(":pleading_face:"), Collections.singletonList(":pleading_face:"), Collections.unmodifiableList(Arrays.asList("begging", "big", "eyes", "face", "mercy", "not", "pleading", "please", "pretty", "puppy", "sad", "why")), false, false, 11.0, Qualification.fromString("fully-qualified"), "pleading face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji FACE_HOLDING_BACK_TEARS = new Emoji("\ud83e\udd79", "\\uD83E\\uDD79", Collections.singletonList(":face_holding_back_tears:"), Collections.singletonList(":face_holding_back_tears:"), Collections.singletonList(":face_holding_back_tears:"), Collections.unmodifiableList(Arrays.asList("admiration", "aww", "back", "cry", "embarrassed", "face", "feelings", "grateful", "gratitude", "holding", "joy", "please", "proud", "resist", "sad", "tears")), false, false, 14.0, Qualification.fromString("fully-qualified"), "face holding back tears", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji FROWNING_FACE_WITH_OPEN_MOUTH = new Emoji("\ud83d\ude26", "\\uD83D\\uDE26", Collections.unmodifiableList(Arrays.asList(":frowning:", ":(", ":-(", "=(", "=-(")), Collections.singletonList(":frowning:"), Collections.singletonList(":frowning:"), Collections.unmodifiableList(Arrays.asList("caught", "face", "frown", "frowning", "guard", "mouth", "open", "scared", "scary", "surprise", "what", "wow")), false, false, 1.0, Qualification.fromString("fully-qualified"), "frowning face with open mouth", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji ANGUISHED_FACE = new Emoji("\ud83d\ude27", "\\uD83D\\uDE27", Collections.singletonList(":anguished:"), Collections.singletonList(":anguished:"), Collections.singletonList(":anguished:"), Collections.unmodifiableList(Arrays.asList("anguished", "face", "forgot", "scared", "scary", "stressed", "surprise", "unhappy", "what", "wow")), false, false, 1.0, Qualification.fromString("fully-qualified"), "anguished face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji FEARFUL_FACE = new Emoji("\ud83d\ude28", "\\uD83D\\uDE28", Collections.unmodifiableList(Arrays.asList(":fearful:", ":fearful_face:")), Collections.singletonList(":fearful:"), Collections.singletonList(":fearful:"), Collections.unmodifiableList(Arrays.asList("afraid", "anxious", "blame", "face", "fear", "fearful", "scared", "worried")), false, false, 0.6, Qualification.fromString("fully-qualified"), "fearful face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji ANXIOUS_FACE_WITH_SWEAT = new Emoji("\ud83d\ude30", "\\uD83D\\uDE30", Collections.singletonList(":cold_sweat:"), Collections.singletonList(":cold_sweat:"), Collections.singletonList(":cold_sweat:"), Collections.unmodifiableList(Arrays.asList("anxious", "blue", "cold", "eek", "face", "mouth", "nervous", "open", "rushed", "scared", "sweat", "yikes")), false, false, 0.6, Qualification.fromString("fully-qualified"), "anxious face with sweat", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji SAD_BUT_RELIEVED_FACE = new Emoji("\ud83d\ude25", "\\uD83D\\uDE25", Collections.singletonList(":disappointed_relieved:"), Collections.singletonList(":disappointed_relieved:"), Collections.singletonList(":disappointed_relieved:"), Collections.unmodifiableList(Arrays.asList("anxious", "call", "close", "complicated", "disappointed", "face", "not", "relieved", "sad", "sweat", "time", "whew")), false, false, 0.6, Qualification.fromString("fully-qualified"), "sad but relieved face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji CRYING_FACE = new Emoji("\ud83d\ude22", "\\uD83D\\uDE22", Collections.unmodifiableList(Arrays.asList(":cry:", ":crying_face:", ":'(", ":'-(", ":,(", ":,-(", "='(", "='-(", "=,(", "=,-(")), Collections.singletonList(":cry:"), Collections.singletonList(":cry:"), Collections.unmodifiableList(Arrays.asList("awful", "cry", "crying", "face", "feels", "miss", "sad", "tear", "triste", "unhappy")), false, false, 0.6, Qualification.fromString("fully-qualified"), "crying face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji LOUDLY_CRYING_FACE = new Emoji("\ud83d\ude2d", "\\uD83D\\uDE2D", Collections.unmodifiableList(Arrays.asList(":sob:", ":,'(", ":,'-(", ";(", ";-(", "=,'(", "=,'-(")), Collections.singletonList(":sob:"), Collections.singletonList(":sob:"), Collections.unmodifiableList(Arrays.asList("bawling", "cry", "crying", "face", "loudly", "sad", "sob", "tear", "tears", "unhappy")), false, false, 0.6, Qualification.fromString("fully-qualified"), "loudly crying face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji FACE_SCREAMING_IN_FEAR = new Emoji("\ud83d\ude31", "\\uD83D\\uDE31", Collections.singletonList(":scream:"), Collections.singletonList(":scream:"), Collections.singletonList(":scream:"), Collections.unmodifiableList(Arrays.asList("epic", "face", "fear", "fearful", "munch", "scared", "scream", "screamer", "screaming", "shocked", "surprised", "woah")), false, false, 0.6, Qualification.fromString("fully-qualified"), "face screaming in fear", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji CONFOUNDED_FACE = new Emoji("\ud83d\ude16", "\\uD83D\\uDE16", Collections.singletonList(":confounded:"), Collections.singletonList(":confounded:"), Collections.singletonList(":confounded:"), Collections.unmodifiableList(Arrays.asList("annoyed", "confounded", "confused", "cringe", "distraught", "face", "feels", "frustrated", "mad", "sad")), false, false, 0.6, Qualification.fromString("fully-qualified"), "confounded face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji PERSEVERING_FACE = new Emoji("\ud83d\ude23", "\\uD83D\\uDE23", Collections.singletonList(":persevere:"), Collections.singletonList(":persevere:"), Collections.singletonList(":persevere:"), Collections.unmodifiableList(Arrays.asList("concentrate", "concentration", "face", "focus", "headache", "persevere", "persevering")), false, false, 0.6, Qualification.fromString("fully-qualified"), "persevering face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji DISAPPOINTED_FACE = new Emoji("\ud83d\ude1e", "\\uD83D\\uDE1E", Collections.singletonList(":disappointed:"), Collections.singletonList(":disappointed:"), Collections.singletonList(":disappointed:"), Collections.unmodifiableList(Arrays.asList("awful", "blame", "dejected", "disappointed", "face", "fail", "losing", "sad", "unhappy")), false, false, 0.6, Qualification.fromString("fully-qualified"), "disappointed face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji DOWNCAST_FACE_WITH_SWEAT = new Emoji("\ud83d\ude13", "\\uD83D\\uDE13", Collections.unmodifiableList(Arrays.asList(":sweat:", ",:(", ",:-(", ",=(", ",=-(")), Collections.singletonList(":sweat:"), Collections.singletonList(":sweat:"), Collections.unmodifiableList(Arrays.asList("close", "cold", "downcast", "face", "feels", "headache", "nervous", "sad", "scared", "sweat", "yikes")), false, false, 0.6, Qualification.fromString("fully-qualified"), "downcast face with sweat", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji WEARY_FACE = new Emoji("\ud83d\ude29", "\\uD83D\\uDE29", Collections.unmodifiableList(Arrays.asList(":weary:", ":weary_face:")), Collections.singletonList(":weary:"), Collections.singletonList(":weary:"), Collections.unmodifiableList(Arrays.asList("crying", "face", "fail", "feels", "hungry", "mad", "nooo", "sad", "sleepy", "tired", "unhappy", "weary")), false, false, 0.6, Qualification.fromString("fully-qualified"), "weary face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji TIRED_FACE = new Emoji("\ud83d\ude2b", "\\uD83D\\uDE2B", Collections.singletonList(":tired_face:"), Collections.singletonList(":tired_face:"), Collections.singletonList(":tired_face:"), Collections.unmodifiableList(Arrays.asList("cost", "face", "feels", "nap", "sad", "sneeze", "tired")), false, false, 0.6, Qualification.fromString("fully-qualified"), "tired face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
    public static final Emoji YAWNING_FACE = new Emoji("\ud83e\udd71", "\\uD83E\\uDD71", Collections.singletonList(":yawning_face:"), Collections.singletonList(":yawning_face:"), Collections.singletonList(":yawning_face:"), Collections.unmodifiableList(Arrays.asList("bedtime", "bored", "face", "goodnight", "nap", "night", "sleep", "sleepy", "tired", "whatever", "yawn", "yawning", "zzz")), false, false, 12.0, Qualification.fromString("fully-qualified"), "yawning face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_CONCERNED, false);
}

