/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiPersonSymbol {
    public static final Emoji SPEAKING_HEAD = new Emoji("\ud83d\udde3\ufe0f", "\\uD83D\\uDDE3\\uFE0F", Collections.unmodifiableList(Arrays.asList(":speaking_head:", ":speaking_head_in_silhouette:")), Collections.singletonList(":speaking_head_in_silhouette:"), Collections.singletonList(":speaking_head:"), Collections.unmodifiableList(Arrays.asList("face", "head", "silhouette", "speak", "speaking")), false, false, 0.7, Qualification.fromString("fully-qualified"), "speaking head", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_SYMBOL, false);
    public static final Emoji SPEAKING_HEAD_UNQUALIFIED = new Emoji("\ud83d\udde3", "\\uD83D\\uDDE3", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("face", "head", "silhouette", "speak", "speaking")), false, false, 0.7, Qualification.fromString("unqualified"), "speaking head", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_SYMBOL, true);
    public static final Emoji BUST_IN_SILHOUETTE = new Emoji("\ud83d\udc64", "\\uD83D\\uDC64", Collections.singletonList(":bust_in_silhouette:"), Collections.singletonList(":bust_in_silhouette:"), Collections.singletonList(":bust_in_silhouette:"), Collections.unmodifiableList(Arrays.asList("bust", "mysterious", "shadow", "silhouette")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bust in silhouette", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_SYMBOL, false);
    public static final Emoji BUSTS_IN_SILHOUETTE = new Emoji("\ud83d\udc65", "\\uD83D\\uDC65", Collections.singletonList(":busts_in_silhouette:"), Collections.singletonList(":busts_in_silhouette:"), Collections.singletonList(":busts_in_silhouette:"), Collections.unmodifiableList(Arrays.asList("bff", "bust", "busts", "everyone", "friend", "friends", "people", "silhouette")), false, false, 1.0, Qualification.fromString("fully-qualified"), "busts in silhouette", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_SYMBOL, false);
    public static final Emoji PEOPLE_HUGGING = new Emoji("\ud83e\udec2", "\\uD83E\\uDEC2", Collections.singletonList(":people_hugging:"), Collections.singletonList(":people_hugging:"), Collections.singletonList(":people_hugging:"), Collections.unmodifiableList(Arrays.asList("comfort", "embrace", "farewell", "friendship", "goodbye", "hello", "hug", "hugging", "love", "people", "thanks")), false, false, 13.0, Qualification.fromString("fully-qualified"), "people hugging", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_SYMBOL, false);
    public static final Emoji FAMILY = new Emoji("\ud83d\udc6a", "\\uD83D\\uDC6A", Collections.singletonList(":family:"), Collections.singletonList(":family:"), Collections.singletonList(":family:"), Collections.unmodifiableList(Arrays.asList("child", "family")), false, false, 0.6, Qualification.fromString("fully-qualified"), "family", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_SYMBOL, true);
    public static final Emoji FAMILY_ADULT_ADULT_CHILD = new Emoji("\ud83e\uddd1\u200d\ud83e\uddd1\u200d\ud83e\uddd2", "\\uD83E\\uDDD1\\u200D\\uD83E\\uDDD1\\u200D\\uD83E\\uDDD2", Collections.singletonList(":family_adult_adult_child:"), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("adult", "child", "family")), false, false, 15.1, Qualification.fromString("fully-qualified"), "family: adult, adult, child", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_SYMBOL, false);
    public static final Emoji FAMILY_ADULT_ADULT_CHILD_CHILD = new Emoji("\ud83e\uddd1\u200d\ud83e\uddd1\u200d\ud83e\uddd2\u200d\ud83e\uddd2", "\\uD83E\\uDDD1\\u200D\\uD83E\\uDDD1\\u200D\\uD83E\\uDDD2\\u200D\\uD83E\\uDDD2", Collections.singletonList(":family_adult_adult_child_child:"), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("adult", "child", "family")), false, false, 15.1, Qualification.fromString("fully-qualified"), "family: adult, adult, child, child", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_SYMBOL, false);
    public static final Emoji FAMILY_ADULT_CHILD = new Emoji("\ud83e\uddd1\u200d\ud83e\uddd2", "\\uD83E\\uDDD1\\u200D\\uD83E\\uDDD2", Collections.singletonList(":family_adult_child:"), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("adult", "child", "family")), false, false, 15.1, Qualification.fromString("fully-qualified"), "family: adult, child", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_SYMBOL, false);
    public static final Emoji FAMILY_ADULT_CHILD_CHILD = new Emoji("\ud83e\uddd1\u200d\ud83e\uddd2\u200d\ud83e\uddd2", "\\uD83E\\uDDD1\\u200D\\uD83E\\uDDD2\\u200D\\uD83E\\uDDD2", Collections.singletonList(":family_adult_child_child:"), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("adult", "child", "family")), false, false, 15.1, Qualification.fromString("fully-qualified"), "family: adult, child, child", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_SYMBOL, false);
    public static final Emoji FOOTPRINTS = new Emoji("\ud83d\udc63", "\\uD83D\\uDC63", Collections.singletonList(":footprints:"), Collections.singletonList(":footprints:"), Collections.singletonList(":footprints:"), Collections.unmodifiableList(Arrays.asList("barefoot", "clothing", "footprint", "footprints", "omw", "print", "walk")), false, false, 0.6, Qualification.fromString("fully-qualified"), "footprints", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_SYMBOL, false);
    public static final Emoji FINGERPRINT = new Emoji("\ud83e\udec6", "\\uD83E\\uDEC6", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("clue", "crime", "detective", "fingerprint", "forensics", "identity", "mystery", "print", "safety", "trace")), false, false, 16.0, Qualification.fromString("fully-qualified"), "fingerprint", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_SYMBOL, false);
}

