/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiFaceSmiling {
    public static final Emoji GRINNING_FACE = new Emoji("\ud83d\ude00", "\\uD83D\\uDE00", Collections.unmodifiableList(Arrays.asList(":grinning:", ":grinning_face:")), Collections.singletonList(":grinning:"), Collections.singletonList(":grinning:"), Collections.unmodifiableList(Arrays.asList("cheerful", "cheery", "face", "grin", "grinning", "happy", "laugh", "nice", "smile", "smiling", "teeth")), false, false, 1.0, Qualification.fromString("fully-qualified"), "grinning face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
    public static final Emoji GRINNING_FACE_WITH_BIG_EYES = new Emoji("\ud83d\ude03", "\\uD83D\\uDE03", Collections.singletonList(":smiley:"), Collections.singletonList(":smiley:"), Collections.singletonList(":smiley:"), Collections.unmodifiableList(Arrays.asList("awesome", "big", "eyes", "face", "grin", "grinning", "happy", "mouth", "open", "smile", "smiling", "teeth", "yay")), false, false, 0.6, Qualification.fromString("fully-qualified"), "grinning face with big eyes", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
    public static final Emoji GRINNING_FACE_WITH_SMILING_EYES = new Emoji("\ud83d\ude04", "\\uD83D\\uDE04", Collections.unmodifiableList(Arrays.asList(":smile:", ":D", ":-D", "=D", "=-D")), Collections.singletonList(":smile:"), Collections.singletonList(":smile:"), Collections.unmodifiableList(Arrays.asList("eye", "eyes", "face", "grin", "grinning", "happy", "laugh", "lol", "mouth", "open", "smile", "smiling")), false, false, 0.6, Qualification.fromString("fully-qualified"), "grinning face with smiling eyes", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
    public static final Emoji BEAMING_FACE_WITH_SMILING_EYES = new Emoji("\ud83d\ude01", "\\uD83D\\uDE01", Collections.singletonList(":grin:"), Collections.singletonList(":grin:"), Collections.singletonList(":grin:"), Collections.unmodifiableList(Arrays.asList("beaming", "eye", "eyes", "face", "grin", "grinning", "happy", "nice", "smile", "smiling", "teeth")), false, false, 0.6, Qualification.fromString("fully-qualified"), "beaming face with smiling eyes", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
    public static final Emoji GRINNING_SQUINTING_FACE = new Emoji("\ud83d\ude06", "\\uD83D\\uDE06", Collections.unmodifiableList(Arrays.asList(":laughing:", ":satisfied:", "x-)", "X-)")), Collections.unmodifiableList(Arrays.asList(":laughing:", ":satisfied:")), Collections.unmodifiableList(Arrays.asList(":laughing:", ":satisfied:")), Collections.unmodifiableList(Arrays.asList("closed", "eyes", "face", "grinning", "haha", "hahaha", "happy", "laugh", "lol", "mouth", "open", "rofl", "smile", "smiling", "squinting")), false, false, 0.6, Qualification.fromString("fully-qualified"), "grinning squinting face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
    public static final Emoji GRINNING_FACE_WITH_SWEAT = new Emoji("\ud83d\ude05", "\\uD83D\\uDE05", Collections.unmodifiableList(Arrays.asList(":sweat_smile:", ",:)", ",:-)", ",=)", ",=-)")), Collections.singletonList(":sweat_smile:"), Collections.singletonList(":sweat_smile:"), Collections.unmodifiableList(Arrays.asList("cold", "dejected", "excited", "face", "grinning", "mouth", "nervous", "open", "smile", "smiling", "stress", "stressed", "sweat")), false, false, 0.6, Qualification.fromString("fully-qualified"), "grinning face with sweat", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
    public static final Emoji ROLLING_ON_THE_FLOOR_LAUGHING = new Emoji("\ud83e\udd23", "\\uD83E\\uDD23", Collections.unmodifiableList(Arrays.asList(":rofl:", ":rolling_on_the_floor_laughing:")), Collections.singletonList(":rolling_on_the_floor_laughing:"), Collections.singletonList(":rofl:"), Collections.unmodifiableList(Arrays.asList("crying", "face", "floor", "funny", "haha", "happy", "hehe", "hilarious", "joy", "laugh", "lmao", "lol", "rofl", "roflmao", "rolling", "tear")), false, false, 3.0, Qualification.fromString("fully-qualified"), "rolling on the floor laughing", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
    public static final Emoji FACE_WITH_TEARS_OF_JOY = new Emoji("\ud83d\ude02", "\\uD83D\\uDE02", Collections.unmodifiableList(Arrays.asList(":joy:", ":'D", ":'-D", ":,D", ":,-D", "='D", "='-D", "=,D", "=,-D")), Collections.singletonList(":joy:"), Collections.singletonList(":joy:"), Collections.unmodifiableList(Arrays.asList("crying", "face", "feels", "funny", "haha", "happy", "hehe", "hilarious", "joy", "laugh", "lmao", "lol", "rofl", "roflmao", "tear")), false, false, 0.6, Qualification.fromString("fully-qualified"), "face with tears of joy", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
    public static final Emoji SLIGHTLY_SMILING_FACE = new Emoji("\ud83d\ude42", "\\uD83D\\uDE42", Collections.unmodifiableList(Arrays.asList(":slight_smile:", ":slightly_smiling_face:", ":)", ":-)", "=)", "=-)")), Collections.singletonList(":slightly_smiling_face:"), Collections.singletonList(":slightly_smiling_face:"), Collections.unmodifiableList(Arrays.asList("face", "happy", "slightly", "smile", "smiling")), false, false, 1.0, Qualification.fromString("fully-qualified"), "slightly smiling face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
    public static final Emoji UPSIDE_DOWN_FACE = new Emoji("\ud83d\ude43", "\\uD83D\\uDE43", Collections.unmodifiableList(Arrays.asList(":upside_down:", ":upside_down_face:")), Collections.singletonList(":upside_down_face:"), Collections.singletonList(":upside_down_face:"), Collections.unmodifiableList(Arrays.asList("face", "hehe", "smile", "upside-down")), false, false, 1.0, Qualification.fromString("fully-qualified"), "upside-down face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
    public static final Emoji MELTING_FACE = new Emoji("\ud83e\udee0", "\\uD83E\\uDEE0", Collections.singletonList(":melting_face:"), Collections.singletonList(":melting_face:"), Collections.singletonList(":melting_face:"), Collections.unmodifiableList(Arrays.asList("disappear", "dissolve", "embarrassed", "face", "haha", "heat", "hot", "liquid", "lol", "melt", "melting", "sarcasm", "sarcastic")), false, false, 14.0, Qualification.fromString("fully-qualified"), "melting face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
    public static final Emoji WINKING_FACE = new Emoji("\ud83d\ude09", "\\uD83D\\uDE09", Collections.unmodifiableList(Arrays.asList(":wink:", ":winking_face:", ";)", ";-)")), Collections.singletonList(":wink:"), Collections.singletonList(":wink:"), Collections.unmodifiableList(Arrays.asList("face", "flirt", "heartbreaker", "sexy", "slide", "tease", "wink", "winking", "winks")), false, false, 0.6, Qualification.fromString("fully-qualified"), "winking face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
    public static final Emoji SMILING_FACE_WITH_SMILING_EYES = new Emoji("\ud83d\ude0a", "\\uD83D\\uDE0A", Collections.unmodifiableList(Arrays.asList(":blush:", ":\")", ":-\")", "=\")", "=-\")")), Collections.singletonList(":blush:"), Collections.singletonList(":blush:"), Collections.unmodifiableList(Arrays.asList("blush", "eye", "eyes", "face", "glad", "satisfied", "smile", "smiling")), false, false, 0.6, Qualification.fromString("fully-qualified"), "smiling face with smiling eyes", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
    public static final Emoji SMILING_FACE_WITH_HALO = new Emoji("\ud83d\ude07", "\\uD83D\\uDE07", Collections.unmodifiableList(Arrays.asList(":innocent:", "o:)", "O:)", "o:-)", "O:-)", "0:)", "0:-)", "o=)", "O=)", "o=-)", "O=-)", "0=)", "0=-)")), Collections.singletonList(":innocent:"), Collections.singletonList(":innocent:"), Collections.unmodifiableList(Arrays.asList("angel", "angelic", "angels", "blessed", "face", "fairy", "fairytale", "fantasy", "halo", "happy", "innocent", "peaceful", "smile", "smiling", "spirit", "tale")), false, false, 1.0, Qualification.fromString("fully-qualified"), "smiling face with halo", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_SMILING, false);
}

