/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiGame {
    public static final Emoji BULLSEYE = new Emoji("\ud83c\udfaf", "\\uD83C\\uDFAF", Collections.unmodifiableList(Arrays.asList(":dart:", ":direct_hit:")), Collections.singletonList(":dart:"), Collections.singletonList(":dart:"), Collections.unmodifiableList(Arrays.asList("bull", "bullseye", "dart", "direct", "entertainment", "game", "hit", "target")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bullseye", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji YO_YO = new Emoji("\ud83e\ude80", "\\uD83E\\uDE80", Collections.singletonList(":yo_yo:"), Collections.singletonList(":yo-yo:"), Collections.singletonList(":yo_yo:"), Collections.unmodifiableList(Arrays.asList("fluctuate", "toy", "yo-yo")), false, false, 12.0, Qualification.fromString("fully-qualified"), "yo-yo", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji KITE = new Emoji("\ud83e\ude81", "\\uD83E\\uDE81", Collections.singletonList(":kite:"), Collections.singletonList(":kite:"), Collections.singletonList(":kite:"), Collections.unmodifiableList(Arrays.asList("fly", "kite", "soar")), false, false, 12.0, Qualification.fromString("fully-qualified"), "kite", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji WATER_PISTOL = new Emoji("\ud83d\udd2b", "\\uD83D\\uDD2B", Collections.unmodifiableList(Arrays.asList(":gun:", ":pistol:")), Collections.singletonList(":gun:"), Collections.singletonList(":gun:"), Collections.unmodifiableList(Arrays.asList("gun", "handgun", "pistol", "revolver", "tool", "water", "weapon")), false, false, 0.6, Qualification.fromString("fully-qualified"), "water pistol", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji POOL_8_BALL = new Emoji("\ud83c\udfb1", "\\uD83C\\uDFB1", Collections.singletonList(":8ball:"), Collections.singletonList(":8ball:"), Collections.singletonList(":8ball:"), Collections.unmodifiableList(Arrays.asList("8", "8ball", "ball", "billiard", "eight", "game", "pool")), false, false, 0.6, Qualification.fromString("fully-qualified"), "pool 8 ball", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji CRYSTAL_BALL = new Emoji("\ud83d\udd2e", "\\uD83D\\uDD2E", Collections.singletonList(":crystal_ball:"), Collections.singletonList(":crystal_ball:"), Collections.singletonList(":crystal_ball:"), Collections.unmodifiableList(Arrays.asList("ball", "crystal", "fairy", "fairytale", "fantasy", "fortune", "future", "magic", "tale", "tool")), false, false, 0.6, Qualification.fromString("fully-qualified"), "crystal ball", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji MAGIC_WAND = new Emoji("\ud83e\ude84", "\\uD83E\\uDE84", Collections.singletonList(":magic_wand:"), Collections.singletonList(":magic_wand:"), Collections.singletonList(":magic_wand:"), Collections.unmodifiableList(Arrays.asList("magic", "magician", "wand", "witch", "wizard")), false, false, 13.0, Qualification.fromString("fully-qualified"), "magic wand", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji VIDEO_GAME = new Emoji("\ud83c\udfae", "\\uD83C\\uDFAE", Collections.singletonList(":video_game:"), Collections.singletonList(":video_game:"), Collections.singletonList(":video_game:"), Collections.unmodifiableList(Arrays.asList("controller", "entertainment", "game", "video")), false, false, 0.6, Qualification.fromString("fully-qualified"), "video game", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, true);
    public static final Emoji JOYSTICK = new Emoji("\ud83d\udd79\ufe0f", "\\uD83D\\uDD79\\uFE0F", Collections.singletonList(":joystick:"), Collections.singletonList(":joystick:"), Collections.singletonList(":joystick:"), Collections.unmodifiableList(Arrays.asList("game", "joystick", "video", "videogame")), false, false, 0.7, Qualification.fromString("fully-qualified"), "joystick", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji JOYSTICK_UNQUALIFIED = new Emoji("\ud83d\udd79", "\\uD83D\\uDD79", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("game", "joystick", "video", "videogame")), false, false, 0.7, Qualification.fromString("unqualified"), "joystick", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, true);
    public static final Emoji SLOT_MACHINE = new Emoji("\ud83c\udfb0", "\\uD83C\\uDFB0", Collections.singletonList(":slot_machine:"), Collections.singletonList(":slot_machine:"), Collections.singletonList(":slot_machine:"), Collections.unmodifiableList(Arrays.asList("casino", "gamble", "gambling", "game", "machine", "slot", "slots")), false, false, 0.6, Qualification.fromString("fully-qualified"), "slot machine", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji GAME_DIE = new Emoji("\ud83c\udfb2", "\\uD83C\\uDFB2", Collections.singletonList(":game_die:"), Collections.singletonList(":game_die:"), Collections.singletonList(":game_die:"), Collections.unmodifiableList(Arrays.asList("dice", "die", "entertainment", "game")), false, false, 0.6, Qualification.fromString("fully-qualified"), "game die", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji PUZZLE_PIECE = new Emoji("\ud83e\udde9", "\\uD83E\\uDDE9", Collections.unmodifiableList(Arrays.asList(":jigsaw:", ":puzzle_piece:")), Collections.singletonList(":jigsaw:"), Collections.singletonList(":jigsaw:"), Collections.unmodifiableList(Arrays.asList("clue", "interlocking", "jigsaw", "piece", "puzzle")), false, false, 11.0, Qualification.fromString("fully-qualified"), "puzzle piece", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji TEDDY_BEAR = new Emoji("\ud83e\uddf8", "\\uD83E\\uDDF8", Collections.singletonList(":teddy_bear:"), Collections.singletonList(":teddy_bear:"), Collections.singletonList(":teddy_bear:"), Collections.unmodifiableList(Arrays.asList("bear", "plaything", "plush", "stuffed", "teddy", "toy")), false, false, 11.0, Qualification.fromString("fully-qualified"), "teddy bear", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji PI_ATA = new Emoji("\ud83e\ude85", "\\uD83E\\uDE85", Collections.singletonList(":pi\u00f1ata:"), Collections.singletonList(":pinata:"), Collections.singletonList(":pinata:"), Collections.unmodifiableList(Arrays.asList("candy", "celebrate", "celebration", "cinco", "de", "festive", "mayo", "party", "pinada", "pinata", "pi\u00f1ata")), false, false, 13.0, Qualification.fromString("fully-qualified"), "pi\u00f1ata", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji MIRROR_BALL = new Emoji("\ud83e\udea9", "\\uD83E\\uDEA9", Collections.singletonList(":mirror_ball:"), Collections.singletonList(":mirror_ball:"), Collections.singletonList(":mirror_ball:"), Collections.unmodifiableList(Arrays.asList("ball", "dance", "disco", "glitter", "mirror", "party")), false, false, 14.0, Qualification.fromString("fully-qualified"), "mirror ball", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji NESTING_DOLLS = new Emoji("\ud83e\ude86", "\\uD83E\\uDE86", Collections.singletonList(":nesting_dolls:"), Collections.singletonList(":nesting_dolls:"), Collections.singletonList(":nesting_dolls:"), Collections.unmodifiableList(Arrays.asList("babooshka", "baboushka", "babushka", "doll", "dolls", "matryoshka", "nesting", "russia")), false, false, 13.0, Qualification.fromString("fully-qualified"), "nesting dolls", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji SPADE_SUIT = new Emoji("\u2660\ufe0f", "\\u2660\\uFE0F", Collections.unmodifiableList(Arrays.asList(":spades:", ":spade_suit:")), Collections.singletonList(":spades:"), Collections.singletonList(":spades:"), Collections.unmodifiableList(Arrays.asList("card", "game", "spade", "suit")), false, false, 0.6, Qualification.fromString("fully-qualified"), "spade suit", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji SPADE_SUIT_UNQUALIFIED = new Emoji("\u2660", "\\u2660", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("card", "game", "spade", "suit")), false, false, 0.6, Qualification.fromString("unqualified"), "spade suit", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, true);
    public static final Emoji HEART_SUIT = new Emoji("\u2665\ufe0f", "\\u2665\\uFE0F", Collections.unmodifiableList(Arrays.asList(":hearts:", ":heart_suit:")), Collections.singletonList(":hearts:"), Collections.singletonList(":hearts:"), Collections.unmodifiableList(Arrays.asList("card", "emotion", "game", "heart", "hearts", "suit")), false, false, 0.6, Qualification.fromString("fully-qualified"), "heart suit", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji HEART_SUIT_UNQUALIFIED = new Emoji("\u2665", "\\u2665", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("card", "emotion", "game", "heart", "hearts", "suit")), false, false, 0.6, Qualification.fromString("unqualified"), "heart suit", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, true);
    public static final Emoji DIAMOND_SUIT = new Emoji("\u2666\ufe0f", "\\u2666\\uFE0F", Collections.unmodifiableList(Arrays.asList(":diamonds:", ":diamond_suit:")), Collections.singletonList(":diamonds:"), Collections.singletonList(":diamonds:"), Collections.unmodifiableList(Arrays.asList("card", "diamond", "game", "suit")), false, false, 0.6, Qualification.fromString("fully-qualified"), "diamond suit", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji DIAMOND_SUIT_UNQUALIFIED = new Emoji("\u2666", "\\u2666", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("card", "diamond", "game", "suit")), false, false, 0.6, Qualification.fromString("unqualified"), "diamond suit", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, true);
    public static final Emoji CLUB_SUIT = new Emoji("\u2663\ufe0f", "\\u2663\\uFE0F", Collections.unmodifiableList(Arrays.asList(":clubs:", ":club_suit:")), Collections.singletonList(":clubs:"), Collections.singletonList(":clubs:"), Collections.unmodifiableList(Arrays.asList("card", "club", "clubs", "game", "suit")), false, false, 0.6, Qualification.fromString("fully-qualified"), "club suit", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji CLUB_SUIT_UNQUALIFIED = new Emoji("\u2663", "\\u2663", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("card", "club", "clubs", "game", "suit")), false, false, 0.6, Qualification.fromString("unqualified"), "club suit", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, true);
    public static final Emoji CHESS_PAWN = new Emoji("\u265f\ufe0f", "\\u265F\\uFE0F", Collections.singletonList(":chess_pawn:"), Collections.singletonList(":chess_pawn:"), Collections.singletonList(":chess_pawn:"), Collections.unmodifiableList(Arrays.asList("chess", "dupe", "expendable", "pawn")), false, false, 11.0, Qualification.fromString("fully-qualified"), "chess pawn", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji CHESS_PAWN_UNQUALIFIED = new Emoji("\u265f", "\\u265F", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("chess", "dupe", "expendable", "pawn")), false, false, 11.0, Qualification.fromString("unqualified"), "chess pawn", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, true);
    public static final Emoji JOKER = new Emoji("\ud83c\udccf", "\\uD83C\\uDCCF", Collections.unmodifiableList(Arrays.asList(":black_joker:", ":joker:")), Collections.singletonList(":black_joker:"), Collections.singletonList(":black_joker:"), Collections.unmodifiableList(Arrays.asList("card", "game", "joker", "wildcard")), false, false, 0.6, Qualification.fromString("fully-qualified"), "joker", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
    public static final Emoji MAHJONG_RED_DRAGON = new Emoji("\ud83c\udc04", "\\uD83C\\uDC04", Collections.singletonList(":mahjong:"), Collections.singletonList(":mahjong:"), Collections.singletonList(":mahjong:"), Collections.unmodifiableList(Arrays.asList("dragon", "game", "mahjong", "red")), false, false, 0.6, Qualification.fromString("fully-qualified"), "mahjong red dragon", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, true);
    public static final Emoji FLOWER_PLAYING_CARDS = new Emoji("\ud83c\udfb4", "\\uD83C\\uDFB4", Collections.singletonList(":flower_playing_cards:"), Collections.singletonList(":flower_playing_cards:"), Collections.singletonList(":flower_playing_cards:"), Collections.unmodifiableList(Arrays.asList("card", "cards", "flower", "game", "Japanese", "playing")), false, false, 0.6, Qualification.fromString("fully-qualified"), "flower playing cards", EmojiGroup.ACTIVITIES, EmojiSubGroup.GAME, false);
}

