/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiReligion {
    public static final Emoji PLACE_OF_WORSHIP = new Emoji("\ud83d\uded0", "\\uD83D\\uDED0", Collections.unmodifiableList(Arrays.asList(":place_of_worship:", ":worship_symbol:")), Collections.singletonList(":place_of_worship:"), Collections.singletonList(":place_of_worship:"), Collections.unmodifiableList(Arrays.asList("place", "pray", "religion", "worship")), false, false, 1.0, Qualification.fromString("fully-qualified"), "place of worship", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, false);
    public static final Emoji ATOM_SYMBOL = new Emoji("\u269b\ufe0f", "\\u269B\\uFE0F", Collections.unmodifiableList(Arrays.asList(":atom:", ":atom_symbol:")), Collections.singletonList(":atom_symbol:"), Collections.singletonList(":atom_symbol:"), Collections.unmodifiableList(Arrays.asList("atheist", "atom", "symbol")), false, false, 1.0, Qualification.fromString("fully-qualified"), "atom symbol", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, false);
    public static final Emoji ATOM_SYMBOL_UNQUALIFIED = new Emoji("\u269b", "\\u269B", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("atheist", "atom", "symbol")), false, false, 1.0, Qualification.fromString("unqualified"), "atom symbol", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, true);
    public static final Emoji OM = new Emoji("\ud83d\udd49\ufe0f", "\\uD83D\\uDD49\\uFE0F", Collections.singletonList(":om_symbol:"), Collections.singletonList(":om_symbol:"), Collections.singletonList(":om:"), Collections.unmodifiableList(Arrays.asList("Hindu", "om", "religion")), false, false, 0.7, Qualification.fromString("fully-qualified"), "om", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, false);
    public static final Emoji OM_UNQUALIFIED = new Emoji("\ud83d\udd49", "\\uD83D\\uDD49", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("Hindu", "om", "religion")), false, false, 0.7, Qualification.fromString("unqualified"), "om", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, true);
    public static final Emoji STAR_OF_DAVID = new Emoji("\u2721\ufe0f", "\\u2721\\uFE0F", Collections.singletonList(":star_of_david:"), Collections.singletonList(":star_of_david:"), Collections.singletonList(":star_of_david:"), Collections.unmodifiableList(Arrays.asList("David", "Jew", "Jewish", "judaism", "religion", "star")), false, false, 0.7, Qualification.fromString("fully-qualified"), "star of David", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, false);
    public static final Emoji STAR_OF_DAVID_UNQUALIFIED = new Emoji("\u2721", "\\u2721", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("David", "Jew", "Jewish", "judaism", "religion", "star")), false, false, 0.7, Qualification.fromString("unqualified"), "star of David", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, true);
    public static final Emoji WHEEL_OF_DHARMA = new Emoji("\u2638\ufe0f", "\\u2638\\uFE0F", Collections.singletonList(":wheel_of_dharma:"), Collections.singletonList(":wheel_of_dharma:"), Collections.singletonList(":wheel_of_dharma:"), Collections.unmodifiableList(Arrays.asList("Buddhist", "dharma", "religion", "wheel")), false, false, 0.7, Qualification.fromString("fully-qualified"), "wheel of dharma", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, false);
    public static final Emoji WHEEL_OF_DHARMA_UNQUALIFIED = new Emoji("\u2638", "\\u2638", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("Buddhist", "dharma", "religion", "wheel")), false, false, 0.7, Qualification.fromString("unqualified"), "wheel of dharma", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, true);
    public static final Emoji YIN_YANG = new Emoji("\u262f\ufe0f", "\\u262F\\uFE0F", Collections.singletonList(":yin_yang:"), Collections.singletonList(":yin_yang:"), Collections.singletonList(":yin_yang:"), Collections.unmodifiableList(Arrays.asList("difficult", "lives", "religion", "tao", "taoist", "total", "yang", "yin", "yinyang")), false, false, 0.7, Qualification.fromString("fully-qualified"), "yin yang", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, false);
    public static final Emoji YIN_YANG_UNQUALIFIED = new Emoji("\u262f", "\\u262F", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("difficult", "lives", "religion", "tao", "taoist", "total", "yang", "yin", "yinyang")), false, false, 0.7, Qualification.fromString("unqualified"), "yin yang", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, true);
    public static final Emoji LATIN_CROSS = new Emoji("\u271d\ufe0f", "\\u271D\\uFE0F", Collections.unmodifiableList(Arrays.asList(":cross:", ":latin_cross:")), Collections.singletonList(":latin_cross:"), Collections.singletonList(":latin_cross:"), Collections.unmodifiableList(Arrays.asList("christ", "Christian", "cross", "latin", "religion")), false, false, 0.7, Qualification.fromString("fully-qualified"), "latin cross", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, false);
    public static final Emoji LATIN_CROSS_UNQUALIFIED = new Emoji("\u271d", "\\u271D", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("christ", "Christian", "cross", "latin", "religion")), false, false, 0.7, Qualification.fromString("unqualified"), "latin cross", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, true);
    public static final Emoji ORTHODOX_CROSS = new Emoji("\u2626\ufe0f", "\\u2626\\uFE0F", Collections.singletonList(":orthodox_cross:"), Collections.singletonList(":orthodox_cross:"), Collections.singletonList(":orthodox_cross:"), Collections.unmodifiableList(Arrays.asList("Christian", "cross", "orthodox", "religion")), false, false, 1.0, Qualification.fromString("fully-qualified"), "orthodox cross", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, false);
    public static final Emoji ORTHODOX_CROSS_UNQUALIFIED = new Emoji("\u2626", "\\u2626", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("Christian", "cross", "orthodox", "religion")), false, false, 1.0, Qualification.fromString("unqualified"), "orthodox cross", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, true);
    public static final Emoji STAR_AND_CRESCENT = new Emoji("\u262a\ufe0f", "\\u262A\\uFE0F", Collections.singletonList(":star_and_crescent:"), Collections.singletonList(":star_and_crescent:"), Collections.singletonList(":star_and_crescent:"), Collections.unmodifiableList(Arrays.asList("crescent", "islam", "Muslim", "ramadan", "religion", "star")), false, false, 0.7, Qualification.fromString("fully-qualified"), "star and crescent", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, false);
    public static final Emoji STAR_AND_CRESCENT_UNQUALIFIED = new Emoji("\u262a", "\\u262A", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("crescent", "islam", "Muslim", "ramadan", "religion", "star")), false, false, 0.7, Qualification.fromString("unqualified"), "star and crescent", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, true);
    public static final Emoji PEACE_SYMBOL = new Emoji("\u262e\ufe0f", "\\u262E\\uFE0F", Collections.unmodifiableList(Arrays.asList(":peace:", ":peace_symbol:")), Collections.singletonList(":peace_symbol:"), Collections.singletonList(":peace_symbol:"), Collections.unmodifiableList(Arrays.asList("healing", "peace", "peaceful", "symbol")), false, false, 1.0, Qualification.fromString("fully-qualified"), "peace symbol", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, false);
    public static final Emoji PEACE_SYMBOL_UNQUALIFIED = new Emoji("\u262e", "\\u262E", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("healing", "peace", "peaceful", "symbol")), false, false, 1.0, Qualification.fromString("unqualified"), "peace symbol", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, true);
    public static final Emoji MENORAH = new Emoji("\ud83d\udd4e", "\\uD83D\\uDD4E", Collections.singletonList(":menorah:"), Collections.singletonList(":menorah_with_nine_branches:"), Collections.singletonList(":menorah:"), Collections.unmodifiableList(Arrays.asList("candelabrum", "candlestick", "hanukkah", "jewish", "judaism", "menorah", "religion")), false, false, 1.0, Qualification.fromString("fully-qualified"), "menorah", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, false);
    public static final Emoji DOTTED_SIX_POINTED_STAR = new Emoji("\ud83d\udd2f", "\\uD83D\\uDD2F", Collections.singletonList(":six_pointed_star:"), Collections.singletonList(":six_pointed_star:"), Collections.singletonList(":six_pointed_star:"), Collections.unmodifiableList(Arrays.asList("dotted", "fortune", "jewish", "judaism", "six-pointed", "star")), false, false, 0.6, Qualification.fromString("fully-qualified"), "dotted six-pointed star", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, false);
    public static final Emoji KHANDA = new Emoji("\ud83e\udeaf", "\\uD83E\\uDEAF", Collections.singletonList(":khanda:"), Collections.emptyList(), Collections.singletonList(":khanda:"), Collections.unmodifiableList(Arrays.asList("Deg", "Fateh", "Khalsa", "Khanda", "religion", "Sikh", "Sikhism", "Tegh")), false, false, 15.0, Qualification.fromString("fully-qualified"), "khanda", EmojiGroup.SYMBOLS, EmojiSubGroup.RELIGION, false);
}

