/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiGeometric {
    public static final Emoji RED_CIRCLE = new Emoji("\ud83d\udd34", "\\uD83D\\uDD34", Collections.singletonList(":red_circle:"), Collections.singletonList(":red_circle:"), Collections.singletonList(":red_circle:"), Collections.unmodifiableList(Arrays.asList("circle", "geometric", "red")), false, false, 0.6, Qualification.fromString("fully-qualified"), "red circle", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji ORANGE_CIRCLE = new Emoji("\ud83d\udfe0", "\\uD83D\\uDFE0", Collections.singletonList(":orange_circle:"), Collections.singletonList(":large_orange_circle:"), Collections.singletonList(":orange_circle:"), Collections.unmodifiableList(Arrays.asList("circle", "orange")), false, false, 12.0, Qualification.fromString("fully-qualified"), "orange circle", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji YELLOW_CIRCLE = new Emoji("\ud83d\udfe1", "\\uD83D\\uDFE1", Collections.singletonList(":yellow_circle:"), Collections.singletonList(":large_yellow_circle:"), Collections.singletonList(":yellow_circle:"), Collections.unmodifiableList(Arrays.asList("circle", "yellow")), false, false, 12.0, Qualification.fromString("fully-qualified"), "yellow circle", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji GREEN_CIRCLE = new Emoji("\ud83d\udfe2", "\\uD83D\\uDFE2", Collections.singletonList(":green_circle:"), Collections.singletonList(":large_green_circle:"), Collections.singletonList(":green_circle:"), Collections.unmodifiableList(Arrays.asList("circle", "green")), false, false, 12.0, Qualification.fromString("fully-qualified"), "green circle", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji BLUE_CIRCLE = new Emoji("\ud83d\udd35", "\\uD83D\\uDD35", Collections.singletonList(":blue_circle:"), Collections.singletonList(":large_blue_circle:"), Collections.singletonList(":large_blue_circle:"), Collections.unmodifiableList(Arrays.asList("blue", "circle", "geometric")), false, false, 0.6, Qualification.fromString("fully-qualified"), "blue circle", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji PURPLE_CIRCLE = new Emoji("\ud83d\udfe3", "\\uD83D\\uDFE3", Collections.singletonList(":purple_circle:"), Collections.singletonList(":large_purple_circle:"), Collections.singletonList(":purple_circle:"), Collections.unmodifiableList(Arrays.asList("circle", "purple")), false, false, 12.0, Qualification.fromString("fully-qualified"), "purple circle", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji BROWN_CIRCLE = new Emoji("\ud83d\udfe4", "\\uD83D\\uDFE4", Collections.singletonList(":brown_circle:"), Collections.singletonList(":large_brown_circle:"), Collections.singletonList(":brown_circle:"), Collections.unmodifiableList(Arrays.asList("brown", "circle")), false, false, 12.0, Qualification.fromString("fully-qualified"), "brown circle", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji BLACK_CIRCLE = new Emoji("\u26ab", "\\u26AB", Collections.singletonList(":black_circle:"), Collections.singletonList(":black_circle:"), Collections.singletonList(":black_circle:"), Collections.unmodifiableList(Arrays.asList("black", "circle", "geometric")), false, false, 0.6, Qualification.fromString("fully-qualified"), "black circle", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, true);
    public static final Emoji WHITE_CIRCLE = new Emoji("\u26aa", "\\u26AA", Collections.singletonList(":white_circle:"), Collections.singletonList(":white_circle:"), Collections.singletonList(":white_circle:"), Collections.unmodifiableList(Arrays.asList("circle", "geometric", "white")), false, false, 0.6, Qualification.fromString("fully-qualified"), "white circle", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, true);
    public static final Emoji RED_SQUARE = new Emoji("\ud83d\udfe5", "\\uD83D\\uDFE5", Collections.singletonList(":red_square:"), Collections.singletonList(":large_red_square:"), Collections.singletonList(":red_square:"), Collections.unmodifiableList(Arrays.asList("card", "penalty", "red", "square")), false, false, 12.0, Qualification.fromString("fully-qualified"), "red square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji ORANGE_SQUARE = new Emoji("\ud83d\udfe7", "\\uD83D\\uDFE7", Collections.singletonList(":orange_square:"), Collections.singletonList(":large_orange_square:"), Collections.singletonList(":orange_square:"), Collections.unmodifiableList(Arrays.asList("orange", "square")), false, false, 12.0, Qualification.fromString("fully-qualified"), "orange square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji YELLOW_SQUARE = new Emoji("\ud83d\udfe8", "\\uD83D\\uDFE8", Collections.singletonList(":yellow_square:"), Collections.singletonList(":large_yellow_square:"), Collections.singletonList(":yellow_square:"), Collections.unmodifiableList(Arrays.asList("card", "penalty", "square", "yellow")), false, false, 12.0, Qualification.fromString("fully-qualified"), "yellow square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji GREEN_SQUARE = new Emoji("\ud83d\udfe9", "\\uD83D\\uDFE9", Collections.singletonList(":green_square:"), Collections.singletonList(":large_green_square:"), Collections.singletonList(":green_square:"), Collections.unmodifiableList(Arrays.asList("green", "square")), false, false, 12.0, Qualification.fromString("fully-qualified"), "green square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji BLUE_SQUARE = new Emoji("\ud83d\udfe6", "\\uD83D\\uDFE6", Collections.singletonList(":blue_square:"), Collections.singletonList(":large_blue_square:"), Collections.singletonList(":blue_square:"), Collections.unmodifiableList(Arrays.asList("blue", "square")), false, false, 12.0, Qualification.fromString("fully-qualified"), "blue square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji PURPLE_SQUARE = new Emoji("\ud83d\udfea", "\\uD83D\\uDFEA", Collections.singletonList(":purple_square:"), Collections.singletonList(":large_purple_square:"), Collections.singletonList(":purple_square:"), Collections.unmodifiableList(Arrays.asList("purple", "square")), false, false, 12.0, Qualification.fromString("fully-qualified"), "purple square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji BROWN_SQUARE = new Emoji("\ud83d\udfeb", "\\uD83D\\uDFEB", Collections.singletonList(":brown_square:"), Collections.singletonList(":large_brown_square:"), Collections.singletonList(":brown_square:"), Collections.unmodifiableList(Arrays.asList("brown", "square")), false, false, 12.0, Qualification.fromString("fully-qualified"), "brown square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji BLACK_LARGE_SQUARE = new Emoji("\u2b1b", "\\u2B1B", Collections.singletonList(":black_large_square:"), Collections.singletonList(":black_large_square:"), Collections.singletonList(":black_large_square:"), Collections.unmodifiableList(Arrays.asList("black", "geometric", "large", "square")), false, false, 0.6, Qualification.fromString("fully-qualified"), "black large square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, true);
    public static final Emoji WHITE_LARGE_SQUARE = new Emoji("\u2b1c", "\\u2B1C", Collections.singletonList(":white_large_square:"), Collections.singletonList(":white_large_square:"), Collections.singletonList(":white_large_square:"), Collections.unmodifiableList(Arrays.asList("geometric", "large", "square", "white")), false, false, 0.6, Qualification.fromString("fully-qualified"), "white large square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, true);
    public static final Emoji BLACK_MEDIUM_SQUARE = new Emoji("\u25fc\ufe0f", "\\u25FC\\uFE0F", Collections.singletonList(":black_medium_square:"), Collections.singletonList(":black_medium_square:"), Collections.singletonList(":black_medium_square:"), Collections.unmodifiableList(Arrays.asList("black", "geometric", "medium", "square")), false, false, 0.6, Qualification.fromString("fully-qualified"), "black medium square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji BLACK_MEDIUM_SQUARE_UNQUALIFIED = new Emoji("\u25fc", "\\u25FC", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("black", "geometric", "medium", "square")), false, false, 0.6, Qualification.fromString("unqualified"), "black medium square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, true);
    public static final Emoji WHITE_MEDIUM_SQUARE = new Emoji("\u25fb\ufe0f", "\\u25FB\\uFE0F", Collections.singletonList(":white_medium_square:"), Collections.singletonList(":white_medium_square:"), Collections.singletonList(":white_medium_square:"), Collections.unmodifiableList(Arrays.asList("geometric", "medium", "square", "white")), false, false, 0.6, Qualification.fromString("fully-qualified"), "white medium square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji WHITE_MEDIUM_SQUARE_UNQUALIFIED = new Emoji("\u25fb", "\\u25FB", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("geometric", "medium", "square", "white")), false, false, 0.6, Qualification.fromString("unqualified"), "white medium square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, true);
    public static final Emoji BLACK_MEDIUM_SMALL_SQUARE = new Emoji("\u25fe", "\\u25FE", Collections.singletonList(":black_medium_small_square:"), Collections.singletonList(":black_medium_small_square:"), Collections.singletonList(":black_medium_small_square:"), Collections.unmodifiableList(Arrays.asList("black", "geometric", "medium-small", "square")), false, false, 0.6, Qualification.fromString("fully-qualified"), "black medium-small square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, true);
    public static final Emoji WHITE_MEDIUM_SMALL_SQUARE = new Emoji("\u25fd", "\\u25FD", Collections.singletonList(":white_medium_small_square:"), Collections.singletonList(":white_medium_small_square:"), Collections.singletonList(":white_medium_small_square:"), Collections.unmodifiableList(Arrays.asList("geometric", "medium-small", "square", "white")), false, false, 0.6, Qualification.fromString("fully-qualified"), "white medium-small square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, true);
    public static final Emoji BLACK_SMALL_SQUARE = new Emoji("\u25aa\ufe0f", "\\u25AA\\uFE0F", Collections.singletonList(":black_small_square:"), Collections.singletonList(":black_small_square:"), Collections.singletonList(":black_small_square:"), Collections.unmodifiableList(Arrays.asList("black", "geometric", "small", "square")), false, false, 0.6, Qualification.fromString("fully-qualified"), "black small square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji BLACK_SMALL_SQUARE_UNQUALIFIED = new Emoji("\u25aa", "\\u25AA", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("black", "geometric", "small", "square")), false, false, 0.6, Qualification.fromString("unqualified"), "black small square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, true);
    public static final Emoji WHITE_SMALL_SQUARE = new Emoji("\u25ab\ufe0f", "\\u25AB\\uFE0F", Collections.singletonList(":white_small_square:"), Collections.singletonList(":white_small_square:"), Collections.singletonList(":white_small_square:"), Collections.unmodifiableList(Arrays.asList("geometric", "small", "square", "white")), false, false, 0.6, Qualification.fromString("fully-qualified"), "white small square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji WHITE_SMALL_SQUARE_UNQUALIFIED = new Emoji("\u25ab", "\\u25AB", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("geometric", "small", "square", "white")), false, false, 0.6, Qualification.fromString("unqualified"), "white small square", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, true);
    public static final Emoji LARGE_ORANGE_DIAMOND = new Emoji("\ud83d\udd36", "\\uD83D\\uDD36", Collections.singletonList(":large_orange_diamond:"), Collections.singletonList(":large_orange_diamond:"), Collections.singletonList(":large_orange_diamond:"), Collections.unmodifiableList(Arrays.asList("diamond", "geometric", "large", "orange")), false, false, 0.6, Qualification.fromString("fully-qualified"), "large orange diamond", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji LARGE_BLUE_DIAMOND = new Emoji("\ud83d\udd37", "\\uD83D\\uDD37", Collections.singletonList(":large_blue_diamond:"), Collections.singletonList(":large_blue_diamond:"), Collections.singletonList(":large_blue_diamond:"), Collections.unmodifiableList(Arrays.asList("blue", "diamond", "geometric", "large")), false, false, 0.6, Qualification.fromString("fully-qualified"), "large blue diamond", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji SMALL_ORANGE_DIAMOND = new Emoji("\ud83d\udd38", "\\uD83D\\uDD38", Collections.singletonList(":small_orange_diamond:"), Collections.singletonList(":small_orange_diamond:"), Collections.singletonList(":small_orange_diamond:"), Collections.unmodifiableList(Arrays.asList("diamond", "geometric", "orange", "small")), false, false, 0.6, Qualification.fromString("fully-qualified"), "small orange diamond", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji SMALL_BLUE_DIAMOND = new Emoji("\ud83d\udd39", "\\uD83D\\uDD39", Collections.singletonList(":small_blue_diamond:"), Collections.singletonList(":small_blue_diamond:"), Collections.singletonList(":small_blue_diamond:"), Collections.unmodifiableList(Arrays.asList("blue", "diamond", "geometric", "small")), false, false, 0.6, Qualification.fromString("fully-qualified"), "small blue diamond", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji RED_TRIANGLE_POINTED_UP = new Emoji("\ud83d\udd3a", "\\uD83D\\uDD3A", Collections.singletonList(":small_red_triangle:"), Collections.singletonList(":small_red_triangle:"), Collections.singletonList(":small_red_triangle:"), Collections.unmodifiableList(Arrays.asList("geometric", "pointed", "red", "triangle", "up")), false, false, 0.6, Qualification.fromString("fully-qualified"), "red triangle pointed up", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji RED_TRIANGLE_POINTED_DOWN = new Emoji("\ud83d\udd3b", "\\uD83D\\uDD3B", Collections.singletonList(":small_red_triangle_down:"), Collections.singletonList(":small_red_triangle_down:"), Collections.singletonList(":small_red_triangle_down:"), Collections.unmodifiableList(Arrays.asList("down", "geometric", "pointed", "red", "triangle")), false, false, 0.6, Qualification.fromString("fully-qualified"), "red triangle pointed down", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji DIAMOND_WITH_A_DOT = new Emoji("\ud83d\udca0", "\\uD83D\\uDCA0", Collections.singletonList(":diamond_shape_with_a_dot_inside:"), Collections.singletonList(":diamond_shape_with_a_dot_inside:"), Collections.singletonList(":diamond_shape_with_a_dot_inside:"), Collections.unmodifiableList(Arrays.asList("comic", "diamond", "dot", "geometric")), false, false, 0.6, Qualification.fromString("fully-qualified"), "diamond with a dot", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji RADIO_BUTTON = new Emoji("\ud83d\udd18", "\\uD83D\\uDD18", Collections.singletonList(":radio_button:"), Collections.singletonList(":radio_button:"), Collections.singletonList(":radio_button:"), Collections.unmodifiableList(Arrays.asList("button", "geometric", "radio")), false, false, 0.6, Qualification.fromString("fully-qualified"), "radio button", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji WHITE_SQUARE_BUTTON = new Emoji("\ud83d\udd33", "\\uD83D\\uDD33", Collections.singletonList(":white_square_button:"), Collections.singletonList(":white_square_button:"), Collections.singletonList(":white_square_button:"), Collections.unmodifiableList(Arrays.asList("button", "geometric", "outlined", "square", "white")), false, false, 0.6, Qualification.fromString("fully-qualified"), "white square button", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
    public static final Emoji BLACK_SQUARE_BUTTON = new Emoji("\ud83d\udd32", "\\uD83D\\uDD32", Collections.singletonList(":black_square_button:"), Collections.singletonList(":black_square_button:"), Collections.singletonList(":black_square_button:"), Collections.unmodifiableList(Arrays.asList("black", "button", "geometric", "square")), false, false, 0.6, Qualification.fromString("fully-qualified"), "black square button", EmojiGroup.SYMBOLS, EmojiSubGroup.GEOMETRIC, false);
}

