/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiLightAndVideo {
    public static final Emoji MOVIE_CAMERA = new Emoji("\ud83c\udfa5", "\\uD83C\\uDFA5", Collections.singletonList(":movie_camera:"), Collections.singletonList(":movie_camera:"), Collections.singletonList(":movie_camera:"), Collections.unmodifiableList(Arrays.asList("bollywood", "camera", "cinema", "film", "hollywood", "movie", "record")), false, false, 0.6, Qualification.fromString("fully-qualified"), "movie camera", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, false);
    public static final Emoji FILM_FRAMES = new Emoji("\ud83c\udf9e\ufe0f", "\\uD83C\\uDF9E\\uFE0F", Collections.singletonList(":film_frames:"), Collections.singletonList(":film_frames:"), Collections.singletonList(":film_strip:"), Collections.unmodifiableList(Arrays.asList("cinema", "film", "frames", "movie")), false, false, 0.7, Qualification.fromString("fully-qualified"), "film frames", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, false);
    public static final Emoji FILM_FRAMES_UNQUALIFIED = new Emoji("\ud83c\udf9e", "\\uD83C\\uDF9E", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cinema", "film", "frames", "movie")), false, false, 0.7, Qualification.fromString("unqualified"), "film frames", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, true);
    public static final Emoji FILM_PROJECTOR = new Emoji("\ud83d\udcfd\ufe0f", "\\uD83D\\uDCFD\\uFE0F", Collections.unmodifiableList(Arrays.asList(":projector:", ":film_projector:")), Collections.singletonList(":film_projector:"), Collections.singletonList(":film_projector:"), Collections.unmodifiableList(Arrays.asList("cinema", "film", "movie", "projector", "video")), false, false, 0.7, Qualification.fromString("fully-qualified"), "film projector", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, false);
    public static final Emoji FILM_PROJECTOR_UNQUALIFIED = new Emoji("\ud83d\udcfd", "\\uD83D\\uDCFD", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cinema", "film", "movie", "projector", "video")), false, false, 0.7, Qualification.fromString("unqualified"), "film projector", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, true);
    public static final Emoji CLAPPER_BOARD = new Emoji("\ud83c\udfac", "\\uD83C\\uDFAC", Collections.unmodifiableList(Arrays.asList(":clapper:", ":clapper_board:")), Collections.singletonList(":clapper:"), Collections.singletonList(":clapper:"), Collections.unmodifiableList(Arrays.asList("action", "board", "clapper", "movie")), false, false, 0.6, Qualification.fromString("fully-qualified"), "clapper board", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, true);
    public static final Emoji TELEVISION = new Emoji("\ud83d\udcfa", "\\uD83D\\uDCFA", Collections.unmodifiableList(Arrays.asList(":tv:", ":television:")), Collections.singletonList(":tv:"), Collections.singletonList(":tv:"), Collections.unmodifiableList(Arrays.asList("television", "tv", "video")), false, false, 0.6, Qualification.fromString("fully-qualified"), "television", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, true);
    public static final Emoji CAMERA = new Emoji("\ud83d\udcf7", "\\uD83D\\uDCF7", Collections.singletonList(":camera:"), Collections.singletonList(":camera:"), Collections.singletonList(":camera:"), Collections.unmodifiableList(Arrays.asList("camera", "photo", "selfie", "snap", "tbt", "trip", "video")), false, false, 0.6, Qualification.fromString("fully-qualified"), "camera", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, true);
    public static final Emoji CAMERA_WITH_FLASH = new Emoji("\ud83d\udcf8", "\\uD83D\\uDCF8", Collections.singletonList(":camera_with_flash:"), Collections.singletonList(":camera_with_flash:"), Collections.singletonList(":camera_flash:"), Collections.unmodifiableList(Arrays.asList("camera", "flash", "video")), false, false, 1.0, Qualification.fromString("fully-qualified"), "camera with flash", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, false);
    public static final Emoji VIDEO_CAMERA = new Emoji("\ud83d\udcf9", "\\uD83D\\uDCF9", Collections.singletonList(":video_camera:"), Collections.singletonList(":video_camera:"), Collections.singletonList(":video_camera:"), Collections.unmodifiableList(Arrays.asList("camcorder", "camera", "tbt", "video")), false, false, 0.6, Qualification.fromString("fully-qualified"), "video camera", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, true);
    public static final Emoji VIDEOCASSETTE = new Emoji("\ud83d\udcfc", "\\uD83D\\uDCFC", Collections.unmodifiableList(Arrays.asList(":vhs:", ":videocassette:")), Collections.singletonList(":vhs:"), Collections.singletonList(":vhs:"), Collections.unmodifiableList(Arrays.asList("old", "school", "tape", "vcr", "vhs", "video", "videocassette")), false, false, 0.6, Qualification.fromString("fully-qualified"), "videocassette", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, false);
    public static final Emoji MAGNIFYING_GLASS_TILTED_LEFT = new Emoji("\ud83d\udd0d", "\\uD83D\\uDD0D", Collections.singletonList(":mag:"), Collections.singletonList(":mag:"), Collections.singletonList(":mag:"), Collections.unmodifiableList(Arrays.asList("glass", "lab", "left", "left-pointing", "magnifying", "science", "search", "tilted", "tool")), false, false, 0.6, Qualification.fromString("fully-qualified"), "magnifying glass tilted left", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, true);
    public static final Emoji MAGNIFYING_GLASS_TILTED_RIGHT = new Emoji("\ud83d\udd0e", "\\uD83D\\uDD0E", Collections.singletonList(":mag_right:"), Collections.singletonList(":mag_right:"), Collections.singletonList(":mag_right:"), Collections.unmodifiableList(Arrays.asList("contact", "glass", "lab", "magnifying", "right", "right-pointing", "science", "search", "tilted", "tool")), false, false, 0.6, Qualification.fromString("fully-qualified"), "magnifying glass tilted right", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, false);
    public static final Emoji CANDLE = new Emoji("\ud83d\udd6f\ufe0f", "\\uD83D\\uDD6F\\uFE0F", Collections.singletonList(":candle:"), Collections.singletonList(":candle:"), Collections.singletonList(":candle:"), Collections.unmodifiableList(Arrays.asList("candle", "light")), false, false, 0.7, Qualification.fromString("fully-qualified"), "candle", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, false);
    public static final Emoji CANDLE_UNQUALIFIED = new Emoji("\ud83d\udd6f", "\\uD83D\\uDD6F", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("candle", "light")), false, false, 0.7, Qualification.fromString("unqualified"), "candle", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, true);
    public static final Emoji LIGHT_BULB = new Emoji("\ud83d\udca1", "\\uD83D\\uDCA1", Collections.unmodifiableList(Arrays.asList(":bulb:", ":light_bulb:")), Collections.singletonList(":bulb:"), Collections.singletonList(":bulb:"), Collections.unmodifiableList(Arrays.asList("bulb", "comic", "electric", "idea", "light")), false, false, 0.6, Qualification.fromString("fully-qualified"), "light bulb", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, false);
    public static final Emoji FLASHLIGHT = new Emoji("\ud83d\udd26", "\\uD83D\\uDD26", Collections.singletonList(":flashlight:"), Collections.singletonList(":flashlight:"), Collections.singletonList(":flashlight:"), Collections.unmodifiableList(Arrays.asList("electric", "flashlight", "light", "tool", "torch")), false, false, 0.6, Qualification.fromString("fully-qualified"), "flashlight", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, false);
    public static final Emoji RED_PAPER_LANTERN = new Emoji("\ud83c\udfee", "\\uD83C\\uDFEE", Collections.singletonList(":izakaya_lantern:"), Collections.unmodifiableList(Arrays.asList(":izakaya_lantern:", ":lantern:")), Collections.unmodifiableList(Arrays.asList(":izakaya_lantern:", ":lantern:")), Collections.unmodifiableList(Arrays.asList("bar", "lantern", "light", "paper", "red", "restaurant")), false, false, 0.6, Qualification.fromString("fully-qualified"), "red paper lantern", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, false);
    public static final Emoji DIYA_LAMP = new Emoji("\ud83e\ude94", "\\uD83E\\uDE94", Collections.singletonList(":diya_lamp:"), Collections.singletonList(":diya_lamp:"), Collections.singletonList(":diya_lamp:"), Collections.unmodifiableList(Arrays.asList("diya", "lamp", "light", "oil")), false, false, 12.0, Qualification.fromString("fully-qualified"), "diya lamp", EmojiGroup.OBJECTS, EmojiSubGroup.LIGHT_AND_VIDEO, false);
}

