/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiFoodPrepared {
    public static final Emoji BREAD = new Emoji("\ud83c\udf5e", "\\uD83C\\uDF5E", Collections.singletonList(":bread:"), Collections.singletonList(":bread:"), Collections.singletonList(":bread:"), Collections.unmodifiableList(Arrays.asList("bread", "carbs", "food", "grain", "loaf", "restaurant", "toast", "wheat")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bread", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji CROISSANT = new Emoji("\ud83e\udd50", "\\uD83E\\uDD50", Collections.singletonList(":croissant:"), Collections.singletonList(":croissant:"), Collections.singletonList(":croissant:"), Collections.unmodifiableList(Arrays.asList("bread", "breakfast", "crescent", "croissant", "food", "french", "roll")), false, false, 3.0, Qualification.fromString("fully-qualified"), "croissant", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji BAGUETTE_BREAD = new Emoji("\ud83e\udd56", "\\uD83E\\uDD56", Collections.unmodifiableList(Arrays.asList(":french_bread:", ":baguette_bread:")), Collections.singletonList(":baguette_bread:"), Collections.singletonList(":baguette_bread:"), Collections.unmodifiableList(Arrays.asList("baguette", "bread", "food", "french")), false, false, 3.0, Qualification.fromString("fully-qualified"), "baguette bread", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji FLATBREAD = new Emoji("\ud83e\uded3", "\\uD83E\\uDED3", Collections.singletonList(":flatbread:"), Collections.singletonList(":flatbread:"), Collections.singletonList(":flatbread:"), Collections.unmodifiableList(Arrays.asList("arepa", "bread", "flatbread", "food", "gordita", "lavash", "naan", "pita")), false, false, 13.0, Qualification.fromString("fully-qualified"), "flatbread", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji PRETZEL = new Emoji("\ud83e\udd68", "\\uD83E\\uDD68", Collections.singletonList(":pretzel:"), Collections.singletonList(":pretzel:"), Collections.singletonList(":pretzel:"), Collections.unmodifiableList(Arrays.asList("convoluted", "pretzel", "twisted")), false, false, 5.0, Qualification.fromString("fully-qualified"), "pretzel", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji BAGEL = new Emoji("\ud83e\udd6f", "\\uD83E\\uDD6F", Collections.singletonList(":bagel:"), Collections.singletonList(":bagel:"), Collections.singletonList(":bagel:"), Collections.unmodifiableList(Arrays.asList("bagel", "bakery", "bread", "breakfast", "schmear")), false, false, 11.0, Qualification.fromString("fully-qualified"), "bagel", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji PANCAKES = new Emoji("\ud83e\udd5e", "\\uD83E\\uDD5E", Collections.singletonList(":pancakes:"), Collections.singletonList(":pancakes:"), Collections.singletonList(":pancakes:"), Collections.unmodifiableList(Arrays.asList("breakfast", "cr\u00eape", "food", "hotcake", "pancake", "pancakes")), false, false, 3.0, Qualification.fromString("fully-qualified"), "pancakes", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji WAFFLE = new Emoji("\ud83e\uddc7", "\\uD83E\\uDDC7", Collections.singletonList(":waffle:"), Collections.singletonList(":waffle:"), Collections.singletonList(":waffle:"), Collections.unmodifiableList(Arrays.asList("breakfast", "indecisive", "iron", "waffle")), false, false, 12.0, Qualification.fromString("fully-qualified"), "waffle", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji CHEESE_WEDGE = new Emoji("\ud83e\uddc0", "\\uD83E\\uDDC0", Collections.unmodifiableList(Arrays.asList(":cheese:", ":cheese_wedge:")), Collections.singletonList(":cheese_wedge:"), Collections.singletonList(":cheese:"), Collections.unmodifiableList(Arrays.asList("cheese", "wedge")), false, false, 1.0, Qualification.fromString("fully-qualified"), "cheese wedge", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji MEAT_ON_BONE = new Emoji("\ud83c\udf56", "\\uD83C\\uDF56", Collections.singletonList(":meat_on_bone:"), Collections.singletonList(":meat_on_bone:"), Collections.singletonList(":meat_on_bone:"), Collections.unmodifiableList(Arrays.asList("bone", "meat")), false, false, 0.6, Qualification.fromString("fully-qualified"), "meat on bone", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji POULTRY_LEG = new Emoji("\ud83c\udf57", "\\uD83C\\uDF57", Collections.singletonList(":poultry_leg:"), Collections.singletonList(":poultry_leg:"), Collections.singletonList(":poultry_leg:"), Collections.unmodifiableList(Arrays.asList("bone", "chicken", "drumstick", "hungry", "leg", "poultry", "turkey")), false, false, 0.6, Qualification.fromString("fully-qualified"), "poultry leg", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji CUT_OF_MEAT = new Emoji("\ud83e\udd69", "\\uD83E\\uDD69", Collections.singletonList(":cut_of_meat:"), Collections.singletonList(":cut_of_meat:"), Collections.singletonList(":cut_of_meat:"), Collections.unmodifiableList(Arrays.asList("chop", "cut", "lambchop", "meat", "porkchop", "red", "steak")), false, false, 5.0, Qualification.fromString("fully-qualified"), "cut of meat", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji BACON = new Emoji("\ud83e\udd53", "\\uD83E\\uDD53", Collections.singletonList(":bacon:"), Collections.singletonList(":bacon:"), Collections.singletonList(":bacon:"), Collections.unmodifiableList(Arrays.asList("bacon", "breakfast", "food", "meat")), false, false, 3.0, Qualification.fromString("fully-qualified"), "bacon", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji HAMBURGER = new Emoji("\ud83c\udf54", "\\uD83C\\uDF54", Collections.singletonList(":hamburger:"), Collections.singletonList(":hamburger:"), Collections.singletonList(":hamburger:"), Collections.unmodifiableList(Arrays.asList("burger", "eat", "fast", "food", "hamburger", "hungry")), false, false, 0.6, Qualification.fromString("fully-qualified"), "hamburger", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji FRENCH_FRIES = new Emoji("\ud83c\udf5f", "\\uD83C\\uDF5F", Collections.unmodifiableList(Arrays.asList(":fries:", ":french_fries:")), Collections.singletonList(":fries:"), Collections.singletonList(":fries:"), Collections.unmodifiableList(Arrays.asList("fast", "food", "french", "fries")), false, false, 0.6, Qualification.fromString("fully-qualified"), "french fries", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji PIZZA = new Emoji("\ud83c\udf55", "\\uD83C\\uDF55", Collections.singletonList(":pizza:"), Collections.singletonList(":pizza:"), Collections.singletonList(":pizza:"), Collections.unmodifiableList(Arrays.asList("cheese", "food", "hungry", "pepperoni", "pizza", "slice")), false, false, 0.6, Qualification.fromString("fully-qualified"), "pizza", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji HOT_DOG = new Emoji("\ud83c\udf2d", "\\uD83C\\uDF2D", Collections.unmodifiableList(Arrays.asList(":hotdog:", ":hot_dog:")), Collections.singletonList(":hotdog:"), Collections.singletonList(":hotdog:"), Collections.unmodifiableList(Arrays.asList("dog", "frankfurter", "hot", "hotdog", "sausage")), false, false, 1.0, Qualification.fromString("fully-qualified"), "hot dog", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji SANDWICH = new Emoji("\ud83e\udd6a", "\\uD83E\\uDD6A", Collections.singletonList(":sandwich:"), Collections.singletonList(":sandwich:"), Collections.singletonList(":sandwich:"), Collections.unmodifiableList(Arrays.asList("bread", "sandwich")), false, false, 5.0, Qualification.fromString("fully-qualified"), "sandwich", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji TACO = new Emoji("\ud83c\udf2e", "\\uD83C\\uDF2E", Collections.singletonList(":taco:"), Collections.singletonList(":taco:"), Collections.singletonList(":taco:"), Collections.unmodifiableList(Arrays.asList("mexican", "taco")), false, false, 1.0, Qualification.fromString("fully-qualified"), "taco", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji BURRITO = new Emoji("\ud83c\udf2f", "\\uD83C\\uDF2F", Collections.singletonList(":burrito:"), Collections.singletonList(":burrito:"), Collections.singletonList(":burrito:"), Collections.unmodifiableList(Arrays.asList("burrito", "mexican", "wrap")), false, false, 1.0, Qualification.fromString("fully-qualified"), "burrito", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji TAMALE = new Emoji("\ud83e\uded4", "\\uD83E\\uDED4", Collections.singletonList(":tamale:"), Collections.singletonList(":tamale:"), Collections.singletonList(":tamale:"), Collections.unmodifiableList(Arrays.asList("food", "mexican", "pamonha", "tamale", "wrapped")), false, false, 13.0, Qualification.fromString("fully-qualified"), "tamale", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji STUFFED_FLATBREAD = new Emoji("\ud83e\udd59", "\\uD83E\\uDD59", Collections.unmodifiableList(Arrays.asList(":stuffed_flatbread:", ":stuffed_pita:")), Collections.singletonList(":stuffed_flatbread:"), Collections.singletonList(":stuffed_flatbread:"), Collections.unmodifiableList(Arrays.asList("falafel", "flatbread", "food", "gyro", "kebab", "stuffed")), false, false, 3.0, Qualification.fromString("fully-qualified"), "stuffed flatbread", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji FALAFEL = new Emoji("\ud83e\uddc6", "\\uD83E\\uDDC6", Collections.singletonList(":falafel:"), Collections.singletonList(":falafel:"), Collections.singletonList(":falafel:"), Collections.unmodifiableList(Arrays.asList("chickpea", "falafel", "meatball")), false, false, 12.0, Qualification.fromString("fully-qualified"), "falafel", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji EGG = new Emoji("\ud83e\udd5a", "\\uD83E\\uDD5A", Collections.singletonList(":egg:"), Collections.singletonList(":egg:"), Collections.singletonList(":egg:"), Collections.unmodifiableList(Arrays.asList("breakfast", "egg", "food")), false, false, 3.0, Qualification.fromString("fully-qualified"), "egg", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji COOKING = new Emoji("\ud83c\udf73", "\\uD83C\\uDF73", Collections.singletonList(":cooking:"), Collections.unmodifiableList(Arrays.asList(":fried_egg:", ":cooking:")), Collections.singletonList(":fried_egg:"), Collections.unmodifiableList(Arrays.asList("breakfast", "cooking", "easy", "egg", "fry", "frying", "over", "pan", "restaurant", "side", "sunny", "up")), false, false, 0.6, Qualification.fromString("fully-qualified"), "cooking", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji SHALLOW_PAN_OF_FOOD = new Emoji("\ud83e\udd58", "\\uD83E\\uDD58", Collections.unmodifiableList(Arrays.asList(":shallow_pan_of_food:", ":paella:")), Collections.singletonList(":shallow_pan_of_food:"), Collections.singletonList(":shallow_pan_of_food:"), Collections.unmodifiableList(Arrays.asList("casserole", "food", "paella", "pan", "shallow")), false, false, 3.0, Qualification.fromString("fully-qualified"), "shallow pan of food", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji POT_OF_FOOD = new Emoji("\ud83c\udf72", "\\uD83C\\uDF72", Collections.unmodifiableList(Arrays.asList(":stew:", ":pot_of_food:")), Collections.singletonList(":stew:"), Collections.singletonList(":stew:"), Collections.unmodifiableList(Arrays.asList("food", "pot", "soup", "stew")), false, false, 0.6, Qualification.fromString("fully-qualified"), "pot of food", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji FONDUE = new Emoji("\ud83e\uded5", "\\uD83E\\uDED5", Collections.singletonList(":fondue:"), Collections.singletonList(":fondue:"), Collections.singletonList(":fondue:"), Collections.unmodifiableList(Arrays.asList("cheese", "chocolate", "fondue", "food", "melted", "pot", "ski")), false, false, 13.0, Qualification.fromString("fully-qualified"), "fondue", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji BOWL_WITH_SPOON = new Emoji("\ud83e\udd63", "\\uD83E\\uDD63", Collections.singletonList(":bowl_with_spoon:"), Collections.singletonList(":bowl_with_spoon:"), Collections.singletonList(":bowl_with_spoon:"), Collections.unmodifiableList(Arrays.asList("bowl", "breakfast", "cereal", "congee", "oatmeal", "porridge", "spoon")), false, false, 5.0, Qualification.fromString("fully-qualified"), "bowl with spoon", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji GREEN_SALAD = new Emoji("\ud83e\udd57", "\\uD83E\\uDD57", Collections.unmodifiableList(Arrays.asList(":salad:", ":green_salad:")), Collections.singletonList(":green_salad:"), Collections.singletonList(":green_salad:"), Collections.unmodifiableList(Arrays.asList("food", "green", "salad")), false, false, 3.0, Qualification.fromString("fully-qualified"), "green salad", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji POPCORN = new Emoji("\ud83c\udf7f", "\\uD83C\\uDF7F", Collections.singletonList(":popcorn:"), Collections.singletonList(":popcorn:"), Collections.singletonList(":popcorn:"), Collections.unmodifiableList(Arrays.asList("corn", "movie", "pop", "popcorn")), false, false, 1.0, Qualification.fromString("fully-qualified"), "popcorn", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji BUTTER = new Emoji("\ud83e\uddc8", "\\uD83E\\uDDC8", Collections.singletonList(":butter:"), Collections.singletonList(":butter:"), Collections.singletonList(":butter:"), Collections.unmodifiableList(Arrays.asList("butter", "dairy")), false, false, 12.0, Qualification.fromString("fully-qualified"), "butter", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji SALT = new Emoji("\ud83e\uddc2", "\\uD83E\\uDDC2", Collections.singletonList(":salt:"), Collections.singletonList(":salt:"), Collections.singletonList(":salt:"), Collections.unmodifiableList(Arrays.asList("condiment", "flavor", "mad", "salt", "salty", "shaker", "taste", "upset")), false, false, 11.0, Qualification.fromString("fully-qualified"), "salt", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
    public static final Emoji CANNED_FOOD = new Emoji("\ud83e\udd6b", "\\uD83E\\uDD6B", Collections.singletonList(":canned_food:"), Collections.singletonList(":canned_food:"), Collections.singletonList(":canned_food:"), Collections.unmodifiableList(Arrays.asList("can", "canned", "food")), false, false, 5.0, Qualification.fromString("fully-qualified"), "canned food", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_PREPARED, false);
}

