/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiHeart {
    public static final Emoji LOVE_LETTER = new Emoji("\ud83d\udc8c", "\\uD83D\\uDC8C", Collections.singletonList(":love_letter:"), Collections.singletonList(":love_letter:"), Collections.singletonList(":love_letter:"), Collections.unmodifiableList(Arrays.asList("heart", "letter", "love", "mail", "romance", "valentine")), false, false, 0.6, Qualification.fromString("fully-qualified"), "love letter", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji HEART_WITH_ARROW = new Emoji("\ud83d\udc98", "\\uD83D\\uDC98", Collections.singletonList(":cupid:"), Collections.singletonList(":cupid:"), Collections.singletonList(":cupid:"), Collections.unmodifiableList(Arrays.asList("143", "adorbs", "arrow", "cupid", "date", "emotion", "heart", "ily", "love", "romance", "valentine")), false, false, 0.6, Qualification.fromString("fully-qualified"), "heart with arrow", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji HEART_WITH_RIBBON = new Emoji("\ud83d\udc9d", "\\uD83D\\uDC9D", Collections.singletonList(":gift_heart:"), Collections.singletonList(":gift_heart:"), Collections.singletonList(":gift_heart:"), Collections.unmodifiableList(Arrays.asList("143", "anniversary", "emotion", "heart", "ily", "kisses", "ribbon", "valentine", "xoxo")), false, false, 0.6, Qualification.fromString("fully-qualified"), "heart with ribbon", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji SPARKLING_HEART = new Emoji("\ud83d\udc96", "\\uD83D\\uDC96", Collections.singletonList(":sparkling_heart:"), Collections.singletonList(":sparkling_heart:"), Collections.singletonList(":sparkling_heart:"), Collections.unmodifiableList(Arrays.asList("143", "emotion", "excited", "good", "heart", "ily", "kisses", "morning", "night", "sparkle", "sparkling", "xoxo")), false, false, 0.6, Qualification.fromString("fully-qualified"), "sparkling heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji GROWING_HEART = new Emoji("\ud83d\udc97", "\\uD83D\\uDC97", Collections.unmodifiableList(Arrays.asList(":heartpulse:", ":growing_heart:")), Collections.singletonList(":heartpulse:"), Collections.singletonList(":heartpulse:"), Collections.unmodifiableList(Arrays.asList("143", "emotion", "excited", "growing", "heart", "heartpulse", "ily", "kisses", "muah", "nervous", "pulse", "xoxo")), false, false, 0.6, Qualification.fromString("fully-qualified"), "growing heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji BEATING_HEART = new Emoji("\ud83d\udc93", "\\uD83D\\uDC93", Collections.unmodifiableList(Arrays.asList(":heartbeat:", ":beating_heart:")), Collections.singletonList(":heartbeat:"), Collections.singletonList(":heartbeat:"), Collections.unmodifiableList(Arrays.asList("143", "beating", "cardio", "emotion", "heart", "heartbeat", "ily", "love", "pulsating", "pulse")), false, false, 0.6, Qualification.fromString("fully-qualified"), "beating heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji REVOLVING_HEARTS = new Emoji("\ud83d\udc9e", "\\uD83D\\uDC9E", Collections.singletonList(":revolving_hearts:"), Collections.singletonList(":revolving_hearts:"), Collections.singletonList(":revolving_hearts:"), Collections.unmodifiableList(Arrays.asList("143", "adorbs", "anniversary", "emotion", "heart", "hearts", "revolving")), false, false, 0.6, Qualification.fromString("fully-qualified"), "revolving hearts", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji TWO_HEARTS = new Emoji("\ud83d\udc95", "\\uD83D\\uDC95", Collections.singletonList(":two_hearts:"), Collections.singletonList(":two_hearts:"), Collections.singletonList(":two_hearts:"), Collections.unmodifiableList(Arrays.asList("143", "anniversary", "date", "dating", "emotion", "heart", "hearts", "ily", "kisses", "love", "loving", "two", "xoxo")), false, false, 0.6, Qualification.fromString("fully-qualified"), "two hearts", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji HEART_DECORATION = new Emoji("\ud83d\udc9f", "\\uD83D\\uDC9F", Collections.singletonList(":heart_decoration:"), Collections.singletonList(":heart_decoration:"), Collections.singletonList(":heart_decoration:"), Collections.unmodifiableList(Arrays.asList("143", "decoration", "emotion", "heart", "hearth", "purple", "white")), false, false, 0.6, Qualification.fromString("fully-qualified"), "heart decoration", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji HEART_EXCLAMATION = new Emoji("\u2763\ufe0f", "\\u2763\\uFE0F", Collections.unmodifiableList(Arrays.asList(":heart_exclamation:", ":heavy_heart_exclamation_mark_ornament:")), Collections.singletonList(":heavy_heart_exclamation_mark_ornament:"), Collections.singletonList(":heavy_heart_exclamation:"), Collections.unmodifiableList(Arrays.asList("exclamation", "heart", "heavy", "mark", "punctuation")), false, false, 1.0, Qualification.fromString("fully-qualified"), "heart exclamation", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji HEART_EXCLAMATION_UNQUALIFIED = new Emoji("\u2763", "\\u2763", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("exclamation", "heart", "heavy", "mark", "punctuation")), false, false, 1.0, Qualification.fromString("unqualified"), "heart exclamation", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, true);
    public static final Emoji BROKEN_HEART = new Emoji("\ud83d\udc94", "\\uD83D\\uDC94", Collections.unmodifiableList(Arrays.asList(":broken_heart:", "</3", "<\\3")), Collections.singletonList(":broken_heart:"), Collections.singletonList(":broken_heart:"), Collections.unmodifiableList(Arrays.asList("break", "broken", "crushed", "emotion", "heart", "heartbroken", "lonely", "sad")), false, false, 0.6, Qualification.fromString("fully-qualified"), "broken heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji HEART_ON_FIRE = new Emoji("\u2764\ufe0f\u200d\ud83d\udd25", "\\u2764\\uFE0F\\u200D\\uD83D\\uDD25", Collections.singletonList(":heart_on_fire:"), Collections.singletonList(":heart_on_fire:"), Collections.singletonList(":heart_on_fire:"), Collections.unmodifiableList(Arrays.asList("burn", "fire", "heart", "love", "lust", "sacred")), false, false, 13.1, Qualification.fromString("fully-qualified"), "heart on fire", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji HEART_ON_FIRE_UNQUALIFIED = new Emoji("\u2764\u200d\ud83d\udd25", "\\u2764\\u200D\\uD83D\\uDD25", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("burn", "fire", "heart", "love", "lust", "sacred")), false, false, 13.1, Qualification.fromString("unqualified"), "heart on fire", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji MENDING_HEART = new Emoji("\u2764\ufe0f\u200d\ud83e\ude79", "\\u2764\\uFE0F\\u200D\\uD83E\\uDE79", Collections.singletonList(":mending_heart:"), Collections.singletonList(":mending_heart:"), Collections.singletonList(":mending_heart:"), Collections.unmodifiableList(Arrays.asList("healthier", "heart", "improving", "mending", "recovering", "recuperating", "well")), false, false, 13.1, Qualification.fromString("fully-qualified"), "mending heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji MENDING_HEART_UNQUALIFIED = new Emoji("\u2764\u200d\ud83e\ude79", "\\u2764\\u200D\\uD83E\\uDE79", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("healthier", "heart", "improving", "mending", "recovering", "recuperating", "well")), false, false, 13.1, Qualification.fromString("unqualified"), "mending heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji RED_HEART = new Emoji("\u2764\ufe0f", "\\u2764\\uFE0F", Collections.unmodifiableList(Arrays.asList(":heart:", ":red_heart:", "<3", "\u2661")), Collections.singletonList(":heart:"), Collections.singletonList(":heart:"), Collections.unmodifiableList(Arrays.asList("emotion", "heart", "love", "red")), false, false, 0.6, Qualification.fromString("fully-qualified"), "red heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji RED_HEART_UNQUALIFIED = new Emoji("\u2764", "\\u2764", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("emotion", "heart", "love", "red")), false, false, 0.6, Qualification.fromString("unqualified"), "red heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, true);
    public static final Emoji PINK_HEART = new Emoji("\ud83e\ude77", "\\uD83E\\uDE77", Collections.singletonList(":pink_heart:"), Collections.emptyList(), Collections.singletonList(":pink_heart:"), Collections.unmodifiableList(Arrays.asList("143", "adorable", "cute", "emotion", "heart", "ily", "like", "love", "pink", "special", "sweet")), false, false, 15.0, Qualification.fromString("fully-qualified"), "pink heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji ORANGE_HEART = new Emoji("\ud83e\udde1", "\\uD83E\\uDDE1", Collections.singletonList(":orange_heart:"), Collections.singletonList(":orange_heart:"), Collections.singletonList(":orange_heart:"), Collections.unmodifiableList(Arrays.asList("143", "heart", "orange")), false, false, 5.0, Qualification.fromString("fully-qualified"), "orange heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji YELLOW_HEART = new Emoji("\ud83d\udc9b", "\\uD83D\\uDC9B", Collections.singletonList(":yellow_heart:"), Collections.singletonList(":yellow_heart:"), Collections.singletonList(":yellow_heart:"), Collections.unmodifiableList(Arrays.asList("143", "cardiac", "emotion", "heart", "ily", "love", "yellow")), false, false, 0.6, Qualification.fromString("fully-qualified"), "yellow heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji GREEN_HEART = new Emoji("\ud83d\udc9a", "\\uD83D\\uDC9A", Collections.singletonList(":green_heart:"), Collections.singletonList(":green_heart:"), Collections.singletonList(":green_heart:"), Collections.unmodifiableList(Arrays.asList("143", "emotion", "green", "heart", "ily", "love", "romantic")), false, false, 0.6, Qualification.fromString("fully-qualified"), "green heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji BLUE_HEART = new Emoji("\ud83d\udc99", "\\uD83D\\uDC99", Collections.singletonList(":blue_heart:"), Collections.singletonList(":blue_heart:"), Collections.singletonList(":blue_heart:"), Collections.unmodifiableList(Arrays.asList("143", "blue", "emotion", "heart", "ily", "love", "romance")), false, false, 0.6, Qualification.fromString("fully-qualified"), "blue heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji LIGHT_BLUE_HEART = new Emoji("\ud83e\ude75", "\\uD83E\\uDE75", Collections.singletonList(":light_blue_heart:"), Collections.emptyList(), Collections.singletonList(":light_blue_heart:"), Collections.unmodifiableList(Arrays.asList("143", "blue", "cute", "cyan", "emotion", "heart", "ily", "light", "like", "love", "sky", "special", "teal")), false, false, 15.0, Qualification.fromString("fully-qualified"), "light blue heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji PURPLE_HEART = new Emoji("\ud83d\udc9c", "\\uD83D\\uDC9C", Collections.singletonList(":purple_heart:"), Collections.singletonList(":purple_heart:"), Collections.singletonList(":purple_heart:"), Collections.unmodifiableList(Arrays.asList("143", "bestest", "emotion", "heart", "ily", "love", "purple")), false, false, 0.6, Qualification.fromString("fully-qualified"), "purple heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji BROWN_HEART = new Emoji("\ud83e\udd0e", "\\uD83E\\uDD0E", Collections.singletonList(":brown_heart:"), Collections.singletonList(":brown_heart:"), Collections.singletonList(":brown_heart:"), Collections.unmodifiableList(Arrays.asList("143", "brown", "heart")), false, false, 12.0, Qualification.fromString("fully-qualified"), "brown heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji BLACK_HEART = new Emoji("\ud83d\udda4", "\\uD83D\\uDDA4", Collections.singletonList(":black_heart:"), Collections.singletonList(":black_heart:"), Collections.singletonList(":black_heart:"), Collections.unmodifiableList(Arrays.asList("black", "evil", "heart", "wicked")), false, false, 3.0, Qualification.fromString("fully-qualified"), "black heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji GREY_HEART = new Emoji("\ud83e\ude76", "\\uD83E\\uDE76", Collections.singletonList(":grey_heart:"), Collections.emptyList(), Collections.singletonList(":grey_heart:"), Collections.unmodifiableList(Arrays.asList("143", "emotion", "gray", "grey", "heart", "ily", "love", "silver", "slate", "special")), false, false, 15.0, Qualification.fromString("fully-qualified"), "grey heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
    public static final Emoji WHITE_HEART = new Emoji("\ud83e\udd0d", "\\uD83E\\uDD0D", Collections.singletonList(":white_heart:"), Collections.singletonList(":white_heart:"), Collections.singletonList(":white_heart:"), Collections.unmodifiableList(Arrays.asList("143", "heart", "white")), false, false, 12.0, Qualification.fromString("fully-qualified"), "white heart", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.HEART, false);
}

