/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiComputer {
    public static final Emoji BATTERY = new Emoji("\ud83d\udd0b", "\\uD83D\\uDD0B", Collections.singletonList(":battery:"), Collections.singletonList(":battery:"), Collections.singletonList(":battery:"), Collections.singletonList("battery"), false, false, 0.6, Qualification.fromString("fully-qualified"), "battery", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, false);
    public static final Emoji LOW_BATTERY = new Emoji("\ud83e\udeab", "\\uD83E\\uDEAB", Collections.singletonList(":low_battery:"), Collections.singletonList(":low_battery:"), Collections.singletonList(":low_battery:"), Collections.unmodifiableList(Arrays.asList("battery", "drained", "electronic", "energy", "low", "power")), false, false, 14.0, Qualification.fromString("fully-qualified"), "low battery", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, false);
    public static final Emoji ELECTRIC_PLUG = new Emoji("\ud83d\udd0c", "\\uD83D\\uDD0C", Collections.singletonList(":electric_plug:"), Collections.singletonList(":electric_plug:"), Collections.singletonList(":electric_plug:"), Collections.unmodifiableList(Arrays.asList("electric", "electricity", "plug")), false, false, 0.6, Qualification.fromString("fully-qualified"), "electric plug", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, false);
    public static final Emoji LAPTOP = new Emoji("\ud83d\udcbb", "\\uD83D\\uDCBB", Collections.singletonList(":computer:"), Collections.singletonList(":computer:"), Collections.singletonList(":computer:"), Collections.unmodifiableList(Arrays.asList("computer", "laptop", "office", "pc", "personal")), false, false, 0.6, Qualification.fromString("fully-qualified"), "laptop", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, true);
    public static final Emoji DESKTOP_COMPUTER = new Emoji("\ud83d\udda5\ufe0f", "\\uD83D\\uDDA5\\uFE0F", Collections.unmodifiableList(Arrays.asList(":desktop:", ":desktop_computer:")), Collections.singletonList(":desktop_computer:"), Collections.singletonList(":desktop_computer:"), Collections.unmodifiableList(Arrays.asList("computer", "desktop", "monitor")), false, false, 0.7, Qualification.fromString("fully-qualified"), "desktop computer", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, false);
    public static final Emoji DESKTOP_COMPUTER_UNQUALIFIED = new Emoji("\ud83d\udda5", "\\uD83D\\uDDA5", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("computer", "desktop", "monitor")), false, false, 0.7, Qualification.fromString("unqualified"), "desktop computer", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, true);
    public static final Emoji PRINTER = new Emoji("\ud83d\udda8\ufe0f", "\\uD83D\\uDDA8\\uFE0F", Collections.singletonList(":printer:"), Collections.singletonList(":printer:"), Collections.singletonList(":printer:"), Collections.unmodifiableList(Arrays.asList("computer", "printer")), false, false, 0.7, Qualification.fromString("fully-qualified"), "printer", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, false);
    public static final Emoji PRINTER_UNQUALIFIED = new Emoji("\ud83d\udda8", "\\uD83D\\uDDA8", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("computer", "printer")), false, false, 0.7, Qualification.fromString("unqualified"), "printer", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, true);
    public static final Emoji KEYBOARD = new Emoji("\u2328\ufe0f", "\\u2328\\uFE0F", Collections.singletonList(":keyboard:"), Collections.singletonList(":keyboard:"), Collections.singletonList(":keyboard:"), Collections.unmodifiableList(Arrays.asList("computer", "keyboard")), false, false, 1.0, Qualification.fromString("fully-qualified"), "keyboard", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, false);
    public static final Emoji KEYBOARD_UNQUALIFIED = new Emoji("\u2328", "\\u2328", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("computer", "keyboard")), false, false, 1.0, Qualification.fromString("unqualified"), "keyboard", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, true);
    public static final Emoji COMPUTER_MOUSE = new Emoji("\ud83d\uddb1\ufe0f", "\\uD83D\\uDDB1\\uFE0F", Collections.unmodifiableList(Arrays.asList(":mouse_three_button:", ":three_button_mouse:")), Collections.singletonList(":three_button_mouse:"), Collections.singletonList(":computer_mouse:"), Collections.unmodifiableList(Arrays.asList("computer", "mouse")), false, false, 0.7, Qualification.fromString("fully-qualified"), "computer mouse", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, false);
    public static final Emoji COMPUTER_MOUSE_UNQUALIFIED = new Emoji("\ud83d\uddb1", "\\uD83D\\uDDB1", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("computer", "mouse")), false, false, 0.7, Qualification.fromString("unqualified"), "computer mouse", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, true);
    public static final Emoji TRACKBALL = new Emoji("\ud83d\uddb2\ufe0f", "\\uD83D\\uDDB2\\uFE0F", Collections.singletonList(":trackball:"), Collections.singletonList(":trackball:"), Collections.singletonList(":trackball:"), Collections.unmodifiableList(Arrays.asList("computer", "trackball")), false, false, 0.7, Qualification.fromString("fully-qualified"), "trackball", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, false);
    public static final Emoji TRACKBALL_UNQUALIFIED = new Emoji("\ud83d\uddb2", "\\uD83D\\uDDB2", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("computer", "trackball")), false, false, 0.7, Qualification.fromString("unqualified"), "trackball", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, true);
    public static final Emoji COMPUTER_DISK = new Emoji("\ud83d\udcbd", "\\uD83D\\uDCBD", Collections.unmodifiableList(Arrays.asList(":minidisc:", ":computer_disk:")), Collections.singletonList(":minidisc:"), Collections.singletonList(":minidisc:"), Collections.unmodifiableList(Arrays.asList("computer", "disk", "minidisk", "optical")), false, false, 0.6, Qualification.fromString("fully-qualified"), "computer disk", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, false);
    public static final Emoji FLOPPY_DISK = new Emoji("\ud83d\udcbe", "\\uD83D\\uDCBE", Collections.singletonList(":floppy_disk:"), Collections.singletonList(":floppy_disk:"), Collections.singletonList(":floppy_disk:"), Collections.unmodifiableList(Arrays.asList("computer", "disk", "floppy")), false, false, 0.6, Qualification.fromString("fully-qualified"), "floppy disk", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, false);
    public static final Emoji OPTICAL_DISK = new Emoji("\ud83d\udcbf", "\\uD83D\\uDCBF", Collections.unmodifiableList(Arrays.asList(":cd:", ":optical_disk:")), Collections.singletonList(":cd:"), Collections.singletonList(":cd:"), Collections.unmodifiableList(Arrays.asList("blu-ray", "CD", "computer", "disk", "dvd", "optical")), false, false, 0.6, Qualification.fromString("fully-qualified"), "optical disk", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, true);
    public static final Emoji DVD = new Emoji("\ud83d\udcc0", "\\uD83D\\uDCC0", Collections.singletonList(":dvd:"), Collections.singletonList(":dvd:"), Collections.singletonList(":dvd:"), Collections.unmodifiableList(Arrays.asList("Blu-ray", "cd", "computer", "disk", "DVD", "optical")), false, false, 0.6, Qualification.fromString("fully-qualified"), "dvd", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, false);
    public static final Emoji ABACUS = new Emoji("\ud83e\uddee", "\\uD83E\\uDDEE", Collections.singletonList(":abacus:"), Collections.singletonList(":abacus:"), Collections.singletonList(":abacus:"), Collections.unmodifiableList(Arrays.asList("abacus", "calculation", "calculator")), false, false, 11.0, Qualification.fromString("fully-qualified"), "abacus", EmojiGroup.OBJECTS, EmojiSubGroup.COMPUTER, false);
}

