/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiEvent {
    public static final Emoji JACK_O_LANTERN = new Emoji("\ud83c\udf83", "\\uD83C\\uDF83", Collections.singletonList(":jack_o_lantern:"), Collections.singletonList(":jack_o_lantern:"), Collections.singletonList(":jack_o_lantern:"), Collections.unmodifiableList(Arrays.asList("celebration", "halloween", "jack", "jack-o-lantern", "lantern", "pumpkin")), false, false, 0.6, Qualification.fromString("fully-qualified"), "jack-o-lantern", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji CHRISTMAS_TREE = new Emoji("\ud83c\udf84", "\\uD83C\\uDF84", Collections.singletonList(":christmas_tree:"), Collections.singletonList(":christmas_tree:"), Collections.singletonList(":christmas_tree:"), Collections.unmodifiableList(Arrays.asList("celebration", "Christmas", "tree")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Christmas tree", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji FIREWORKS = new Emoji("\ud83c\udf86", "\\uD83C\\uDF86", Collections.singletonList(":fireworks:"), Collections.singletonList(":fireworks:"), Collections.singletonList(":fireworks:"), Collections.unmodifiableList(Arrays.asList("boom", "celebration", "entertainment", "fireworks", "yolo")), false, false, 0.6, Qualification.fromString("fully-qualified"), "fireworks", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji SPARKLER = new Emoji("\ud83c\udf87", "\\uD83C\\uDF87", Collections.singletonList(":sparkler:"), Collections.singletonList(":sparkler:"), Collections.singletonList(":sparkler:"), Collections.unmodifiableList(Arrays.asList("boom", "celebration", "fireworks", "sparkle", "sparkler")), false, false, 0.6, Qualification.fromString("fully-qualified"), "sparkler", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji FIRECRACKER = new Emoji("\ud83e\udde8", "\\uD83E\\uDDE8", Collections.singletonList(":firecracker:"), Collections.singletonList(":firecracker:"), Collections.singletonList(":firecracker:"), Collections.unmodifiableList(Arrays.asList("dynamite", "explosive", "fire", "firecracker", "fireworks", "light", "pop", "popping", "spark")), false, false, 11.0, Qualification.fromString("fully-qualified"), "firecracker", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji SPARKLES = new Emoji("\u2728", "\\u2728", Collections.singletonList(":sparkles:"), Collections.singletonList(":sparkles:"), Collections.singletonList(":sparkles:"), Collections.unmodifiableList(Arrays.asList("*", "magic", "sparkle", "sparkles", "star")), false, false, 0.6, Qualification.fromString("fully-qualified"), "sparkles", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, true);
    public static final Emoji BALLOON = new Emoji("\ud83c\udf88", "\\uD83C\\uDF88", Collections.singletonList(":balloon:"), Collections.singletonList(":balloon:"), Collections.singletonList(":balloon:"), Collections.unmodifiableList(Arrays.asList("balloon", "birthday", "celebrate", "celebration")), false, false, 0.6, Qualification.fromString("fully-qualified"), "balloon", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji PARTY_POPPER = new Emoji("\ud83c\udf89", "\\uD83C\\uDF89", Collections.unmodifiableList(Arrays.asList(":tada:", ":party_popper:")), Collections.singletonList(":tada:"), Collections.singletonList(":tada:"), Collections.unmodifiableList(Arrays.asList("awesome", "birthday", "celebrate", "celebration", "excited", "hooray", "party", "popper", "tada", "woohoo")), false, false, 0.6, Qualification.fromString("fully-qualified"), "party popper", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji CONFETTI_BALL = new Emoji("\ud83c\udf8a", "\\uD83C\\uDF8A", Collections.singletonList(":confetti_ball:"), Collections.singletonList(":confetti_ball:"), Collections.singletonList(":confetti_ball:"), Collections.unmodifiableList(Arrays.asList("ball", "celebrate", "celebration", "confetti", "party", "woohoo")), false, false, 0.6, Qualification.fromString("fully-qualified"), "confetti ball", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji TANABATA_TREE = new Emoji("\ud83c\udf8b", "\\uD83C\\uDF8B", Collections.singletonList(":tanabata_tree:"), Collections.singletonList(":tanabata_tree:"), Collections.singletonList(":tanabata_tree:"), Collections.unmodifiableList(Arrays.asList("banner", "celebration", "Japanese", "tanabata", "tree")), false, false, 0.6, Qualification.fromString("fully-qualified"), "tanabata tree", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji PINE_DECORATION = new Emoji("\ud83c\udf8d", "\\uD83C\\uDF8D", Collections.singletonList(":bamboo:"), Collections.singletonList(":bamboo:"), Collections.singletonList(":bamboo:"), Collections.unmodifiableList(Arrays.asList("bamboo", "celebration", "decoration", "Japanese", "pine", "plant")), false, false, 0.6, Qualification.fromString("fully-qualified"), "pine decoration", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji JAPANESE_DOLLS = new Emoji("\ud83c\udf8e", "\\uD83C\\uDF8E", Collections.singletonList(":dolls:"), Collections.singletonList(":dolls:"), Collections.singletonList(":dolls:"), Collections.unmodifiableList(Arrays.asList("celebration", "doll", "dolls", "festival", "Japanese")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese dolls", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji CARP_STREAMER = new Emoji("\ud83c\udf8f", "\\uD83C\\uDF8F", Collections.unmodifiableList(Arrays.asList(":flags:", ":carp_streamer:")), Collections.singletonList(":flags:"), Collections.singletonList(":flags:"), Collections.unmodifiableList(Arrays.asList("carp", "celebration", "streamer")), false, false, 0.6, Qualification.fromString("fully-qualified"), "carp streamer", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji WIND_CHIME = new Emoji("\ud83c\udf90", "\\uD83C\\uDF90", Collections.singletonList(":wind_chime:"), Collections.singletonList(":wind_chime:"), Collections.singletonList(":wind_chime:"), Collections.unmodifiableList(Arrays.asList("bell", "celebration", "chime", "wind")), false, false, 0.6, Qualification.fromString("fully-qualified"), "wind chime", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji MOON_VIEWING_CEREMONY = new Emoji("\ud83c\udf91", "\\uD83C\\uDF91", Collections.singletonList(":rice_scene:"), Collections.singletonList(":rice_scene:"), Collections.singletonList(":rice_scene:"), Collections.unmodifiableList(Arrays.asList("celebration", "ceremony", "moon", "viewing")), false, false, 0.6, Qualification.fromString("fully-qualified"), "moon viewing ceremony", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji RED_ENVELOPE = new Emoji("\ud83e\udde7", "\\uD83E\\uDDE7", Collections.singletonList(":red_envelope:"), Collections.singletonList(":red_envelope:"), Collections.singletonList(":red_envelope:"), Collections.unmodifiableList(Arrays.asList("envelope", "gift", "good", "h\u00f3ngb\u0101o", "lai", "luck", "money", "red", "see")), false, false, 11.0, Qualification.fromString("fully-qualified"), "red envelope", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji RIBBON = new Emoji("\ud83c\udf80", "\\uD83C\\uDF80", Collections.singletonList(":ribbon:"), Collections.singletonList(":ribbon:"), Collections.singletonList(":ribbon:"), Collections.unmodifiableList(Arrays.asList("celebration", "ribbon")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ribbon", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji WRAPPED_GIFT = new Emoji("\ud83c\udf81", "\\uD83C\\uDF81", Collections.unmodifiableList(Arrays.asList(":gift:", ":wrapped_gift:")), Collections.singletonList(":gift:"), Collections.singletonList(":gift:"), Collections.unmodifiableList(Arrays.asList("birthday", "bow", "box", "celebration", "christmas", "gift", "present", "surprise", "wrapped")), false, false, 0.6, Qualification.fromString("fully-qualified"), "wrapped gift", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji REMINDER_RIBBON = new Emoji("\ud83c\udf97\ufe0f", "\\uD83C\\uDF97\\uFE0F", Collections.singletonList(":reminder_ribbon:"), Collections.singletonList(":reminder_ribbon:"), Collections.singletonList(":reminder_ribbon:"), Collections.unmodifiableList(Arrays.asList("celebration", "reminder", "ribbon")), false, false, 0.7, Qualification.fromString("fully-qualified"), "reminder ribbon", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji REMINDER_RIBBON_UNQUALIFIED = new Emoji("\ud83c\udf97", "\\uD83C\\uDF97", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("celebration", "reminder", "ribbon")), false, false, 0.7, Qualification.fromString("unqualified"), "reminder ribbon", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, true);
    public static final Emoji ADMISSION_TICKETS = new Emoji("\ud83c\udf9f\ufe0f", "\\uD83C\\uDF9F\\uFE0F", Collections.unmodifiableList(Arrays.asList(":tickets:", ":admission_tickets:")), Collections.singletonList(":admission_tickets:"), Collections.singletonList(":tickets:"), Collections.unmodifiableList(Arrays.asList("admission", "ticket", "tickets")), false, false, 0.7, Qualification.fromString("fully-qualified"), "admission tickets", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
    public static final Emoji ADMISSION_TICKETS_UNQUALIFIED = new Emoji("\ud83c\udf9f", "\\uD83C\\uDF9F", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("admission", "ticket", "tickets")), false, false, 0.7, Qualification.fromString("unqualified"), "admission tickets", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, true);
    public static final Emoji TICKET = new Emoji("\ud83c\udfab", "\\uD83C\\uDFAB", Collections.singletonList(":ticket:"), Collections.singletonList(":ticket:"), Collections.singletonList(":ticket:"), Collections.unmodifiableList(Arrays.asList("admission", "stub", "ticket")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ticket", EmojiGroup.ACTIVITIES, EmojiSubGroup.EVENT, false);
}

