/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiSkyAndWeather {
    public static final Emoji NEW_MOON = new Emoji("\ud83c\udf11", "\\uD83C\\uDF11", Collections.singletonList(":new_moon:"), Collections.singletonList(":new_moon:"), Collections.singletonList(":new_moon:"), Collections.unmodifiableList(Arrays.asList("dark", "moon", "new", "space")), false, false, 0.6, Qualification.fromString("fully-qualified"), "new moon", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji WAXING_CRESCENT_MOON = new Emoji("\ud83c\udf12", "\\uD83C\\uDF12", Collections.singletonList(":waxing_crescent_moon:"), Collections.singletonList(":waxing_crescent_moon:"), Collections.singletonList(":waxing_crescent_moon:"), Collections.unmodifiableList(Arrays.asList("crescent", "dreams", "moon", "space", "waxing")), false, false, 1.0, Qualification.fromString("fully-qualified"), "waxing crescent moon", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji FIRST_QUARTER_MOON = new Emoji("\ud83c\udf13", "\\uD83C\\uDF13", Collections.singletonList(":first_quarter_moon:"), Collections.singletonList(":first_quarter_moon:"), Collections.singletonList(":first_quarter_moon:"), Collections.unmodifiableList(Arrays.asList("first", "moon", "quarter", "space")), false, false, 0.6, Qualification.fromString("fully-qualified"), "first quarter moon", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji WAXING_GIBBOUS_MOON = new Emoji("\ud83c\udf14", "\\uD83C\\uDF14", Collections.singletonList(":waxing_gibbous_moon:"), Collections.unmodifiableList(Arrays.asList(":moon:", ":waxing_gibbous_moon:")), Collections.unmodifiableList(Arrays.asList(":moon:", ":waxing_gibbous_moon:")), Collections.unmodifiableList(Arrays.asList("gibbous", "moon", "space", "waxing")), false, false, 0.6, Qualification.fromString("fully-qualified"), "waxing gibbous moon", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji FULL_MOON = new Emoji("\ud83c\udf15", "\\uD83C\\uDF15", Collections.singletonList(":full_moon:"), Collections.singletonList(":full_moon:"), Collections.singletonList(":full_moon:"), Collections.unmodifiableList(Arrays.asList("full", "moon", "space")), false, false, 0.6, Qualification.fromString("fully-qualified"), "full moon", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji WANING_GIBBOUS_MOON = new Emoji("\ud83c\udf16", "\\uD83C\\uDF16", Collections.singletonList(":waning_gibbous_moon:"), Collections.singletonList(":waning_gibbous_moon:"), Collections.singletonList(":waning_gibbous_moon:"), Collections.unmodifiableList(Arrays.asList("gibbous", "moon", "space", "waning")), false, false, 1.0, Qualification.fromString("fully-qualified"), "waning gibbous moon", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji LAST_QUARTER_MOON = new Emoji("\ud83c\udf17", "\\uD83C\\uDF17", Collections.singletonList(":last_quarter_moon:"), Collections.singletonList(":last_quarter_moon:"), Collections.singletonList(":last_quarter_moon:"), Collections.unmodifiableList(Arrays.asList("last", "moon", "quarter", "space")), false, false, 1.0, Qualification.fromString("fully-qualified"), "last quarter moon", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji WANING_CRESCENT_MOON = new Emoji("\ud83c\udf18", "\\uD83C\\uDF18", Collections.singletonList(":waning_crescent_moon:"), Collections.singletonList(":waning_crescent_moon:"), Collections.singletonList(":waning_crescent_moon:"), Collections.unmodifiableList(Arrays.asList("crescent", "moon", "space", "waning")), false, false, 1.0, Qualification.fromString("fully-qualified"), "waning crescent moon", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji CRESCENT_MOON = new Emoji("\ud83c\udf19", "\\uD83C\\uDF19", Collections.singletonList(":crescent_moon:"), Collections.singletonList(":crescent_moon:"), Collections.singletonList(":crescent_moon:"), Collections.unmodifiableList(Arrays.asList("crescent", "moon", "ramadan", "space")), false, false, 0.6, Qualification.fromString("fully-qualified"), "crescent moon", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji NEW_MOON_FACE = new Emoji("\ud83c\udf1a", "\\uD83C\\uDF1A", Collections.unmodifiableList(Arrays.asList(":new_moon_with_face:", ":new_moon_face:")), Collections.singletonList(":new_moon_with_face:"), Collections.singletonList(":new_moon_with_face:"), Collections.unmodifiableList(Arrays.asList("face", "moon", "new", "space")), false, false, 1.0, Qualification.fromString("fully-qualified"), "new moon face", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji FIRST_QUARTER_MOON_FACE = new Emoji("\ud83c\udf1b", "\\uD83C\\uDF1B", Collections.singletonList(":first_quarter_moon_with_face:"), Collections.singletonList(":first_quarter_moon_with_face:"), Collections.singletonList(":first_quarter_moon_with_face:"), Collections.unmodifiableList(Arrays.asList("face", "first", "moon", "quarter", "space")), false, false, 0.6, Qualification.fromString("fully-qualified"), "first quarter moon face", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji LAST_QUARTER_MOON_FACE = new Emoji("\ud83c\udf1c", "\\uD83C\\uDF1C", Collections.singletonList(":last_quarter_moon_with_face:"), Collections.singletonList(":last_quarter_moon_with_face:"), Collections.singletonList(":last_quarter_moon_with_face:"), Collections.unmodifiableList(Arrays.asList("dreams", "face", "last", "moon", "quarter")), false, false, 0.7, Qualification.fromString("fully-qualified"), "last quarter moon face", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji THERMOMETER = new Emoji("\ud83c\udf21\ufe0f", "\\uD83C\\uDF21\\uFE0F", Collections.singletonList(":thermometer:"), Collections.singletonList(":thermometer:"), Collections.singletonList(":thermometer:"), Collections.unmodifiableList(Arrays.asList("thermometer", "weather")), false, false, 0.7, Qualification.fromString("fully-qualified"), "thermometer", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji THERMOMETER_UNQUALIFIED = new Emoji("\ud83c\udf21", "\\uD83C\\uDF21", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("thermometer", "weather")), false, false, 0.7, Qualification.fromString("unqualified"), "thermometer", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji SUN = new Emoji("\u2600\ufe0f", "\\u2600\\uFE0F", Collections.unmodifiableList(Arrays.asList(":sunny:", ":sun:")), Collections.singletonList(":sunny:"), Collections.singletonList(":sunny:"), Collections.unmodifiableList(Arrays.asList("bright", "rays", "space", "sun", "sunny", "weather")), false, false, 0.6, Qualification.fromString("fully-qualified"), "sun", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji SUN_UNQUALIFIED = new Emoji("\u2600", "\\u2600", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("bright", "rays", "space", "sun", "sunny", "weather")), false, false, 0.6, Qualification.fromString("unqualified"), "sun", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji FULL_MOON_FACE = new Emoji("\ud83c\udf1d", "\\uD83C\\uDF1D", Collections.singletonList(":full_moon_with_face:"), Collections.singletonList(":full_moon_with_face:"), Collections.singletonList(":full_moon_with_face:"), Collections.unmodifiableList(Arrays.asList("bright", "face", "full", "moon")), false, false, 1.0, Qualification.fromString("fully-qualified"), "full moon face", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji SUN_WITH_FACE = new Emoji("\ud83c\udf1e", "\\uD83C\\uDF1E", Collections.singletonList(":sun_with_face:"), Collections.singletonList(":sun_with_face:"), Collections.singletonList(":sun_with_face:"), Collections.unmodifiableList(Arrays.asList("beach", "bright", "day", "face", "heat", "shine", "sun", "sunny", "sunshine", "weather")), false, false, 1.0, Qualification.fromString("fully-qualified"), "sun with face", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji RINGED_PLANET = new Emoji("\ud83e\ude90", "\\uD83E\\uDE90", Collections.singletonList(":ringed_planet:"), Collections.singletonList(":ringed_planet:"), Collections.singletonList(":ringed_planet:"), Collections.unmodifiableList(Arrays.asList("planet", "ringed", "saturn", "saturnine")), false, false, 12.0, Qualification.fromString("fully-qualified"), "ringed planet", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji STAR = new Emoji("\u2b50", "\\u2B50", Collections.singletonList(":star:"), Collections.singletonList(":star:"), Collections.singletonList(":star:"), Collections.unmodifiableList(Arrays.asList("astronomy", "medium", "star", "stars", "white")), false, false, 0.6, Qualification.fromString("fully-qualified"), "star", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji GLOWING_STAR = new Emoji("\ud83c\udf1f", "\\uD83C\\uDF1F", Collections.unmodifiableList(Arrays.asList(":star2:", ":glowing_star:")), Collections.singletonList(":star2:"), Collections.singletonList(":star2:"), Collections.unmodifiableList(Arrays.asList("glittery", "glow", "glowing", "night", "shining", "sparkle", "star", "win")), false, false, 0.6, Qualification.fromString("fully-qualified"), "glowing star", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji SHOOTING_STAR = new Emoji("\ud83c\udf20", "\\uD83C\\uDF20", Collections.unmodifiableList(Arrays.asList(":stars:", ":shooting_star:")), Collections.singletonList(":stars:"), Collections.singletonList(":stars:"), Collections.unmodifiableList(Arrays.asList("falling", "night", "shooting", "space", "star")), false, false, 0.6, Qualification.fromString("fully-qualified"), "shooting star", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji MILKY_WAY = new Emoji("\ud83c\udf0c", "\\uD83C\\uDF0C", Collections.singletonList(":milky_way:"), Collections.singletonList(":milky_way:"), Collections.singletonList(":milky_way:"), Collections.unmodifiableList(Arrays.asList("milky", "space", "way")), false, false, 0.6, Qualification.fromString("fully-qualified"), "milky way", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji CLOUD = new Emoji("\u2601\ufe0f", "\\u2601\\uFE0F", Collections.singletonList(":cloud:"), Collections.singletonList(":cloud:"), Collections.singletonList(":cloud:"), Collections.unmodifiableList(Arrays.asList("cloud", "weather")), false, false, 0.6, Qualification.fromString("fully-qualified"), "cloud", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji CLOUD_UNQUALIFIED = new Emoji("\u2601", "\\u2601", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cloud", "weather")), false, false, 0.6, Qualification.fromString("unqualified"), "cloud", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji SUN_BEHIND_CLOUD = new Emoji("\u26c5", "\\u26C5", Collections.singletonList(":partly_sunny:"), Collections.singletonList(":partly_sunny:"), Collections.singletonList(":partly_sunny:"), Collections.unmodifiableList(Arrays.asList("behind", "cloud", "cloudy", "sun", "weather")), false, false, 0.6, Qualification.fromString("fully-qualified"), "sun behind cloud", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji CLOUD_WITH_LIGHTNING_AND_RAIN = new Emoji("\u26c8\ufe0f", "\\u26C8\\uFE0F", Collections.unmodifiableList(Arrays.asList(":thunder_cloud_rain:", ":thunder_cloud_and_rain:")), Collections.singletonList(":thunder_cloud_and_rain:"), Collections.singletonList(":cloud_with_lightning_and_rain:"), Collections.unmodifiableList(Arrays.asList("cloud", "lightning", "rain", "thunder", "thunderstorm")), false, false, 0.7, Qualification.fromString("fully-qualified"), "cloud with lightning and rain", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji CLOUD_WITH_LIGHTNING_AND_RAIN_UNQUALIFIED = new Emoji("\u26c8", "\\u26C8", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cloud", "lightning", "rain", "thunder", "thunderstorm")), false, false, 0.7, Qualification.fromString("unqualified"), "cloud with lightning and rain", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji SUN_BEHIND_SMALL_CLOUD = new Emoji("\ud83c\udf24\ufe0f", "\\uD83C\\uDF24\\uFE0F", Collections.unmodifiableList(Arrays.asList(":white_sun_small_cloud:", ":white_sun_with_small_cloud:")), Collections.unmodifiableList(Arrays.asList(":mostly_sunny:", ":sun_small_cloud:")), Collections.singletonList(":sun_behind_small_cloud:"), Collections.unmodifiableList(Arrays.asList("behind", "cloud", "sun", "weather")), false, false, 0.7, Qualification.fromString("fully-qualified"), "sun behind small cloud", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji SUN_BEHIND_SMALL_CLOUD_UNQUALIFIED = new Emoji("\ud83c\udf24", "\\uD83C\\uDF24", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("behind", "cloud", "sun", "weather")), false, false, 0.7, Qualification.fromString("unqualified"), "sun behind small cloud", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji SUN_BEHIND_LARGE_CLOUD = new Emoji("\ud83c\udf25\ufe0f", "\\uD83C\\uDF25\\uFE0F", Collections.unmodifiableList(Arrays.asList(":white_sun_cloud:", ":white_sun_behind_cloud:")), Collections.unmodifiableList(Arrays.asList(":barely_sunny:", ":sun_behind_cloud:")), Collections.singletonList(":sun_behind_large_cloud:"), Collections.unmodifiableList(Arrays.asList("behind", "cloud", "sun", "weather")), false, false, 0.7, Qualification.fromString("fully-qualified"), "sun behind large cloud", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji SUN_BEHIND_LARGE_CLOUD_UNQUALIFIED = new Emoji("\ud83c\udf25", "\\uD83C\\uDF25", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("behind", "cloud", "sun", "weather")), false, false, 0.7, Qualification.fromString("unqualified"), "sun behind large cloud", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji SUN_BEHIND_RAIN_CLOUD = new Emoji("\ud83c\udf26\ufe0f", "\\uD83C\\uDF26\\uFE0F", Collections.unmodifiableList(Arrays.asList(":white_sun_rain_cloud:", ":white_sun_behind_cloud_with_rain:")), Collections.unmodifiableList(Arrays.asList(":partly_sunny_rain:", ":sun_behind_rain_cloud:")), Collections.singletonList(":sun_behind_rain_cloud:"), Collections.unmodifiableList(Arrays.asList("behind", "cloud", "rain", "sun", "weather")), false, false, 0.7, Qualification.fromString("fully-qualified"), "sun behind rain cloud", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji SUN_BEHIND_RAIN_CLOUD_UNQUALIFIED = new Emoji("\ud83c\udf26", "\\uD83C\\uDF26", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("behind", "cloud", "rain", "sun", "weather")), false, false, 0.7, Qualification.fromString("unqualified"), "sun behind rain cloud", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji CLOUD_WITH_RAIN = new Emoji("\ud83c\udf27\ufe0f", "\\uD83C\\uDF27\\uFE0F", Collections.unmodifiableList(Arrays.asList(":cloud_rain:", ":cloud_with_rain:")), Collections.singletonList(":rain_cloud:"), Collections.singletonList(":cloud_with_rain:"), Collections.unmodifiableList(Arrays.asList("cloud", "rain", "weather")), false, false, 0.7, Qualification.fromString("fully-qualified"), "cloud with rain", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji CLOUD_WITH_RAIN_UNQUALIFIED = new Emoji("\ud83c\udf27", "\\uD83C\\uDF27", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cloud", "rain", "weather")), false, false, 0.7, Qualification.fromString("unqualified"), "cloud with rain", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji CLOUD_WITH_SNOW = new Emoji("\ud83c\udf28\ufe0f", "\\uD83C\\uDF28\\uFE0F", Collections.unmodifiableList(Arrays.asList(":cloud_snow:", ":cloud_with_snow:")), Collections.singletonList(":snow_cloud:"), Collections.singletonList(":cloud_with_snow:"), Collections.unmodifiableList(Arrays.asList("cloud", "cold", "snow", "weather")), false, false, 0.7, Qualification.fromString("fully-qualified"), "cloud with snow", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji CLOUD_WITH_SNOW_UNQUALIFIED = new Emoji("\ud83c\udf28", "\\uD83C\\uDF28", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cloud", "cold", "snow", "weather")), false, false, 0.7, Qualification.fromString("unqualified"), "cloud with snow", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji CLOUD_WITH_LIGHTNING = new Emoji("\ud83c\udf29\ufe0f", "\\uD83C\\uDF29\\uFE0F", Collections.unmodifiableList(Arrays.asList(":cloud_lightning:", ":cloud_with_lightning:")), Collections.unmodifiableList(Arrays.asList(":lightning:", ":lightning_cloud:")), Collections.singletonList(":cloud_with_lightning:"), Collections.unmodifiableList(Arrays.asList("cloud", "lightning", "weather")), false, false, 0.7, Qualification.fromString("fully-qualified"), "cloud with lightning", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji CLOUD_WITH_LIGHTNING_UNQUALIFIED = new Emoji("\ud83c\udf29", "\\uD83C\\uDF29", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cloud", "lightning", "weather")), false, false, 0.7, Qualification.fromString("unqualified"), "cloud with lightning", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji TORNADO = new Emoji("\ud83c\udf2a\ufe0f", "\\uD83C\\uDF2A\\uFE0F", Collections.unmodifiableList(Arrays.asList(":cloud_tornado:", ":cloud_with_tornado:", ":tornado:")), Collections.unmodifiableList(Arrays.asList(":tornado:", ":tornado_cloud:")), Collections.singletonList(":tornado:"), Collections.unmodifiableList(Arrays.asList("cloud", "tornado", "weather", "whirlwind")), false, false, 0.7, Qualification.fromString("fully-qualified"), "tornado", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji TORNADO_UNQUALIFIED = new Emoji("\ud83c\udf2a", "\\uD83C\\uDF2A", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cloud", "tornado", "weather", "whirlwind")), false, false, 0.7, Qualification.fromString("unqualified"), "tornado", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji FOG = new Emoji("\ud83c\udf2b\ufe0f", "\\uD83C\\uDF2B\\uFE0F", Collections.singletonList(":fog:"), Collections.singletonList(":fog:"), Collections.singletonList(":fog:"), Collections.unmodifiableList(Arrays.asList("cloud", "fog", "weather")), false, false, 0.7, Qualification.fromString("fully-qualified"), "fog", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji FOG_UNQUALIFIED = new Emoji("\ud83c\udf2b", "\\uD83C\\uDF2B", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cloud", "fog", "weather")), false, false, 0.7, Qualification.fromString("unqualified"), "fog", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji WIND_FACE = new Emoji("\ud83c\udf2c\ufe0f", "\\uD83C\\uDF2C\\uFE0F", Collections.unmodifiableList(Arrays.asList(":wind_blowing_face:", ":wind_face:")), Collections.singletonList(":wind_blowing_face:"), Collections.singletonList(":wind_face:"), Collections.unmodifiableList(Arrays.asList("blow", "cloud", "face", "wind")), false, false, 0.7, Qualification.fromString("fully-qualified"), "wind face", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji WIND_FACE_UNQUALIFIED = new Emoji("\ud83c\udf2c", "\\uD83C\\uDF2C", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("blow", "cloud", "face", "wind")), false, false, 0.7, Qualification.fromString("unqualified"), "wind face", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji CYCLONE = new Emoji("\ud83c\udf00", "\\uD83C\\uDF00", Collections.singletonList(":cyclone:"), Collections.singletonList(":cyclone:"), Collections.singletonList(":cyclone:"), Collections.unmodifiableList(Arrays.asList("cyclone", "dizzy", "hurricane", "twister", "typhoon", "weather")), false, false, 0.6, Qualification.fromString("fully-qualified"), "cyclone", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji RAINBOW = new Emoji("\ud83c\udf08", "\\uD83C\\uDF08", Collections.singletonList(":rainbow:"), Collections.singletonList(":rainbow:"), Collections.singletonList(":rainbow:"), Collections.unmodifiableList(Arrays.asList("gay", "genderqueer", "glbt", "glbtq", "lesbian", "lgbt", "lgbtq", "lgbtqia", "nature", "pride", "queer", "rain", "rainbow", "trans", "transgender", "weather")), false, false, 0.6, Qualification.fromString("fully-qualified"), "rainbow", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji CLOSED_UMBRELLA = new Emoji("\ud83c\udf02", "\\uD83C\\uDF02", Collections.singletonList(":closed_umbrella:"), Collections.singletonList(":closed_umbrella:"), Collections.singletonList(":closed_umbrella:"), Collections.unmodifiableList(Arrays.asList("closed", "clothing", "rain", "umbrella")), false, false, 0.6, Qualification.fromString("fully-qualified"), "closed umbrella", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji UMBRELLA = new Emoji("\u2602\ufe0f", "\\u2602\\uFE0F", Collections.singletonList(":umbrella2:"), Collections.singletonList(":umbrella:"), Collections.singletonList(":open_umbrella:"), Collections.unmodifiableList(Arrays.asList("clothing", "rain", "umbrella")), false, false, 0.7, Qualification.fromString("fully-qualified"), "umbrella", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji UMBRELLA_UNQUALIFIED = new Emoji("\u2602", "\\u2602", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("clothing", "rain", "umbrella")), false, false, 0.7, Qualification.fromString("unqualified"), "umbrella", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji UMBRELLA_WITH_RAIN_DROPS = new Emoji("\u2614", "\\u2614", Collections.singletonList(":umbrella:"), Collections.singletonList(":umbrella_with_rain_drops:"), Collections.singletonList(":umbrella:"), Collections.unmodifiableList(Arrays.asList("clothing", "drop", "drops", "rain", "umbrella", "weather")), false, false, 0.6, Qualification.fromString("fully-qualified"), "umbrella with rain drops", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji UMBRELLA_ON_GROUND = new Emoji("\u26f1\ufe0f", "\\u26F1\\uFE0F", Collections.unmodifiableList(Arrays.asList(":beach_umbrella:", ":umbrella_on_ground:")), Collections.singletonList(":umbrella_on_ground:"), Collections.singletonList(":parasol_on_ground:"), Collections.unmodifiableList(Arrays.asList("ground", "rain", "sun", "umbrella")), false, false, 0.7, Qualification.fromString("fully-qualified"), "umbrella on ground", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji UMBRELLA_ON_GROUND_UNQUALIFIED = new Emoji("\u26f1", "\\u26F1", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("ground", "rain", "sun", "umbrella")), false, false, 0.7, Qualification.fromString("unqualified"), "umbrella on ground", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji HIGH_VOLTAGE = new Emoji("\u26a1", "\\u26A1", Collections.unmodifiableList(Arrays.asList(":zap:", ":high_voltage:")), Collections.singletonList(":zap:"), Collections.singletonList(":zap:"), Collections.unmodifiableList(Arrays.asList("danger", "electric", "electricity", "high", "lightning", "nature", "thunder", "thunderbolt", "voltage", "zap")), false, false, 0.6, Qualification.fromString("fully-qualified"), "high voltage", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji SNOWFLAKE = new Emoji("\u2744\ufe0f", "\\u2744\\uFE0F", Collections.singletonList(":snowflake:"), Collections.singletonList(":snowflake:"), Collections.singletonList(":snowflake:"), Collections.unmodifiableList(Arrays.asList("cold", "snow", "snowflake", "weather")), false, false, 0.6, Qualification.fromString("fully-qualified"), "snowflake", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji SNOWFLAKE_UNQUALIFIED = new Emoji("\u2744", "\\u2744", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cold", "snow", "snowflake", "weather")), false, false, 0.6, Qualification.fromString("unqualified"), "snowflake", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji SNOWMAN = new Emoji("\u2603\ufe0f", "\\u2603\\uFE0F", Collections.singletonList(":snowman2:"), Collections.singletonList(":snowman:"), Collections.singletonList(":snowman_with_snow:"), Collections.unmodifiableList(Arrays.asList("cold", "man", "snow", "snowman")), false, false, 0.7, Qualification.fromString("fully-qualified"), "snowman", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji SNOWMAN_UNQUALIFIED = new Emoji("\u2603", "\\u2603", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("cold", "man", "snow", "snowman")), false, false, 0.7, Qualification.fromString("unqualified"), "snowman", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji SNOWMAN_WITHOUT_SNOW = new Emoji("\u26c4", "\\u26C4", Collections.singletonList(":snowman:"), Collections.singletonList(":snowman_without_snow:"), Collections.singletonList(":snowman:"), Collections.unmodifiableList(Arrays.asList("cold", "man", "snow", "snowman")), false, false, 0.6, Qualification.fromString("fully-qualified"), "snowman without snow", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji COMET = new Emoji("\u2604\ufe0f", "\\u2604\\uFE0F", Collections.singletonList(":comet:"), Collections.singletonList(":comet:"), Collections.singletonList(":comet:"), Collections.unmodifiableList(Arrays.asList("comet", "space")), false, false, 1.0, Qualification.fromString("fully-qualified"), "comet", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji COMET_UNQUALIFIED = new Emoji("\u2604", "\\u2604", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("comet", "space")), false, false, 1.0, Qualification.fromString("unqualified"), "comet", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, true);
    public static final Emoji FIRE = new Emoji("\ud83d\udd25", "\\uD83D\\uDD25", Collections.unmodifiableList(Arrays.asList(":fire:", ":flame:")), Collections.singletonList(":fire:"), Collections.singletonList(":fire:"), Collections.unmodifiableList(Arrays.asList("af", "burn", "fire", "flame", "hot", "lit", "litaf", "tool")), false, false, 0.6, Qualification.fromString("fully-qualified"), "fire", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji DROPLET = new Emoji("\ud83d\udca7", "\\uD83D\\uDCA7", Collections.singletonList(":droplet:"), Collections.singletonList(":droplet:"), Collections.singletonList(":droplet:"), Collections.unmodifiableList(Arrays.asList("cold", "comic", "drop", "droplet", "nature", "sad", "sweat", "tear", "water", "weather")), false, false, 0.6, Qualification.fromString("fully-qualified"), "droplet", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
    public static final Emoji WATER_WAVE = new Emoji("\ud83c\udf0a", "\\uD83C\\uDF0A", Collections.unmodifiableList(Arrays.asList(":ocean:", ":water_wave:")), Collections.singletonList(":ocean:"), Collections.singletonList(":ocean:"), Collections.unmodifiableList(Arrays.asList("nature", "ocean", "surf", "surfer", "surfing", "water", "wave")), false, false, 0.6, Qualification.fromString("fully-qualified"), "water wave", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.SKY_AND_WEATHER, false);
}

