/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiFoodVegetable {
    public static final Emoji AVOCADO = new Emoji("\ud83e\udd51", "\\uD83E\\uDD51", Collections.singletonList(":avocado:"), Collections.singletonList(":avocado:"), Collections.singletonList(":avocado:"), Collections.unmodifiableList(Arrays.asList("avocado", "food", "fruit")), false, false, 3.0, Qualification.fromString("fully-qualified"), "avocado", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji EGGPLANT = new Emoji("\ud83c\udf46", "\\uD83C\\uDF46", Collections.singletonList(":eggplant:"), Collections.singletonList(":eggplant:"), Collections.singletonList(":eggplant:"), Collections.unmodifiableList(Arrays.asList("aubergine", "eggplant", "vegetable")), false, false, 0.6, Qualification.fromString("fully-qualified"), "eggplant", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji POTATO = new Emoji("\ud83e\udd54", "\\uD83E\\uDD54", Collections.singletonList(":potato:"), Collections.singletonList(":potato:"), Collections.singletonList(":potato:"), Collections.unmodifiableList(Arrays.asList("food", "potato", "vegetable")), false, false, 3.0, Qualification.fromString("fully-qualified"), "potato", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji CARROT = new Emoji("\ud83e\udd55", "\\uD83E\\uDD55", Collections.singletonList(":carrot:"), Collections.singletonList(":carrot:"), Collections.singletonList(":carrot:"), Collections.unmodifiableList(Arrays.asList("carrot", "food", "vegetable")), false, false, 3.0, Qualification.fromString("fully-qualified"), "carrot", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji EAR_OF_CORN = new Emoji("\ud83c\udf3d", "\\uD83C\\uDF3D", Collections.unmodifiableList(Arrays.asList(":corn:", ":ear_of_corn:")), Collections.singletonList(":corn:"), Collections.singletonList(":corn:"), Collections.unmodifiableList(Arrays.asList("corn", "crops", "ear", "farm", "maize", "maze")), false, false, 0.6, Qualification.fromString("fully-qualified"), "ear of corn", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji HOT_PEPPER = new Emoji("\ud83c\udf36\ufe0f", "\\uD83C\\uDF36\\uFE0F", Collections.singletonList(":hot_pepper:"), Collections.singletonList(":hot_pepper:"), Collections.singletonList(":hot_pepper:"), Collections.unmodifiableList(Arrays.asList("hot", "pepper")), false, false, 0.7, Qualification.fromString("fully-qualified"), "hot pepper", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji HOT_PEPPER_UNQUALIFIED = new Emoji("\ud83c\udf36", "\\uD83C\\uDF36", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("hot", "pepper")), false, false, 0.7, Qualification.fromString("unqualified"), "hot pepper", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, true);
    public static final Emoji BELL_PEPPER = new Emoji("\ud83e\uded1", "\\uD83E\\uDED1", Collections.singletonList(":bell_pepper:"), Collections.singletonList(":bell_pepper:"), Collections.singletonList(":bell_pepper:"), Collections.unmodifiableList(Arrays.asList("bell", "capsicum", "food", "pepper", "vegetable")), false, false, 13.0, Qualification.fromString("fully-qualified"), "bell pepper", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji CUCUMBER = new Emoji("\ud83e\udd52", "\\uD83E\\uDD52", Collections.singletonList(":cucumber:"), Collections.singletonList(":cucumber:"), Collections.singletonList(":cucumber:"), Collections.unmodifiableList(Arrays.asList("cucumber", "food", "pickle", "vegetable")), false, false, 3.0, Qualification.fromString("fully-qualified"), "cucumber", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji LEAFY_GREEN = new Emoji("\ud83e\udd6c", "\\uD83E\\uDD6C", Collections.singletonList(":leafy_green:"), Collections.singletonList(":leafy_green:"), Collections.singletonList(":leafy_green:"), Collections.unmodifiableList(Arrays.asList("bok", "burgers", "cabbage", "choy", "green", "kale", "leafy", "lettuce", "salad")), false, false, 11.0, Qualification.fromString("fully-qualified"), "leafy green", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji BROCCOLI = new Emoji("\ud83e\udd66", "\\uD83E\\uDD66", Collections.singletonList(":broccoli:"), Collections.singletonList(":broccoli:"), Collections.singletonList(":broccoli:"), Collections.unmodifiableList(Arrays.asList("broccoli", "cabbage", "wild")), false, false, 5.0, Qualification.fromString("fully-qualified"), "broccoli", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji GARLIC = new Emoji("\ud83e\uddc4", "\\uD83E\\uDDC4", Collections.singletonList(":garlic:"), Collections.singletonList(":garlic:"), Collections.singletonList(":garlic:"), Collections.unmodifiableList(Arrays.asList("flavoring", "garlic")), false, false, 12.0, Qualification.fromString("fully-qualified"), "garlic", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji ONION = new Emoji("\ud83e\uddc5", "\\uD83E\\uDDC5", Collections.singletonList(":onion:"), Collections.singletonList(":onion:"), Collections.singletonList(":onion:"), Collections.unmodifiableList(Arrays.asList("flavoring", "onion")), false, false, 12.0, Qualification.fromString("fully-qualified"), "onion", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji PEANUTS = new Emoji("\ud83e\udd5c", "\\uD83E\\uDD5C", Collections.unmodifiableList(Arrays.asList(":peanuts:", ":shelled_peanut:")), Collections.singletonList(":peanuts:"), Collections.singletonList(":peanuts:"), Collections.unmodifiableList(Arrays.asList("food", "nut", "peanut", "peanuts", "vegetable")), false, false, 3.0, Qualification.fromString("fully-qualified"), "peanuts", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji BEANS = new Emoji("\ud83e\uded8", "\\uD83E\\uDED8", Collections.singletonList(":beans:"), Collections.singletonList(":beans:"), Collections.singletonList(":beans:"), Collections.unmodifiableList(Arrays.asList("beans", "food", "kidney", "legume", "small")), false, false, 14.0, Qualification.fromString("fully-qualified"), "beans", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji CHESTNUT = new Emoji("\ud83c\udf30", "\\uD83C\\uDF30", Collections.singletonList(":chestnut:"), Collections.singletonList(":chestnut:"), Collections.singletonList(":chestnut:"), Collections.unmodifiableList(Arrays.asList("almond", "chestnut", "plant")), false, false, 0.6, Qualification.fromString("fully-qualified"), "chestnut", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji GINGER_ROOT = new Emoji("\ud83e\udeda", "\\uD83E\\uDEDA", Collections.singletonList(":ginger_root:"), Collections.emptyList(), Collections.singletonList(":ginger_root:"), Collections.unmodifiableList(Arrays.asList("beer", "ginger", "health", "herb", "natural", "root", "spice")), false, false, 15.0, Qualification.fromString("fully-qualified"), "ginger root", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji PEA_POD = new Emoji("\ud83e\udedb", "\\uD83E\\uDEDB", Collections.singletonList(":pea_pod:"), Collections.emptyList(), Collections.singletonList(":pea_pod:"), Collections.unmodifiableList(Arrays.asList("beans", "beanstalk", "edamame", "legume", "pea", "pod", "soybean", "vegetable", "veggie")), false, false, 15.0, Qualification.fromString("fully-qualified"), "pea pod", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji BROWN_MUSHROOM = new Emoji("\ud83c\udf44\u200d\ud83d\udfeb", "\\uD83C\\uDF44\\u200D\\uD83D\\uDFEB", Collections.singletonList(":brown_mushroom:"), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("food", "fungi", "fungus", "mushroom", "nature", "pizza", "portobello", "shiitake", "shroom", "spore", "sprout", "toppings", "truffle", "vegetable", "vegetarian", "veggie")), false, false, 15.1, Qualification.fromString("fully-qualified"), "brown mushroom", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
    public static final Emoji ROOT_VEGETABLE = new Emoji("\ud83e\udedc", "\\uD83E\\uDEDC", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("beet", "food", "garden", "radish", "root", "salad", "turnip", "vegetable", "vegetarian")), false, false, 16.0, Qualification.fromString("fully-qualified"), "root vegetable", EmojiGroup.FOOD_AND_DRINK, EmojiSubGroup.FOOD_VEGETABLE, false);
}

