/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiPlaceBuilding {
    public static final Emoji STADIUM = new Emoji("\ud83c\udfdf\ufe0f", "\\uD83C\\uDFDF\\uFE0F", Collections.singletonList(":stadium:"), Collections.singletonList(":stadium:"), Collections.singletonList(":stadium:"), Collections.singletonList("stadium"), false, false, 0.7, Qualification.fromString("fully-qualified"), "stadium", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji STADIUM_UNQUALIFIED = new Emoji("\ud83c\udfdf", "\\uD83C\\uDFDF", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.singletonList("stadium"), false, false, 0.7, Qualification.fromString("unqualified"), "stadium", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, true);
    public static final Emoji CLASSICAL_BUILDING = new Emoji("\ud83c\udfdb\ufe0f", "\\uD83C\\uDFDB\\uFE0F", Collections.singletonList(":classical_building:"), Collections.singletonList(":classical_building:"), Collections.singletonList(":classical_building:"), Collections.unmodifiableList(Arrays.asList("building", "classical")), false, false, 0.7, Qualification.fromString("fully-qualified"), "classical building", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji CLASSICAL_BUILDING_UNQUALIFIED = new Emoji("\ud83c\udfdb", "\\uD83C\\uDFDB", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("building", "classical")), false, false, 0.7, Qualification.fromString("unqualified"), "classical building", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, true);
    public static final Emoji BUILDING_CONSTRUCTION = new Emoji("\ud83c\udfd7\ufe0f", "\\uD83C\\uDFD7\\uFE0F", Collections.unmodifiableList(Arrays.asList(":construction_site:", ":building_construction:")), Collections.singletonList(":building_construction:"), Collections.singletonList(":building_construction:"), Collections.unmodifiableList(Arrays.asList("building", "construction", "crane")), false, false, 0.7, Qualification.fromString("fully-qualified"), "building construction", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji BUILDING_CONSTRUCTION_UNQUALIFIED = new Emoji("\ud83c\udfd7", "\\uD83C\\uDFD7", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("building", "construction", "crane")), false, false, 0.7, Qualification.fromString("unqualified"), "building construction", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, true);
    public static final Emoji BRICK = new Emoji("\ud83e\uddf1", "\\uD83E\\uDDF1", Collections.unmodifiableList(Arrays.asList(":bricks:", ":brick:")), Collections.singletonList(":bricks:"), Collections.singletonList(":bricks:"), Collections.unmodifiableList(Arrays.asList("brick", "bricks", "clay", "mortar", "wall")), false, false, 11.0, Qualification.fromString("fully-qualified"), "brick", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji ROCK = new Emoji("\ud83e\udea8", "\\uD83E\\uDEA8", Collections.singletonList(":rock:"), Collections.singletonList(":rock:"), Collections.singletonList(":rock:"), Collections.unmodifiableList(Arrays.asList("boulder", "heavy", "rock", "solid", "stone", "tough")), false, false, 13.0, Qualification.fromString("fully-qualified"), "rock", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji WOOD = new Emoji("\ud83e\udeb5", "\\uD83E\\uDEB5", Collections.singletonList(":wood:"), Collections.singletonList(":wood:"), Collections.singletonList(":wood:"), Collections.unmodifiableList(Arrays.asList("log", "lumber", "timber", "wood")), false, false, 13.0, Qualification.fromString("fully-qualified"), "wood", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji HUT = new Emoji("\ud83d\uded6", "\\uD83D\\uDED6", Collections.singletonList(":hut:"), Collections.singletonList(":hut:"), Collections.singletonList(":hut:"), Collections.unmodifiableList(Arrays.asList("home", "house", "hut", "roundhouse", "shelter", "yurt")), false, false, 13.0, Qualification.fromString("fully-qualified"), "hut", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji HOUSES = new Emoji("\ud83c\udfd8\ufe0f", "\\uD83C\\uDFD8\\uFE0F", Collections.unmodifiableList(Arrays.asList(":homes:", ":house_buildings:", ":houses:")), Collections.singletonList(":house_buildings:"), Collections.singletonList(":houses:"), Collections.unmodifiableList(Arrays.asList("house", "houses")), false, false, 0.7, Qualification.fromString("fully-qualified"), "houses", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji HOUSES_UNQUALIFIED = new Emoji("\ud83c\udfd8", "\\uD83C\\uDFD8", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("house", "houses")), false, false, 0.7, Qualification.fromString("unqualified"), "houses", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, true);
    public static final Emoji DERELICT_HOUSE = new Emoji("\ud83c\udfda\ufe0f", "\\uD83C\\uDFDA\\uFE0F", Collections.unmodifiableList(Arrays.asList(":house_abandoned:", ":derelict_house_building:")), Collections.singletonList(":derelict_house_building:"), Collections.singletonList(":derelict_house:"), Collections.unmodifiableList(Arrays.asList("derelict", "home", "house")), false, false, 0.7, Qualification.fromString("fully-qualified"), "derelict house", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji DERELICT_HOUSE_UNQUALIFIED = new Emoji("\ud83c\udfda", "\\uD83C\\uDFDA", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("derelict", "home", "house")), false, false, 0.7, Qualification.fromString("unqualified"), "derelict house", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, true);
    public static final Emoji HOUSE = new Emoji("\ud83c\udfe0", "\\uD83C\\uDFE0", Collections.singletonList(":house:"), Collections.singletonList(":house:"), Collections.singletonList(":house:"), Collections.unmodifiableList(Arrays.asList("building", "country", "heart", "home", "house", "ranch", "settle", "simple", "suburban", "suburbia", "where")), false, false, 0.6, Qualification.fromString("fully-qualified"), "house", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, true);
    public static final Emoji HOUSE_WITH_GARDEN = new Emoji("\ud83c\udfe1", "\\uD83C\\uDFE1", Collections.singletonList(":house_with_garden:"), Collections.singletonList(":house_with_garden:"), Collections.singletonList(":house_with_garden:"), Collections.unmodifiableList(Arrays.asList("building", "country", "garden", "heart", "home", "house", "ranch", "settle", "simple", "suburban", "suburbia", "where")), false, false, 0.6, Qualification.fromString("fully-qualified"), "house with garden", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji OFFICE_BUILDING = new Emoji("\ud83c\udfe2", "\\uD83C\\uDFE2", Collections.singletonList(":office:"), Collections.singletonList(":office:"), Collections.singletonList(":office:"), Collections.unmodifiableList(Arrays.asList("building", "city", "cubical", "job", "office")), false, false, 0.6, Qualification.fromString("fully-qualified"), "office building", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji JAPANESE_POST_OFFICE = new Emoji("\ud83c\udfe3", "\\uD83C\\uDFE3", Collections.singletonList(":post_office:"), Collections.singletonList(":post_office:"), Collections.singletonList(":post_office:"), Collections.unmodifiableList(Arrays.asList("building", "Japanese", "office", "post")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese post office", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji POST_OFFICE = new Emoji("\ud83c\udfe4", "\\uD83C\\uDFE4", Collections.singletonList(":european_post_office:"), Collections.singletonList(":european_post_office:"), Collections.singletonList(":european_post_office:"), Collections.unmodifiableList(Arrays.asList("building", "European", "office", "post")), false, false, 1.0, Qualification.fromString("fully-qualified"), "post office", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji HOSPITAL = new Emoji("\ud83c\udfe5", "\\uD83C\\uDFE5", Collections.singletonList(":hospital:"), Collections.singletonList(":hospital:"), Collections.singletonList(":hospital:"), Collections.unmodifiableList(Arrays.asList("building", "doctor", "hospital", "medicine")), false, false, 0.6, Qualification.fromString("fully-qualified"), "hospital", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji BANK = new Emoji("\ud83c\udfe6", "\\uD83C\\uDFE6", Collections.singletonList(":bank:"), Collections.singletonList(":bank:"), Collections.singletonList(":bank:"), Collections.unmodifiableList(Arrays.asList("bank", "building")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bank", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji HOTEL = new Emoji("\ud83c\udfe8", "\\uD83C\\uDFE8", Collections.singletonList(":hotel:"), Collections.singletonList(":hotel:"), Collections.singletonList(":hotel:"), Collections.unmodifiableList(Arrays.asList("building", "hotel")), false, false, 0.6, Qualification.fromString("fully-qualified"), "hotel", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji LOVE_HOTEL = new Emoji("\ud83c\udfe9", "\\uD83C\\uDFE9", Collections.singletonList(":love_hotel:"), Collections.singletonList(":love_hotel:"), Collections.singletonList(":love_hotel:"), Collections.unmodifiableList(Arrays.asList("building", "hotel", "love")), false, false, 0.6, Qualification.fromString("fully-qualified"), "love hotel", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji CONVENIENCE_STORE = new Emoji("\ud83c\udfea", "\\uD83C\\uDFEA", Collections.singletonList(":convenience_store:"), Collections.singletonList(":convenience_store:"), Collections.singletonList(":convenience_store:"), Collections.unmodifiableList(Arrays.asList("24", "building", "convenience", "hours", "store")), false, false, 0.6, Qualification.fromString("fully-qualified"), "convenience store", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji SCHOOL = new Emoji("\ud83c\udfeb", "\\uD83C\\uDFEB", Collections.singletonList(":school:"), Collections.singletonList(":school:"), Collections.singletonList(":school:"), Collections.unmodifiableList(Arrays.asList("building", "school")), false, false, 0.6, Qualification.fromString("fully-qualified"), "school", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji DEPARTMENT_STORE = new Emoji("\ud83c\udfec", "\\uD83C\\uDFEC", Collections.singletonList(":department_store:"), Collections.singletonList(":department_store:"), Collections.singletonList(":department_store:"), Collections.unmodifiableList(Arrays.asList("building", "department", "store")), false, false, 0.6, Qualification.fromString("fully-qualified"), "department store", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji FACTORY = new Emoji("\ud83c\udfed", "\\uD83C\\uDFED", Collections.singletonList(":factory:"), Collections.singletonList(":factory:"), Collections.singletonList(":factory:"), Collections.unmodifiableList(Arrays.asList("building", "factory")), false, false, 0.6, Qualification.fromString("fully-qualified"), "factory", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, true);
    public static final Emoji JAPANESE_CASTLE = new Emoji("\ud83c\udfef", "\\uD83C\\uDFEF", Collections.singletonList(":japanese_castle:"), Collections.singletonList(":japanese_castle:"), Collections.singletonList(":japanese_castle:"), Collections.unmodifiableList(Arrays.asList("building", "castle", "Japanese")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Japanese castle", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji CASTLE = new Emoji("\ud83c\udff0", "\\uD83C\\uDFF0", Collections.unmodifiableList(Arrays.asList(":european_castle:", ":castle:")), Collections.singletonList(":european_castle:"), Collections.singletonList(":european_castle:"), Collections.unmodifiableList(Arrays.asList("building", "castle", "European")), false, false, 0.6, Qualification.fromString("fully-qualified"), "castle", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji WEDDING = new Emoji("\ud83d\udc92", "\\uD83D\\uDC92", Collections.singletonList(":wedding:"), Collections.singletonList(":wedding:"), Collections.singletonList(":wedding:"), Collections.unmodifiableList(Arrays.asList("chapel", "hitched", "nuptials", "romance", "wedding")), false, false, 0.6, Qualification.fromString("fully-qualified"), "wedding", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji TOKYO_TOWER = new Emoji("\ud83d\uddfc", "\\uD83D\\uDDFC", Collections.singletonList(":tokyo_tower:"), Collections.singletonList(":tokyo_tower:"), Collections.singletonList(":tokyo_tower:"), Collections.unmodifiableList(Arrays.asList("Tokyo", "tower")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Tokyo tower", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
    public static final Emoji STATUE_OF_LIBERTY = new Emoji("\ud83d\uddfd", "\\uD83D\\uDDFD", Collections.singletonList(":statue_of_liberty:"), Collections.singletonList(":statue_of_liberty:"), Collections.singletonList(":statue_of_liberty:"), Collections.unmodifiableList(Arrays.asList("liberty", "Liberty", "new", "ny", "nyc", "statue", "Statue", "york")), false, false, 0.6, Qualification.fromString("fully-qualified"), "Statue of Liberty", EmojiGroup.TRAVEL_AND_PLACES, EmojiSubGroup.PLACE_BUILDING, false);
}

