/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiSport {
    public static final Emoji SOCCER_BALL = new Emoji("\u26bd", "\\u26BD", Collections.unmodifiableList(Arrays.asList(":soccer:", ":soccer_ball:")), Collections.singletonList(":soccer:"), Collections.singletonList(":soccer:"), Collections.unmodifiableList(Arrays.asList("ball", "football", "futbol", "soccer", "sport")), false, false, 0.6, Qualification.fromString("fully-qualified"), "soccer ball", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, true);
    public static final Emoji BASEBALL = new Emoji("\u26be", "\\u26BE", Collections.singletonList(":baseball:"), Collections.singletonList(":baseball:"), Collections.singletonList(":baseball:"), Collections.unmodifiableList(Arrays.asList("ball", "baseball", "sport")), false, false, 0.6, Qualification.fromString("fully-qualified"), "baseball", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, true);
    public static final Emoji SOFTBALL = new Emoji("\ud83e\udd4e", "\\uD83E\\uDD4E", Collections.singletonList(":softball:"), Collections.singletonList(":softball:"), Collections.singletonList(":softball:"), Collections.unmodifiableList(Arrays.asList("ball", "glove", "softball", "sports", "underarm")), false, false, 11.0, Qualification.fromString("fully-qualified"), "softball", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji BASKETBALL = new Emoji("\ud83c\udfc0", "\\uD83C\\uDFC0", Collections.singletonList(":basketball:"), Collections.singletonList(":basketball:"), Collections.singletonList(":basketball:"), Collections.unmodifiableList(Arrays.asList("ball", "basketball", "hoop", "sport")), false, false, 0.6, Qualification.fromString("fully-qualified"), "basketball", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji VOLLEYBALL = new Emoji("\ud83c\udfd0", "\\uD83C\\uDFD0", Collections.singletonList(":volleyball:"), Collections.singletonList(":volleyball:"), Collections.singletonList(":volleyball:"), Collections.unmodifiableList(Arrays.asList("ball", "game", "volleyball")), false, false, 1.0, Qualification.fromString("fully-qualified"), "volleyball", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji AMERICAN_FOOTBALL = new Emoji("\ud83c\udfc8", "\\uD83C\\uDFC8", Collections.singletonList(":football:"), Collections.singletonList(":football:"), Collections.singletonList(":football:"), Collections.unmodifiableList(Arrays.asList("american", "ball", "bowl", "football", "sport", "super")), false, false, 0.6, Qualification.fromString("fully-qualified"), "american football", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji RUGBY_FOOTBALL = new Emoji("\ud83c\udfc9", "\\uD83C\\uDFC9", Collections.singletonList(":rugby_football:"), Collections.singletonList(":rugby_football:"), Collections.singletonList(":rugby_football:"), Collections.unmodifiableList(Arrays.asList("ball", "football", "rugby", "sport")), false, false, 1.0, Qualification.fromString("fully-qualified"), "rugby football", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji TENNIS = new Emoji("\ud83c\udfbe", "\\uD83C\\uDFBE", Collections.singletonList(":tennis:"), Collections.singletonList(":tennis:"), Collections.singletonList(":tennis:"), Collections.unmodifiableList(Arrays.asList("ball", "racquet", "sport", "tennis")), false, false, 0.6, Qualification.fromString("fully-qualified"), "tennis", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji FLYING_DISC = new Emoji("\ud83e\udd4f", "\\uD83E\\uDD4F", Collections.singletonList(":flying_disc:"), Collections.singletonList(":flying_disc:"), Collections.singletonList(":flying_disc:"), Collections.unmodifiableList(Arrays.asList("disc", "flying", "ultimate")), false, false, 11.0, Qualification.fromString("fully-qualified"), "flying disc", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji BOWLING = new Emoji("\ud83c\udfb3", "\\uD83C\\uDFB3", Collections.singletonList(":bowling:"), Collections.singletonList(":bowling:"), Collections.singletonList(":bowling:"), Collections.unmodifiableList(Arrays.asList("ball", "bowling", "game", "sport", "strike")), false, false, 0.6, Qualification.fromString("fully-qualified"), "bowling", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji CRICKET_GAME = new Emoji("\ud83c\udfcf", "\\uD83C\\uDFCF", Collections.unmodifiableList(Arrays.asList(":cricket_game:", ":cricket_bat_ball:")), Collections.singletonList(":cricket_bat_and_ball:"), Collections.singletonList(":cricket_game:"), Collections.unmodifiableList(Arrays.asList("ball", "bat", "cricket", "game")), false, false, 1.0, Qualification.fromString("fully-qualified"), "cricket game", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji FIELD_HOCKEY = new Emoji("\ud83c\udfd1", "\\uD83C\\uDFD1", Collections.singletonList(":field_hockey:"), Collections.singletonList(":field_hockey_stick_and_ball:"), Collections.singletonList(":field_hockey:"), Collections.unmodifiableList(Arrays.asList("ball", "field", "game", "hockey", "stick")), false, false, 1.0, Qualification.fromString("fully-qualified"), "field hockey", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji ICE_HOCKEY = new Emoji("\ud83c\udfd2", "\\uD83C\\uDFD2", Collections.unmodifiableList(Arrays.asList(":hockey:", ":ice_hockey:")), Collections.singletonList(":ice_hockey_stick_and_puck:"), Collections.singletonList(":ice_hockey:"), Collections.unmodifiableList(Arrays.asList("game", "hockey", "ice", "puck", "stick")), false, false, 1.0, Qualification.fromString("fully-qualified"), "ice hockey", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji LACROSSE = new Emoji("\ud83e\udd4d", "\\uD83E\\uDD4D", Collections.singletonList(":lacrosse:"), Collections.singletonList(":lacrosse:"), Collections.singletonList(":lacrosse:"), Collections.unmodifiableList(Arrays.asList("ball", "goal", "lacrosse", "sports", "stick")), false, false, 11.0, Qualification.fromString("fully-qualified"), "lacrosse", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji PING_PONG = new Emoji("\ud83c\udfd3", "\\uD83C\\uDFD3", Collections.unmodifiableList(Arrays.asList(":ping_pong:", ":table_tennis:")), Collections.singletonList(":table_tennis_paddle_and_ball:"), Collections.singletonList(":ping_pong:"), Collections.unmodifiableList(Arrays.asList("ball", "bat", "game", "paddle", "ping", "pingpong", "pong", "table", "tennis")), false, false, 1.0, Qualification.fromString("fully-qualified"), "ping pong", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji BADMINTON = new Emoji("\ud83c\udff8", "\\uD83C\\uDFF8", Collections.singletonList(":badminton:"), Collections.singletonList(":badminton_racquet_and_shuttlecock:"), Collections.singletonList(":badminton:"), Collections.unmodifiableList(Arrays.asList("badminton", "birdie", "game", "racquet", "shuttlecock")), false, false, 1.0, Qualification.fromString("fully-qualified"), "badminton", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji BOXING_GLOVE = new Emoji("\ud83e\udd4a", "\\uD83E\\uDD4A", Collections.unmodifiableList(Arrays.asList(":boxing_glove:", ":boxing_gloves:")), Collections.singletonList(":boxing_glove:"), Collections.singletonList(":boxing_glove:"), Collections.unmodifiableList(Arrays.asList("boxing", "glove")), false, false, 3.0, Qualification.fromString("fully-qualified"), "boxing glove", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji MARTIAL_ARTS_UNIFORM = new Emoji("\ud83e\udd4b", "\\uD83E\\uDD4B", Collections.unmodifiableList(Arrays.asList(":martial_arts_uniform:", ":karate_uniform:")), Collections.singletonList(":martial_arts_uniform:"), Collections.singletonList(":martial_arts_uniform:"), Collections.unmodifiableList(Arrays.asList("arts", "judo", "karate", "martial", "taekwondo", "uniform")), false, false, 3.0, Qualification.fromString("fully-qualified"), "martial arts uniform", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji GOAL_NET = new Emoji("\ud83e\udd45", "\\uD83E\\uDD45", Collections.unmodifiableList(Arrays.asList(":goal:", ":goal_net:")), Collections.singletonList(":goal_net:"), Collections.singletonList(":goal_net:"), Collections.unmodifiableList(Arrays.asList("goal", "net")), false, false, 3.0, Qualification.fromString("fully-qualified"), "goal net", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji FLAG_IN_HOLE = new Emoji("\u26f3", "\\u26F3", Collections.unmodifiableList(Arrays.asList(":golf:", ":flag_in_hole:")), Collections.singletonList(":golf:"), Collections.singletonList(":golf:"), Collections.unmodifiableList(Arrays.asList("flag", "golf", "hole", "sport")), false, false, 0.6, Qualification.fromString("fully-qualified"), "flag in hole", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, true);
    public static final Emoji ICE_SKATE = new Emoji("\u26f8\ufe0f", "\\u26F8\\uFE0F", Collections.singletonList(":ice_skate:"), Collections.singletonList(":ice_skate:"), Collections.singletonList(":ice_skate:"), Collections.unmodifiableList(Arrays.asList("ice", "skate", "skating")), false, false, 0.7, Qualification.fromString("fully-qualified"), "ice skate", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji ICE_SKATE_UNQUALIFIED = new Emoji("\u26f8", "\\u26F8", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("ice", "skate", "skating")), false, false, 0.7, Qualification.fromString("unqualified"), "ice skate", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, true);
    public static final Emoji FISHING_POLE = new Emoji("\ud83c\udfa3", "\\uD83C\\uDFA3", Collections.unmodifiableList(Arrays.asList(":fishing_pole_and_fish:", ":fishing_pole:")), Collections.singletonList(":fishing_pole_and_fish:"), Collections.singletonList(":fishing_pole_and_fish:"), Collections.unmodifiableList(Arrays.asList("entertainment", "fish", "fishing", "pole", "sport")), false, false, 0.6, Qualification.fromString("fully-qualified"), "fishing pole", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji DIVING_MASK = new Emoji("\ud83e\udd3f", "\\uD83E\\uDD3F", Collections.singletonList(":diving_mask:"), Collections.singletonList(":diving_mask:"), Collections.singletonList(":diving_mask:"), Collections.unmodifiableList(Arrays.asList("diving", "mask", "scuba", "snorkeling")), false, false, 12.0, Qualification.fromString("fully-qualified"), "diving mask", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji RUNNING_SHIRT = new Emoji("\ud83c\udfbd", "\\uD83C\\uDFBD", Collections.unmodifiableList(Arrays.asList(":running_shirt_with_sash:", ":running_shirt:")), Collections.singletonList(":running_shirt_with_sash:"), Collections.singletonList(":running_shirt_with_sash:"), Collections.unmodifiableList(Arrays.asList("athletics", "running", "sash", "shirt")), false, false, 0.6, Qualification.fromString("fully-qualified"), "running shirt", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji SKIS = new Emoji("\ud83c\udfbf", "\\uD83C\\uDFBF", Collections.unmodifiableList(Arrays.asList(":ski:", ":skis:")), Collections.singletonList(":ski:"), Collections.singletonList(":ski:"), Collections.unmodifiableList(Arrays.asList("ski", "skis", "snow", "sport")), false, false, 0.6, Qualification.fromString("fully-qualified"), "skis", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji SLED = new Emoji("\ud83d\udef7", "\\uD83D\\uDEF7", Collections.singletonList(":sled:"), Collections.singletonList(":sled:"), Collections.singletonList(":sled:"), Collections.unmodifiableList(Arrays.asList("luge", "sled", "sledge", "sleigh", "snow", "toboggan")), false, false, 5.0, Qualification.fromString("fully-qualified"), "sled", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
    public static final Emoji CURLING_STONE = new Emoji("\ud83e\udd4c", "\\uD83E\\uDD4C", Collections.singletonList(":curling_stone:"), Collections.singletonList(":curling_stone:"), Collections.singletonList(":curling_stone:"), Collections.unmodifiableList(Arrays.asList("curling", "game", "rock", "stone")), false, false, 5.0, Qualification.fromString("fully-qualified"), "curling stone", EmojiGroup.ACTIVITIES, EmojiSubGroup.SPORT, false);
}

