/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiFaceUnwell {
    public static final Emoji FACE_WITH_MEDICAL_MASK = new Emoji("\ud83d\ude37", "\\uD83D\\uDE37", Collections.singletonList(":mask:"), Collections.singletonList(":mask:"), Collections.singletonList(":mask:"), Collections.unmodifiableList(Arrays.asList("cold", "dentist", "dermatologist", "doctor", "dr", "face", "germs", "mask", "medical", "medicine", "sick")), false, false, 0.6, Qualification.fromString("fully-qualified"), "face with medical mask", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_UNWELL, false);
    public static final Emoji FACE_WITH_THERMOMETER = new Emoji("\ud83e\udd12", "\\uD83E\\uDD12", Collections.unmodifiableList(Arrays.asList(":thermometer_face:", ":face_with_thermometer:")), Collections.singletonList(":face_with_thermometer:"), Collections.singletonList(":face_with_thermometer:"), Collections.unmodifiableList(Arrays.asList("face", "ill", "sick", "thermometer")), false, false, 1.0, Qualification.fromString("fully-qualified"), "face with thermometer", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_UNWELL, false);
    public static final Emoji FACE_WITH_HEAD_BANDAGE = new Emoji("\ud83e\udd15", "\\uD83E\\uDD15", Collections.unmodifiableList(Arrays.asList(":head_bandage:", ":face_with_head_bandage:")), Collections.singletonList(":face_with_head_bandage:"), Collections.singletonList(":face_with_head_bandage:"), Collections.unmodifiableList(Arrays.asList("bandage", "face", "head-bandage", "hurt", "injury", "ouch")), false, false, 1.0, Qualification.fromString("fully-qualified"), "face with head-bandage", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_UNWELL, false);
    public static final Emoji NAUSEATED_FACE = new Emoji("\ud83e\udd22", "\\uD83E\\uDD22", Collections.unmodifiableList(Arrays.asList(":nauseated_face:", ":sick:")), Collections.singletonList(":nauseated_face:"), Collections.singletonList(":nauseated_face:"), Collections.unmodifiableList(Arrays.asList("face", "gross", "nasty", "nauseated", "sick", "vomit")), false, false, 3.0, Qualification.fromString("fully-qualified"), "nauseated face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_UNWELL, false);
    public static final Emoji FACE_VOMITING = new Emoji("\ud83e\udd2e", "\\uD83E\\uDD2E", Collections.singletonList(":face_vomiting:"), Collections.unmodifiableList(Arrays.asList(":face_vomiting:", ":face_with_open_mouth_vomiting:")), Collections.singletonList(":vomiting_face:"), Collections.unmodifiableList(Arrays.asList("barf", "ew", "face", "gross", "puke", "sick", "spew", "throw", "up", "vomit", "vomiting")), false, false, 5.0, Qualification.fromString("fully-qualified"), "face vomiting", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_UNWELL, false);
    public static final Emoji SNEEZING_FACE = new Emoji("\ud83e\udd27", "\\uD83E\\uDD27", Collections.unmodifiableList(Arrays.asList(":sneezing_face:", ":sneeze:")), Collections.singletonList(":sneezing_face:"), Collections.singletonList(":sneezing_face:"), Collections.unmodifiableList(Arrays.asList("face", "fever", "flu", "gesundheit", "sick", "sneeze", "sneezing")), false, false, 3.0, Qualification.fromString("fully-qualified"), "sneezing face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_UNWELL, false);
    public static final Emoji HOT_FACE = new Emoji("\ud83e\udd75", "\\uD83E\\uDD75", Collections.singletonList(":hot_face:"), Collections.singletonList(":hot_face:"), Collections.singletonList(":hot_face:"), Collections.unmodifiableList(Arrays.asList("dying", "face", "feverish", "heat", "hot", "panting", "red-faced", "stroke", "sweating", "tongue")), false, false, 11.0, Qualification.fromString("fully-qualified"), "hot face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_UNWELL, false);
    public static final Emoji COLD_FACE = new Emoji("\ud83e\udd76", "\\uD83E\\uDD76", Collections.singletonList(":cold_face:"), Collections.singletonList(":cold_face:"), Collections.singletonList(":cold_face:"), Collections.unmodifiableList(Arrays.asList("blue", "blue-faced", "cold", "face", "freezing", "frostbite", "icicles", "subzero", "teeth")), false, false, 11.0, Qualification.fromString("fully-qualified"), "cold face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_UNWELL, false);
    public static final Emoji WOOZY_FACE = new Emoji("\ud83e\udd74", "\\uD83E\\uDD74", Collections.singletonList(":woozy_face:"), Collections.singletonList(":woozy_face:"), Collections.singletonList(":woozy_face:"), Collections.unmodifiableList(Arrays.asList("dizzy", "drunk", "eyes", "face", "intoxicated", "mouth", "tipsy", "uneven", "wavy", "woozy")), false, false, 11.0, Qualification.fromString("fully-qualified"), "woozy face", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_UNWELL, false);
    public static final Emoji FACE_WITH_CROSSED_OUT_EYES = new Emoji("\ud83d\ude35", "\\uD83D\\uDE35", Collections.singletonList(":dizzy_face:"), Collections.singletonList(":dizzy_face:"), Collections.singletonList(":dizzy_face:"), Collections.unmodifiableList(Arrays.asList("crossed-out", "dead", "dizzy", "eyes", "face", "feels", "knocked", "out", "sick", "tired")), false, false, 0.6, Qualification.fromString("fully-qualified"), "face with crossed-out eyes", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_UNWELL, false);
    public static final Emoji FACE_WITH_SPIRAL_EYES = new Emoji("\ud83d\ude35\u200d\ud83d\udcab", "\\uD83D\\uDE35\\u200D\\uD83D\\uDCAB", Collections.singletonList(":face_with_spiral_eyes:"), Collections.singletonList(":face_with_spiral_eyes:"), Collections.singletonList(":face_with_spiral_eyes:"), Collections.unmodifiableList(Arrays.asList("confused", "dizzy", "eyes", "face", "hypnotized", "omg", "smiley", "spiral", "trouble", "whoa", "woah", "woozy")), false, false, 13.1, Qualification.fromString("fully-qualified"), "face with spiral eyes", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_UNWELL, false);
    public static final Emoji EXPLODING_HEAD = new Emoji("\ud83e\udd2f", "\\uD83E\\uDD2F", Collections.singletonList(":exploding_head:"), Collections.unmodifiableList(Arrays.asList(":exploding_head:", ":shocked_face_with_exploding_head:")), Collections.singletonList(":exploding_head:"), Collections.unmodifiableList(Arrays.asList("blown", "explode", "exploding", "head", "mind", "mindblown", "no", "shocked", "way")), false, false, 5.0, Qualification.fromString("fully-qualified"), "exploding head", EmojiGroup.SMILEYS_AND_EMOTION, EmojiSubGroup.FACE_UNWELL, false);
}

