/*
 * Decompiled with CFR 0.152.
 */
package com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji;

import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Emoji;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.EmojiSubGroup;
import com.hypherionmc.sdlink.shaded.net.fellbaum.jemoji.Qualification;
import java.util.Arrays;
import java.util.Collections;

interface EmojiPersonRoleC {
    public static final Emoji PREGNANT_MAN_LIGHT_SKIN_TONE = new Emoji("\ud83e\udec3\ud83c\udffb", "\\uD83E\\uDEC3\\uD83C\\uDFFB", Collections.unmodifiableList(Arrays.asList(":pregnant_man_tone1:", ":pregnant_man_light_skin_tone:", ":pregnant_man::skin-tone-1:")), Collections.singletonList(":pregnant_man::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("belly", "bloated", "full", "light skin tone", "man", "overeat", "pregnant")), true, false, 14.0, Qualification.fromString("fully-qualified"), "pregnant man: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PREGNANT_MAN_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83e\udec3\ud83c\udffc", "\\uD83E\\uDEC3\\uD83C\\uDFFC", Collections.unmodifiableList(Arrays.asList(":pregnant_man_tone2:", ":pregnant_man_medium_light_skin_tone:", ":pregnant_man::skin-tone-2:")), Collections.singletonList(":pregnant_man::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("belly", "bloated", "full", "man", "medium-light skin tone", "overeat", "pregnant")), true, false, 14.0, Qualification.fromString("fully-qualified"), "pregnant man: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PREGNANT_MAN_MEDIUM_SKIN_TONE = new Emoji("\ud83e\udec3\ud83c\udffd", "\\uD83E\\uDEC3\\uD83C\\uDFFD", Collections.unmodifiableList(Arrays.asList(":pregnant_man_tone3:", ":pregnant_man_medium_skin_tone:", ":pregnant_man::skin-tone-3:")), Collections.singletonList(":pregnant_man::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("belly", "bloated", "full", "man", "medium skin tone", "overeat", "pregnant")), true, false, 14.0, Qualification.fromString("fully-qualified"), "pregnant man: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PREGNANT_MAN_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83e\udec3\ud83c\udffe", "\\uD83E\\uDEC3\\uD83C\\uDFFE", Collections.unmodifiableList(Arrays.asList(":pregnant_man_tone4:", ":pregnant_man_medium_dark_skin_tone:", ":pregnant_man::skin-tone-4:")), Collections.singletonList(":pregnant_man::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("belly", "bloated", "full", "man", "medium-dark skin tone", "overeat", "pregnant")), true, false, 14.0, Qualification.fromString("fully-qualified"), "pregnant man: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PREGNANT_MAN_DARK_SKIN_TONE = new Emoji("\ud83e\udec3\ud83c\udfff", "\\uD83E\\uDEC3\\uD83C\\uDFFF", Collections.unmodifiableList(Arrays.asList(":pregnant_man_tone5:", ":pregnant_man_dark_skin_tone:", ":pregnant_man::skin-tone-5:")), Collections.singletonList(":pregnant_man::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("belly", "bloated", "dark skin tone", "full", "man", "overeat", "pregnant")), true, false, 14.0, Qualification.fromString("fully-qualified"), "pregnant man: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PREGNANT_PERSON = new Emoji("\ud83e\udec4", "\\uD83E\\uDEC4", Collections.singletonList(":pregnant_person:"), Collections.singletonList(":pregnant_person:"), Collections.singletonList(":pregnant_person:"), Collections.unmodifiableList(Arrays.asList("belly", "bloated", "full", "overeat", "person", "pregnant", "stuffed")), false, false, 14.0, Qualification.fromString("fully-qualified"), "pregnant person", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PREGNANT_PERSON_LIGHT_SKIN_TONE = new Emoji("\ud83e\udec4\ud83c\udffb", "\\uD83E\\uDEC4\\uD83C\\uDFFB", Collections.unmodifiableList(Arrays.asList(":pregnant_person_tone1:", ":pregnant_person_light_skin_tone:", ":pregnant_person::skin-tone-1:")), Collections.singletonList(":pregnant_person::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("belly", "bloated", "full", "light skin tone", "overeat", "person", "pregnant", "stuffed")), true, false, 14.0, Qualification.fromString("fully-qualified"), "pregnant person: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PREGNANT_PERSON_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83e\udec4\ud83c\udffc", "\\uD83E\\uDEC4\\uD83C\\uDFFC", Collections.unmodifiableList(Arrays.asList(":pregnant_person_tone2:", ":pregnant_person_medium_light_skin_tone:", ":pregnant_person::skin-tone-2:")), Collections.singletonList(":pregnant_person::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("belly", "bloated", "full", "medium-light skin tone", "overeat", "person", "pregnant", "stuffed")), true, false, 14.0, Qualification.fromString("fully-qualified"), "pregnant person: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PREGNANT_PERSON_MEDIUM_SKIN_TONE = new Emoji("\ud83e\udec4\ud83c\udffd", "\\uD83E\\uDEC4\\uD83C\\uDFFD", Collections.unmodifiableList(Arrays.asList(":pregnant_person_tone3:", ":pregnant_person_medium_skin_tone:", ":pregnant_person::skin-tone-3:")), Collections.singletonList(":pregnant_person::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("belly", "bloated", "full", "medium skin tone", "overeat", "person", "pregnant", "stuffed")), true, false, 14.0, Qualification.fromString("fully-qualified"), "pregnant person: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PREGNANT_PERSON_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83e\udec4\ud83c\udffe", "\\uD83E\\uDEC4\\uD83C\\uDFFE", Collections.unmodifiableList(Arrays.asList(":pregnant_person_tone4:", ":pregnant_person_medium_dark_skin_tone:", ":pregnant_person::skin-tone-4:")), Collections.singletonList(":pregnant_person::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("belly", "bloated", "full", "medium-dark skin tone", "overeat", "person", "pregnant", "stuffed")), true, false, 14.0, Qualification.fromString("fully-qualified"), "pregnant person: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PREGNANT_PERSON_DARK_SKIN_TONE = new Emoji("\ud83e\udec4\ud83c\udfff", "\\uD83E\\uDEC4\\uD83C\\uDFFF", Collections.unmodifiableList(Arrays.asList(":pregnant_person_tone5:", ":pregnant_person_dark_skin_tone:", ":pregnant_person::skin-tone-5:")), Collections.singletonList(":pregnant_person::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("belly", "bloated", "dark skin tone", "full", "overeat", "person", "pregnant", "stuffed")), true, false, 14.0, Qualification.fromString("fully-qualified"), "pregnant person: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji BREAST_FEEDING = new Emoji("\ud83e\udd31", "\\uD83E\\uDD31", Collections.singletonList(":breast_feeding:"), Collections.singletonList(":breast-feeding:"), Collections.singletonList(":breast_feeding:"), Collections.unmodifiableList(Arrays.asList("baby", "breast", "breast-feeding", "feeding", "mom", "mother", "nursing", "woman")), false, false, 5.0, Qualification.fromString("fully-qualified"), "breast-feeding", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji BREAST_FEEDING_LIGHT_SKIN_TONE = new Emoji("\ud83e\udd31\ud83c\udffb", "\\uD83E\\uDD31\\uD83C\\uDFFB", Collections.unmodifiableList(Arrays.asList(":breast_feeding_tone1:", ":breast_feeding_light_skin_tone:", ":breast_feeding::skin-tone-1:")), Collections.singletonList(":breast-feeding::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "breast", "breast-feeding", "feeding", "light skin tone", "mom", "mother", "nursing", "woman")), true, false, 5.0, Qualification.fromString("fully-qualified"), "breast-feeding: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji BREAST_FEEDING_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83e\udd31\ud83c\udffc", "\\uD83E\\uDD31\\uD83C\\uDFFC", Collections.unmodifiableList(Arrays.asList(":breast_feeding_tone2:", ":breast_feeding_medium_light_skin_tone:", ":breast_feeding::skin-tone-2:")), Collections.singletonList(":breast-feeding::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "breast", "breast-feeding", "feeding", "medium-light skin tone", "mom", "mother", "nursing", "woman")), true, false, 5.0, Qualification.fromString("fully-qualified"), "breast-feeding: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji BREAST_FEEDING_MEDIUM_SKIN_TONE = new Emoji("\ud83e\udd31\ud83c\udffd", "\\uD83E\\uDD31\\uD83C\\uDFFD", Collections.unmodifiableList(Arrays.asList(":breast_feeding_tone3:", ":breast_feeding_medium_skin_tone:", ":breast_feeding::skin-tone-3:")), Collections.singletonList(":breast-feeding::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "breast", "breast-feeding", "feeding", "medium skin tone", "mom", "mother", "nursing", "woman")), true, false, 5.0, Qualification.fromString("fully-qualified"), "breast-feeding: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji BREAST_FEEDING_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83e\udd31\ud83c\udffe", "\\uD83E\\uDD31\\uD83C\\uDFFE", Collections.unmodifiableList(Arrays.asList(":breast_feeding_tone4:", ":breast_feeding_medium_dark_skin_tone:", ":breast_feeding::skin-tone-4:")), Collections.singletonList(":breast-feeding::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "breast", "breast-feeding", "feeding", "medium-dark skin tone", "mom", "mother", "nursing", "woman")), true, false, 5.0, Qualification.fromString("fully-qualified"), "breast-feeding: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji BREAST_FEEDING_DARK_SKIN_TONE = new Emoji("\ud83e\udd31\ud83c\udfff", "\\uD83E\\uDD31\\uD83C\\uDFFF", Collections.unmodifiableList(Arrays.asList(":breast_feeding_tone5:", ":breast_feeding_dark_skin_tone:", ":breast_feeding::skin-tone-5:")), Collections.singletonList(":breast-feeding::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "breast", "breast-feeding", "dark skin tone", "feeding", "mom", "mother", "nursing", "woman")), true, false, 5.0, Qualification.fromString("fully-qualified"), "breast-feeding: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji WOMAN_FEEDING_BABY = new Emoji("\ud83d\udc69\u200d\ud83c\udf7c", "\\uD83D\\uDC69\\u200D\\uD83C\\uDF7C", Collections.singletonList(":woman_feeding_baby:"), Collections.singletonList(":woman_feeding_baby:"), Collections.singletonList(":woman_feeding_baby:"), Collections.unmodifiableList(Arrays.asList("baby", "feed", "feeding", "mom", "mother", "nanny", "newborn", "nursing", "woman")), false, false, 13.0, Qualification.fromString("fully-qualified"), "woman feeding baby", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji WOMAN_FEEDING_BABY_LIGHT_SKIN_TONE = new Emoji("\ud83d\udc69\ud83c\udffb\u200d\ud83c\udf7c", "\\uD83D\\uDC69\\uD83C\\uDFFB\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":woman_feeding_baby_tone1:", ":woman_feeding_baby_light_skin_tone:", ":woman_feeding_baby::skin-tone-1:")), Collections.singletonList(":woman_feeding_baby::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "feed", "feeding", "light skin tone", "mom", "mother", "nanny", "newborn", "nursing", "woman")), true, false, 13.0, Qualification.fromString("fully-qualified"), "woman feeding baby: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji WOMAN_FEEDING_BABY_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83d\udc69\ud83c\udffc\u200d\ud83c\udf7c", "\\uD83D\\uDC69\\uD83C\\uDFFC\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":woman_feeding_baby_tone2:", ":woman_feeding_baby_medium_light_skin_tone:", ":woman_feeding_baby::skin-tone-2:")), Collections.singletonList(":woman_feeding_baby::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "feed", "feeding", "medium-light skin tone", "mom", "mother", "nanny", "newborn", "nursing", "woman")), true, false, 13.0, Qualification.fromString("fully-qualified"), "woman feeding baby: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji WOMAN_FEEDING_BABY_MEDIUM_SKIN_TONE = new Emoji("\ud83d\udc69\ud83c\udffd\u200d\ud83c\udf7c", "\\uD83D\\uDC69\\uD83C\\uDFFD\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":woman_feeding_baby_tone3:", ":woman_feeding_baby_medium_skin_tone:", ":woman_feeding_baby::skin-tone-3:")), Collections.singletonList(":woman_feeding_baby::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "feed", "feeding", "medium skin tone", "mom", "mother", "nanny", "newborn", "nursing", "woman")), true, false, 13.0, Qualification.fromString("fully-qualified"), "woman feeding baby: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji WOMAN_FEEDING_BABY_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83d\udc69\ud83c\udffe\u200d\ud83c\udf7c", "\\uD83D\\uDC69\\uD83C\\uDFFE\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":woman_feeding_baby_tone4:", ":woman_feeding_baby_medium_dark_skin_tone:", ":woman_feeding_baby::skin-tone-4:")), Collections.singletonList(":woman_feeding_baby::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "feed", "feeding", "medium-dark skin tone", "mom", "mother", "nanny", "newborn", "nursing", "woman")), true, false, 13.0, Qualification.fromString("fully-qualified"), "woman feeding baby: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji WOMAN_FEEDING_BABY_DARK_SKIN_TONE = new Emoji("\ud83d\udc69\ud83c\udfff\u200d\ud83c\udf7c", "\\uD83D\\uDC69\\uD83C\\uDFFF\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":woman_feeding_baby_tone5:", ":woman_feeding_baby_dark_skin_tone:", ":woman_feeding_baby::skin-tone-5:")), Collections.singletonList(":woman_feeding_baby::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "dark skin tone", "feed", "feeding", "mom", "mother", "nanny", "newborn", "nursing", "woman")), true, false, 13.0, Qualification.fromString("fully-qualified"), "woman feeding baby: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji MAN_FEEDING_BABY = new Emoji("\ud83d\udc68\u200d\ud83c\udf7c", "\\uD83D\\uDC68\\u200D\\uD83C\\uDF7C", Collections.singletonList(":man_feeding_baby:"), Collections.singletonList(":man_feeding_baby:"), Collections.singletonList(":man_feeding_baby:"), Collections.unmodifiableList(Arrays.asList("baby", "dad", "father", "feed", "feeding", "man", "nanny", "newborn", "nursing")), false, false, 13.0, Qualification.fromString("fully-qualified"), "man feeding baby", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji MAN_FEEDING_BABY_LIGHT_SKIN_TONE = new Emoji("\ud83d\udc68\ud83c\udffb\u200d\ud83c\udf7c", "\\uD83D\\uDC68\\uD83C\\uDFFB\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":man_feeding_baby_tone1:", ":man_feeding_baby_light_skin_tone:", ":man_feeding_baby::skin-tone-1:")), Collections.singletonList(":man_feeding_baby::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "dad", "father", "feed", "feeding", "light skin tone", "man", "nanny", "newborn", "nursing")), true, false, 13.0, Qualification.fromString("fully-qualified"), "man feeding baby: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji MAN_FEEDING_BABY_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83d\udc68\ud83c\udffc\u200d\ud83c\udf7c", "\\uD83D\\uDC68\\uD83C\\uDFFC\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":man_feeding_baby_tone2:", ":man_feeding_baby_medium_light_skin_tone:", ":man_feeding_baby::skin-tone-2:")), Collections.singletonList(":man_feeding_baby::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "dad", "father", "feed", "feeding", "man", "medium-light skin tone", "nanny", "newborn", "nursing")), true, false, 13.0, Qualification.fromString("fully-qualified"), "man feeding baby: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji MAN_FEEDING_BABY_MEDIUM_SKIN_TONE = new Emoji("\ud83d\udc68\ud83c\udffd\u200d\ud83c\udf7c", "\\uD83D\\uDC68\\uD83C\\uDFFD\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":man_feeding_baby_tone3:", ":man_feeding_baby_medium_skin_tone:", ":man_feeding_baby::skin-tone-3:")), Collections.singletonList(":man_feeding_baby::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "dad", "father", "feed", "feeding", "man", "medium skin tone", "nanny", "newborn", "nursing")), true, false, 13.0, Qualification.fromString("fully-qualified"), "man feeding baby: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji MAN_FEEDING_BABY_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83d\udc68\ud83c\udffe\u200d\ud83c\udf7c", "\\uD83D\\uDC68\\uD83C\\uDFFE\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":man_feeding_baby_tone4:", ":man_feeding_baby_medium_dark_skin_tone:", ":man_feeding_baby::skin-tone-4:")), Collections.singletonList(":man_feeding_baby::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "dad", "father", "feed", "feeding", "man", "medium-dark skin tone", "nanny", "newborn", "nursing")), true, false, 13.0, Qualification.fromString("fully-qualified"), "man feeding baby: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji MAN_FEEDING_BABY_DARK_SKIN_TONE = new Emoji("\ud83d\udc68\ud83c\udfff\u200d\ud83c\udf7c", "\\uD83D\\uDC68\\uD83C\\uDFFF\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":man_feeding_baby_tone5:", ":man_feeding_baby_dark_skin_tone:", ":man_feeding_baby::skin-tone-5:")), Collections.singletonList(":man_feeding_baby::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "dad", "dark skin tone", "father", "feed", "feeding", "man", "nanny", "newborn", "nursing")), true, false, 13.0, Qualification.fromString("fully-qualified"), "man feeding baby: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PERSON_FEEDING_BABY = new Emoji("\ud83e\uddd1\u200d\ud83c\udf7c", "\\uD83E\\uDDD1\\u200D\\uD83C\\uDF7C", Collections.singletonList(":person_feeding_baby:"), Collections.singletonList(":person_feeding_baby:"), Collections.singletonList(":person_feeding_baby:"), Collections.unmodifiableList(Arrays.asList("baby", "feed", "feeding", "nanny", "newborn", "nursing", "parent")), false, false, 13.0, Qualification.fromString("fully-qualified"), "person feeding baby", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PERSON_FEEDING_BABY_LIGHT_SKIN_TONE = new Emoji("\ud83e\uddd1\ud83c\udffb\u200d\ud83c\udf7c", "\\uD83E\\uDDD1\\uD83C\\uDFFB\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":person_feeding_baby_tone1:", ":person_feeding_baby_light_skin_tone:", ":person_feeding_baby::skin-tone-1:")), Collections.singletonList(":person_feeding_baby::skin-tone-2:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "feed", "feeding", "light skin tone", "nanny", "newborn", "nursing", "parent")), true, false, 13.0, Qualification.fromString("fully-qualified"), "person feeding baby: light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PERSON_FEEDING_BABY_MEDIUM_LIGHT_SKIN_TONE = new Emoji("\ud83e\uddd1\ud83c\udffc\u200d\ud83c\udf7c", "\\uD83E\\uDDD1\\uD83C\\uDFFC\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":person_feeding_baby_tone2:", ":person_feeding_baby_medium_light_skin_tone:", ":person_feeding_baby::skin-tone-2:")), Collections.singletonList(":person_feeding_baby::skin-tone-3:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "feed", "feeding", "medium-light skin tone", "nanny", "newborn", "nursing", "parent")), true, false, 13.0, Qualification.fromString("fully-qualified"), "person feeding baby: medium-light skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PERSON_FEEDING_BABY_MEDIUM_SKIN_TONE = new Emoji("\ud83e\uddd1\ud83c\udffd\u200d\ud83c\udf7c", "\\uD83E\\uDDD1\\uD83C\\uDFFD\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":person_feeding_baby_tone3:", ":person_feeding_baby_medium_skin_tone:", ":person_feeding_baby::skin-tone-3:")), Collections.singletonList(":person_feeding_baby::skin-tone-4:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "feed", "feeding", "medium skin tone", "nanny", "newborn", "nursing", "parent")), true, false, 13.0, Qualification.fromString("fully-qualified"), "person feeding baby: medium skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PERSON_FEEDING_BABY_MEDIUM_DARK_SKIN_TONE = new Emoji("\ud83e\uddd1\ud83c\udffe\u200d\ud83c\udf7c", "\\uD83E\\uDDD1\\uD83C\\uDFFE\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":person_feeding_baby_tone4:", ":person_feeding_baby_medium_dark_skin_tone:", ":person_feeding_baby::skin-tone-4:")), Collections.singletonList(":person_feeding_baby::skin-tone-5:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "feed", "feeding", "medium-dark skin tone", "nanny", "newborn", "nursing", "parent")), true, false, 13.0, Qualification.fromString("fully-qualified"), "person feeding baby: medium-dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
    public static final Emoji PERSON_FEEDING_BABY_DARK_SKIN_TONE = new Emoji("\ud83e\uddd1\ud83c\udfff\u200d\ud83c\udf7c", "\\uD83E\\uDDD1\\uD83C\\uDFFF\\u200D\\uD83C\\uDF7C", Collections.unmodifiableList(Arrays.asList(":person_feeding_baby_tone5:", ":person_feeding_baby_dark_skin_tone:", ":person_feeding_baby::skin-tone-5:")), Collections.singletonList(":person_feeding_baby::skin-tone-6:"), Collections.emptyList(), Collections.unmodifiableList(Arrays.asList("baby", "dark skin tone", "feed", "feeding", "nanny", "newborn", "nursing", "parent")), true, false, 13.0, Qualification.fromString("fully-qualified"), "person feeding baby: dark skin tone", EmojiGroup.PEOPLE_AND_BODY, EmojiSubGroup.PERSON_ROLE, false);
}

